### ISSUE TITLE
validate input parameters

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4338]
This error came when user used "+" in publishDataName. What about validating user input with regular expression?

```
        data: {'node': ['T2_US_Vanderbilt'], 'custodial': 'n', 'lfn': ['/store/user/adelanno/SingleMu/vbfDM-Data-SingleMu+VBF-CRAB3.Met050NoMJJCut.2012A/140630_191854/0000'], 'protocol': 'srmv2'}
2014-06-30 21:19:28,359:WARNING:Service:The cachefile /tmp/.wmcore_cache_wh1bsu/cmsweb.cern.ch/-8362775712894654629_GET_lfn2pfn does not exist and the service at https://cmsweb.cern.ch/phedex/datasvc/json/prod/lfn2pfn is unavailable - it returned 400 because Bad Request
 with result: The 'lfn' parameter ("/store/user/adelanno/SingleMu/vbfDM-Data-SingleMu+VBF-CRAB3.Met050NoMJJCut.2012A/140630_191854/0000") to (eval) did not pass the 'lfn' callback\n\n

2014-06-30 21:19:28,359:ERROR:DagmanCreator:Pushing information centrally {'subuser': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=adelanno/CN=724138/CN=Andres Guillermo Delannoy Sotomayor', 'subfailure': '', 'subjobdef': -1, 'substatus': 'FAILED', 'workflow': '140630_191854_crab3test-1:adelanno_crab_dir'}
2014-06-30 21:19:28,647:ERROR:Handler:Problem handling 140630_191854_crab3test-1:adelanno_crab_dir because of  failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 58, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DagmanCreator.py", line 680, in execute
    return self.executeInternal(*args, **kw)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DagmanCreator.py", line 671, in executeInternal
    info = self.createSubdag(*args, **kw)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DagmanCreator.py", line 568, in createSubdag
    jobgroupspecs, startjobid = self.makeSpecs(kwargs['task'], sitead, siteinfo, jobgroup, block, availablesites, outfiles, startjobid)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DagmanCreator.py", line 471, in makeSpecs
    lastDirectPfn = self.resolvePFNs(task['tm_asyncdest'], directDest)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DagmanCreator.py", line 323, in resolvePFNs
    pfn_info = self.phedex.getPFN(nodes=dest_sites_, lfns=lfns)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/WMCore/Services/PhEDEx/PhEDEx.py", line 353, in getPFN
    data = self._getResult('lfn2pfn', args = input_dict, verb = 'GET')
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/WMCore/Services/PhEDEx/PhEDEx.py", line 52, in _getResult
    f = self.refreshCache(file, callname, args, verb = verb)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/WMCore/Services/Service.py", line 210, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/TaskManager/3.3.7.rc3/slc5_amd64_gcc461/cms/crabtaskworker/3.3.7.rc3/lib/python2.6/site-packages/WMCore/Services/Service.py", line 314, in getData
    raise he
HTTPException
```

Phedex page : https://cmsweb-testbed.cern.ch/phedex/datasvc/json/prod/lfn2pfn?node=T2_US_Vanderbilt&protocol=srmv2&lfn=/store/user/adelanno/SingleMu/vbfDM-Data-SingleMu-VBF+CRAB3.Met050NoMJJCut.2012A/140630_191854/0000

**Comment by mmascher** [comment]
similar to (if not duplicated): https://github.com/dmwm/CRABServer/issues/4262

Closing.
