### ISSUE TITLE
Missmatch python versions on WN

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4556]
If task is submitted with old CMSSW version `CMSSW_5_3_22_patch1` and here https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.sh#L12-L70 script will make sure that python2.[67] is used from the system. If python2.6 chosen - ok, if python2.7 :

```
++ ls /uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python
++ egrep '2.[67]'
+ PY_PATH=/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python
+ echo 'python version: ' 2.7.3-cms4
python version:  2.7.3-cms4
Python found in /uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4
I found python at..
/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/bin/python
```

This leads to :

```
        Stderr: 'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/storage/local/data1/condor/execute/dir_326/glide_rQVJFy/execute/dir_25878/WMCore.zip/PSetTweaks/WMTweak.py", line 10, in <module>
  File "/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref
  File "/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/os.py", line 398, in <module>
    import UserDict
  File "/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/UserDict.py", line 84, in <module>
    _abcoll.MutableMapping.register(IterableUserDict)
  File "/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/abc.py", line 109, in register
    if issubclass(subclass, cls):
  File "/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/abc.py", line 184, in __subclasscheck__
    cls._abc_negative_cache.add(subclass)
  File "/uscmst1/prod/sw/cms/slc6_amd64_gcc472/external/python/2.7.3-cms4/lib/python2.7/_weakrefset.py", line 84, in add
    self.data.add(ref(item, self._remove))
TypeError: cannot create weak reference to 'classobj' object
```

Task on same site shows different pythons and one succeeds other fails :
Failed : http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms087/141128_133038_crab3test-2:geonmo_crab_cat_ttbar_20141128_WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball/job_out.1282.2.txt
Success : http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms0109.cern.ch/mon/cms087/141128_133825_crab3test-4:geonmo_crab_cat_ttbar_20141128_TTJets_mass184_5_TuneZ2star_8TeV-madgraph-tauola/job_out.25.0.txt

For CRAB3 we are making sure, that python 2.6 is used : https://github.com/dmwm/CRABServer/blob/8b6bccbaf463bf8d4f14c9060beecdd7ead221a3/scripts/gWMS-CMSRunAnalysis.sh#L74-L128

**Comment by belforte** [comment]
not relevant any more
