### ISSUE TITLE
Do not use merge but insert/update in filemetadata upload

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4584]
```
[09/Dec/2014:19:14:41]    Traceback (most recent call last):
[09/Dec/2014:19:14:41]      File "/data/srv/beHG1412e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.12.rc7/lib/python2.6/site-packages/WMCore/REST/Server.py", line 1728, in dbapi_wrapp
er
[09/Dec/2014:19:14:41]        return handler(*xargs, **xkwargs)
[09/Dec/2014:19:14:41]      File "/data/srv/beHG1412e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.12.rc7/lib/python2.6/site-packages/CRABInterface/RESTFileMetadata.py", line 89, in p
ut
[09/Dec/2014:19:14:41]        directstageout=directstageout)
[09/Dec/2014:19:14:41]      File "/data/srv/beHG1412e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.12.rc7/lib/python2.6/site-packages/CRABInterface/DataFileMetadata.py", line 63, in i
nject
[09/Dec/2014:19:14:41]        self.api.modifynocheck(self.FileMetaData.New_sql, **binds)
[09/Dec/2014:19:14:41]      File "/data/srv/beHG1412e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.12.rc7/lib/python2.6/site-packages/CRABInterface/RESTBaseAPI.py", line 77, in modify
nocheck
[09/Dec/2014:19:14:41]        c, _ = self.executemany(sql, kwbinds, *binds)
[09/Dec/2014:19:14:41]      File "/data/srv/beHG1412e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.12.rc7/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2071, in executemany
[09/Dec/2014:19:14:41]        return c, c.executemany(None, *binds, **kwbinds)
[09/Dec/2014:19:14:41]    DatabaseError: ORA-25408: can not safely replay call
[09/Dec/2014:19:14:41] vocms0136.cern.ch 128.142.143.118 "PUT /crabserver/prod/filemetadata HTTP/1.1" 500 [data: 25698 in 726 out 144075 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Uni
ts/OU=Users/CN=jlee/CN=661342/CN=Jason Lee" "" ] [ref: "" "CRABClient/0.0.0" ]
```

More details : 
```
For example if you are doing an insert and the database goes down and failover occurs, "ORA-25408 can not safely replay call" is expected and the application should handle this exception and re-execute the insert.

If you are in a transaction and failover occurs you will also receive an error message and you have to handle this and issue a rollback. 
```

**Comment by mmascher** [comment]
Relabeled, the merge fails because of an oracle but. We have to workaround it using insert/update instead of merge.
