### ISSUE TITLE
Problems in cmscp.py

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4650]
1)  local variable 'local_stageout_mgr' referenced before assignment (Have not checked where it looses it.)
```
ERROR: Unhandled exception.
Traceback (most recent call last):
  File "./cmscp.py", line 1839, in <module>
    JOB_STGOUT_WRAPPER_EXIT_INFO = main()
  File "./cmscp.py", line 1632, in main
    clean_stageout_area(local_stageout_mgr, direct_stageout_impl, \
UnboundLocalError: local variable 'local_stageout_mgr' referenced before assignment
```
2) Variable is not defined in except part
```
 try:
JOB_STGOUT_WRAPPER_EXIT_INFO = main()
except:
```
if it fails for some reason, you don't have JOB_STGOUT_WRAPPER_EXIT_INFO variable in except part. https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L1854 add here `JOB_STGOUT_WRAPPER_EXIT_INFO = {}`

**Comment by juztas** [comment]
Log file : http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms220/150129_083712_crab3test-2:tmulholl_crab_SMS_TChipChimStauSnu_ext_4/job_out.2.0.txt

**Comment by juztas** [comment]
@AndresTanasijczuk
