### ISSUE TITLE
New monitoring API lastfailures fails with a big number of minutes

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4686]
See https://cmsweb.cern.ch/crabserver/prod/task?subresource=lastfailures&minutes=144000

**Comment by mmascher** [comment]
server stacktrace is:

```
[03/Mar/2015:15:49:45]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 135dbab44a61d893ded48136432525e8 (Execution error)
[03/Mar/2015:15:49:45]    Traceback (most recent call last):
[03/Mar/2015:15:49:45]      File "/data/srv/beHG1503d/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.14.rc4-comp/lib/python2.6/site-packages/WMCore/REST/Format.py", line 228, in stream_chunked
[03/Mar/2015:15:49:45]        for obj in stream:
[03/Mar/2015:15:49:45]      File "/data/srv/beHG1503d/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.14.rc4-comp/lib/python2.6/site-packages/CRABInterface/RESTTask.py", line 105, in lastfailures
[03/Mar/2015:15:49:45]        yield [row[0], row[1], row[2].read()]
[03/Mar/2015:15:49:45]    AttributeError: 'NoneType' object has no attribute 'read'
```
