### ISSUE TITLE
File descriptor leakage in the TW (?)

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4744]
That is (*) the error I was seeing in the logs during this incident: https://cms-logbook.cern.ch/elog/Analysis+Operations/537

It references a certificate error, however the real reason the certificate could not be used should be that too many files were opened. In fact, I found this in the logs just before the first certificate error (**), the `Too many open files` should be it. We need to find what was the reason of the leakage.

(*)
```
2015-04-03 21:46:24,584:DEBUG:Worker:Process-1: Starting <function handleNewTask at 0x110dc80> on 150403_194605:sciaba_HC-101-T1_ES_PIC-13479-20150403122315
2015-04-03 21:46:24,597:INFO:Worker:Uploading error message to REST: Process-1: I just had a failure for (58, 'unable to use client certificate (no key found or wrong pass phrase?)')
    workid=0
    task=150403_194605:sciaba_HC-101-T1_ES_PIC-13479-20150403122315
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Worker.py", line 46, in processWorker
    outputs = work(resthost, resturi, WORKER_CONFIG, task, procnum, inputargs)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 128, in handleNewTask
    handler.addWork( MyProxyLogon(config=config, server=server, resturi=resturi, procnum=procnum, myproxylen=60*60*24) )
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/MyProxyLogon.py", line 19, in __init__
    TaskAction.__init__(self, config, server, resturi, procnum)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/TaskAction.py", line 27, in __init__
    self.backendurls = self.server.get(self.restURInoAPI + '/info', data = {'subresource': 'backendurls'})[0]['result'][0]
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/RESTInteractions.py", line 63, in get
    return self.makeRequest(uri = uri, data = data, verb = 'GET')
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/RESTInteractions.py", line 113, in makeRequest
    capath=caCertPath)#, verbose=True)# for debug
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/WMCore/Services/pycurl_manager.py", line 150, in request
    curl.perform()
error: (58, 'unable to use client certificate (no key found or wrong pass phrase?)')

2015-04-03 21:46:24,603:WARNING:Worker:Cannot upload failure message to the REST for workflow 150403_194605:sciaba_HC-101-T1_ES_PIC-13479-20150403122315.
Reason: (58, 'unable to use client certificate (no key found or wrong pass phrase?)')
2015-04-03 21:46:24,603:DEBUG:Worker:Process-1: ...work on 150403_194605:sciaba_HC-101-T1_ES_PIC-13479-20150403122315 completed in 0 seconds: Task = 150403_194605:sciaba_HC-101-T1_ES_PIC-13479-20150403122315
```

(**)
```
2015-04-03 09:48:05,911:DEBUG:Worker:Process-1: Starting <function handleNewTask at 0x110dc80> on 150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN
2015-04-03 09:48:09,980:DEBUG:Handler:Starting <TaskWorker.Actions.MyProxyLogon.MyProxyLogon object at 0xc44fa90> on 150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN
2015-04-03 09:48:10,068:ERROR:Handler:Problem handling 150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN because of [Errno 24] Too many open files failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 73, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/MyProxyLogon.py", line 42, in execute
    proxy.logonRenewMyProxy()
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/WMCore/Credential/Proxy.py", line 523, in logonRenewMyProxy
    attribute = self.getAttributeFromProxy( proxyFilename )
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/WMCore/Credential/Proxy.py", line 699, in getAttributeFromProxy
    self.commandTimeout)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/WMCore/Credential/Proxy.py", line 30, in execute_command
    stdin=subprocess.PIPE,
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/external/python/2.6.8-comp4/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/external/python/2.6.8-comp4/lib/python2.6/subprocess.py", line 1041, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

2015-04-03 09:48:10,072:INFO:Worker:Uploading error message to REST: Process-1: I just had a failure for 'user_proxy'
    workid=0
    task=150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Worker.py", line 46, in processWorker
    outputs = work(resthost, resturi, WORKER_CONFIG, task, procnum, inputargs)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 151, in handleNewTask
    return handler.actionWork(args)
  File "/data/srv/TaskManager/3.3.14.rc7-comp3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 91, in actionWork
    cacheurldict = {'endpoint': self._task['tm_cache_url'], 'cert' : self._task['user_proxy'], 'key' : self._task['user_proxy']}
KeyError: 'user_proxy'

2015-04-03 09:48:10,079:WARNING:Worker:Cannot upload failure message to the REST for workflow 150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN.
Reason: (58, 'unable to use client certificate (no key found or wrong pass phrase?)')
2015-04-03 09:48:10,080:DEBUG:Worker:Process-1: ...work on 150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN completed in 4 seconds: Task = 150403_074803:fiorendi_crab_PFClusterIso_PixelBadQ_HcalMethod3_DYToMuMu_M-50_Tune4C_13TeV-pythia8_Flat20to50_ntupleGEN
Error = 'user_proxy'
```

**Comment by belforte** [comment]
or maybe something different caused too many processes to start and pile up
which eventually gave too many open files ?

**Comment by juztas** [comment]
Seems TW  upgrade to newer version and gracefully kill did not killed all processes. I have killed 3 of Mar processes which were idle for long time and had huge number of fds
```
[crab3@vocms052 current]$ for x in `ps -eF|grep MasterWorker | awk '{ print $2 }'`;do echo `ls /proc/$x/fd 2> /dev/null | wc -l`; done
27
22
51
55
53
53
55
56
57
61
60
62
0
723
[crab3@vocms052 current]$ for x in `ps -eF|grep MasterWorker | awk '{ print $2 }'`;do echo `ls /proc^Cx/fd 2> /dev/null | wc -l`; done
[crab3@vocms052 current]$ ps -eF|grep MasterWorker
crab3     4181     1  0 67271 38340  18 Mar03 ?        00:00:53 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc5/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25696     1 14 61330 21460  19 Apr03 ?        02:50:01 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25701 25696  0 116388 238252 18 Apr03 ?       00:07:03 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25702 25696  0 98079 165028  9 Apr03 ?        00:06:10 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25703 25696  0 73446 66476  19 Apr03 ?        00:05:42 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25704 25696  0 76556 78912  18 Apr03 ?        00:05:26 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25705 25696  0 112644 223364 19 Apr03 ?       00:06:49 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25706 25696  0 95920 156360 19 Apr03 ?        00:06:25 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25707 25696  0 94703 151516 18 Apr03 ?        00:05:54 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25708 25696  0 98755 165696 17 Apr03 ?        00:06:00 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25709 25696  0 106794 199956 19 Apr03 ?       00:05:48 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    25710 25696  0 87470 122492 19 Apr03 ?        00:05:49 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc7-comp3/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
crab3    27987 27304  0 26843   924   6 17:31 pts/0    00:00:00 grep MasterWorker
crab3    29816     1  0 123242 261968 16 Mar03 ?       02:13:58 python /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.14.rc5/lib/python2.6/site-packages/TaskWorker/MasterWorker.py --config /data/srv/TaskManager/current/TaskWorkerConfig.py --debug
```
After kill:
```
[crab3@vocms052 ~]$ for x in `ps -eF|grep MasterWorker | awk '{ print $2 }'`;do echo `ls /proc/$x/fd 2> /dev/null | wc -l`; done
23
51
55
53
53
55
56
57
61
60
62
0
```
I would think that each subprocess should be using almost same number of fds, and it seems to be like this. Slaves: 50 -- 62, Master: 23.

**Comment by juztas** [comment]
Something strange is going on and fd's are increasing:
```
[crab3@vocms052 current]$ for x in `ps -eF|grep MasterWorker | awk '{ print $2 }'`;do echo `ls /proc/$x/fd 2> /dev/null | wc -l`; done
22
133
133
137
137
138
136
139
142
143
145
0
```

**Comment by juztas** [comment]
I think here is the problem:
https://github.com/dmwm/CRABServer/blob/09758e2a61a6d9cf4189db700beb588d0a52d062/src/python/TaskWorker/Actions/Handler.py#L105

I think before removing handler it needs to be closed `taskhandler.close()`

**Comment by mmascher** [comment]
I think this has been solved here: https://github.com/dmwm/CRABServer/commit/2bfa9385d18281cbd1bd8fce2fb782218cd92ab7

Not sure this commit got into the april release, in case we should apply it and verify that we do not have the fd leakage with this patch. Then we can close this issue
