### ISSUE TITLE
CRAB3 did not catched that dataset is only on T0 ant TAPE

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4747]
Dataset: https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fglobal&input=%2Fstore%2Fhidata%2FHIRun2011%2FHIMinBiasUPC%2FRAW%2Fv1%2F000%2F182%2F838%2F247BDAFB-E91C-E111-BD46-BCAEC532972F.root
```
2015-04-09 00:55:13,967:ERROR:Handler:Problem handling 150408_225428:gdyckes_crab_QCD_Pt_30to80_bcToE_Tune4C_13TeV_pythia8_Phys14DR-PU20bx25_PHYS14_25_V1-v1 because of 'NoneType' object has no attribute 'addFile'
 failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 74, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/TaskWorker/Actions/Splitter.py", line 42, in execute
    factory = jobfactory(**splitparam)
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/WMCore/JobSplitting/JobFactory.py", line 90, in __call__
    self.algorithm(*args, **kwargs)
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/WMCore/JobSplitting/LumiBased.py", line 378, in algorithm
    self.lumiChecker.fixInputFiles()
  File "/data/srv/TaskManager/3.3.15.rc2/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc2/lib/python2.6/site-packages/WMCore/JobSplitting/LumiBased.py", line 129, in fixInputFiles
    self.lumiJobs[(run, lumi)].addFile(file_)
AttributeError: 'NoneType' object has no attribute 'addFile'
```

**Comment by mmascher** [comment]
I am afraid I am not ble to replicate this issue :(

I patched some similar errors here https://github.com/dmwm/CRABServer/pull/4751 , but I am afraid we will hit this one again.. Please, post the dataset(or task) name if you see this again

**Comment by belforte** [comment]
let's close as unreproducible ?

**Comment by mmascher** [comment]
I have fixed this in https://github.com/mmascher/WMCore/commit/6278b96b32a37c915e88e1e2a0f32feb9a120074#diff-bfc92e8b3cc81b4db99bbf9af9f0b3ffR130

Basically it was happening if there was only one job generated during the splitting, and the lumi coretion was on.

**Comment by mmascher** [comment]
BTW: this was an error in the splitting, not sure what it had to do with dataset being only on T0 ant TAPE.
