### ISSUE TITLE
crab resubmit is not working

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4784]
```
Traceback (most recent call last):
  File "AdjustSites.py", line 325, in <module>
    main()
  File "AdjustSites.py", line 290, in main
    htcondor.Schedd().edit([dagJobId], 'CRAB_ResubmitList', ad['foo'])
TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type list
```

**Comment by juztas** [comment]
And it might be related due to fact, that we moved to 8.3.5 htcondor version

**Comment by juztas** [comment]
tested current prod version and resubmit works. So it is due to our changes to switch dagman to recovery mode.
