### ISSUE TITLE
Non-ASCII problem and ValueError of new ClassAd

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4786]
so 3.3.16.rc1 was kind of ok with several bugs, but from 3.3.16.rc2 today I am not able to test anything:/
First issue:
```
  File "/data/srv/glidecondor/condor_local/spool/1954/0/cluster2411954.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 15, in <module>
    import TaskWorker.Actions.PostJob as PostJob
  File "TaskWorker/Actions/PostJob.py", line 173
SyntaxError: Non-ASCII character '\xc2' in file TaskWorker/Actions/PostJob.py on line 173, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
If I fix this, I am stuck here:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/data/srv/glidecondor/condor_local/spool/1954/0/cluster2411954.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 96, in <module>
    retval = bootstrap()
  File "/data/srv/glidecondor/condor_local/spool/1954/0/cluster2411954.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 39, in bootstrap
    ad = classad.parseOld(fd)
ValueError
```
It is already too late for me to look right now where the problem is, and this function is not returning anything which ClassAd is not correct.

**Comment by mmascher** [comment]
The first error should go away if you delete and rewrite the line

**Comment by juztas** [comment]
this is what I did and ended up with second error

**Comment by mmascher** [comment]
Don't know about the second, looks like a classad has a wrong value, but the python bindings are not telling which one. We need to look at the .job.ad file

**Comment by juztas** [comment]
@mmascher I removed this line and created pull request to start and finish validation.
