### ISSUE TITLE
Improve error message when user makes mistake in input dataset

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4794]
```
2015-05-05 18:47:41,917:DEBUG:Service:Service initialised ({'endpoint': 'https://cmsweb.cern.ch/crabcache/', 'key': '/data/certs/creds/8e81240beffa768ea021ea30d6c0d2852318ff02', 'maxcachereuse': 24.0, 'cachepath': '/tmp/.wmcore_cache_yX7L7V/cmsweb.cern.ch', 'inputdata': {}, 'cert': '/data/certs/creds/8e81240beffa768ea021ea30d6c0d2852318ff02', 'timeout': 300, 'service_name': 'UserFileCache', 'requests': {'timeout': 300, 'endpoint': 'https://cmsweb.cern.ch/crabcache/', 'key': '/data/certs/creds/8e81240beffa768ea021ea30d6c0d2852318ff02', 'req_cache_path': '/tmp/.wmcore_cache_yX7L7V/cmsweb.cern.ch/.cache', 'cachepath': '/tmp/.wmcore_cache_yX7L7V/cmsweb.cern.ch', 'cert': '/data/certs/creds/8e81240beffa768ea021ea30d6c0d2852318ff02', 'host': 'https://cmsweb.cern.ch/crabcache/', 'accept_type': 'text/html', 'content_type': 'application/x-www-form-urlencoded', 'deleteCacheOnExit': <WMCore.Services.Requests.TempDirectory instance at 0x1f93cb0>, 'endpoint_components': ParseResult(scheme='https', netloc='cmsweb.cern.ch', path='/crabcache/', params='', query='', fragment=''), 'logger': <logging.Logger instance at 0x1ec2710>, 'conn': <httplib2.Http object at 0x7719450>}, 'cacheduration': 0.5, 'method': None, 'logger': <logging.Logger instance at 0x1ec2710>}):
         host: cmsweb.cern.ch, basepath: https://cmsweb.cern.ch/crabcache/ (text/html)
         cache: /tmp/.wmcore_cache_yX7L7V/cmsweb.cern.ch (duration 0.5 hours, max reuse 24.0 hours)
2015-05-05 18:47:42,216:INFO:Worker:Uploading error message to REST: Problem handling 150505_164726:gpaspala_crab_CRAB_HEPPY_test_3 because of list index out of range failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.16.rc5/slc6_amd64_gcc481/cms/crabtaskworker/3.3.16.rc5/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 74, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.16.rc5/slc6_amd64_gcc481/cms/crabtaskworker/3.3.16.rc5/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 98, in execute
    self.checkDatasetStatus(kwargs['task']['tm_input_dataset'], kwargs)
  File "/data/srv/TaskManager/3.3.16.rc5/slc6_amd64_gcc481/cms/crabtaskworker/3.3.16.rc5/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 49, in checkDatasetStatus
    res = res[0]
IndexError: list index out of range

```

**Comment by mmascher** [comment]
I already had a fix for this, but there was some duplicated code added by git during a merge.

**Comment by belforte** [comment]
do we really want to have a pointer to JIRA here ?
https://github.com/dmwm/CRABServer/blob/2a11da0eefbc3ed9bf660691e75994cadc91a899/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L29

Should always and only say 'check with support' or 'read the workbook' or 'see CRAB FAQ'
but have only in those places pointers to specific things like where to open a ticket,
which we keep changing !

**Comment by mmascher** [comment]
It was a request from Dima https://github.com/dmwm/CRABServer/issues/4739

But maybe you are right, we should put the JIRA pointer into one of our twikies, and point to them. can you open a github issue about that?
