### ISSUE TITLE
Instance name in error message for DBS lookup

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4846]
Show instance in the error message. Also maybe add a link to das where user can check?
```
,["brosser", "150623_045226:brosser_crab_T_t-channel_TuneZ2star_8TeV-powheg-tauola_smearup", "Cannot find dataset /T_t-channel_TuneZ2star_8TeV-powheg-tauola/StoreResults-Summer12_DR53X-PU_S10_START53_V7A-v1_TLBSM_53x_v3-99bd99199697666ff01397dad5652e9e/USER in DBS"]
,["brosser", "150623_045039:brosser_crab_Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola_scaleup", "Cannot find dataset /Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/StoreResults-Summer12_DR53X-PU_S10_START53_V7A-v1_TLBSM_53x_v3-99bd99199697666ff01397dad5652e9e/USER in DBS"]
```

```
2015-06-23 06:51:41,247:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1506.rc3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1506.rc3/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 74, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.1506.rc3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1506.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 73, in execute
    self.checkDatasetStatus(kwargs['task']['tm_input_dataset'], kwargs)
  File "/data/srv/TaskManager/3.3.1506.rc3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1506.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 22, in checkDatasetStatus
    raise TaskWorkerException("Cannot find dataset %s in DBS" % dataset)
TaskWorkerException: Cannot find dataset /Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola/StoreResults-Summer12_DR53X-PU_S10_START53_V7A-v1_TLBSM_53x_v3-99bd99199697666ff01397dad5652e9e/USER in DBS
```
```
[jbalcas@lxplus0098 user_tasks]$ crab st crab_Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola_scaleup/
CRAB project directory:		/afs/cern.ch/user/j/jbalcas/user_tasks/crab_Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola_scaleup
Task name:			150623_045118:brosser_crab_Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola_scaleup
Task status:			FAILED
Error during task injection:	Cannot find dataset /Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola/StoreResults-Summer12_DR53X-PU_S10_START53_V7A-v1_TLBSM_53x_v3-99bd99199697666ff01397dad5652e9e/USER in DBS

No jobs created yet!
```

**Comment by mmascher** [comment]
I thought @emaszs did this at some point. @emaszs can you check this out and tell us so we can close this, please?

**Comment by jmarra13** [comment]
@mmascher this is already done, actually this morning when you asked me about that failed submissions on kibana plots my answer was based on this error message.

**Comment by belforte** [comment]
thanks @jmarra13 
I am closing
