### ISSUE TITLE
url malformed should have better err message

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4904]
This is a test scheduler, which has no port 80 open.  Requires better error message
```
[jbalcas@lxplus0045 user_tasks]$ crab status crab_20150731_111349/
Warning: Incompatible CRABClient version 3.3.1507
Server is saying that compatible versions are: ['3.3.11', '3.3.12', '3.3.13.rc4', '3.3.1507.rc5']
Error contacting the server.
Server answered with: Execution error
Log file is /afs/cern.ch/user/j/jbalcas/user_tasks/crab_20150731_111349/crab.log
```
```
[31/Jul/2015:11:17:40]    Traceback (most recent call last):
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/WMCore/REST/Server.py", line 1728, in dbapi_wrapper
[31/Jul/2015:11:17:40]        return handler(*xargs, **xkwargs)
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/CRABInterface/RESTUserWorkflow.py", line 493, in get
[31/Jul/2015:11:17:40]        result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/CRABInterface/DataUserWorkflow.py", line 143, in status
[31/Jul/2015:11:17:40]        return self.workflow.status(workflow, userdn, userproxy, verbose=verbose)
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/CRABInterface/Utils.py", line 186, in throttled_wrapped_function
[31/Jul/2015:11:17:40]        return fn(*args, **kw)
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/CRABInterface/Utils.py", line 144, in wrapped_func
[31/Jul/2015:11:17:40]        return func(*args, **kwargs)
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 411, in status
[31/Jul/2015:11:17:40]        taskStatus = self.taskWebStatus(results[0], verbose=verbose)
[31/Jul/2015:11:17:40]      File "/data/srv/beHG1509a/sw.pre.diego/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5-comp/lib/python2.6/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 563, in taskWebStatus
[31/Jul/2015:11:17:40]        curl.perform()
[31/Jul/2015:11:17:40]    error: (3, '<url> malformed')

```

**Comment by mmascher** [comment]
I think I fixed this in https://github.com/dmwm/CRABServer/pull/4879

Closing as duplicated. Reopen if necessary.
