### ISSUE TITLE
crabserver is not able to start...

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4994]
```
[16/Sep/2015:07:00:16]  WATCHDOG: starting server daemon (pid 27839)
[16/Sep/2015:07:00:16]  INFO: loading data into /crabserver
[16/Sep/2015:07:02:02]  ERROR: terminating due to error, error trace follows
[16/Sep/2015:07:02:02]  ERROR:   Traceback (most recent call last):
[16/Sep/2015:07:02:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 387, in start_daemon
[16/Sep/2015:07:02:02]  ERROR:       self.run()
[16/Sep/2015:07:02:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 440, in run
[16/Sep/2015:07:02:02]  ERROR:       self.install_application()
[16/Sep/2015:07:02:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 241, in install_application
[16/Sep/2015:07:02:02]  ERROR:       obj = getattr(module, class_name)(self, view, path)
[16/Sep/2015:07:02:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/RESTBaseAPI.py", line 42, in __init__
[16/Sep/2015:07:02:02]  ERROR:       extconfig = Utils.ConfigCache(centralconfig=Utils.getCentralConfig(extconfigurl=config.extconfigurl, mode=config.mode),
[16/Sep/2015:07:02:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/Utils.py", line 103, in getCentralConfig
[16/Sep/2015:07:02:02]  ERROR:       curl.perform()
[16/Sep/2015:07:02:02]  ERROR:   error: (56, 'Recv failure: Connection reset by peer')
[16/Sep/2015:07:02:02]  WATCHDOG: server exited with exit code 1
[16/Sep/2015:07:20:05]  WATCHDOG: starting server daemon (pid 1369)
[16/Sep/2015:07:20:05]  INFO: loading data into /crabserver
[16/Sep/2015:07:24:02]  Reading http://git.cern.ch/pubweb/?p=CRAB3ServerConfig.git;a=blob_plain;f=cmsweb-rest-config.json returned 503.
[16/Sep/2015:07:24:02]  ERROR: terminating due to error, error trace follows
[16/Sep/2015:07:24:02]  ERROR:   Traceback (most recent call last):
[16/Sep/2015:07:24:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 387, in start_daemon
[16/Sep/2015:07:24:02]  ERROR:       self.run()
[16/Sep/2015:07:24:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 440, in run
[16/Sep/2015:07:24:02]  ERROR:       self.install_application()
[16/Sep/2015:07:24:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 241, in install_application
[16/Sep/2015:07:24:02]  ERROR:       obj = getattr(module, class_name)(self, view, path)
[16/Sep/2015:07:24:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/RESTBaseAPI.py", line 42, in __init__
[16/Sep/2015:07:24:02]  ERROR:       extconfig = Utils.ConfigCache(centralconfig=Utils.getCentralConfig(extconfigurl=config.extconfigurl, mode=config.mode),
[16/Sep/2015:07:24:02]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/Utils.py", line 115, in getCentralConfig
[16/Sep/2015:07:24:02]  ERROR:       raise ExecutionError("Internal issue when retrieving external confifuration")
[16/Sep/2015:07:24:02]  ERROR:   ExecutionError
[16/Sep/2015:07:24:02]  WATCHDOG: server exited with exit code 1
[16/Sep/2015:07:51:27]  WATCHDOG: starting server daemon (pid 12653)
[16/Sep/2015:07:51:27]  INFO: loading data into /crabserver
[16/Sep/2015:07:53:13]  ERROR: terminating due to error, error trace follows
[16/Sep/2015:07:53:13]  ERROR:   Traceback (most recent call last):
[16/Sep/2015:07:53:13]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 387, in start_daemon
[16/Sep/2015:07:53:13]  ERROR:       self.run()
[16/Sep/2015:07:53:13]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 440, in run
[16/Sep/2015:07:53:13]  ERROR:       self.install_application()
[16/Sep/2015:07:53:13]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Main.py", line 241, in install_application
[16/Sep/2015:07:53:13]  ERROR:       obj = getattr(module, class_name)(self, view, path)
[16/Sep/2015:07:53:13]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/RESTBaseAPI.py", line 42, in __init__
[16/Sep/2015:07:53:13]  ERROR:       extconfig = Utils.ConfigCache(centralconfig=Utils.getCentralConfig(extconfigurl=config.extconfigurl, mode=config.mode),
[16/Sep/2015:07:53:13]  ERROR:     File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/Utils.py", line 103, in getCentralConfig
[16/Sep/2015:07:53:13]  ERROR:       curl.perform()
[16/Sep/2015:07:53:13]  ERROR:   error: (56, 'Recv failure: Connection reset by peer')
```

**Comment by belforte** [comment]
too old to debug now !
