### ISSUE TITLE
Long taskname submitted, but failing to update status to queued

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5016]
So user submitted a task with long task name, and TW succeeded to update to Holding, but not to any other status. All validations should be using same regexp for validating task name

```
[30/Sep/2015:10:01:21]  RESTSQL:GTnOdeFiEgzo execute: () {'taskname': '150929_222044:algomez_crab_JetHT_Run2015D-PromptReco-v3_RUNA_v06', 'filetype': 'EDM'}
[30/Sep/2015:10:01:22]  SERVER REST ERROR WMCore.REST.Error.InvalidParameter fa7abf5fdbed72a492e65307b3f34759 (Invalid input parameter)
[30/Sep/2015:10:01:22]    Traceback (most recent call last):
[30/Sep/2015:10:01:22]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[30/Sep/2015:10:01:22]        return self._call(RESTArgs(list(args), kwargs))
[30/Sep/2015:10:01:22]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Server.py", line 768, in _call
[30/Sep/2015:10:01:22]        v(apiobj, request.method, api, param, safe)
[30/Sep/2015:10:01:22]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/CRABInterface/RESTTask.py", line 44, in validate
[30/Sep/2015:10:01:22]        validate_str("workflow", param, safe, RX_WORKFLOW, optional=True)
[30/Sep/2015:10:01:22]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Validation.py", line 121, in validate_str
[30/Sep/2015:10:01:22]        _validate_one(argname, param, safe, _check_str, optional, rx, custom_err)
[30/Sep/2015:10:01:22]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Validation.py", line 84, in _validate_one
[30/Sep/2015:10:01:22]        safe.kwargs[argname] = checker(argname, val, *args)
[30/Sep/2015:10:01:22]      File "/data/srv/beHG1509i/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1509.rc8/lib/python2.6/site-packages/WMCore/REST/Validation.py", line 38, in _check_str
[30/Sep/2015:10:01:22]        raise InvalidParameter(return_message("Incorrect '%s' parameter" % argname, custom_err))
[30/Sep/2015:10:01:22]    InvalidParameter
[30/Sep/2015:10:01:22] vocms0165.cern.ch 137.138.53.230 "GET /crabserver/prod/task?subresource=search&workflow=150929_132941:algomez_crab_QCD_Pt_2400to3200_TuneCUETP8M1_13TeV_pythia8_RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1_RunIISpring15DR74_RUNA_Asympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50ns_v03p2 HTTP/1.1" 400 Bad Request [data: 5315 in 714 out 3757 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=jbalcas/CN=751133/CN=Justas Balcas" "" ] [ref: "https://cmsweb.cern.ch/crabserver/ui/task/150929_132941:algomez_crab_QCD_Pt_2400to3200_TuneCUETP8M1_13TeV_pythia8_RunIISpring15DR74-Asympt50ns_MCRUN2_74_V9A-v1_RunIISpring15DR74_RUNA_Asympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50nsAsympt50ns_v03p2" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0" ]
```

**Comment by belforte** [comment]
This was likley not addressed immediately as people thought it only affected that one task. But in reality it makes CRAb3 fully stop putting all tasks in HOLDING.
See: https://cms-logbook.cern.ch/elog/Analysis+Operations/727
Needs to be fixed ASAP.  In particular failing to work on one task should *NOT* block others.

**Comment by juztas** [comment]
I gaved all details/description to @jmarra13 there is the bug and how things work. Also find out why it is failing in this particular case.

**Comment by belforte** [comment]
As reported in the PR[*] by Andres:
Diego requested today in the release planning meeting that this fix is included in December release.

[*] https://github.com/dmwm/CRABServer/pull/5060#issuecomment-154429561
