### ISSUE TITLE
crabcache failing to upload log files

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABServer#5021]
SERVER OTHER ERROR __builtins__.TypeError 44e9bdcb47fd28b358c55ff0625c35c5 (put() takes exactly 4 arguments (3 given))
[01/Oct/2015:11:03:38] vocms0131.cern.ch 128.142.142.23 "PUT /crabcache/logfile HTTP/1.1" 500 Internal Server Error [data: 17815 in 723 out 3639 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=riahi/CN=672488/CN=Hassen Riahi" "" ] [ref: "" "PycURL/7.19.3 libcurl/7.35.0 OpenSSL/1.0.1p zlib/1.2.8 c-ares/1.10.0" ]
[01/Oct/2015:11:03:38]  SERVER OTHER ERROR __builtins__.TypeError 30105bce99a0d85950b0abf4b4548a0c (put() takes exactly 4 arguments (3 given))
[01/Oct/2015:11:03:38]    Traceback (most recent call last):
[01/Oct/2015:11:03:38]      File "/data/srv/beHG1510d/sw.pre/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc7/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[01/Oct/2015:11:03:38]        return self._call(RESTArgs(list(args), kwargs))
[01/Oct/2015:11:03:38]      File "/data/srv/beHG1510d/sw.pre/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc7/lib/python2.6/site-packages/WMCore/REST/Server.py", line 772, in _call
[01/Oct/2015:11:03:38]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[01/Oct/2015:11:03:38]      File "/data/srv/beHG1510d/sw.pre/slc6_amd64_gcc481/cms/crabcache/3.3.1510.rc7/lib/python2.6/site-packages/UserFileCache/RESTFile.py", line 142, in put
[01/Oct/2015:11:03:38]        return RESTFile.put(self, inputfile, name)
[01/Oct/2015:11:03:38]    TypeError: put() takes exactly 4 arguments (3 given)

**Comment by mmascher** [comment]
Solved in ad13f1d3b3c3acfe8a580e76235a0af57bc67e8c
