### ISSUE TITLE
missing file in tarball is not fatal error for task submission.

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5058]
```
2015-11-01 23:21:16,864:ERROR:DagmanCreator:"filename 'debug/crabConfig.py' not found"
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1510.rc7-comp/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1510.rc7-comp/lib/python2.6/site-packages/TaskWorker/Actions/DagmanCreator.py", line 
796, in extractMonitorFiles
    sandboxTar.extract('debug/crabConfig.py')
  File "/data/srv/TaskManager/3.3.1510.rc7-comp/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/tarfile.py", line 2065, in extract
    tarinfo = self.getmember(member)
  File "/data/srv/TaskManager/3.3.1510.rc7-comp/slc6_amd64_gcc481/external/python/2.6.8-comp9/lib/python2.6/tarfile.py", line 1789, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'debug/crabConfig.py' not found"
```

**Comment by belforte** [comment]
that's as it supposed to be
