### ISSUE TITLE
improve TW loggin when no job can be created

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5110]
look at following final part of this twlog
```
2015-12-07 22:36:02,152:DEBUG:DataDiscovery:Tot events found: 5725251
2015-12-07 22:36:02,152:DEBUG:DataDiscovery:Tot lumis found: 13353
2015-12-07 22:36:02,152:DEBUG:DataDiscovery:Duplicate lumis found: 0
2015-12-07 22:36:02,152:DEBUG:DataDiscovery:Tot files found: 9934
2015-12-07 22:36:02,340:DEBUG:DBSDataDiscovery:Got 9934 files
2015-12-07 22:36:03,050:INFO:Handler:Finished <TaskWorker.Actions.DBSDataDiscovery.DBSDataDiscovery object at 0x38d0fd0> on 151207_213513:treis_crab_20151207_223449 in 18 seconds
2015-12-07 22:36:03,050:DEBUG:Handler:Starting <TaskWorker.Actions.Splitter.Splitter object at 0x38d0a50> on 151207_213513:treis_crab_20151207_223449
2015-12-07 22:36:03,759:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1512.rc6/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1512.rc6/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 98, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.1512.rc6/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1512.rc6/lib/python2.6/site-packages/TaskWorker/Actions/Splitter.py", line 53, in execute
    raise TaskWorkerException(msg)
TaskWorkerException: The CRAB3 server backend could not submit any job to the Grid scheduler: Splitting task 151207_213513:treis_crab_20151207_223449 on dataset /HIExpressPhysics/HIRun2015-Express-v1/FEVT with LumiBased method does not generate any job
```

The reason that no job was generated, is that the dataset is not fully in PhEDEx and after the blocks with no known location have been removed, the intersection with the user run selection is empty.

The TW could and should print a more clear message , describing the above condition.

This would greatly simplify and speed up dealing with user help requests like:

Hi Stefano,

thanks for looking into this. I did a crab status as well after the
error. I copy here the output from the log file that contains the lines
from that command. I did not learn more from it I must say.
Btw., I have also tried file base splitting before with the same result.

Cheers,
Thomas

DEBUG 2015-12-07 22:36:58,154:   Executing command: 'status'
DEBUG 2015-12-07 22:36:58,154:   Found CRAB cache file
/afs/cern.ch/user/t/treis/.crab3
DEBUG 2015-12-07 22:36:58,171:   Checking credentials
DEBUG 2015-12-07 22:36:58,172:   Found proxy file /tmp/x509up_u7202
DEBUG 2015-12-07 22:36:58,172:   Getting proxy life time left
DEBUG 2015-12-07 22:36:58,779:   Executing :
 command : voms-proxy-info -file /tmp/x509up_u7202 -timeleft
 output : 54478

 error:
 retcode : 0
DEBUG 2015-12-07 22:36:59,704:   Executing :
 command : voms-proxy-info -file /tmp/x509up_u7202 -actimeleft
 output : 54476

 error:
 retcode : 0
DEBUG 2015-12-07 22:36:59,705:   Proxy valid for 15:07:58 hours
DEBUG 2015-12-07 22:36:59,822:   Executing :
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic
Units/OU=Users/CN=treis/CN=719752/CN=Thomas Reis

 error: WARNING: can't open config file:
/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/ef35842be28ecca6d10195ea8182a5ac/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1p/ssl/openssl.cnf

 retcode : 0
DEBUG 2015-12-07 22:36:59,823:   Checking credentials
DEBUG 2015-12-07 22:36:59,823:   Found proxy file /tmp/x509up_u7202
DEBUG 2015-12-07 22:36:59,823:   Getting proxy life time left
DEBUG 2015-12-07 22:37:00,428:   Executing :
 command : voms-proxy-info -file /tmp/x509up_u7202 -timeleft
 output : 54476

 error:
 retcode : 0
DEBUG 2015-12-07 22:37:01,042:   Executing :
 command : voms-proxy-info -file /tmp/x509up_u7202 -actimeleft
 output : 54475

 error:
 retcode : 0
DEBUG 2015-12-07 22:37:01,043:   Proxy valid for 15:07:56 hours
DEBUG 2015-12-07 22:37:01,305:   Registering user credentials for server
/DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119).cern.ch
DEBUG 2015-12-07 22:37:01,422:   Executing :
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /DC=ch/DC=cern/OU=Organic
Units/OU=Users/CN=treis/CN=719752/CN=Thomas Reis

 error: WARNING: can't open config file:
/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/ef35842be28ecca6d10195ea8182a5ac/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1p/ssl/openssl.cnf

 retcode : 0
DEBUG 2015-12-07 22:37:01,422:   Getting myproxy life time left for
myproxy.cern.ch
DEBUG 2015-12-07 22:37:01,422:   Calculating hash of
/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=treis/CN=719752/CN=Thomas
Reis_cmsweb.cern.ch for credential name
DEBUG 2015-12-07 22:37:02,045:   Executing :
 command : myproxy-info -l c7e83dd1c9b84802b10b7e0ce13e287d1d245f87 -s
myproxy.cern.ch
 output : username: c7e83dd1c9b84802b10b7e0ce13e287d1d245f87
owner: /DC=ch/DC=cern/OU=Organic
Units/OU=Users/CN=treis/CN=719752/CN=Thomas Reis
  renewal policy:
/DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119).cern.ch
  trusted retrieval policy:
/DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119).cern.ch
  timeleft: 711:08:07  (29.6 days)

 error:
 retcode : 0
DEBUG 2015-12-07 22:37:02,046:   Myproxy is valid: 2560087
DEBUG 2015-12-07 22:37:02,046:   Command use: status
DEBUG 2015-12-07 22:37:02,046:   Options use: ['-d',
'crab_20151207_223449/']
DEBUG 2015-12-07 22:37:02,281:   CRABClient version: 3.3.1512
DEBUG 2015-12-07 22:37:02,281:   Instance is prod
DEBUG 2015-12-07 22:37:02,281:   Server base url is cmsweb.cern.ch
DEBUG 2015-12-07 22:37:02,281:   Command url /crabserver/prod/workflow
DEBUG 2015-12-07 22:37:02,281:   Looking up detailed status of task
151207_213513:treis_crab_20151207_223449
DEBUG 2015-12-07 22:37:02,527:   {'status': 'SUBMITFAILED', 'schedd':
'', 'totalJobdefs': 0, 'jobsPerStatus': {}, 'taskWarningMsg': [],
'statusFailureMsg': '', 'taskFailureMsg': 'The CRAB3 server backend
could not submit any job to the Grid scheduler: Splitting task
151207_213513:treis_crab_20151207_223449 on dataset
/HIExpressPhysics/HIRun2015-Express-v1/FEVT with LumiBased method does
not generate any job', 'failedJobdefs': 0, 'jobdefErrors': [],
'collector': '', 'jobList': []}
INFO 2015-12-07 22:37:02,527:    CRAB project directory:
/afs/cern.ch/work/t/treis/ugmt/offline/CMSSW_8_0_0_pre1/src/grid/data/crab_20151207_223449
INFO 2015-12-07 22:37:02,527:    Task name:
151207_213513:treis_crab_20151207_223449
INFO 2015-12-07 22:37:02,527:    Task status:                   SUBMITFAILED
ERROR 2015-12-07 22:37:02,527:   Failure message:               The
CRAB3 server backend could not submit any job to the Grid scheduler:
Splitting task 151207_213513:treis_crab_20151207_223449 on dataset
/HIExpressPhysics/HIRun2015-Express-v1/FEVT with LumiBased method does
not generate any job
INFO 2015-12-07 22:37:02,530:    Log file is
/afs/cern.ch/work/t/treis/ugmt/offline/CMSSW_8_0_0_pre1/src/grid/data/crab_20151207_223449/crab.log

On 08.12.2015 17:29, Stefano Belforte wrote:
> Seens something went wrong in the task preparation
> (SUBMIT failed) and the sandbox for --dryrun was not prepared.
> Unfortuantely crab log file has no other info.
> did you do a crab status ?
> Stefano
>
> On 12/07/2015 10:51 PM, Thomas Reis wrote:
>>
>> *** Discussion title: Computing Tools
>>
>> Hi,
>>
>> I try to run on the latest HI data runs and get a submitfailed error
>> when I try a dry run.
>> The dataset is of the FEVT tier and the analysis works fine in a local
>> run.
>>
>> Could you explain me what the error message means please?
>>
>> Thanks for your help,
>> Thomas
>>
>> Log file:
>> https://cmsweb.cern.ch/crabcache/logfile?name=2015-12-07_223616_crab.log&username=treis
>>
>>
>> The complete error message is this one:
>>
>> Will use CRAB configuration file crab_cfg.py
>> Importing CMSSW configuration
>> ../../L1Trigger/L1TMuon/test/runMuonFromRawDataStream.py
>> Finished importing CMSSW configuration
>> ../../L1Trigger/L1TMuon/test/runMuonFromRawDataStream.py
>> Sending the request to the server
>> Success: Your task has been delivered to the CRAB3 server.
>> Waiting for task to be processed
>> Checking task status
>> Task status: NEW
>> Please wait...
>> Task status: QUEUED
>> Please wait...
>> Task status: SUBMITFAILED
>> Error: The submission of your task has failed. You can do 'crab status'
>> to get the error message.
>>
>> Creating temporary directory for dry run sandbox in /tmp/treis/tmp8wBa8l
>> ERROR: RuntimeError: Reading
>> https://cmsweb.cern.ch/crabcache/logfile?name=dry-run-sandbox.tar.gz
>> failed with code 400
>>
>>          Please email hn-cms-computing-tools@cern.ch for support with the
>> crab.log file or crab.log URL.
>>          Client Version: 3.3.1512
>>          The log file
>> /afs/cern.ch/work/t/treis/ugmt/offline/CMSSW_8_0_0_pre1/src/grid/data/crab_20151207_223449/crab.log
>>
>> has been uploaded automatically to the CRAB cache.
>>          Please email the following URL
>> 'https://cmsweb.cern.ch/crabcache/logfile?name=2015-12-07_223616_crab.log&username=treis'
>>
>> to hn-cms-computing-tools@cern.ch if you need help from Analysis
>> Operations.
>>
>>   [ MIME part of type application/pkcs7-signature stripped ]
>>
>> -------------------------------------------------------------
>> Visit this CMS message (to reply or unsubscribe) at:
>> https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1196.html
>>
>

**Comment by KUJayhawk** [comment]
I am having the same issue. I noticed while running:

openssl pkcs12 -in YourCert.p12 -clcerts -nokeys -out $HOME/.globus/usercert.pem

to install my grid credentials that I received the following error:

WARNING: can't open config file: /build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/ef35842be28ecca6d10195ea8182a5ac/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1p/ssl/openssl.cnf

This consequentially lead to the same error as described above while running a job on Crab.

**Comment by mmascher** [comment]
Hi @KUJayhawk , the warning is always present and it is unrelated to this specific issue. Have you written to computing-tools about this?
