### ISSUE TITLE
check output LFN length at submission time - DatabaseError: ORA-12899: value too large for column "FILEMETADATA"."FMD_LFN" (actual: 523, maximum: 500)

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5116]
Just to let you know. This also might happen with fmd_tmp_lfn

```
[11/Dec/2015:02:24:10]  RESTSQL:SqiVnLTNlytW execute: () {'outlfn': '/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSI
M/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l/151209_021929/0000/ST_t-channel_4f
_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_8.root', 'taskname': '151209_021929:bockjoo_crab_20151208_211814'}
[11/Dec/2015:02:24:10]  RESTSQL:SqiVnLTNlytW prepare [INSERT INTO filemetadata (                tm_taskname, panda_job_id, fmd_outdataset, fmd_acq_era, fmd_sw_ver, fmd_in_events, fmd_global_tag,               fmd_publish_name, fmd_locati
on, fmd_tmp_location, fmd_runlumi, fmd_adler32, fmd_cksum, fmd_md5, fmd_lfn, fmd_size,               fmd_type, fmd_parent, fmd_creation_time, fmd_filestate, fmd_direct_stageout, fmd_tmplfn)                VALUES (:taskname, :pandajobid, 
:outdatasetname, :acquisitionera, :appver, :events, :globalTag,                       :publishdataname, :outlocation, :outtmplocation, :runlumi, :checksumadler32, :checksumcksum, :checksummd5, :outlfn, :outsize,                       :ou
ttype, :inparentlfns, SYS_EXTRACT_UTC(SYSTIMESTAMP), :filestate, :directstageout, :outtmplfn)]
[11/Dec/2015:02:24:10]  RESTSQL:SqiVnLTNlytW executemany: ([{'filestate': 'None', 'outlfn': '/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_as
ymptotic_v2-v1/MINIAODSIM/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l/151209_021
929/0000/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_8.root', 'acquisitionera': 'null', 'outlocation': 'T2_US_Florida', 'globalTag': 'None', 'outsize': '3
9853678', 'checksumcksum': '2516377998', 'runlumi': '{}', 'events': '0', 'outtmplfn': '/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_asymptot
ic_v2-v1/MINIAODSIM/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l/151209_021929/00
00/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_8.root', 'pandajobid': '8', 'appver': 'CMSSW_7_4_12_patch2', 'checksumadler32': '6d5b53f5', 'checksummd5': 
'asda', 'inparentlfns': '[]', 'publishdataname': 'ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l-00000000000000000000000000000000', 'outtype': 'TFIL
E', 'outdatasetname': '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER', 'outtmplocation': 'T2_US_MIT', 'taskname': '151209_021929:bockjoo_crab_20151208_211814', 'directstageout': 'F'}],) {}
[11/Dec/2015:02:24:10]  SERVER DATABASE ERROR 500/403 Execution error cx_Oracle.DatabaseError 57d5708acf5ea25fb3a3d64a27eb00cb [instance: prod] (ORA-12899: value too large for column "CMS_ANALYSIS_REQMGR"."FILEMETADATA"."FMD_LFN" (actual: 523, maximum: 500)); last statement: INSERT INTO filemetadata (                tm_taskname, panda_job_id, fmd_outdataset, fmd_acq_era, fmd_sw_ver, fmd_in_events, fmd_global_tag,               fmd_publish_name, fmd_location, fmd_tmp_location, fmd_runlumi, fmd_adler32, fmd_cksum, fmd_md5, fmd_lfn, fmd_size,               fmd_type, fmd_parent, fmd_creation_time, fmd_filestate, fmd_direct_stageout, fmd_tmplfn)                VALUES (:taskname, :pandajobid, :outdatasetname, :acquisitionera, :appver, :events, :globalTag,                       :publishdataname, :outlocation, :outtmplocation, :runlumi, :checksumadler32, :checksumcksum, :checksummd5, :<**>outlfn, :outsize,                       :outtype, :inparentlfns, SYS_EXTRACT_UTC(SYSTIMESTAMP), :filestate, :directstageout, :outtmplfn); binds: ([{'filestate': 'None', 'outlfn': '/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l/151209_021929/0000/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_8.root', 'acquisitionera': 'null', 'outlocation': 'T2_US_Florida', 'globalTag': 'None', 'outsize': '39853678', 'checksumcksum': '2516377998', 'runlumi': '{}', 'events': '0', 'outtmplfn': '/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l/151209_021929/0000/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_8.root', 'pandajobid': '8', 'appver': 'CMSSW_7_4_12_patch2', 'checksumadler32': '6d5b53f5', 'checksummd5': 'asda', 'inparentlfns': '[]', 'publishdataname': 'ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l-00000000000000000000000000000000', 'outtype': 'TFILE', 'outdatasetname': '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER', 'outtmplocation': 'T2_US_MIT', 'taskname': '151209_021929:bockjoo_crab_20151208_211814', 'directstageout': 'F'}],), {}; offset: 614
[11/Dec/2015:02:24:10]    Traceback (most recent call last):
[11/Dec/2015:02:24:10]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 1728, in dbapi_wrapper
[11/Dec/2015:02:24:10]        return handler(*xargs, **xkwargs)
[11/Dec/2015:02:24:10]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/CRABInterface/RESTFileMetadata.py", line 86, in put
[11/Dec/2015:02:24:10]        directstageout=directstageout)
[11/Dec/2015:02:24:10]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/CRABInterface/DataFileMetadata.py", line 68, in inject
[11/Dec/2015:02:24:10]        self.api.modify(self.FileMetaData.New_sql, **binds)
[11/Dec/2015:02:24:10]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2162, in modify
[11/Dec/2015:02:24:10]        c, _ = self.executemany(sql, kwbinds, *binds)
[11/Dec/2015:02:24:10]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2071, in executemany
[11/Dec/2015:02:24:10]        return c, c.executemany(None, *binds, **kwbinds)
[11/Dec/2015:02:24:10]    DatabaseError: ORA-12899: value too large for column "CMS_ANALYSIS_REQMGR"."FILEMETADATA"."FMD_LFN" (actual: 523, maximum: 500)
[11/Dec/2015:02:24:10] vocms0165.cern.ch 188.184.68.253 "PUT /crabserver/prod/filemetadata HTTP/1.1" 500 Internal Server Error [data: 4146 in 726 out 35188 us ] [auth: OK "/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=People/CN=Bockjoo Kim 118811" "" ] [ref: "" "CRABClient/0.0.0" ]
```

**Comment by belforte** [comment]
thanks Justas, sorry for stupid question: is this TW log or REST log ?

**Comment by juztas** [comment]
rest, it is postjob which tried to put filemetadata info. so with fmd_lfn and fmd_tmp_lfn this can happen. Question is why only 500 chars for full lfn or tmp_lfn? Another thing to look is that fmd_lfn is used as key, if there would be increase, not sure about change on performance.

**Comment by mmascher** [comment]
Thanks Justas. IIRC the 500 limit is because that's the limit for an LFN in DBS. Of course we should check upfront the len of lfns, but probably the tmp_lfn is generated "at runtime but the postjob".

**Comment by juztas** [comment]
good to know :)

**Comment by belforte** [comment]
You don't want to really allow more than 500 chars, right? 
Sent from Stefano's mobile

**Comment by mmascher** [comment]
No, 500 is the limit, we should verify at submission time we do not exceed it, not when the jobs is finished and we try to upload the FMD

**Comment by belforte** [comment]
OK. put that in the title of the issue

**Comment by mmascher** [comment]
I had a look at this. the offending lfn is:

`/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_27_HZZ4l/151209_021929/0000/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1_MINIAODSIM_8.root`

The client uploads the LFN till `/store/local/users/bockjoo/ana/Run2/HZZ4l//ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1/MINIAODSIM`(see `tm_output_lfn` field in the task info section here https://cmsweb.cern.ch/crabserver/ui/task/151209_021929:bockjoo_crab_20151208_211814)

The TW then appends the primary dataset, the publishname (or the taskname if it's empty), and the timestamp (see https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L198)

The last two parts (`0000/filename`) comes from the job wrapper (I haven't check the code)

IMHO one thing we can already do is to change the RX_PARENTLFN regexp (https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/Regexps.py#L30) which is used for for both the outlfn and the outtmplfn (and the parent input lfn). This way we will avoid hitting the database error and get a (slightly) cleaner error. But we should probably verify these are really the limits in DBS.

The other thing we can do, check the length of the outlfn and outtmplfn upfront, seems bit more complicated, I'll try to see where `0000/filename` is built and if we can do the whole check upfront (but gotta go now).

**Comment by mmascher** [comment]
Filenames are added here in the TW: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L522 which in turn are a combination of edm + tfiles + additional outputs created in the client (https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L559)

So, all in all I think we can also add a check in the REST interface for this kind of error:

```
For each file in tm_tfile_outfiles + tm_edm_outfiles + tm_outfiles
    if len(os.path.join(tm_output_lfn + tm_primary_dataset + (tm_publishname or tm_taskname) + '0000' + 'failed' + file)) > 500:
        raise InvalidParameter("A nice message")
```


I know it seems fragile, so probably it would be good to have some refactoring, and only use some new methods in ServerUtilities to create filenames. That's why I'm moving the issue to Soon and we will rediscuss the priority of this.

**Comment by belforte** [comment]
@mmascher one year later.. shall we say priority is low enough to close and ignore, or still worth putting a quick fix ?
