### ISSUE TITLE
DatabaseError: ORA-00907: missing right parenthesis

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5118]
Mh... It would be good idea to have unit tests for these cases or just query all possible urls and check if they are working. 
```
[11/Dec/2015:13:34:14]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 9507a45f3cd77ba00a9533862d22f2ca (Execution error)
[11/Dec/2015:13:34:14]    Traceback (most recent call last):
[11/Dec/2015:13:34:14]  RESTSQL:douNsaBFMOyz check [select sysdate from dual]
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Format.py", line 228, in stream_chunked
[11/Dec/2015:13:34:14]        for obj in stream:
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/CRABInterface/RESTTask.py", line 184, in lastfailures
[11/Dec/2015:13:34:14]        rows = self.api.query(None, None, self.Task.LastFailures, minutes=kwargs["minutes"])
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2112, in query
[11/Dec/2015:13:34:14]        c, _ = self.execute(sql, *binds, **kwbinds)
[11/Dec/2015:13:34:14]  RESTSQL:douNsaBFMOyz connection established
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2053, in execute
[11/Dec/2015:13:34:14]        return c, c.execute(None, *binds, **kwbinds)
[11/Dec/2015:13:34:14]    DatabaseError: ORA-00907: missing right parenthesis
[11/Dec/2015:13:34:14]  SERVER HTTP ERROR cherrypy._cperror.HTTPError acbdc83382b53927cc8502a1171d1bca ((500, 'Execution error'))
[11/Dec/2015:13:34:14]    Traceback (most recent call last):
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[11/Dec/2015:13:34:14]        return self._call(RESTArgs(list(args), kwargs))
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Server.py", line 807, in _call
[11/Dec/2015:13:34:14]        return stream_maybe_etag(apiobj.get('etag_limit', self.etag_limit), etagger, reply)
[11/Dec/2015:13:34:14]      File "/data/srv/beHG1512e/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1512.rc2/lib/python2.6/site-packages/WMCore/REST/Format.py", line 475, in stream_maybe_etag
[11/Dec/2015:13:34:14]        raise cherrypy.HTTPError(int(err), message)
[11/Dec/2015:13:34:14]    HTTPError: (500, 'Execution error')
[11/Dec/2015:13:34:14] vocms0163.cern.ch 137.138.42.16 "GET /crabserver/prod/task?subresource=lastfailures&minutes=120 HTTP/1.1" 500 Internal Server Error [data: 4485 in 726 out 74450 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Us
ers/CN=jbalcas/CN=751133/CN=Justas Balcas" "" ] [ref: "" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0" ]

```

**Comment by jmarra13** [comment]
https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/TaskDB/Oracle/Task/Task.py#L35

the right parentheses is inside the quotes

>...tm_task_status='RESUBMITFAILED)'

**Comment by juztas** [comment]
I saw that to, but this is what you get in server. Try on your VM to take newest CS and WMCore code and test

**Comment by jmarra13** [comment]
I just updated my fork with the newest code and it is still there.

**Comment by juztas** [comment]
but you tried to call that API?

**Comment by jmarra13** [comment]
No

**Comment by belforte** [comment]
maybe this is the reason for https://github.com/dmwm/CRABServer/issues/5028 ?

**Comment by belforte** [comment]
anyhow we should first fix it, and if we see more problems, look again

**Comment by mmascher** [comment]
I fixed this, but since it is low priority (only used by the monitoring) I wil let @jmarra13 test this on preprod for the February release

**Comment by mmascher** [comment]
Yes stefano, was also the reason of #5028
