### ISSUE TITLE
make it possible to debug myproxy problems in TW

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5168]
see e.g. https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1410/1.html
this already the 3rd or 4th time some user report problems with myproxy inside TW and I can't figure out what's going on.
currenlty when TW fails to delegate, we get totally useless messages like this in tw log
```
2016-03-07 19:35:25,484:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1602.rc5/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1602.rc5/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 99, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.1602.rc5/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1602.rc5/lib/python2.7/site-packages/TaskWorker/Actions/MyProxyLogon.py", line 45, in execute
    raise TaskWorkerException(msg)
TaskWorkerException: Impossible to retrieve proxy from myproxy.cern.ch for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sbreeze/CN=763090/CN=Shane Davy Breeze.

```

I tried to replicate what TaskWorker/Actions/MyProxyLogon.py does in a standalone python, but it is very lenghty and in the end almost impossible so I gave up, I reached the point where the command returns 0 as timeleft, which matches the exception, but  it is difficult to be sure that I passed all correct arg, and it was very painful. In the end we need simply to see the exact myproxy command that was issued.
I am aware that this may need to be done in WMCore. Or otherwise replace that with a direct call to myproxy-info, or whatever.

Also, as I think we discussed other times... do we really need that stupid, criptic login name ? Or could we use something that e.g. shows if we ask the user to do myproxy-info -d so that we can see w/o getting nuts what's store on myproxy ?

**Comment by juztas** [comment]
```
2016-03-07 19:35:18,891:DEBUG:Worker:Process-5: Starting <function handleNewTask at 0x2a3a0c8> on 160307_183013:sbreeze_crab_run260627_zb
2016-03-07 19:35:21,165:DEBUG:Handler:Process 5 is starting handleNewTask on task 160307_183013:sbreeze_crab_run260627_zb
2016-03-07 19:35:21,166:DEBUG:Handler:Starting <TaskWorker.Actions.MyProxyLogon.MyProxyLogon object at 0x344ce90> on 160307_183013:sbreeze_crab_run260627_zb
2016-03-07 19:35:22,224:DEBUG:Proxy:Executing : 
 command : env -i sh -c 'env X509_USER_PROXY=/data/certs/creds/74e1d131dc833733363da8f94a22d57e76af2782 voms-proxy-info -fqan'
 output : 
 error: No VOMS attributes found!

 retcode : 1
2016-03-07 19:35:22,496:DEBUG:Proxy:Executing : 
 command : env -i sh -c 'unset X509_USER_CERT X509_USER_KEY && env X509_USER_CERT=/data/certs/hostcert.pem X509_USER_KEY=/data/certs/hostkey.pem myproxy-logon -d -n -s myproxy.cern.ch -o /data/certs/creds/74e1d131dc833733363da8f94a22d57e
76af2782.5029 -l "6e638a1e10d725add1c6df5a2a83c424a5141459" -t 168:00'
 output : 
 error: Failed to receive credentials.
ERROR from myproxy-server:
X509_verify_cert() failed: certificate revoked

 retcode : 1
2016-03-07 19:35:22,498:ERROR:Proxy:Unable to retrieve delegated proxy for user DN /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sbreeze/CN=763090/CN=Shane Davy Breeze! Exit code:1 output:
2016-03-07 19:35:23,473:DEBUG:Proxy:Executing : 
 command : env -i sh -c 'voms-proxy-info -file /data/certs/creds/74e1d131dc833733363da8f94a22d57e76af2782 -timeleft'
 output : 248234

 error: 
 retcode : 0
2016-03-07 19:35:24,446:DEBUG:Proxy:Executing : 
 command : env -i sh -c 'voms-proxy-info -file /data/certs/creds/74e1d131dc833733363da8f94a22d57e76af2782 -actimeleft'
 output : 
 error: No VOMS attributes found!

 retcode : 1
2016-03-07 19:35:25,481:DEBUG:Proxy:Executing : 
 command : env -i sh -c 'env X509_USER_PROXY=/data/certs/creds/74e1d131dc833733363da8f94a22d57e76af2782 voms-proxy-info -fqan'
 output : 
 error: No VOMS attributes found!

 retcode : 1
2016-03-07 19:35:25,484:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1602.rc5/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1602.rc5/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 99, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.1602.rc5/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1602.rc5/lib/python2.7/site-packages/TaskWorker/Actions/MyProxyLogon.py", line 45, in execute
    raise TaskWorkerException(msg)
TaskWorkerException: Impossible to retrieve proxy from myproxy.cern.ch for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sbreeze/CN=763090/CN=Shane Davy Breeze.

2016-03-07 19:35:25,513:INFO:Worker:Uploading error message to REST: Impossible to retrieve proxy from myproxy.cern.ch for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sbreeze/CN=763090/CN=Shane Davy Breeze.
2016-03-07 19:35:25,891:INFO:Worker:Error message successfully uploaded to the REST
2016-03-07 19:35:25,892:DEBUG:Worker:Process-5: ...work on 160307_183013:sbreeze_crab_run260627_zb completed in 7 seconds: Task = 160307_183013:sbreeze_crab_run260627_zb
Error = Impossible to retrieve proxy from myproxy.cern.ch for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sbreeze/CN=763090/CN=Shane Davy Breeze.
```

**Comment by belforte** [comment]
OK. I was blind the other night.
Indeed the message is in the log in the task directory as well [1]

and the `X509_verify_cert() failed: certificate revoked`  explain.

And I also understand what's happened, here's time history:
  1 user works happily
  2 user certificate expires
  3 user gets new certificate with same DN/CA and keeps submitting
  4 2016-03-07 19:29 crab client checks credential in myproxy and finds it OK for 24 more days [2]
  5 six minutes later at 2016-03-07 19:35 TaskWorker tries to get proxy from myproxy and fails because the [1] certificate was revoked

So the credential in myproxy is not valid anymore when the original certificate expires, but myproxy-info does not detect it :-(

6 I instructed the user to do a myproxy-destroy and indeed the report is that things worked after it

All understood. Now .. how to make our life easier next time this happens ? I will open an ad-hoc issue referring to this.

[1]
```
 command : env -i sh -c 'unset X509_USER_CERT X509_USER_KEY && env X509_USER_CERT=/data/certs/hostcert.pem X509_USER_KEY=/data/certs/hostkey.pem myproxy-logon -d -n -s myproxy.cern.ch -o /data/certs/creds/74e1d131dc833733363da8f94a22d57e76af2782.5029 -l "6e638a1e10d725add1c6df5a2a83c424a5141459" -t 168:00'
 output : 
 error: Failed to receive credentials.
ERROR from myproxy-server:
X509_verify_cert() failed: certificate revoked
```

[2]
```
DEBUG 2016-03-07 19:29:35,639: 	 Executing : 
 command : myproxy-info -l 6e638a1e10d725add1c6df5a2a83c424a5141459 -s myproxy.cern.ch
 output : username: 6e638a1e10d725add1c6df5a2a83c424a5141459
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sbreeze/CN=763090/CN=Shane Davy Breeze
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(045|052|021|031|0118|0118a|0119).cern.ch
  timeleft: 593:11:28  (24.7 days)
```

**Comment by belforte** [comment]
I decided not to add a new `crab cleanCredential` command, but rather wrote a FAQ
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#crab_command_fails_with_Impossib
