### ISSUE TITLE
odd error in REST: can't talk to PhEDEx

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5232]
following up on this user problem report
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1692.html
I was lead to
vocms022: /build/srv-logs/vocms0165/crabserver/crabserver-20160526.log

where I find 

```
[26/May/2016:16:39:51]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 082c2f233b8e208fd8cd895ced8c9ab2 (Execution error)
[26/May/2016:16:39:51]    Traceback (most recent call last):
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Format.py", line 228, in stream_chunked
[26/May/2016:16:39:51]        for obj in stream:
[26/May/2016:16:39:51]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 9f7de5218b272a32d6394ef9101b3c1a (Execution error)
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 149, in getFiles
[26/May/2016:16:39:51]    Traceback (most recent call last):
[26/May/2016:16:39:51]        raise ExecutionError("Exception while contacting PhEDEX.")
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Format.py", line 228, in stream_chunked
[26/May/2016:16:39:51]    ExecutionError: ExecutionError 082c2f233b8e208fd8cd895ced8c9ab2 [HTTP 500, APP 403, MSG 'Execution error', INFO 'Exception while contacting PhEDEX.', ERR None]
[26/May/2016:16:39:51]        for obj in stream:
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 149, in getFiles
[26/May/2016:16:39:51]  SERVER HTTP ERROR cherrypy._cperror.HTTPError 01d90be44ee357645b1cb3e5f2e54755 ((500, 'Execution error'))
[26/May/2016:16:39:51]        raise ExecutionError("Exception while contacting PhEDEX.")
[26/May/2016:16:39:51]    Traceback (most recent call last):
[26/May/2016:16:39:51]    ExecutionError: ExecutionError 9f7de5218b272a32d6394ef9101b3c1a [HTTP 500, APP 403, MSG 'Execution error', INFO 'Exception while contacting PhEDEX.', ERR None]
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 701, in default
[26/May/2016:16:39:51]  SERVER HTTP ERROR cherrypy._cperror.HTTPError 445aea74a26fb4b1f983b778d844ce1f ((500, 'Execution error'))
[26/May/2016:16:39:51]        return self._call(RESTArgs(list(args), kwargs))
[26/May/2016:16:39:51]    Traceback (most recent call last):
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 811, in _call
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 701, in default
[26/May/2016:16:39:51]        return stream_maybe_etag(apiobj.get('etag_limit', self.etag_limit), etagger, reply)
[26/May/2016:16:39:51]        return self._call(RESTArgs(list(args), kwargs))
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Format.py", line 510, in stream_maybe_etag
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 811, in _call
[26/May/2016:16:39:51]        raise cherrypy.HTTPError(int(err), message)
[26/May/2016:16:39:51]        return stream_maybe_etag(apiobj.get('etag_limit', self.etag_limit), etagger, reply)
[26/May/2016:16:39:51]    HTTPError: (500, 'Execution error')
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Format.py", line 510, in stream_maybe_etag
[26/May/2016:16:39:51] vocms0165.cern.ch 212.189.205.6 "GET /crabserver/prod/workflow?workflow=160524_152155%3Agminiell_crab_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8&subresource=logs&limit=-1 HTTP/1.1" 500 Internal Server Error [data: 5908 in 726 out 140555299 us ] [auth: OK "/C=IT/O=INFN/OU=Personal Certificate/L=Bari/CN=Giorgia Miniello" "" ] [ref: "" "CRABClient/3.3.1605" ]
[26/May/2016:16:39:51]        raise cherrypy.HTTPError(int(err), message)
[26/May/2016:16:39:51]    HTTPError: (500, 'Execution error')

```

**Comment by mmascher** [comment]
Looks like there was a phedex error:

```
[26/May/2016:16:39:51]      File "/data/srv/beHG1605c/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1605.rc1-comp/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 149, in getFiles
[26/May/2016:16:39:51]  SERVER HTTP ERROR cherrypy._cperror.HTTPError 01d90be44ee357645b1cb3e5f2e54755 ((500, 'Execution error'))
[26/May/2016:16:39:51]        raise ExecutionError("Exception while contacting PhEDEX.")
```

AFAIU the error is temporary and there is not much we acn do.

**Comment by belforte** [comment]
should tell a bit more about what was doing which failed, IIUC the error has to come from
```
pfn = self.phedex.getPFN(site, lfn)[(site, lfn)]
```
so should print that and the current values of `site` and `lfn`. 

looking in the WMCore part, the error was while processing the JSON output of the http call, which may mean that WMCore is trying to parse an error message as a JSON result and should in turn be fixed to throw  a more useful exception.

**Comment by belforte** [comment]
basically this means:
put a useful message in here:
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L189

so that one can e.g. try to reproduce interactively and help phedex people to solve.
