### ISSUE TITLE
CRAB server fails on fake ASO report created by PostJob

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5324]
when PostJob creates a fact ASO report because CouchDB is not responding, it make CRAB server crash on crab status commands with this traceback
```
01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV ENTER cms_analysis_reqmgr_r@cmsr CRABInterface.RESTBaseAPI.RESTBaseAPI (GET prod workflow) inuse=0 idle=2
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV (previously QLPZkWnvuMoJ) connected, client: 11.2.0.4.0, server: 11.2.0.4.0, stmtcache: 50
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV ping
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV check [select sysdate from dual]
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV connection established
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV prepare [SELECT tm_taskname, panda_jobset_id, tm_task_status, tm_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_args, panda_resubmitted_jobs, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir, tm_asourl,              tm_asodb, tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time              FROM tasks WHERE tm_taskname=:taskname]
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV execute: () {'taskname': '161130_205910:gsfs_crab_EPOSpPbMinBias2510_2510_GEN_SIM_v2'}
[01/Dec/2016:13:01:34]  SERVER DATABASE ERROR 500/403 Execution error __builtins__.KeyError f76c2631e73da32808e922f5920efa0e [instance: prod] ('results'); last statement: SELECT tm_taskname, panda_jobset_id, tm_task_status, tm_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_args, panda_resubmitted_jobs, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir, tm_asourl,              tm_asodb, tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time              FROM tasks WHERE tm_taskname=:taskname; binds: (), {'taskname': '161130_205910:gsfs_crab_EPOSpPbMinBias2510_2510_GEN_SIM_v2'}; offset: None
[01/Dec/2016:13:01:34]    Traceback (most recent call last):
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1739, in dbapi_wrapper
[01/Dec/2016:13:01:34]        return handler(*xargs, **xkwargs)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/RESTUserWorkflow.py", line 667, in get
[01/Dec/2016:13:01:34]        result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/DataUserWorkflow.py", line 165, in status
[01/Dec/2016:13:01:34]  RESTSQL:EwRrWQgCKHvV disconnecting
[01/Dec/2016:13:01:34]        return self.workflow.status(workflow, userdn, userproxy, verbose=verbose)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/Utils.py", line 186, in throttled_wrapped_function
[01/Dec/2016:13:01:34]        return fn(*args, **kw)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/Utils.py", line 144, in wrapped_func
[01/Dec/2016:13:01:34]        return func(*args, **kwargs)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 530, in status
[01/Dec/2016:13:01:34]        taskStatus = self.taskWebStatus({'CRAB_UserWebDir' : row.user_webdir}, verbose, result)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 811, in taskWebStatus
[01/Dec/2016:13:01:34]        self.parseASOState(fp, nodes, statusResult)
[01/Dec/2016:13:01:34]      File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1611.rc1-comp3/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 1049, in parseASOState
[01/Dec/2016:13:01:34]        for docid, result in data['results'].iteritems():
[01/Dec/2016:13:01:34]    KeyError: 'results'

```

**Comment by belforte** [comment]
@mmascher IIRC you already have a fix for this. Did you also deploy it ? Can you please put the correct reference to the merged PR and close ?

**Comment by emaszs** [comment]
Actually fixed already with https://github.com/dmwm/CRABServer/commit/05c4b027fdd743ecf4067f3d9ede9f6f65cf1f44
