### ISSUE TITLE
catch all exceptions in script which feeds kibana

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5390]
make sure lock file is always deleted

**Comment by belforte** [comment]
actually cron died with
```
Traceback (most recent call last):
  File "/home/crab3/GenerateXMLForTW.py", line 261, in <module>
    pr.execute()
  File "/home/crab3/GenerateXMLForTW.py", line 191, in execute
    numDagIdle = len(idleDags)
TypeError: object of type 'int' has no len()
```
which is due to wrong type returned in the except clause
https://github.com/dmwm/CRABServer/blob/master/scripts/Monitor/GenerateXMLForTW.py#L184
and
https://github.com/dmwm/CRABServer/blob/master/scripts/Monitor/GenerateXMLForTW.py#L189
