### ISSUE TITLE
when jobs run into timeout, the CMSSW stdout/err is not printed

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5410]
example
```
PSetDump.py
==== CMSSW JOB Execution started at Wed Feb 22 21:35:51 2017 ====
2017-02-22 21:35:51,957:INFO:Scram:    Invoking command: python -c 'from PSetTweaks.WMTweak import makeTweak;config = __import__("WMTaskSpace.cmsRun.PSet", globals(), locals(), ["process"], -1);tweakJson = makeTweak(config.process).jsondictionary();print tweakJson["process"]["outputModules_"]'
2017-02-22 21:35:52,995:INFO:CMSSW:User files are 
2017-02-22 21:35:52,995:INFO:CMSSW:User sandboxes are sandbox.tar.gz
2017-02-22 21:35:52,995:INFO:CMSSW:CMSSW configured for 1 cores
2017-02-22 21:35:52,996:INFO:CMSSW:Executing CMSSW step
2017-02-22 21:35:52,996:INFO:CMSSW:Runing SCRAM
2017-02-22 21:35:53,547:INFO:CMSSW:Running PRE scripts
2017-02-22 21:35:53,548:INFO:CMSSW:RUNNING SCRAM SCRIPTS
2017-02-22 21:35:53,551:INFO:Scram:    Invoking command: python /tmp/glide_HT5maw/execute/dir_170808/TweakPSet.py --location=/tmp/glide_HT5maw/execute/dir_170808 --inputFile='job_input_file_list_105.txt' --runAndLumis='job_lumis_105.json' --firstEvent=None --lastEvent=None --firstLumi=None --firstRun=None --seeding=AutomaticSeeding --lheInputFiles=False --oneEventMode=0 --eventsPerLumi=None --maxRuntime=-1 

2017-02-22 21:35:54,397:INFO:CMSSW:Executing CMSSW. args: ['/bin/bash', '/tmp/glide_HT5maw/execute/dir_170808/cmsRun-main.sh', '', 'slc6_amd64_gcc530', 'scramv1', 'CMSSW', 'CMSSW_8_0_26_patch2', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', 'sandbox.tar.gz', '', '']
======== Figuring out long exit code of the job for condor_chirp ========
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/lib64/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
==== Failed to load the long exit code from jobReport.json.105. Falling back to short exit code ====
======== Short exit code also missing. Settint exit code to 80001 ========
======== Finished condor_chirp -ing the exit code of the job. Exit code of condor_chirp: 0 ========
Job Running time in seconds:  75082
./CMSRunAnalysis.sh: line 169: 170980 Killed                  python CMSRunAnalysis.py -r "`pwd`" "$@"
+ jobrc=137
+ set +x
== The job had an exit code of 137 
======== CMSRunAnalysis.py FINISHING at Thu Feb 23 18:27:12 GMT 2017 ========
Job was killed. Check Postjob for kill reason.
ERROR: Job was killed. Logging ulimits:
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
```

**Comment by belforte** [comment]
that was jobs 105 in this task
http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=oglez&refresh=0&table=Jobs&p=5&records=25&activemenu=2&status=&site=&tid=170222_205626%3Aoglez_crab_ogjob_2017_02_22_215616_electron_data2016g_3feb2017_v1_80VMINI

**Comment by belforte** [comment]
initial assumption after some code readin is that I can simply add `tail -100 cmsRun-stdout.log` in here
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.sh#L12-L28
will not bother to call in the stdout trimming and clipping... just try to tell what it was doing when it was signaled.

**Comment by belforte** [comment]
I need to reproduce the problem.

**Comment by belforte** [comment]
When I run test jobs, things work as  expected an desired.
THe only explanation for the problem which started this is that the job was somehow stuck in CMSSW initialization and when killed because of running out of time there was no stdout to print.

I am closing as INVALID.
