### ISSUE TITLE
Insufficient privileges when getting publication status from oracle DB during resubmission

### ISSUE THREAD

**Issue by emaszs** [dmwm/CRABServer#5459]
Not yet sure under what circumstances this happens, resubmission seems to work for me currently. Will keep trying to reproduce.

https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2762.html

From cmsweb crabserver log:
```
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe connection established
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe prepare [SELECT tm_username FROM tasks WHERE tm_taskname=:taskname]
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe execute: () {'taskname': '170329_161705:jpata_crab_SingleMuon-Run2016D-03Feb2017-v1_Mar29_rereco_v1'}
[03/Apr/2017:07:38:28]  DEBUG: authz user {'dn': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=jpata/CN=727914/CN=Joosep Pata', 'login': 'jpata', 'method': 'X509Proxy', 'roles': {'phedex-contact': {'group': set([]), 'site': set(['t3-ch-psi', 't2-ch-cscs', 't2-ch-cscs-hpc'])}, 'data-manager': {'group': set([]), 'site': set(['t3-ch-psi', 't2-ch-cscs', 't2-ch-cscs-hpc'])}, 'site-admin': {'group': set([]), 'site': set(['t3-ch-psi', 't2-ch-cscs', 't2-ch-cscs-hpc'])}}, 'name': u'Joosep Pata'} to access resources ['170329_161705:jpata_crab_SingleMuon-Run2016D-03Feb2017-v1_Mar29_rereco_v1']
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe prepare [SELECT tm_taskname, panda_jobset_id, tm_task_status, tm_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_args, panda_resubmitted_jobs, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir, tm_asourl,              tm_asodb, tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time              FROM tasks WHERE tm_taskname=:taskname]
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe execute: () {'taskname': '170329_161705:jpata_crab_SingleMuon-Run2016D-03Feb2017-v1_Mar29_rereco_v1'}
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe prepare [SELECT tm_id, tm_jobid, tm_publication_state, tm_start_time, tm_last_update FROM filetransfersdb                                        WHERE tm_username = :username AND tm_taskname = :taskname]
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe execute: () {'username': 'jpata', 'taskname': '170329_161705:jpata_crab_SingleMuon-Run2016D-03Feb2017-v1_Mar29_rereco_v1'}
[03/Apr/2017:07:38:28]  SERVER DATABASE ERROR 500/403 Execution error cx_Oracle.DatabaseError 5778a1e4f0e7ef957affeec96c58f770 [instance: prod] (ORA-01031: insufficient privileges); last statement: SELECT tm_id, tm_jobid, tm_publication_state, tm_start_time, tm_last_update FROM <**>filetransfersdb                                        WHERE tm_username = :username AND tm_taskname = :taskname; binds: (), {'username': 'jpata', 'taskname': '170329_161705:jpata_crab_SingleMuon-Run2016D-03Feb2017-v1_Mar29_rereco_v1'}; offset: 81
[03/Apr/2017:07:38:28]    Traceback (most recent call last):
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1739, in dbapi_wrapper
[03/Apr/2017:07:38:28]        return handler(*xargs, **xkwargs)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/RESTUserWorkflow.py", line 643, in post
[03/Apr/2017:07:38:28]        userdn=cherrypy.request.headers['Cms-Authn-Dn'])
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/DataUserWorkflow.py", line 147, in resubmit
[03/Apr/2017:07:38:28]        return self.workflow.resubmit(workflow, publication, jobids, force, siteblacklist, sitewhitelist, maxjobruntime, maxmemory, numcores, priority, userdn, userproxy)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/DataWorkflow.py", line 420, in resubmit
[03/Apr/2017:07:38:28]        statusRes = self.status(workflow, userdn, userproxy)[0]
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/Utils.py", line 186, in throttled_wrapped_function
[03/Apr/2017:07:38:28]        return fn(*args, **kw)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/Utils.py", line 144, in wrapped_func
[03/Apr/2017:07:38:28]        return func(*args, **kwargs)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 676, in status
[03/Apr/2017:07:38:28]        publicationInfo = self.publicationStatus(workflow, row.asourl, asodb, row.username)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/Utils.py", line 144, in wrapped_func
[03/Apr/2017:07:38:28]        return func(*args, **kwargs)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 844, in publicationStatus
[03/Apr/2017:07:38:28]        return self.publicationStatusOracle(workflow, user)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 905, in publicationStatusOracle
[03/Apr/2017:07:38:28]        res = list(self.api.query(None, None, self.transferDB.GetTaskStatusForPublication_sql, **binds))
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2123, in query
[03/Apr/2017:07:38:28]        c, _ = self.execute(sql, *binds, **kwbinds)
[03/Apr/2017:07:38:28]      File "/data/srv/beHG1703i/sw/slc6_amd64_gcc493/cms/crabserver/3.3.1703.rc5/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2064, in execute
[03/Apr/2017:07:38:28]        return c, c.execute(None, *binds, **kwbinds)
[03/Apr/2017:07:38:28]    DatabaseError: ORA-01031: insufficient privileges
[03/Apr/2017:07:38:28] vocms0163.cern.ch 192.33.123.29 "POST /crabserver/prod/workflow HTTP/1.1" 500 Internal Server Error [data: 6310 in 746 out 121295 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=jpata/CN=727914/CN=Joosep Pata" "" ] [ref: "" "CRABClient/3.3.1703" ]
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe disconnecting
[03/Apr/2017:07:38:28]  RESTSQL:xTDFEkMwSOVe DISCONNECTED cms_
```

**Comment by mmascher** [comment]
Last time I saw this was because we were using a server.get instead of a server.post. @dciangot , do you remember?

**Comment by emaszs** [comment]
We've already had a quick chat about this and @dciangot mentioned this, but if this https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L933 line is failing, does it matter what HTTP request it was called from initially? Seems to me like this wouldn't be related.

**Comment by emaszs** [comment]
Although the publicationStatus method is part of a GET API, whereas a resubmit request is a POST [1]. Is it the fact that it's exposed as a GET causing the problem? Furthermore, why am I able to resubmit my own tasks ( with publication ) successfully, at least on pre-prod? 


[1]
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L692

**Comment by mmascher** [comment]
This is called by a POST according to those logs (probably a resubmit?) which in turn call the status. All the POST uses the writer account on CMSWEB, and I suspect the writer account is not authorized to do SELECT for the FILETRANSFER table..

**Comment by emaszs** [comment]
Ohhh... so this is above CRAB and @dciangot was right :)

**Comment by emaszs** [comment]
Marco granted the SELECT permission to the writer account, I believe this is fixed now. Though I was not able to reproduce the problem because of the problems on ASO at the time (publication backlog), now I did a `--force` resubmission on a task that had some finished publications and it worked. That should've hit the query for the publication status on oracle which was previously failing.
