### ISSUE TITLE
task_process should not fail on missing events in condor log

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5661]
From Todd T:
```
On 21/03/18 21:58, Todd Tannenbaum wrote:
You cannot safely _always_ assume that you will always see an execute event before seeing a terminate event in the job event log (especially true in grid universe). Typically you will see an execute event first, but not guaranteed. About the only guarantees HTCondor gives is you will see a submit event before a terminate event, and that you will see a terminate event before the job leaves the queue.  Also be aware that in various corner cases it is possible to have duplicate events, e.g. two terminate events for the same job.

```
which came on the following up to
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3674.html

The relevant errors in task_process/cache_status.log are
```
ERROR:root:error during main loop
Traceback (most recent call last):
  File "task_process/cache_status.py", line 351, in main
    storeNodesInfoInFile()
  File "task_process/cache_status.py", line 292, in storeNodesInfoInFile
    parseJobLog(jobsLog, nodes, nodeMap)
  File "task_process/cache_status.py", line 94, in parseJobLog
    nodes[node]['WallDurations'][-1] = nodes[node]['EndTimes'][-1] - nodes[node]['StartTimes'][-1]
IndexError: list index out of range
```
which I tracked to the fact that  the Executing message is missing for one job

```
The condor log (we submit jobs asking for a userlog file) is
https://cmsweb.cern.ch/scheddmon/0122/cms898/180316_220223:emacdona_crab_Step1_DQM_test2/SPOOL_DIR/job_log
but will be deeted in a month, so I am pasting it at the bottom (it a short log,
5 jobs were submitted and immediately failed when executing)

One can see immediately that one jobs looks different:

[root@vocms0122 cluster26368119.proc0.subproc0]# condor_q -userlog job_log


-- Userlog: job_log @ 03/20/18 23:24:24
 ID          OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
26368125.0   root            3/16 23:03   0+00:05:01 X  0    0.0 ???
26368126.0   root            3/16 23:03   0+00:00:00 C  0    0.0 ???
26368127.0   root            3/16 23:03   0+00:05:01 X  0    0.0 ???
26368128.0   root            3/16 23:03   0+00:05:01 X  0    0.0 ???
26368129.0   root            3/16 23:03   0+00:05:01 X  0    0.0 ???

5 jobs; 1 completed, 4 removed, 0 idle, 0 running, 0 held, 0 suspended
[root@vocms0122 cluster26368119.proc0.subproc0]#

clusterId 26368126 lacks the "Job executing on host" line.

[root@vocms0122 cluster26368119.proc0.subproc0]# grep executing job_log
001 (26368125.000.000) 03/16 23:10:44 Job executing on host:
001 (26368127.000.000) 03/16 23:10:44 Job executing on host:
001 (26368128.000.000) 03/16 23:10:44 Job executing on host:
001 (26368129.000.000) 03/16 23:10:44 Job executing on host:
[root@vocms0122 cluster26368119.proc0.subproc0]#
```

**Comment by belforte** [comment]
for reproducing/debugging, here's the condor job_log
[job_log.txt](https://github.com/dmwm/CRABServer/files/1837334/job_log.txt)

**Comment by belforte** [comment]
What condor does in such cases is to simply report 0:00 for running time.
Maybe we can start with a simply tif to deal with missing start execution command and worry later about the possibility that even more messages may be missing and e.g. how to catch that a job is runnng by things like periodic image size reports in case start execution msg is missing.
E.g. for one of the jobs in above example:
```
[root@vocms0121 cluster25628358.proc0.subproc0]# condor_q 25628362 -userlog job_log 


-- Userlog: job_log @ 07/19/18 09:03:30
 ID          OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
25628362.0   root            7/18 21:29   0+00:00:00 C  0    0.0 ???

1 jobs; 1 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended

or from central logs:

[root@vocms0121 cluster25628358.proc0.subproc0]# condor_history -m 1 25628362  
 ID     OWNER          SUBMITTED   RUN_TIME     ST COMPLETED   CMD            
25628362.0   cms814          7/18 21:29   0+00:05:55 C   7/18 21:44 /data/srv/glidecondor/condor_local/spool/8358/0/cluster25628358.proc0.s
[root@vocms0121 cluster25628358.proc0.subproc0]# 

```
