### ISSUE TITLE
align CRAB to most recent WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5673]
see
https://github.com/dmwm/WMCore/pull/8611#issuecomment-389294737

**Comment by belforte** [comment]
looks like it is this one
https://github.com/dmwm/WMCore/releases/tag/1.1.14

**Comment by belforte** [comment]
I the end @amaltaro says that we need a separate CRAB branch [1]
so he made this tag:
https://github.com/dmwm/WMCore/releases/tag/1.1.14.crab1


[1]
https://github.com/dmwm/WMCore/pull/8611#issuecomment-397079345

**Comment by belforte** [comment]
I gave a first try building TW with wmcore 1.1.14.crab1 and put it in pre-prod, but got many errors.
Maybe I did something wrong.
Now I deployed HG1806 on my VM ad redirected crabserver and taskworker to the new WMCore via a git checkout, and it seems to work. But I have to at least verify that the new code is used.
Than I'll try again a build and should have a reference to compare with if I screw up again.

**Comment by belforte** [comment]
It works in my VM.
But the CERN stageout still fails with `xrdcp: Invalid option, '--wma-disablewriterecovery'.` 
that option is not present in the old WMCore we were using, but it is in new version
pff...

```
xrdcp --force --nopbar --wma-disablewriterecovery  "kk.root"  "root://eoscms.cern.ch//eos/cms/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_112519/0000/kk_2.root" 

2018-07-01T11:51:10 : Running the stage out...
Local File Size is: 42348790
xrdcp: Invalid option, '--wma-disablewriterecovery'.

Usage:   xrdcp [<options>] <src> [<src> [. . .]] <dest>

Options: [--cksum <args>] [--debug <lvl>] [--coerce] [--dynamic-src]
         [--force] [--help] [--infiles <fn>] [--license] [--nopbar]
         [--path] [--posc] [--proxy <host>:<port>] [--recursive]
         [--retry <n>] [--server] [--silent] [--sources <n>] [--streams <n>]
         [--tpc {first|only}] [--verbose] [--version] [--xrate <rate>]
         [--parallel <n>] [--zip <file>]
<src>:   [[x]root://<host>[:<port>]/]<path> | -
<dest>:  [[x]root://<host>[:<port>]/]<path> | -
[ERROR] Server responded with an error: [3011] Unable to stat /eos/cms/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_112519/0000/kk_2.root

```

**Comment by belforte** [comment]
Stage out at CERN works, I had simply forgotton to run `updateTMRuntime.sh`
Will try again to build server and worker with same new WMCore and check them.

**Comment by belforte** [comment]
I built the TW with new WMCore and deployed it, and jobs fail with:
```
==== FAILURE WHEN LOADING WMCORE AT Tue Jul 10 13:58:04 2018 ====
Traceback (most recent call last):
  File "CMSRunAnalysis.py", line 847, in <module>
    from WMCore.Algorithms.BasicAlgos import calculateChecksums
ImportError: No module named BasicAlgos
```
which is OK since BasicAlgs.py is gone from WMCore.
https://github.com/dmwm/WMCore/tree/1.1.14.crab1/src/python/WMCore/Algorithms
I do not know how it came that it was working in previous test.
But surely CMSRunAnalysis.py needs fixing.

Bottom line,updatng WMcore is not transparent :-(

**Comment by belforte** [comment]
Likely it was this commit 3 months ago:
https://github.com/dmwm/WMCore/commit/4b2735e47b73132096a319d6dbf462ca0ca2e710#diff-624e34dd78eb39079cd9deb0003cecac
@amaltaro surely this was for the better, but can you please broadcast a warning next time a non-backward compatible change is planned for WMCore ?

**Comment by belforte** [comment]
@amaltaro do nothing, I'd rather have a new CRAB version which works with new WMcore. Not get stuck again with obsolete tags !

**Comment by amaltaro** [comment]
Daahhh, you're right! There is nothing for me to do here :) Thanks

**Comment by belforte** [comment]
but if you know of other similar situations... before I find them one after another, shout !!

**Comment by belforte** [comment]
- [1] update CMSRunAnalysis.py to import from Utils/FileTools
- [2] update bin/htcondor_make_runtime.sh not to e stuck to WMCOREVER=1.0.14_crab_4

**Comment by belforte** [comment]
I need two actions here

- [ ] update CMSRunAnalysis.py to import from Utils/FileTools
- [ ]  update bin/htcondor_make_runtime.sh not to e stuck to WMCOREVER=1.0.14_crab_4

**Comment by mmascher** [comment]
For the RPM you do not need to update bin/htcondor_make_runtime.sh, you will use whatever you put in the specfile AFAIR.

Remember that in general you might need to add Utils/FileTools here https://github.com/dmwm/WMCore/blob/master/setup_dependencies.py#L138 ,  although you might be lucky this time since Utils+ is already there (the + adds the whole dir)

**Comment by belforte** [comment]
@mmascher thanks, Yes. I am aware now that bin/htcondor_make_runtime.sh is not relevant for RPMs, this is the reason why I did not hit the error when updating only WMCore in the tw personal installation, but only when I deployed via RPM's
But isn't the second part (updating WMCore...dependencies...) for @amaltaro instead ?

**Comment by mmascher** [comment]
We are the ones who knows the dependencies and traditionally we have been updating that dependency file for our needs. Alan can modify it sure, but we might need to tell him what to add. Anyway, for this case we are fine, I was just pointing it out so that you knows (it's a common pitfall, and you only realize those things when you build the rpm/install it/and send some tasks)

**Comment by belforte** [comment]
RATS ! Now that I read the https://github.com/dmwm/WMCore/blob/master/setup_dependencies.py#L138 file I see that it has dependencies for crabserve etc. not for WMCore.
I do not like this way of tracking dependencies, but maybe its the least bad of many evils. I will try to find a good place for putting a note in the documentation, since I will have surely forgotten by Aug 10.

**Comment by belforte** [comment]
New WMCore + fixes now work again on SL6 install + patches. Again, to be safe, I built a new CRAB release and will deploy on my VM
https://github.com/dmwm/CRABServer/releases/tag/3.3.1809.rc2

**Comment by belforte** [comment]
New WMCore + fixes now work again on SL6 install + patches. Again, to be safe, I built a new CRAB release and will deploy on my VM
https://github.com/dmwm/CRABServer/releases/tag/3.3.1809.rc2

**Comment by belforte** [comment]
things work on my VM but failed on prep-prod.
I can make it fail on my VM although with a different error by
`unset X509_USER_PROXY`. So looks like it was accidentally working due to  the presence of a personal proxy.
The error in my VM is:
```
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 140, in execute
    locationsMap = self.dbs.listFileBlockLocation(list(blocks), dbsOnly=dbsOnly)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 650, in listFileBlockLocation
    raise Exception(msg)
Exception: Error while getting block location from PhEDEx for block_name=['/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#3517e1b6-76e3-11e7-a0c8-02163e00d7b3', '/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#35197562-76e3-11e7-a0c8-02163e00d7b3'])
[Errno 22] Invalid argument
```

**Comment by mmascher** [comment]
Really curious to know where the "Invalid Argument" is coming from. The real error gets swallowed here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L647-L650
Should probably print the exception traceback in DBS3Reader to see more.

Is it possible os.environ['X509_USER_PROXY'] is still there but empty giving the invalid argument when you try to open the file to connect do cmsweb?

Anyway, if the real error in preprod is different it does not help..

**Comment by belforte** [comment]
Yes it is odd. But I will find out. sent from Stefano's mobileOn Jul 13, 2018 9:20 PM, Marco Mascheroni <notifications@github.com> wrote:Really curious to know where the "Invalid Argument" is coming from. The real error gets swallowed here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L647-L650
Should probably print the exception traceback in DBS3Reader to see more.
Is it possible os.environ['X509_USER_PROXY'] is still there but empty giving the invalid argument when you try to open the file to connect do cmsweb?
Anyway, if the real error in preprod is different it does not help..

**Comment by belforte** [comment]
and this is the error in pre-prod. Again in a call to PhEDEx. I think in WMCore they
introduced an other argument. But this was when I looked at things a few weeks ago,
maybe I was mistaken. debug time.

```
2018-07-13 15:24:53,353:ERROR:Handler:Problem handling 180713_132428:belforte_crab_20180713_152352 because of <@========== WMException Start ==========@>
Exception Class: WMException
Message: Request requires a host certificate and key
	ModuleName : WMCore.Services.Requests
	MethodName : getKeyCert
	ClassInstance : None
	FileName : /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py
	ClassName : None
	LineNumber : 420
	ErrorNr : WMCORE-11

Traceback: 
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 131, in actionWork
    nextinput = output.result

<@---------- WMException End ----------@> failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DagmanCreator.py", line 1183, in execute
    info, params, inputFiles, splitterResult = self.executeInternal(*args, **kw)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DagmanCreator.py", line 1172, in executeInternal
    info, splitterResult, subdags, dagSpecs = self.createSubdag(*args, **kw)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DagmanCreator.py", line 875, in createSubdag
    datasites, outfiles, startjobid, parent=parent, stage=stage)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DagmanCreator.py", line 600, in makeDagSpecs
    lastDirectPfn = self.resolvePFNs(task['tm_asyncdest'], directDest)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DagmanCreator.py", line 370, in resolvePFNs
    pfn_info = self.phedex.getPFN(nodes=dest_sites_, lfns=lfns)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/PhEDEx/PhEDEx.py", line 367, in getPFN
    data = self._getResult('lfn2pfn', args=input_dict, verb='GET')
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/PhEDEx/PhEDEx.py", line 50, in _getResult
    fobj = self.refreshCache(ifile, callname, args, verb=verb)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 201, in refreshCache
    self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Service.py", line 272, in getData
    contentType = contentType)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 150, in makeRequest
    encoder, decoder, contentType)
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 162, in makeRequest_pycurl
    ckey, cert = self.getKeyCert()
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py", line 420, in getKeyCert
    "WMCORE-11")
WMException: <@========== WMException Start ==========@>
Exception Class: WMException
Message: Request requires a host certificate and key
	ModuleName : WMCore.Services.Requests
	MethodName : getKeyCert
	ClassInstance : None
	FileName : /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py
	ClassName : None
	LineNumber : 420
	ErrorNr : WMCORE-11

Traceback: 
  File "/data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 131, in actionWork
    nextinput = output.result

<@---------- WMException End ----------@>

```

**Comment by belforte** [comment]
here's where the invalid argument comes from
```
> /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/external/py2-httplib2/0.7.1-comp4/lib/python2.7/site-packages/httplib2/__init__.py(1309)request()
-> self.disable_ssl_certificate_validation)
(Pdb) 
Enter PEM pass phrase:
IOError: (22, 'Invalid argument')
```

**Comment by belforte** [comment]
most likely becasue at this point the code being executed is
```
1302 	                    if certs:
1303 	                        conn = self.connections[conn_key] = connection_type(
1304 	                                authority, key_file=certs[0][0],
1305 	                                cert_file=certs[0][1], timeout=self.timeout,
1306 	                                proxy_info=self.proxy_info,
1307 	                                ca_certs=self.ca_certs,
1308 	                                disable_ssl_certificate_validation=
1309 ->	                                        self.disable_ssl_certificate_validation)
```
but
```(Pdb) certs
[('/afs/cern.ch/user/b/belforte/.globus/userkey.pem', '/afs/cern.ch/user/b/belforte/.globus/usercert.pem')]
(Pdb) 
```

**Comment by belforte** [comment]
relevant stack trace
```
-> output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py(142)execute()
-> locationsMap = self.dbs.listFileBlockLocation(list(blocks), dbsOnly=dbsOnly)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py(646)listFileBlockLocation()
-> blocksInfo = self.phedex.getReplicaPhEDExNodesForBlocks(block=fileBlockNames, complete='y')
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/PhEDEx/PhEDEx.py(523)getReplicaPhEDExNodesForBlocks()
-> response = self._getResult(callname, args=kwargs)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/PhEDEx/PhEDEx.py(50)_getResult()
-> fobj = self.refreshCache(ifile, callname, args, verb=verb)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Service.py(201)refreshCache()
-> self.getData(cachefile, url, inputdata, incoming_headers, encoder, decoder, verb, contentType)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Service.py(272)getData()
-> contentType = contentType)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py(153)makeRequest()
-> encoder, decoder, contentType)
  /data/srv/TaskManager/3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py(250)makeRequest_httplib()

```

**Comment by belforte** [comment]
and indeed executing these beforte starting it make the TW work on my VM:
```
export X509_USER_CERT=/data/certs/servicecert.pem 
export X509_USER_KEY=/data/certs/servicekey.pem
```

**Comment by belforte** [comment]
also works in preprod, at least as talking to PhEDEx. But it is currently failing to submit to schedd.. maybe for other reasons ?
Bottom line:
somthing has changed in WMCore so that cert/key is not propagated anymore from
dbsreader instance to phedex instance (if I can guess how it was working before).
OTOH we do not want to keep X509 variables around since they are likely a problem with HTCondor authentication. So a more clean solution, which does not require changes to configs, setups etc. is needed anyhow

**Comment by belforte** [comment]
Most puzzling:
looking at what's changed in WMCore, all the part about DBS and PhEDEx seems the same
https://github.com/dmwm/WMCore/compare/1.1.14.crab1...1.1.2.crab8

Why all this mess with certificate then ?

**Comment by belforte** [comment]
I think, difference in github does not work well.
The following from the different deployed versions of CRAB seems more telling
```
belforte@stefanovm2/TaskManager> diff -y  --width=180 --suppress-common-lines --exclude='*pyc' 3.3.1804.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1804.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py 3.3.1809.rc2/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1809.rc2/lib/python2.7/site-packages/WMCore/Services/Requests.py
										      >	from __future__ import division, print_function
										      >	from Utils.CertTools import getKeyCertFromEnv, getCAPathFromEnv
										      >	try:
										      >	    from httplib2 import ServerNotFoundError
										      >	except ImportError:
										      >	    #Mock ServerNotFoundError since we don't want that WMCore depend on httplib2 usin
										      >	    class ServerNotFoundError(Exception):
										      >	        pass
										      >
										      >
										      <
										      >	        self.setdefault("cert", None)
										      >	        self.setdefault("key", None)
										      >	        self.setdefault('capath', None)
										      >	        except ServerNotFoundError as ex:
										      >	            # DNS cannot resolve this domain name, let's call it 'Service Unavailable
										      >	            e = HTTPException()
										      >	            setattr(e, 'url', uri)
										      >	            setattr(e, 'status', 503)
										      >	            setattr(e, 'reason', 'Service Unavailable')
										      >	            setattr(e, 'result', str(ex))
										      >	            raise e
        cert = None								      |
        key = None								      <
        if 'cert' in self and 'key' in self and self['cert'] and self['key']:	      |	        if self['cert'] and self['key']:
										      |	        else:
        # Now we're trying to guess what the right cert/key combo is...		      |	            key, cert = getKeyCertFromEnv()
        # First preference to HOST Certificate, This is how it set in Tier0	      <
        elif 'X509_HOST_CERT' in os.environ:					      <
            cert = os.environ['X509_HOST_CERT']					      <
            key = os.environ['X509_HOST_KEY']					      <
        # Second preference to User Proxy, very common				      <
        elif 'X509_USER_PROXY' in os.environ and os.path.exists(os.environ['X509_USER <
            cert = os.environ['X509_USER_PROXY']				      <
            key = cert								      <
        # Third preference to User Cert/Proxy combinition			      <
        elif 'X509_USER_CERT' in os.environ:					      <
            cert = os.environ['X509_USER_CERT']					      <
            key = os.environ['X509_USER_KEY']					      <
        # TODO: only in linux, unix case, add other os case			      <
        # look for proxy at default location /tmp/x509up_u$uid			      <
        elif os.path.exists('/tmp/x509up_u' + str(os.getuid())):		      <
            cert = '/tmp/x509up_u' + str(os.getuid())				      <
            key = cert								      <
										      <
        # if interactive we can use an encrypted certificate			      <
        elif sys.stdin.isatty():						      <
            if os.path.exists(os.environ['HOME'] + '/.globus/usercert.pem'):	      <
                cert = os.environ['HOME'] + '/.globus/usercert.pem'		      <
                if os.path.exists(os.environ['HOME'] + '/.globus/userkey.pem'):	      <
                    key = os.environ['HOME'] + '/.globus/userkey.pem'		      <
                else:								      <
                    key = cert							      <
        if key and cert:							      |	        if key is None or cert is None:
            if not os.path.exists(cert) or not os.path.exists(key):		      |	            raise WMException('Request requires a host certificate and key',
                raise WMException('Request requires a host certificate and key',      <
        cacert = None								      |	        capath = self['capath']
        if 'capath' in self:							      |	        if not capath:
            cacert = self['capath']						      |	            capath = getCAPathFromEnv()
        elif "X509_CERT_DIR" in os.environ:					      |	        return capath
            cacert = os.environ["X509_CERT_DIR"]				      <
        return cacert								      <
        except (IOError, OSError):						      |	        except Exception:
belforte@stefanovm2/TaskManager> 

```

**Comment by belforte** [comment]
i.e. the way to autodiscover certificates has changed.
I'd like to avoid WMCore guessing and tell it explicitly what to use, of course

**Comment by belforte** [comment]
and by the way the error I was getting in pre-prod comes indeed from here
https://github.com/dmwm/WMCore/blob/1.1.14_crab/src/python/WMCore/Services/Requests.py#L401-L423

Now... if I only knew how exactly to make sure that the dreaded self dictionary contains the proper key/cert...

**Comment by mmascher** [comment]
Maybe one of the problem is that the phedex object here is not initialized properly? => https://github.com/dmwm/WMCore/blob/e94c88658e4aca3973bee32ba793fe67b0eff316/src/python/WMCore/Services/DBS/DBS3Reader.py#L66

Like here: https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L271

That's just something I noticed, I am looking really quickly. Ping me on gmail @belforte we can have a look at this together if you want.

**Comment by belforte** [comment]
thanks @mmascher that's exactly what bothers me. But the way DBSReader is defined does not allow to pass cert/key IMHO, so I am puzzled how they make this work in WMA. Though I suspect that they consolidated the code to aways use X509 env. vars.  I guess a clean way would be to bypass a lot of WMCore overhead and talk directly to PhEDEx. I will see if next week at CERN I can tal kwith Alan about this.

**Comment by belforte** [comment]
Having slept on it, talked with @amaltaro , etc. I think that we need to improve TW code to be more careful in cleaning/setting/restoring the X509 env. before various services are used.

E.g. the code @mmascher pointed at before
https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L271
allows for passing a proxy, but not a cert/key pair.
The problem IIRC is that no matter what our API's offer and say, the underlaying SSL system libraries have their own idea of where to pick credentials among X509_USER_PROXY/CERT/KEY, ~/.globus, /tmp/x509* etc.
So I will add a couple of utility functions to save/switch/restore.
And hopefully it will be the end to all such issues which plagued us for years.
@mmascher I will not be able to this immediately, so if you have other ideas, you are welcome to offer them.

**Comment by belforte** [comment]
@mmascher yes this is a nice example
https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L271
too bad that other part of CRABServer does things differently
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L328
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L370

what would be the cleanest way to harmonize ?
was there some specific reason why DagmanCreator can't use the utilities in ServerUtilities ?

So far I have wrapped basically all of DBSDataDiscovery into save/restor x509_proxy/cert/key and it works, but as in that example above there are other places where environment matters.

**Comment by belforte** [comment]
by the way in DagmanCreator self.phedex is created in the __init__ metod, but only used in the resolvePFNs one, which is also used only once.
Would make more sense to instantiate phedex in that resolvePFN !
(there are more odd things in that resolvePFN like taking lists as input, creating a list of result, but only returning result[0]  but let's ignore).

**Comment by belforte** [comment]
puzzled.
After I wrapped all DBS/PhEDEx calls I now have failure to submit to schedd.
Which what looks like GSI problem, but while up to now a band x509 env/setup was showing as a cleaer "can't map DN such and such ... in the /var/log/message file as reported form gsi-pep" now I verify that the proper user proxy is passed to htcondor binding (which I can't follow in with pdb since it is C++ code), no error in /var/log/messages, but /var/log/condor/SchedLog has
```
07/17/18 02:21:36 (pid:7836) Condor GSI authentication failure
GSS Major Status: Communications Error
GSS Minor Status Error Chain:
(null)
07/17/18 02:21:36 (pid:7836) DC_AUTHENTICATE: authentication of <128.142.142.209:47224> did not result in a valid mapped user name, which is required for this command (1112 QMGMT_WRITE_CMD), so aborting.
```
note that 128.142.142.209 is the IP of my VM: stefanovm2.cern.ch

By thw way I see a small amount of such messages also in e.g. vocms0195 with reference to vocms052 IP number... and that was surely not me experimenting with code.

**Comment by belforte** [comment]
for reference, the SchedLog on same schedd when submitting via production TW has
```
07/17/18 02:51:38 (pid:13339) This process has a valid certificate & key
07/17/18 02:51:38 (pid:13339) ZKM: setting FQAN: /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it,/cms/Role=NULL/Capability=NULL,/cms/ALARM/Role=NULL/Capability=NULL,/cms/TEAM/Role=NULL/Capability=NULL,/cms/integration/Role=NULL/Capability=NULL,/cms/itcms/Role=NULL/Capability=NULL
07/17/18 02:51:38 (pid:13339) Finishing authenticate_server_gss_post with status=1
07/17/18 02:51:38 (pid:13339) Finishing authenticate_server_gss_post with status=1
07/17/18 02:51:38 (pid:13339) ZKM: successful mapping to GSS_ASSIST_GRIDMAP
07/17/18 02:51:39 (pid:13339) OwnerCheck retval 1 (success),no ad
07/17/18 02:51:39 (pid:13339) schedd: NewCluster rval 6469383 errno 0

```

**Comment by belforte** [comment]
as feared, submission works if I set this before starting the TW in my VM:
```
X509_USER_PROXY=/tmp/x509up_u8516
```
and of course have a valid proxy there.
While the TW is actually trying to use for submission `/data/certs/creds/cfa0cb32f2043a8042e1290debf652b8fd62334e ` which is still my proxy, but the one retrieved from myproxy.cern.ch
pfff...
they are totally the same...
```
belforte@stefanovm2/TaskManager> voms-proxy-info --file /data/certs/creds/cfa0cb32f2043a8042e1290debf652b8fd62334e 
subject   : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it/CN=885139544/CN=1267230042/CN=1095233893/CN=1955623334
issuer    : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it/CN=885139544/CN=1267230042/CN=1095233893
identity  : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it
type      : RFC3820 compliant impersonation proxy
strength  : 1024
path      : /data/certs/creds/cfa0cb32f2043a8042e1290debf652b8fd62334e
timeleft  : 167:56:52
key usage : Digital Signature, Key Encipherment, Data Encipherment
belforte@stefanovm2/TaskManager> voms-proxy-info --file /tmp/x509up_u8516 
subject   : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it/CN=1218165064
issuer    : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it
identity  : /DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it
type      : RFC3820 compliant impersonation proxy
strength  : 1024
path      : /tmp/x509up_u8516
timeleft  : 191:52:06
key usage : Digital Signature, Key Encipherment, Data Encipherment
belforte@stefanovm2/TaskManager> 

```

**Comment by belforte** [comment]
OTOH.. I put this branch in pre-prod /data/user/... switched env. and it works.
With nothing defined in the env for *509*
Maybe I only need a full reset of my VM ?

**Comment by belforte** [comment]
may I got it.
When running in my VM  I am using my user belforte and some time ago I put in the .bashrc the export of export X509_USER_PROXY=/tmp/x509up_u`id -u`. I suspect that this was interfering with the TW by being sourced during some command forking after env had been set/reset in python !
That explains why it works in pre-prod.
And once I removed it, it works also in my VM.

Will do some cleanup, build a 3.3.1809.rc3 and try again from scratch.

**Comment by belforte** [comment]
tagged 
https://github.com/dmwm/CRABServer/releases/tag/3.3.1809.rc3

**Comment by belforte** [comment]
built 3.3.1809.rc3 for SL7, deployed on my VM. All OK.
will do an SL6 build for preprod machine

**Comment by belforte** [comment]
works also in preprod. Decaling 3.3.1809.rc3 good
