### ISSUE TITLE
automatic splitting does not respect global black list

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5693]
Christoph Wissing just found that some CRAB jobs run at T0_CH_CSCS_HPC.
But they should not.
Here's the mail  thread.

```
THere are two recent tasks (submitted after Stefan blacklisted the T0)
which ran there. Both show the swiss T0 correctly removed
during the task preparation in the CRAB TaskWorker log.
Both use the new automatic splitting which re-creates submission
information in the schedd at run time based on probe jobs.
I have to fear that this new thing does not properly respect the black list.
As you may know the developer has left CMS (and HEP).
I am looking into decoding the source code.

May take a bit longer sorry. But so far it looks a clear
CRAB bug 

In case I do not find a quick solution, I fear that we need
SI people to step in by e.g. introducing some new requirement
for matching this site which default CRAB jobs will not specify.

Will let you know more ASAP.

Stefano
```

```
I dag out this task via ES:

180613_122903:raggleto_crab_DYJetsToLL_M-50_HT-400to600_ext1_80Xv5_13_Jun_18

It run at several other sites incl. T2_CH_CSCS, which made me think it
could be related to the data location.

Thanks anyway for your investigations!

Christoph


On 15.06.2018 11:49, Stefano Belforte wrote:
> Let me see if I can find some details on those CRAB jobs.
> Stefano
>
> On 15/06/18 10:42, Christoph Wissing wrote:
>>
>> Hello,
>>
>> let me re-use this thread, we might move to some other channel, if you
>> let me know about your preferences.
>>
>> Looks like that HC is now running at T0_CH_CSCS_HPC. The CPUeff is very
>> low (~20%) and needs to be investigated by the site.
>>
>> I have noticed that also CRAB jobs are going to the resource, although
>> it is disabled for Analysis. Jobs are proceeding, however we explicitly
>> agreed with the site not to have Analysis going there and since the
>> topic is somewhat political, we better understand what's going on.
>>
>> Would you know, why some jobs are going there? Is it because of the data
>> location, which is T2_CH_CSCS and T0_CH_CSCS_HPC is a processing
>> location for that? With the site being disabled this should not happen,
>> but I do not know the mechanisms behind. Perhaps we need some input from
>> the SI experts here.
>>
>> Thanks for your help!
>>
>> Christoph
>>
>>
>> On 08.06.2018 18:08, Stephan Lammel wrote:
>>> Hallo Stefano,
>>>     it's the handling of "no data" that is the issue. (Or so i think.)
>>>                                                       cheers,  Stephan
>>>
>>>
>>> P.S.: I manually disabled production status to avoid the same issue
>>> there.
>>>
>>>
>>> On Fri, 8 Jun 2018, Stefano Belforte wrote:
>>>
>>>> Date: Fri, 8 Jun 2018 15:33:21 +0000
>>>> From: Stefano Belforte <stefano.belforte@cern.ch>
>>>> To: Stephan Lammel <lammel@fnal.gov>
>>>> Cc: stefano.belforte@cern.ch, Giuseppe Bagliesi
>>>> <Giuseppe.Bagliesi@cern.ch>,
>>>>      Rokas Maciulaitis <rokas.maciulaitis@cern.ch>,
>>>>      Christoph Wissing <christoph.wissing@desy.de>,
>>>>      Andrea Sciaba' <Andrea.Sciaba@cern.ch>, mp.acosta141@gmail.com,
>>>>      jiangxw@mail.ihep.ac.cn
>>>> Subject: Re: T0_CH_CSCS_HPC crab submit error
>>>>
>>>> Maybe we do not have consistent
>>>> site vs. PNN vs PSN conversion/usage somewhere ?
>>>> I'd be honestly surprised if we do, I get often
>>>> confused myself !!! If only we could stop using the "site" word 
>>>>
>>>> On 08/06/18 16:45, Stephan Lammel wrote:
>>>>>
>>>>>   The site is in Waiting Room state, that should have prevented any
>>>>>   user or production job from running at the site. Since user jobs
>>>>>   run, there is a bug somewhere we need to find/correct. (I just dug
>>>>>   a bit and believe i understand how this came about.)
>>>>

```

**Comment by belforte** [comment]
`SPOOL_DIR/prejob_logs/predag.0.txt`  has this fishy line
```
Thu, 14 Jun 2018 09:14:35 CEST(+0000):DEBUG:DagmanCreator CRAB site blacklist: []
```

**Comment by belforte** [comment]
that come from these two lines
```
 global_blacklist = set(self.getBlacklistedSites())
self.logger.debug("CRAB site blacklist: %s", list(global_blacklist))
```
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L736-L737
and things are consistent with that not finding the file with the blacklist, but
I am quite confused that I do no see any error from the  `getBlacklistedSites` function

https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/TaskAction.py#L54

somehow logs for those piece are hard to find.

**Comment by mmascher** [comment]
The blacklistedSites.txt (https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/TaskAction.py#L56) comes from a file downloaded by a recurring action that does not run on the schedd.

Two ways to fix this, (1) add the txt file here https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L1154 , (2) do not return the bannedSites here https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/TaskAction.py#L54-L64 but set thewm in the config (e.g.: self.config.bannedSites), and since the config is already propageated we should be fine (assuming the getBannedSites is called before we pickle the config..)

**Comment by belforte** [comment]
crap...
given this line: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/TaskAction.py#L57
```
 if os.path.isfile(fileLocation):
```
if the fileLocation where to find the black list is not existing, no error is thrown.

**Comment by belforte** [comment]
thanks @mmascher . Sorry I read your posting after I figured out.
I do not fully like either of the proposed fixes, since they are ways to progagate the blackList from the TW to the schedd and keep using for a month.
I'd rather setup a recurrent action in the schedd to have an uptodate list cached there.
Or maybe we have some simple method in WMCore to read from web caching in /tmp.

**Comment by belforte** [comment]
A possible fix turned out to be mush simpler than I feared.
So I prepared PR now that I have things fresh in mind.
Will need more testing, of course.

**Comment by belforte** [comment]
https://github.com/dmwm/CRABServer/pull/5694

**Comment by belforte** [comment]
created a test release with it
https://github.com/dmwm/CRABServer/releases/tag/test_fix_5693_1

**Comment by belforte** [comment]
did not work:
```Sat, 16 Jun 2018 00:01:22 CEST(+0000):DEBUG:DagmanCreator CRAB site blacklist: [u'T2_PK_NCP', u'T3_US_Kansas', u'T3_RU_FIAN', u'T2_FI_HIP', u'T3_UK_London_UCL', u'T3_US_UCD', u'T3_CO_Uniandes', u'T2_UK_SGrid_Bristol', u'T3_US_NU', u'T3_US_NotreDame', u'T3_US_MIT', u'T3_IN_PUHEP', u'T3_UK_ScotGrid_ECDF', u'T2_IT_Rome', u'T3_CH_CERN_HelixNebula', u'T3_IN_TIFRCloud', u'T0_CH_CERN', u'T3_GR_IASA', u'T3_CN_PKU', u'T0_CH_CSCS_HPC', u'T3_IR_IPM', u'T2_PL_Warsaw', u'T2_RU_ITEP', u'T3_US_JHU', u'T3_BY_NCPHEP', u'T3_US_FSU', u'T3_KR_UOS', u'T3_CH_PSI']
TaskWorker/Actions/DagmanCreator.py:757: DeprecationWarning: ClassAd Deprecation: parse is deprecated; use parseOne, parseNext, or parseAds instead.
  sitead = classad.parse(fd)
Sat, 16 Jun 2018 00:01:22 CEST(+0000):DEBUG:DagmanCreator Site whitelist: [u'T2_US_Purdue', u'T2_UK_SGrid_RALPP', u'T2_FR_GRIF_LLR', u'T2_ES_IFCA', u'T2_UK_SGrid_Bristol', u'T2_FR_IPHC', u'T2_DE_DESY', u'T2_IT_Legnaro', u'T2_US_Caltech', u'T2_UK_London_Brunel', u'T2_IT_Pisa', u'T2_US_Vanderbilt', u'T2_IT_Rome', u'T2_US_Florida', u'T2_FR_GRIF_IRFU', u'T2_UK_London_IC', u'T2_IT_Bari', u'T2_US_Nebraska', u'T2_FR_CCIN2P3', u'T2_US_UCSD', u'T2_ES_CIEMAT', u'T2_US_Wisconsin', u'T2_US_MIT', u'T2_DE_RWTH']
Sat, 16 Jun 2018 00:01:22 CEST(+0000):DEBUG:DagmanCreator Site blacklist: []
Got a fatal exception: 'NoneType' object is unsubscriptable
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/data/srv/glidecondor/condor_local/spool/7389/0/cluster6467389.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 85, in <module>
    retval = bootstrap()
  File "/data/srv/glidecondor/condor_local/spool/7389/0/cluster6467389.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 28, in bootstrap
    return PreDAG.PreDAG().execute(*sys.argv[2:])
  File "TaskWorker/Actions/PreDAG.py", line 111, in execute
    retval = self.executeInternal(*args)
  File "TaskWorker/Actions/PreDAG.py", line 251, in executeInternal
    creator.createSubdag(split_result.result, task=task, parent=parent, stage=self.stage)
  File "TaskWorker/Actions/DagmanCreator.py", line 773, in createSubdag
    self.uploadWarning(msg, kwargs['task']['user_proxy'], kwargs['task']['tm_taskname'])
  File "TaskWorker/Actions/TaskAction.py", line 44, in uploadWarning
    userServer = HTTPRequests(self.server['host'], userProxy, userProxy, retry=2,
TypeError: 'NoneType' object is unsubscriptable


```

**Comment by belforte** [comment]
@mmascher seems to me that the problem is that for some reason specific of the config. I was using, DagmanCreator is going through the uploadWarning where it tries to act like on the TW machine and use as proxy the user credentials in
```
 (Pdb) kwargs['task']['user_proxy']
'/data/certs/creds/cfa0cb32f2043a8042e1290debf652b8fd62334e'
```
which are not there on the schedd.

What do you think ? Is this possible (odd that it was never spotted), or did I mess up something so that the proxy is not properly set ? I am not sure that we ever intended the automatic splitting execution in the schedd to upload messages to the REST !

If you agree, I will add something to uploadWarning so that it becomes dummy if not executed on the TW.

**Comment by belforte** [comment]
the failing call to uploadWarning comes from a piece of code which was not executed when globalBlacklist is empty, which explains why the problem never occurred before
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L770-L780

**Comment by belforte** [comment]
looks allright now. This is a quick patch which ignores failures to upload warning, restoring previous behavior. It is left as a possible enhancement to make uploadWarning work from schedd.
IMO it is part of the bigger problem that we have poor access to the logs of the various preDags to report and diagnose problems. If something goes wrong there I am not even sure what is reported to the user, not to mention how task could be recovered.
