### ISSUE TITLE
DataDiscovery fails when secondaryInputDataset has some empty blocks

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5794]
see: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4343.html
relevant text below:
```
2018-11-20 23:28:16,330:ERROR:Handler:Problem handling 181120_222744:belforte_crab_20181120_232735 because of DBSReaderError
Message: DBSReader.listDatasetSummary(None, /JetHT/Run2016H-07Aug17-v1/AOD#1fa28224-7f7a-11e7-9af5-02163e0184a6): No matching data
	ModuleName : WMCore.Services.DBS.DBSErrors
	MethodName : __init__
	ClassInstance : None
	FileName : /data/srv/TaskManager/3.3.1810.patch7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1810.patch7/lib/python2.7/site-packages/WMCore/Services/DBS/DBSErrors.py
	ClassName : None
	LineNumber : 38
	ErrorNr : 1002
 failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1810.patch7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1810.patch7/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/3.3.1810.patch7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1810.patch7/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 92, in execute
    result = self.executeInternal(*args, **kwargs)
  File "/data/srv/TaskManager/3.3.1810.patch7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1810.patch7/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 217, in executeInternal
    self.checkBlocksSize(secondaryBlocks)
  File "/data/srv/TaskManager/3.3.1810.patch7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1810.patch7/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 73, in checkBlocksSize
    blockInfo = self.dbs.getDBSSummaryInfo(block=block)
  File "/data/srv/TaskManager/3.3.1810.patch7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1810.patch7/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 395, in getDBSSummaryInfo
    raise DBSReaderError(msg % (dataset, block))
DBSReaderError: DBSReaderError
Message: DBSReader.listDatasetSummary(None, /JetHT/Run2016H-07Aug17-v1/AOD#1fa28224-7f7a-11e7-9af5-02163e0184a6): No matching data
```
and from later in that tread:
```
I can reproduce the problem in production with this simple configuration [1]

OTOH the preproduction TW (where some improvements to data discovery
for those odd datasets have been made already) fails with a different error [2]
and somehow looks closer to work.
I should be able to come up with a fix to be deployed in next cycle (December).

Stefano

[1]
config.section_("JobType")
config.JobType.pluginName = 'Analysis'
config.JobType.psetName = 'demoanalyzer.py'

config.section_("Data")
config.Data.inputDataset = '/JetHT/Run2016H-17Jul2018-v1/MINIAOD'
config.Data.secondaryInputDataset = '/JetHT/Run2016H-07Aug17-v1/AOD'

config.Data.splitting = 'FileBased'

[2]
  File "/data/srv/TaskManager/3.3.1811.rc7/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1811.rc7/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py",
line 78, in checkBlocksSize
    if blockInfo['NumberOfLumis'] > MAX_LUMIS:
KeyError: 'NumberOfLumis'
```

**Comment by belforte** [comment]
problem is in these lines
https://github.com/dmwm/CRABServer/blob/8e91c3e04dd70bed51423a8b5b4ef4df11ee6611/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L76-L78
when the block contains only invalid files, the blockInfo dictionary is empty `{}`
