### ISSUE TITLE
problems in 3.3.1812.rc1

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5799]
recurring actions starting fails for old ones:
```
2018-12-01 00:38:59,791:INFO:Worker,83:Uploading error message to REST: Process-2: I just had a failure for __init__() takes exactly 2 arguments (1 given)
        workid=0
        task=TaskWorker.Actions.Recurring.RemovetmpDir
Traceback (most recent call last):
  File "/data/user/CRABServer/src/python/TaskWorker/Worker.py", line 68, in processWorkerLoop
    outputs = work(resthost, resturi, WORKER_CONFIG, task, procnum, inputargs)
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/Recurring/BaseRecurringAction.py", line 10, in handleRecurring
    getattr(mod, actionClass)().execute(resthost, resturi, config, task, procnum)
TypeError: __init__() takes exactly 2 arguments (1 given)

2018-12-01 00:38:59,795:DEBUG:Worker,65:Process-1: Starting <function handleRecurring at 0x7f5a948a2cf8> on TaskWorker.Actions.Recurring.BanDestinationSites
2018-12-01 00:38:59,797:INFO:Worker,83:Uploading error message to REST: Process-1: I just had a failure for __init__() takes exactly 2 arguments (1 given)
        workid=1
        task=TaskWorker.Actions.Recurring.BanDestinationSites
Traceback (most recent call last):
  File "/data/user/CRABServer/src/python/TaskWorker/Worker.py", line 68, in processWorkerLoop
    outputs = work(resthost, resturi, WORKER_CONFIG, task, procnum, inputargs)
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/Recurring/BaseRecurringAction.py", line 10, in handleRecurring
    getattr(mod, actionClass)().execute(resthost, resturi, config, task, procnum)
TypeError: __init__() takes exactly 2 arguments (1 given)

```

**Comment by belforte** [comment]
also this one:
https://cms-logbook.cern.ch/elog/Analysis+Operations/2388
