### ISSUE TITLE
job is declared failed in PJ and rerun, but output is published

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5811]

**Comment by belforte** [comment]
see this HN thread
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4414.html

from PostJob
https://cmsweb.cern.ch/scheddmon/0137/cms040/181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2/postjob.475.0.txt

* publication flag was initially 0 as it should in initial upload in transferdb [1]
* transfer and output metadata upload went OK [2]
* at this point publication flag was updated (telling ASO to publish) [3]
* but then upload of input file metadata fails and the jon is marked as permanently failed [4], leading to resubmission (in this case it was one of the jobs in the main processing DAG of an automatic splitting task, so it was re-executed in several smaller jobs).

It is not clear why input metadata upload failed, if it was something wrong in the job output or a code bug, but if PostJob decides to call this a fata failures, needs to do so before publish flag is updated.


[1]
```
Mon, 17 Dec 2018 01:36:44 CET(+0000):INFO:PostJob ====== Starting to check uploads to ASO database.
Mon, 17 Dec 2018 01:36:44 CET(+0000):WARNING:PostJob Unable to determine ASO start time from job report. Will use ASO start time = 2018-12-17 01:36:44.444150 (1545007004).
Mon, 17 Dec 2018 01:36:44 CET(+0000):INFO:PostJob Working on file myNanoRunData2018ABC_NANO_475.root
Mon, 17 Dec 2018 01:36:44 CET(+0000):INFO:PostJob Temporarily disabling publication flag.It will be updated once the transfer is done (and filemetadata uploaded).
Mon, 17 Dec 2018 01:36:44 CET(+0000):INFO:PostJob LFN /store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000/myNanoRunData2018ABC_NANO_475.root (id d7ec7f1193ebe60a6703acf0ffb04826b149bd1e61f0687e3623d583) is not in ASO database. Will inject a new transfer and publication request.
Mon, 17 Dec 2018 01:36:44 CET(+0000):INFO:PostJob ASO job description: {'_id': 'd7ec7f1193ebe60a6703acf0ffb04826b149bd1e61f0687e3623d583',
 'checksums': {u'adler32': u'e9c33605', u'cksum': u'2295538394'},
 'dbs_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader',
 'destination': 'T2_CH_CERN',
 'destination_lfn': '/store/group/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000/myNanoRunData2018ABC_NANO_475.root',
 'end_time': '',
 'failure_reason': [],
 'group': '',
 'inputdataset': '/SingleMuon/Run2018A-17Sep2018-v2/MINIAOD',
 'job_end_time': '2018-12-17 01:36:44',
 'job_retry_count': 0,
 'jobid': '475',
 'last_update': 1545007004,
 'lfn': '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000/myNanoRunData2018ABC_NANO_475.root',
 'publication_retry_count': [],
 'publication_state': 'not_published',
 'publish': 0,
 'rest_host': 'cmsweb.cern.ch',
 'rest_uri': '/crabserver/prod',
 'retry_count': [],
 'role': '',
 'size': 134463344,
 'source': u'T2_US_Vanderbilt',
 'source_lfn': '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000/myNanoRunData2018ABC_NANO_475.root',
 'start_time': '2018-12-17 01:36:44.444150',
 'state': 'new',
 'type': 'output',
 'user': 'manzoni',
 'workflow': '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'}
Mon, 17 Dec 2018 01:36:44 CET(+0000):INFO:PostJob ====== Finished to check uploads to ASO database.
```

[2]

```
Mon, 17 Dec 2018 02:06:44 CET(+0000):INFO:PostJob ====== Finished to monitor ASO transfers.
Mon, 17 Dec 2018 02:06:44 CET(+0000):INFO:PostJob ====== Finished to check for ASO transfers.
Mon, 17 Dec 2018 02:06:44 CET(+0000):INFO:PostJob ====== Starting upload of output files metadata.
Mon, 17 Dec 2018 02:06:44 CET(+0000):DEBUG:PostJob Uploading output metadata for myNanoRunData2018ABC_NANO.root to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [...]
Mon, 17 Dec 2018 02:06:44 CET(+0000):INFO:PostJob ====== Finished upload of output files metadata.
```

[3]
```
Mon, 17 Dec 2018 02:06:44 CET(+0000):INFO:PostJob ====== Finished upload of output files metadata.
Mon, 17 Dec 2018 02:06:44 CET(+0000):INFO:PostJob ====== About to update publication flags of transfered files.
Mon, 17 Dec 2018 02:06:44 CET(+0000):DEBUG:PostJob Found doc d7ec7f1193ebe60a6703acf0ffb04826b149bd1e61f0687e3623d583
Mon, 17 Dec 2018 02:06:45 CET(+0000):INFO:PostJob ====== Finished to update publication flags of transfered files.
```

[4]
```
Mon, 17 Dec 2018 02:06:45 CET(+0000):INFO:PostJob ====== Starting upload of input files metadata.
Mon, 17 Dec 2018 02:06:45 CET(+0000):DEBUG:PostJob Uploading input metadata for /store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/60000/AA9C3550-D1CE-2F46-94A5-C681B39931F3.root_475 to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', u'/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/60000/AA9C3550-D1CE-2F46-94A5-C681B39931F3.root_475'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '475'), ('outtmplfn', '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000'), ('appver', 'CMSSW_10_2_9'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'Run2018A-from_17Sep2018_ver2-NanoAODv4Priv-00000000000000000000000000000000'), ('events', 40565), ('taskname', '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Vanderbilt'), ('outlocation', 'T2_CH_CERN'), ('directstageout', 0), ('outfileruns', '316187'), ('outfileruns', '316722'), ('outfileruns', '316928'), ('outfilelumis', '1814,1644,1949,1636,1674,1638,1851,1941,1854,2069,1573,1576'), ('outfilelumis', '313'), ('outfilelumis', '108,111')]
Mon, 17 Dec 2018 02:06:45 CET(+0000):DEBUG:PostJob Uploading input metadata for /store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/CF98FD5A-599D-E24D-A9AE-6B1EB570DA1A.root_475 to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', u'/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/CF98FD5A-599D-E24D-A9AE-6B1EB570DA1A.root_475'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '475'), ('outtmplfn', '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000'), ('appver', 'CMSSW_10_2_9'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'Run2018A-from_17Sep2018_ver2-NanoAODv4Priv-00000000000000000000000000000000'), ('events', 70910), ('taskname', '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Vanderbilt'), ('outlocation', 'T2_CH_CERN'), ('directstageout', 0), ('outfileruns', '315645'), ('outfileruns', '315361'), ('outfileruns', '315366'), ('outfileruns', '315339'), ('outfileruns', '316218'), ('outfileruns', '315420'), ('outfileruns', '315322'), ('outfilelumis', '458,583'), ('outfilelumis', '492'), ('outfilelumis', '12,28'), ('outfilelumis', '100'), ('outfilelumis', '989'), ('outfilelumis', '468,467,413,405,404,397,286,401,400,403,398,119,493'), ('outfilelumis', '562,515,521')]
Mon, 17 Dec 2018 02:06:45 CET(+0000):DEBUG:PostJob Uploading input metadata for /store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/00000/08292888-5454-964C-A7E6-F7A8C4E9F388.root_475 to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', u'/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/00000/08292888-5454-964C-A7E6-F7A8C4E9F388.root_475'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '475'), ('outtmplfn', '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000'), ('appver', 'CMSSW_10_2_9'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'Run2018A-from_17Sep2018_ver2-NanoAODv4Priv-00000000000000000000000000000000'), ('events', 74033), ('taskname', '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Vanderbilt'), ('outlocation', 'T2_CH_CERN'), ('directstageout', 0), ('outfileruns', '316240'), ('outfileruns', '316362'), ('outfileruns', '316199'), ('outfileruns', '316271'), ('outfileruns', '315339'), ('outfileruns', '315357'), ('outfileruns', '316218'), ('outfileruns', '316187'), ('outfileruns', '316202'), ('outfileruns', '315784'), ('outfileruns', '315322'), ('outfilelumis', '889,880,907,904'), ('outfilelumis', '130,351'), ('outfilelumis', '56'), ('outfilelumis', '116'), ('outfilelumis', '593'), ('outfilelumis', '728'), ('outfilelumis', '784,786,781,840,955,867,866,810'), ('outfilelumis', '1212'), ('outfilelumis', '5,126,105'), ('outfilelumis', '200,34'), ('outfilelumis', '551,550')]
Mon, 17 Dec 2018 02:06:46 CET(+0000):DEBUG:PostJob Uploading input metadata for /store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/60000/A94671D3-0E20-9A41-98EB-5B24EECCB7FC.root_475 to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', u'/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/60000/A94671D3-0E20-9A41-98EB-5B24EECCB7FC.root_475'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '475'), ('outtmplfn', '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000'), ('appver', 'CMSSW_10_2_9'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'Run2018A-from_17Sep2018_ver2-NanoAODv4Priv-00000000000000000000000000000000'), ('events', 69667), ('taskname', '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Vanderbilt'), ('outlocation', 'T2_CH_CERN'), ('directstageout', 0), ('outfileruns', '316187'), ('outfileruns', '315702'), ('outfileruns', '315322'), ('outfilelumis', '2024,1773,1794,1819,1963,2037,1887,1696,1692,1699,1667,1570,1769,1765'), ('outfilelumis', '45'), ('outfilelumis', '586,868,632,625,622,946,860,863,862,865,864,867,861,572,847')]
Mon, 17 Dec 2018 02:06:46 CET(+0000):DEBUG:PostJob Uploading input metadata for /store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root_475 to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', u'/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root_475'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '475'), ('outtmplfn', '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000'), ('appver', 'CMSSW_10_2_9'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'Run2018A-from_17Sep2018_ver2-NanoAODv4Priv-00000000000000000000000000000000'), ('events', 0), ('taskname', '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Vanderbilt'), ('outlocation', 'T2_CH_CERN'), ('directstageout', 0), ('outfileruns', '315322'), ('outfilelumis', '')]
Mon, 17 Dec 2018 02:06:46 CET(+0000):ERROR:PostJob Error uploading input file metadata: {'Content-Length': '734', 'X-Error-Http': '400', 'X-Rest-Time': '2156.019 us', 'Server': 'CherryPy/unknown', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=14295 t=1545008806521880', 'X-Rest-Status': '302', 'Date': 'Mon, 17 Dec 2018 01:06:46 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outfilelumis' parameter", 'X-Error-Id': 'b29d4e56571476306c59976f4ac1e355'}
Mon, 17 Dec 2018 02:06:46 CET(+0000):ERROR:PostJob Fatal error uploading input files metadata: url=https://cmsweb.cern.ch/crabserver/prod/filemetadata, code=400, reason=Bad Request, headers={'Content-Length': '734', 'X-Error-Http': '400', 'X-Rest-Time': '2156.019 us', 'Server': 'CherryPy/unknown', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=14295 t=1545008806521880', 'X-Rest-Status': '302', 'Date': 'Mon, 17 Dec 2018 01:06:46 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outfilelumis' parameter", 'X-Error-Id': 'b29d4e56571476306c59976f4ac1e355'}
Traceback (most recent call last):
  File "TaskWorker/Actions/PostJob.py", line 1987, in execute_internal
    self.upload_input_files_metadata()
  File "TaskWorker/Actions/PostJob.py", line 2249, in upload_input_files_metadata
    self.server.put(rest_uri, data = encodeRequest(configreq))
  File "RESTInteractions.py", line 92, in put
    return self.makeRequest(uri = uri, data = data, verb = 'PUT')
  File "RESTInteractions.py", line 129, in makeRequest
    capath=caCertPath, verbose=self['verbose'])
  File "WMCore/Services/pycurl_manager.py", line 258, in request
    raise exc
HTTPException: url=https://cmsweb.cern.ch/crabserver/prod/filemetadata, code=400, reason=Bad Request, headers={'Content-Length': '734', 'X-Error-Http': '400', 'X-Rest-Time': '2156.019 us', 'Server': 'CherryPy/unknown', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=14295 t=1545008806521880', 'X-Rest-Status': '302', 'Date': 'Mon, 17 Dec 2018 01:06:46 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outfilelumis' parameter", 'X-Error-Id': 'b29d4e56571476306c59976f4ac1e355'}
Mon, 17 Dec 2018 02:06:46 CET(+0000):INFO:PostJob ====== Finished upload of input files metadata.
Mon, 17 Dec 2018 02:06:46 CET(+0000):INFO:PostJob Job could be retried, but the maximum allowed number of retries was hit. Setting this node (job) to permanent failure. DAGMan will NOT retry.
```

**Comment by belforte** [comment]
clearly there's a bug in the logical flow.
OTOH  a fatal falilure in uploading of input metadata is highly unusual.
In this case it is due to:
```
Mon, 17 Dec 2018 02:06:46 CET(+0000):DEBUG:PostJob Uploading input metadata for /store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root_475 to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', u'/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root_475'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '475'), ('outtmplfn', '/store/temp/user/manzoni.2ffa33518b49678a359ef30ac577806ca67a9549/phys_tau/ProdNanoAODv4Priv/16dec18/SingleMuon/Run2018A-from_17Sep2018_ver2-NanoAODv4Priv/181216_124906/0000'), ('appver', 'CMSSW_10_2_9'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'Run2018A-from_17Sep2018_ver2-NanoAODv4Priv-00000000000000000000000000000000'), ('events', 0), ('taskname', '181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Vanderbilt'), ('outlocation', 'T2_CH_CERN'), ('directstageout', 0), ('outfileruns', '315322'), ('outfilelumis', '')]
```
the odd part is the last two entries
```
('outfileruns', '315322'), ('outfilelumis', '')
```
this file `/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root_475`  is reported to contain just one run, but no lumis !
The upload API is not prepared to handle this

That file has lumi for that and other runs:
belforte@lxplus091/~> dasgoclient --query 'lumi file=/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root run=315322' 
[706,686,700]
belforte@lxplus091/~> 
belforte@lxplus091/~> dasgoclient --query 'lumi file=/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root ' 
[331,615,220,418,304,420,650]
[345]
[607,935,956,594,964,968,953,999,600,938,678,932,936,948,954]
[706,686,700]
belforte@lxplus091/~> 

https://cmsweb.cern.ch/das/request?instance=prod/global&input=lumi+file%3D%2Fstore%2Fdata%2FRun2018A%2FSingleMuon%2FMINIAOD%2F17Sep2018-v2%2F100000%2F925EBE76-2518-1A40-8DDE-1A3713E68780.root

**Comment by belforte** [comment]
more on the empty lumi list, the FJR for that job [1] has
```
{
    "runs": {
        "315322": { }
    },
    "input_source_class": "PoolSource",
    "input_type": "primaryFiles",
    "lfn": "/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root",
    "pfn": "/cms/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root",
    "catalog": "",
    "module_label": "source",
    "guid": "925EBE76-2518-1A40-8DDE-1A3713E68780",
    "events": 0
}
```
Note the empput { } after the run number where the lumi list should be ! 

[1]
https://cmsweb.cern.ch/scheddmon/0137/cms040/181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2/job_fjr.475.0.json

the only thing that job stdout has to say about that input file is
```
== CMSSW: 17-Dec-2018 00:35:04 UTC  Successfully opened file /cms/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root
== CMSSW: 17-Dec-2018 00:35:09 UTC  Closed file /cms/store/data/Run2018A/SingleMuon/MINIAOD/17Sep2018-v2/100000/925EBE76-2518-1A40-8DDE-1A3713E68780.root
```
from https://cmsweb.cern.ch/scheddmon/0137/cms040/181216_124906:manzoni_crab_SingleMuon_Run2018A-17Sep2018-v2/job_out.475.0.txt

JOb ran for 480 min which is the target time used in automatic splitttig, given that last file was opened and closed in 5 seconds it is possivle that time limit kicked in and prevented the fist lumi of last file to be processed so that FJR ended with empty list for last run.

Now... one could say that if no lumi for run 315322 was processed, the entry for this run should have ot been in FJR, rather than having an entry with no lumis...
But one could also say that there was no good reason to expect this not to be possible so CRAB should handle it.

Ayhow, I think this explais whay the input metadata is not accepted by CRAB and the notes above explain why the output file was published anyhow (decision to publish or not is taken before input metadata is uploaded).

Now we have to pinpoit the simplest, most solid, fix.

**Comment by belforte** [comment]
looking at PostJob `execute_internal` method with PyCharm so to collapse block and see structure:
![screenshot from 2019-01-18 11-56-40](https://user-images.githubusercontent.com/1837785/51404182-f1d44780-1b52-11e9-828e-ee9a6ca87c51.png)
it seems that the simple solution is to upload input metadata before output ones, since the publication flag is updates as part of the upload output metadata code block
