### ISSUE TITLE
cleanup old exceptoion

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5825]
In CMSRunAnalysis we still try to find calculateChecksums in two places, for compatibility with older WMCore, but there's no need.
The bad thing with current code is that even if the exception is properly handled, some failures which happen later print its message and confuse users with stdouts like the following:
```
=== ScriptEXE Execution started at Fri Feb 15 09:40:48 2019 ====
2019-02-15 09:40:48,556:INFO:Scram:    Invoking command: python /srv/TweakPSet.py --location=/srv --inputFile='job_input_file_list_1.txt' --runAndLumis='job_lumis_1.json' --firstEvent=None --lastEvent=None --firstLumi=None --firstRun=None --seeding=AutomaticSeeding --lheInputFiles=False --oneEventMode=0 --eventsPerLumi=None --maxRuntime=-60
2019-02-15 09:40:49,178:INFO:Scram:    Invoking command: /srv/crab_script.sh 1 
WARNING: Unable to parse WMCore's jobReport.json; FJR will not be useful.
 Traceback (most recent call last):
  File "CMSRunAnalysis.py", line 360, in handleException
    report = json.load(open("jobReport.json"))
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

ERROR: Exceptional exit at Fri Feb 15 09:40:49 2019 (10040): Error executing scriptExe.
	Scram Env 
        Scram Command Diagnostic:
        Command : scramv1
        Architecture: slc6_amd64_gcc630
        Executed: /srv/crab_script.sh 1 
        Exit Status: 5
        Stdout: None
        Stderr: None 
	Command: /srv/crab_script.sh 1 
ERROR: Traceback follows:
 Traceback (most recent call last):
  File "CMSRunAnalysis.py", line 856, in <module>
    from WMCore.Algorithms.BasicAlgos import calculateChecksums
ImportError: No module named BasicAlgos

```

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/5826
