### ISSUE TITLE
readEvents broken in new condor 8.8.*

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/CRABServer#5829]
The new version of condor (8.8.*) removes one method from the htcondor module in python bindings which we use in the task_process. The method in question is read_events() it is used at the very first step of submission and breaks the whole DAG at this line: 

https://github.com/dmwm/CRABServer/blob/35ff3bf0b0d7b9f83f18278e94f853dae81df70f/src/python/HTCondorUtils.py#L28

The error is the following: [1]

The condor developers said this method have been broken beyond repair both in  API and functionality so they changed it with a class called 'JobEventLog' [2]. There are three major differences between the new and the old method/class:

- We need an explicit instance of that class in order to parse the job events log file.

- The new class is expecting a file path instead of a File Descriptor. We used to open the file in our code and then seek to the last point where the parsing has stopped during  the previous iteration and start the new parsing from that point onwards: 

https://github.com/dmwm/CRABServer/blob/a4aa634d241a0a3f157f1199118ae983b8efb996/scripts/task_process/cache_status.py#L294

- The new class does not return an iterator of objects of type 'Classad', instead it returns an iterator of objects of type 'JobEvent'. See the test from ipython at [3]. An explicit check is needed if both types overlap, even though at first glance it seems that 'JobEvent' has all the key-value pairs that we need in the rest of the code here:

https://github.com/dmwm/CRABServer/blob/a4aa634d241a0a3f157f1199118ae983b8efb996/scripts/task_process/cache_status.py#L65

[1]
```
[cms209@vocms068 cluster395399.proc0.subproc0]$ export X509_USER_PROXY=f145d4807a7b2c5b5940006bd88fe09271c3737c 
[cms209@vocms068 cluster395399.proc0.subproc0]$ ./dag_bootstrap.sh PREJOB 2 8 
190225_164036:tivanov_crab_test_for_schedd_vocms068_itb_2 crab-prod-tw01.cern.ch conventional
+ echo 'Beginning dag_bootstrap.sh (stdout)'
Beginning dag_bootstrap.sh (stdout)
+ echo 'Beginning dag_bootstrap.sh (stderr)'
Beginning dag_bootstrap.sh (stderr)
+ '[' X = X -a '!' -e CRAB3.zip ']'
+ export 
PYTHONPATH=/data/srv/glidecondor/condor_local/spool/5399/0/cluster395399.proc0.subproc0:/data/srv/glidecondor/cond

...

++ pwd
+ echo 'Now running the job in /data/srv/glidecondor/condor_local/spool/5399/0/cluster395399.proc0.subproc0...'
Now running the job in /data/srv/glidecondor/condor_local/spool/5399/0/cluster395399.proc0.subproc0...
+ exec nice -n 19 python -m TaskWorker.TaskManagerBootstrap PREJOB 2 8 
190225_164036:tivanov_crab_test_for_schedd_vocms068_itb_2 crab-prod-tw01.cern.ch conventional
Cannot import ldap
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File 
"/data/srv/glidecondor/condor_local/spool/5399/0/cluster395399.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", 
line 16, in <module>
    import HTCondorUtils
  File "HTCondorUtils.py", line 28, in <module>
    readEvents = getattr(htcondor, 'readEvents', htcondor.read_events)
AttributeError: 'module' object has no attribute 'read_events'
```

[2]
http://research.cs.wisc.edu/htcondor/manual/v8.8/PythonBindings.html#x68-5500007.1.1
http://research.cs.wisc.edu/htcondor/manual/v8.8/PythonBindings.html#x68-5510007.1.2

[3]

In [8]: jel = htcondor.JobEventLog("job_log")
In [9]: event = jel.next()
In [10]: event
Out[10]: <htcondor.JobEvent at 0x128f848>
...
In [18]: event['MyType'] 
Out[18]: 'JobAdInformationEvent'

**Comment by bbockelm** [comment]
I'm sorry, but the HTCondor developers don't get to simply remove APIs like this.  Will follow up locally.

**Comment by belforte** [comment]
conclusion is that the missing method will be ported to HTCondor 8.8 and a new API will be discussed and evaluated before going in e.g. 8.9.
Being followed up in
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6939

```
-------- Forwarded Message --------
Date: 	Mon, 4 Mar 2019 21:47:18 +0000
From: 	Jaime Frey <jfrey@cs.wisc.edu>
To: 	Stefano Belforte <stefano.belforte@cern.ch>
CC: 	Todor Trendafilov Ivanov <todor.trendafilov.ivanov@cern.ch>, Todd Tannenbaum <tannenba@cs.wisc.edu>, James Letts <letts@physics.ucsd.edu>, Marco Mascheroni <marco.mascheroni@cern.ch>, Leonardo Cristella <leonardo.cristella@cern.ch>, Todd L Miller <tlmiller@cs.wisc.edu>



You’ve convinced me that the new API is insufficient for your needs. You need a way to start reading events in the middle of the file (i.e. resuming reading where a previous round of reading left off). We’re currently discussing how that should look in the new API. Some of the ideas would require significant code changes and would happen in the 8.9 series.

As a short term solution, we could re-introduce the old API for Python 2, marked as deprecated. The old code is completely broken for Python 3 on windows, which is part of why we removed it. Would that be acceptable?

We have a ticket for this:
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6939
I’ll put further discussion of why we removed the old API and what the new API should look like there.

  - Jaime

> On Mar 1, 2019, at 1:50 PM, Stefano Belforte <stefano.belforte@cern.ch <mailto:stefano.belforte@cern.ch>> wrote:
>
> Hi Jamie, others,
>
> in other words, it seems to me that what is missing in new class
> is the concept of "look at this log file and only read the
> events since when I stopped looking at it last night, rather
> than give me all history since 10 days ago or so".
>
> Also note that now we have a persistent bash shell which
> only executes the log parsing in python every 5min, since
> the python script only takes a few seconds to run, this
> allow us to keep a light memory footprint. We have up to
> 200 such processed on a schedd which can run 200 DAG's
> and we found that O(100) python processes running all
> of the time is heavy enough to affect schedd performance.
> So it would surely be easy to rewrite 100 lines of
> bash in python, but that's not the end of the story.
>
> Maybe we simply have not done it "the right way" to
> being with, parsing all of those log files is indeed
> an expensive operation and advice is welcome.
>
> The goal of this log parsing is to keep
> a constantly up to date view of the status
> of all jobs in the DAG (can be up to 10K jobs in each)
> which:
> 1. can be quickly http-ed to clients w/o doing heavyish condor_q's
>    (also relieves us from having a service which runs condor_q on demand)
> 2. keeps updating even after DAG is halted as grid jobs complete
>     (so dag node status file will not do)
> 3. the report includes not only job status (idle/running) but also
>     things like where they ran, how long, how much memory, exit code i.e.
>     ten or so classAds
>
> at least at the time this parsing of MyLog was found much ligther than
> a lot of condor_q -l -userlog MyLog
>
> I hope having put a bit of context helps in enabling you to
> give us the best advice ! Of course we are manpower short
> in CRAB now, as it was supposed to be in "just keep it alive"
> mode, with no significant changes expected, so the less
> we need to change existing code, the better in any case.
>
> Stefano
>
>
>
> On 01/03/2019 11:00, Stefano Belforte wrote:
>> Hi Jaime,
>> I supect folks in CERN timezone are gone for the day (weekend).
>> let me chime in with the little I know:
>>  we keep the object in memory when the process runs, but this process
>>   keeps track of the DAG over its lifetime, so it runs for weeks, need
>>   to be able to have it stop/re-start (it runs as a condor job in local universe)
>>  this log is local to the DAG and specified in the submit file, it does not rotate
>> Thanks !
>> Stefano
>> On 01/03/2019 09:32, Jaime Frey wrote:
>>> Does all of your parsing of the event log happen in the same process, or does it happen across different processes? If it’s all in the same process, then you could keep a single JobEventLog object around for the lifetime of the process (or as long as necessary).
>>> Also, are you parsing an EVENT_LOG of all jobs that HTCondor will be rotating, or a user job log (specified in the submit file) that HTCondor doesn’t rotate?
>>>
>>>   - Jaime
>>>
>>>> On Mar 1, 2019, at 8:46 AM, Todor Trendafilov Ivanov <todor.trendafilov.ivanov@cern.ch <mailto:todor.trendafilov.ivanov@cern.ch> <mailto:todor.trendafilov.ivanov@cern.ch>> wrote:
>>>>
>>>> Hi Todd, Jaime,
>>>>
>>>> Me and Marco went through the CRAB3 code and now there is a detailed explanation of the issue regarding the API change in the htcondor module and how the differences between the old method/class affects us. Here is the link to the issue [1].
>>>>
>>>> The show stopper for us is that we are not able to pass a file descriptor to the new class but instead only  path to the events log file is required. We use to open the file in advance and parse  it in junks, while keeping the position of file pointer between the iterations, so every second time we can start parsing from the point where we have stopped the previous time. We need this because those event log files are enormous in our case. Can we do something in order to have that functionality again? We believe the change of the rest of our code is not that  dramatic for us. Thanks in advance!
>>>>
>>>> Regards,
>>>> Todor
>>>>
>>>>
>>>> [1]
>>>> https://github.com/dmwm/CRABServer/issues/5829
>>>


```

**Comment by belforte** [comment]
update from Jamie
```



-------- Forwarded Message --------
Subject: Re: changes in API for JobEventLog class
Resent-From: stefano.belforte@cern.ch
Date: Thu, 28 Mar 2019 21:26:52 +0000
From: Jaime Frey <jfrey@cs.wisc.edu>
To: Stefano Belforte <stefano.belforte@cern.ch>
CC: Todor Trendafilov Ivanov <todor.trendafilov.ivanov@cern.ch>, Todd Tannenbaum <tannenba@cs.wisc.edu>, James Letts <letts@physics.ucsd.edu>, Marco Mascheroni <marco.mascheroni@cern.ch>, Leonardo Cristella <leonardo.cristella@cern.ch>, Todd L Miller <tlmiller@cs.wisc.edu>

The old API will be restored in HTCondor 8.8.2 and 8.9.1, which are due to be released in about 2 weeks.
Changes in the new API will happen in a future 8.9 release.

 - Jaime

```

**Comment by belforte** [comment]
HTCondor 8.8.2 is out. @todor-ivanov let's test

**Comment by lecriste** [comment]
I have built a TW RPM with the most recent CRABServer tag (3.3.1906.rc1) and HTCondor 8.8.2:
http://cmsrep.cern.ch/cmssw/repos/comp.lecriste/slc7_amd64_gcc630/latest/RPMS/78/78469c06b4f34b7e88e33aa1e4a59b47/

The build finishes without errors but when I start the TW I get:
```
Traceback (most recent call last):
  File "/data/srv/TaskManager/current/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1906.rc1-comp/lib/python2.7/site-packages/TaskWorker/MasterWorker.py", line 18, in <module>
    import HTCondorLocator
  File "/data/srv/TaskManager/3.3.1906.rc1-comp/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1906.rc1-comp/lib/python2.7/site-packages/HTCondorLocator.py", line 9, in <module>
    import HTCondorUtils
  File "/data/srv/TaskManager/3.3.1906.rc1-comp/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1906.rc1-comp/lib/python2.7/site-packages/HTCondorUtils.py", line 28, in <module>
    readEvents = getattr(htcondor, 'readEvents', htcondor.read_events)
AttributeError: 'module' object has no attribute 'read_events'
```

How can we check whether the old API is actually restored in HTCondor 8.8.2?

**Comment by belforte** [comment]
I thought that we need to install HTCondor 8.8.2 on a schedd for this. It is on @todor-ivanov list.
But maybe I am confused ?
Anyhow as a separate item we should verify TW code with 8.8.2 bindings as per #5884

**Comment by lecriste** [comment]
> I thought that we need to install HTCondor 8.8.2 on a schedd for this. It is on @todor-ivanov list.
> But maybe I am confused ?

Apparently it breaks already on the TW when starting it.

> Anyhow as a separate item we should verify TW code with 8.8.2 bindings as per #5884

This is exactly what I did:
https://github.com/dmwm/CRABServer/issues/5884#issuecomment-488435415

**Comment by belforte** [comment]
I am puzzled. Theinitial report from Marco and Todor was of failure in the schedd.
We do not use that API in the TW. Are you sure that you have the correct build ?
I never tried to change HTCodnor version in the TW.

**Comment by lecriste** [comment]
```
[crab3@crab-preprod-tw01 TaskManager]$ ls 3.3.1906.rc1/slc7_amd64_gcc630/external/condor/
8.5.7-comp3
[crab3@crab-preprod-tw01 TaskManager]$ ls 3.3.1906.rc1-comp/slc7_amd64_gcc630/external/condor/
8.8.2

[crab3@crab-preprod-tw01 TaskManager]$ grep read_events -r 3.3.1906.rc1/slc7_amd64_gcc630/external/condor/
Binary file 3.3.1906.rc1/slc7_amd64_gcc630/external/condor/8.5.7-comp3/lib/python2.7/site-packages/htcondor.so matches
[crab3@crab-preprod-tw01 TaskManager]$ grep read_events -r 3.3.1906.rc1-comp/slc7_amd64_gcc630/external/condor/
Binary file 3.3.1906.rc1-comp/slc7_amd64_gcc630/external/condor/8.8.2/lib/python2.7/site-packages/htcondor.so matches

```

**Comment by belforte** [comment]
?? do you mean that it is there and yet 'module' object has no attribute 'read_events' ?
if this is for your bookkeeping, fine. If it is meant as a way to communicate with me, I do not get it.
If it is meant a way to reach HTCondor developers, I suspect they do not read this, and can't say whether they would understand, I surely don't.

**Comment by lecriste** [comment]
It is just my answer to your question:
> Are you sure that you have the correct build ?

and apparently, as you said, it is there and yet `'module' object has no attribute 'read_events'`.

**Comment by belforte** [comment]
let's ping Jaime then.

**Comment by khurtado** [comment]
If it helps, this is how I setup the environment to use a specific version of condor in the external repos

```
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ pwd
/data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ ls
autotools         c-ares    couchdb15  expat       gdbm      libtool  ncurses         p5-extutils-makemaker  pcre             py2-bz2file  py2-cheetah       py2-dogpile-cache  py2-httplib2   py2-nose          py2-pycurl        py2-pyzmq     py2-rucio-clients  py2-stomp     readline      xz
boost             cherrypy  curl       fakesystem  icu4c     libuuid  openssl         p5-io-zlib             py2-argcomplete  py2-certifi  py2-cjson         py2-enum34         py2-idna       py2-progressbar2  py2-pyOpenSSL     py2-requests  py2-setuptools     py2-tabulate  rpm           yui
bootstrap-bundle  condor    db4        gcc         jemalloc  libxml2  oracle          p5-package-constants   py2-asn1crypto   py2-cffi     py2-cryptography  py2-future         py2-ipaddress  py2-psutil        py2-python-magic  py2-restkit   py2-six            py2-urllib3   spidermonkey  zlib
bz2lib            couchapp  erlang     gdb         libffi    mariadb  p5-archive-tar  p5-time-hires          py2-boto         py2-chardet  py2-cx-oracle     py2-futures        py2-mysqldb    py2-pycparser     py2-python-utils  py2-retry     py2-sqlalchemy     python        sqlite
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ export LD_LIBRARY_PATH=$PWD/boost/1.57.0-comp2/lib:$LD_LIBRARY_PATH
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ export LD_LIBRARY_PATH=$PWD/gcc/6.3.0/lib64:$LD_LIBRARY_PATH
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ export LD_LIBRARY_PATH=$PWD/openssl/1.0.1r-comp/lib:$LD_LIBRARY_PATH
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ export LD_LIBRARY_PATH=$PWD/condor/8.8.2/lib:$LD_LIBRARY_PATH
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external]$ cd condor/8.8.2/lib/python2.7/site-packages/
[khurtado@vocms0263 /data/srv/wmagent/current/sw.khurtado/slc7_amd64_gcc630/external/condor/8.8.2/lib/python2.7/site-packages]$ python
Python 2.7.5 (default, Apr  9 2019, 14:30:50)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import htcondor
>>> htcondor.version()
'$CondorVersion: 8.8.2 May 02 2019 $'
>>> readEvents = getattr(htcondor, 'readEvents', htcondor.read_events)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'read_events'
>>> dir(htcondor)
['AdTypes', 'BlockingMode', 'BulkQueryIterator', 'Claim', 'Collector', 'DaemonCommands', 'DaemonTypes', 'DrainTypes', 'EntryType', 'HistoryIterator', 'JobAction', 'JobEvent', 'JobEventLog', 'JobEventType', 'LogLevel', 'LogReader', 'Negotiator', 'QueryIterator', 'QueryOpts', 'QueueItemsIterator', 'RemoteParam', 'ResourceRequestIterator', 'Schedd', 'ScheddNegotiate', 'SecMan', 'Startd', 'Submit', 'SubmitJobsIterator', 'SubmitResult', 'SubsystemType', 'Transaction', 'TransactionFlags', 'VacateTypes', '_Param', '__doc__', '__file__', '__name__', '__package__', 'enable_classad_extensions', 'enable_debug', 'enable_log', 'log', 'param', 'platform', 'poll', 'reload_config', 'send_alive', 'send_command', 'set_subsystem', 'version']
>>>
```

**Comment by belforte** [comment]
thanks Kenyi. It is useful to reproduce the problem w/o the specifics of CRAB TW build in the way. We should make this available to Jaime et al. Can you add to the HTCondor tkt ? I don't have write there, maybe only Brian has among us CMS'ers...
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6939

**Comment by belforte** [comment]
curious that Todor's comment is "3 hours from now" making GIT confused about when to refresh the page. A  bug in github ?

**Comment by belforte** [comment]
Problem understood, here's from Jaime:
```
 This is a screw-up on our part. We decided to restore read_events() and friends for Python 2 but not Python 3 (because it’s completely broken for Python 3 on Windows). But we got the version check backwards, so they’re available in Python 3 but not Python 2. This will be fixed in the next release.

 - Jaime
```

**Comment by khurtado** [comment]
@belforte I have permissions to  write comments into the ticket, but  it seems it is not necessary anymore.

**Comment by belforte** [comment]
from Jaime:
```
Here’s a pre-release you can try out:
http://submit-3.batlab.org//nmi-runs/condorauto/2019/05/condorauto_submit-3.batlab.org_1557326446_201007/userdir/nmi:x86_64_RedHat6/results.tar.gz

 - Jaime
```

**Comment by belforte** [comment]
this issue is long and confused. Anyhow the missing API was backported to 8.8* and other problems reported here were fake or solved. 
The goal now is to validate the new condor API to read the log in 8.9
I will make and ad-hoc new issue.
