### ISSUE TITLE
PostJob fails when xfer timesout

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5853]
looks like e2623b7283a82a692aa366ebbdbe13cb934d7b14
either introduced some new bug or triggered some old one, or was anyhow insufficient:
I have shortened the timeout and killed transfers.py on my test task in order to test:
```
Mon, 25 Mar 2019 22:14:32 CET(+0000):INFO:PostJob ====== Starting to cancel ongoing ASO transfers.
Mon, 25 Mar 2019 22:14:32 CET(+0000):INFO:PostJob In case of cancellation failure, will retry up to 2 times.
Mon, 25 Mar 2019 22:14:32 CET(+0000):INFO:PostJob Cancelling ASO transfer 4442f6dffbdb12fc908db1498e0e39329091aebe5c9b1a6c39ba0230 with following reason: Cancelled ASO transfer after timeout of 3600 seconds.
Mon, 25 Mar 2019 22:17:32 CET(+0000):INFO:PostJob This is cancellation retry number 1.
Mon, 25 Mar 2019 22:17:32 CET(+0000):INFO:PostJob Cancelling ASO transfer 4442f6dffbdb12fc908db1498e0e39329091aebe5c9b1a6c39ba0230 with following reason: Cancelled ASO transfer after timeout of 3600 seconds.
Mon, 25 Mar 2019 22:20:32 CET(+0000):INFO:PostJob This is cancellation retry number 2.
Mon, 25 Mar 2019 22:20:32 CET(+0000):INFO:PostJob Cancelling ASO transfer 4442f6dffbdb12fc908db1498e0e39329091aebe5c9b1a6c39ba0230 with following reason: Cancelled ASO transfer after timeout of 3600 seconds.
Mon, 25 Mar 2019 22:20:32 CET(+0000):ERROR:PostJob Stageout failure: object of type 'int' has no len()
Traceback (most recent call last):
  File "TaskWorker/Actions/PostJob.py", line 1925, in execute_internal
    ret_code = self.perform_transfers()
  File "TaskWorker/Actions/PostJob.py", line 2063, in perform_transfers
    aso_job_retval = ASO_JOB.check_transfers()
  File "TaskWorker/Actions/PostJob.py", line 433, in check_transfers
    cancelled, not_cancelled = self.cancel(docs_to_cancel, max_retries = 2)
  File "TaskWorker/Actions/PostJob.py", line 1145, in cancel
    killedFiles = self.server.post(self.rest_uri_file_user_transfers, data=encodeRequest(newDoc, ['listOfIds', 'publish']))
  File "ServerUtilities.py", line 381, in encodeRequest
    if len(configreq[lparam]) > 0:
TypeError: object of type 'int' has no len()
```

**Comment by belforte** [comment]
@dciangot I am trying to look, but of course help is more than welcome

**Comment by belforte** [comment]
After I put in a fix in https://github.com/belforte/CRABServer/commit/9f99b1acdab9586ade2818eb744efdd999fa177d for the
```
TypeError: object of type 'int' has no len()
```
I am back at
```
Thu, 28 Mar 2019 05:35:38 CET(+0000):WARNING:PostJob Error setting KILL status in database. Transfer KILL failed.
{'Content-Length': '734', 'X-Error-Http': '400', 'X-Rest-Time': '1724.005 us', 'Server': 'CherryPy/unknown', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=15031 t=1553747738132296', 'X-Rest-Status': '302', 'Date': 'Thu, 28 Mar 2019 04:35:38 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'publish' parameter", 'X-Error-Id': '5dc54a5b19c9f1b96cf652596c8c7d73'}
```

**Comment by belforte** [comment]
2 notes so far:
1. looks like PostJob has been broken since the first time ASO was mved from Couch to Oracle in the fact that it cancels xfers 3 times in a row no matter what, and only at the end of the loop it attempts the update in Oracle. This makes it difficult to decide how to change the lines after these w/o risk or w/o extensive testing
https://github.com/dmwm/CRABServer/blob/f9ec90ab2937d1c162c366cb9b5a2bbc7bace634/src/python/TaskWorker/Actions/PostJob.py#L1092-L1136

2. I have no idea how this coudl work until now
https://github.com/dmwm/CRABServer/blob/6321853aecb08ddf53890d23b8eff60a79d2cdb3/src/python/ServerUtilities.py#L381
 and have trouble in fixing since the overall logic of this `encodeRequest` is obscure, in particular what is the exact purpose of the second argument, given that it caused things to be removed from the dictionary passed as first arg before it gets encoded (which is why Diego's attempt to add `'publish`':0` still fails

**Comment by belforte** [comment]
Update:

- point 1. above: is and stays true. Plainly wrong, but harmless, just prepares the same list 3 times sleeping 3 minutes each time 
- point 2. above: I believe that the original implementor meant the second argument in `encodeRequest` https://github.com/dmwm/CRABServer/blob/6321853aecb08ddf53890d23b8eff60a79d2cdb3/src/python/ServerUtilities.py#L373 to indicate which of the keys in the dictionary passed as first argument has a list as value. OMG !! It is a feature only used in the new (failing) committ and in the new PublisherMaster, https://github.com/dmwm/CRABServer/blob/6321853aecb08ddf53890d23b8eff60a79d2cdb3/src/python/Publisher/PublisherMaster.py#L217 clearly @dciangot did not remember/test and added `'publish'` in there which has a number, not a list, as value. I think that it would be better to make an isinstance test in the encodeRequest code. But this can wait, in case I am missing something.
- The real reason why the PJ was failing to make ASO timeouts as failed is that the call to the REST lacks the username which is needed by the call to `/crabserver/dev/fileusertransfers?killTransfersById` https://github.com/dmwm/CRABServer/blob/6321853aecb08ddf53890d23b8eff60a79d2cdb3/src/python/Databases/FileTransfersDB/Oracle/FileTransfers/FileTransfers.py#L205-L207
- I can't say now why there was a message about Incorrect publish parameter before [1]
- It makes sense of course not to  publish when transfer times out but there is no need to do anything since at least since a while PostJob only activated the publish flag after the transfer was OK

So I have some cleanup to do and add the missing username.

[1] from https://cmsweb.cern.ch/scheddmon/0120/cms225/190313_224259:beaucero_crab_Run2018C/postjob.30.0.txt see https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4685.html :
Fri, 15 Mar 2019 00:30:04 CET(+0000):WARNING:PostJob Error setting KILL status in database. Transfer KILL failed.
{'Content-Length': '734', 'X-Error-Http': '400', 'X-Rest-Time': '1789.093 us', 'Server': 'CherryPy/unknown', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=13241 t=1552606204339577', 'X-Rest-Status': '302', 'Date': 'Thu, 14 Mar 2019 23:30:04 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'publish' parameter", 'X-Error-Id': '123e476597848bcef205f3d0527e09bb'}

**Comment by belforte** [comment]
OK. I found the reason for "Incorrect 'publish' parameter". The POST calls to RESTFileUserTransfers now require the "publish" parameter at all times:
https://github.com/dmwm/CRABServer/blob/5e94890b1aa130c16d8479ccf85172341f6996c9/src/python/CRABInterface/RESTFileUserTransfers.py#L78
as per https://github.com/dmwm/CRABServer/commit/fb71606bd0117dad984dab145f44aaefcc622edf
adding it to the PostJob cancel call. So what Diego did was half right (add publish to the dictionary) and half wrong (add it to listparams)

**Comment by belforte** [comment]
have now a tested PR with all those fixes, including for the exit code which now is correctly set to 60317
https://github.com/dmwm/CRABServer/pull/5859
will put in PreProd after some final tests

**Comment by belforte** [comment]
well.... not 60317 is sent to dashboard, but crab status has
```
xtended Job Status Table:

 Job State        Most Recent Site        Runtime   Mem (MB)      CPU %    Retries   Restarts      Waste       Exit Code
   1 failed       T1_ES_PIC               0:03:13          3         12          0          0    0:01:43  Postprocessing failed

```
and using --verbose 
```
	1 jobs failed with following error message: (for example, job 2)

		Got fatal stageout exception:
		Stageout failed with code 1.
		There were 1 failed/killed stageout jobs. 1 of those jobs had a permanent failure.
		Failure reasons (per document) follow:
		- 98faf2a314b5c9444c3a1229805c395d33186913edf803674eade8b3:
		  ['Cancelled ASO transfer after timeout of 100 seconds.']
		  The last failure reason is permanent.
```

I guess this is the first time that stuck stageout is catched with a proper exit code in the PJ and the part that deals with FJR needs to be reviewed.

**Comment by belforte** [comment]
I found same messages in the user task indicated above.
So it seems more likely that such an odd output from crab status has been there forever and nobody bothered to point it out, I would expect crab status to show exit code 60317, not `Postprocessing failed`.
Will deal with this at low priority and open a new issue
