### ISSUE TITLE
improve DagmanSubmitter report of failed submissions

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5868]

**Comment by belforte** [comment]
we have submission failing because "all schedd's have zero weight"  where the TW log does not print exactly what it tries and what it find. Schedds' are not in IsCritical and so this makes little sense.
Example of current output is below
```
2019-04-10 18:22:49,113:INFO:Handler:Finished <TaskWorker.Actions.DagmanCreator.DagmanCreator object at 0x7f23dd39dfd0> on 190410_162157:bsoubasi_crab_NanoBSM3G_TT_13TeV_PH_MC in 2 seconds
2019-04-10 18:22:49,114:DEBUG:Handler:Starting <TaskWorker.Actions.DagmanSubmitter.DagmanSubmitter object at 0x7f23dd39df90> on 190410_162157:bsoubasi_crab_NanoBSM3G_TT_13TeV_PH_MC
2019-04-10 18:22:49,114:DEBUG:DagmanSubmitter:Picking up the scheduler using <function capacityMetricsChoicesHybrid at 0x7f23dffd9050>
2019-04-10 18:22:49,119:DEBUG:HTCondorLocator:Total Mem: 117777, Total Jobs: 30000, Total Uploads: 600
2019-04-10 18:22:49,120:DEBUG:HTCondorLocator:crab3@vocms0106.cern.ch: Mem 37445, MemPrct 0.32, Run 215, RunPrct 0.49, Trf 0, TrfPrct 0.50, weight: 0.317931
2019-04-10 18:22:49,120:DEBUG:HTCondorLocator:crab3@vocms0199.cern.ch: Mem 54486, MemPrct 0.46, Run 0, RunPrct 0.50, Trf 0, TrfPrct 0.50, weight: 0.462620
2019-04-10 18:22:49,121:ERROR:Handler:Problem handling 190410_162157:bsoubasi_crab_NanoBSM3G_TT_13TeV_PH_MC because of Could not find any schedd to submit to. Exception was raised: all choices have zero weight
 failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1903.rc3/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1903.rc3/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/3.3.1903.rc3/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1903.rc3/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 245, in execute
    schedd = self.pickAndSetSchedd(task)
  File "/data/srv/TaskManager/3.3.1903.rc3/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1903.rc3/lib/python2.7/site-packages/TaskWorker/Actions/DagmanSubmitter.py", line 220, in pickAndSetSchedd
    schedd = loc.getSchedd(chooserFunction=self.config.TaskWorker.scheddPickerFunction)
  File "/data/srv/TaskManager/3.3.1903.rc3/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1903.rc3/lib/python2.7/site-packages/HTCondorLocator.py", line 144, in getSchedd
    raise Exception("Could not find any schedd to submit to. Exception was raised: %s\n" % str(ex))
Exception: Could not find any schedd to submit to. Exception was raised: all choices have zero weight
```
it only lists weigth for the disabled schedd's (106 and 199) !

**Comment by belforte** [comment]
looking at the code
https://github.com/dmwm/CRABServer/blob/bdcca1fe61f4d2f1efa78360ddaaeb93d9f06a9e/src/python/HTCondorLocator.py#L113
the list of schedd's comes from the REST config and then is filter by 
https://github.com/dmwm/CRABServer/blob/bdcca1fe61f4d2f1efa78360ddaaeb93d9f06a9e/src/python/HTCondorLocator.py#L135-L136
and the weighted choice is only applied on what survives.
So it looks like at some time ALL schedd's where havin `isOk` False, which sould be very worrying, and is in constrant with what https://cms-gwmsmon.cern.ch/poolview was reporting.
I will add some diagnostic for when a schedd is not OK.

**Comment by todor-ivanov** [comment]
The actual list of schedds is  stripped again in this line: 
https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/HTCondorLocator.py#L138

Which basically should use the scheddPickerFunction from the TW config file and currently this one is:
config.TaskWorker.scheddPickerFunction = HTCondorLocator.capacityMetricsChoicesHybrid

So even if the schedds are Ok we can still end up with a list of schedds with only 0 weights and through the error from here:
https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/HTCondorLocator.py#L21

**Comment by todor-ivanov** [comment]
so we are calling this one:

https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/HTCondorLocator.py#L47

**Comment by belforte** [comment]
yes. But then the printout should list the weigth of all schedd's. Intead only 106 and 199 are listed and there the weigth computed by capacityMetricsChoicesHybrid is overwritten with 0 from the configuration.
This matches my memory, the only reason for not submitting to one schedd is that its isOk flag is false.
But this is the first time that I see this happengin w/o schedd's being clearly critical in gwmsmon

**Comment by belforte** [comment]
I think I understand the flow of the code here.
I will simply add the printing of some information whenever a schedd is not OK

**Comment by todor-ivanov** [comment]
I think for some reason inside 'capacityMetricsChoicesHybrid' we end up with only those two schedds in the 'choises' list (vocms0106 and vocms0199) which both has 0 weights in the REST config

**Comment by belforte** [comment]
@todor-ivanov that was the starting point. I am adding logging exactly to go from "for some reason" to a definitive answer.

**Comment by belforte** [comment]
I found it the key point.
Indeed at some point we added in the code the filtering out of schedd's which are at the limit of running dagmans
https://github.com/dmwm/CRABServer/blob/bdcca1fe61f4d2f1efa78360ddaaeb93d9f06a9e/src/python/HTCondorLocator.py#L126-L129

Note the 'StartSchedulerUniverse =?= true'  !
I am not sure how we can then end up with tens of Idle tasks, other then... submitting so fast that by the time the TW notices that the start expression is false, a lof of stuff has been sent.
Another thing which can make for idle tasks are resubmissions, where a dagman job is released from Hold status of course w/o this kind of check, and then stays Idle. We do get plenty of resubmissions.

**Comment by belforte** [comment]
In conclusion, I see no indication of problems. Other then the fact that I keep forgetting what's the design behavior when we reach saturation.
I guess it would be useful to detect the "all schedd's are saturated" and print to users a better message than "all have zero weight" which they can't understand and confuses us.
