### ISSUE TITLE
transfers.py does not delegate proxy

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5917]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5046/2/2/2.html

transfer_inject.log has:
```
2019-07-08 17:57:15,013[   214]MainThread: error during main loop
Traceback (most recent call last):
  File "task_process/transfers.py", line 580, in <module>
    algorithm()
  File "task_process/transfers.py", line 551, in algorithm
    proxy,
NameError: global name 'proxy' is not defined
```
which seems to come from these lines, where indeed `proxy` is an undefined variable:
https://github.com/dmwm/CRABServer/blob/67c45b2bfcf650e1e2f4f086fa88a9f23e20d3e9/scripts/task_process/transfers.py#L550-L556

**Comment by belforte** [comment]
AFAICT it has been like this since ever:
https://github.com/dmwm/CRABServer/commit/fa43606e194777a8363afe34c4c425e7dfdc32fb#diff-d74ab69ad0e2fc7a4574344b3bf09397

@dciangot any idea ?

**Comment by belforte** [comment]
Actually the `proxy` variable should have been filled here
https://github.com/dmwm/CRABServer/blob/67c45b2bfcf650e1e2f4f086fa88a9f23e20d3e9/scripts/task_process/transfers.py#L29-L33
Maybe it is by design that transfers.py fails until the `task_process/rest_filetransfers.txt` is created as jobs start to complete.
Yet there is no error logger from the delegation and trasnfers are submitted. But when 5 min after the first submissions, FTS complains about invalid delegated credentials:
```
2019-07-08 18:32:19,167[   748]Thread-1: Processing transfers from: T2_US_Vanderbilt
2019-07-08 18:32:19,168[   748]Thread-1: Submitting 2 transfers to FTS server
2019-07-08 18:32:19,276[   856]Thread-1: Marking submitted 2 files
2019-07-08 18:32:19,418[   999]MainThread: Marked submitted ['32986c4f9c515dc3426427a6d4c00fd48e916bb3f29706bbece6815d', 'e7876b3301e603d28bfe3317e3dc02be90b926ed882b6403b5f2acab'] files
2019-07-08 18:32:19,419[   999]MainThread: Monitor link: https://fts3.cern.ch:8449/fts3/ftsmon/#/job/f4510fee-a19d-11e9-b8a6-02163e007803
2019-07-08 18:32:19,419[   999]MainThread: Transfer jobs ongoing: [], new: [u'f4510fee-a19d-11e9-b8a6-02163e007803'] 
2019-07-08 18:32:19,421[  1001]MainThread: transfer_inject.py exiting
2019-07-08 18:37:20,132[   512]Thread-1: Getting state of job f4510fee-a19d-11e9-b8a6-02163e007803
2019-07-08 18:37:20,228[   609]Thread-1: State of job f4510fee-a19d-11e9-b8a6-02163e007803: FAILED
2019-07-08 18:37:20,328[   709]Thread-1: Failure reason: SOURCE [13] globus_ftp_client: the server responded with an error 530 530-globus_xio: Authentication Error  530-OpenSSL Error: s3_srvr.c:3327: in library: SSL routines, function ssl3_get_client_certificate: certificate verify failed  530-globus_gsi_callback_module: Could not verify credential  530-globus_gsi_callback_module: The certificate has expired: Credential with subject: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=binghuan/CN=780072/CN=Binghuan Li/CN=513534465/CN=1187379417/CN=767359201 has expired.  530 End.  

```

**Comment by belforte** [comment]
the proxy file is fine [*]
so this seems a problem inside FTS.

[*]
```
belforte@vocms0121/transfers> ls ../../228b52d2a8af50f71f43285d8cf0f420b0b16582 
../../228b52d2a8af50f71f43285d8cf0f420b0b16582
belforte@vocms0121/transfers> ls -l ../../228b52d2a8af50f71f43285d8cf0f420b0b16582 
-rw------- 1 cms415 zh 16096 Jul 15 04:04 ../../228b52d2a8af50f71f43285d8cf0f420b0b16582
belforte@vocms0121/transfers> sudo voms-proxy-info -file ../../228b52d2a8af50f71f43285d8cf0f420b0b16582
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=binghuan/CN=780072/CN=Binghuan Li/CN=630425041/CN=418024431/CN=531504508/CN=3105862966/CN=1589357286
issuer    : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=binghuan/CN=780072/CN=Binghuan Li/CN=630425041/CN=418024431/CN=531504508/CN=3105862966
identity  : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=binghuan/CN=780072/CN=Binghuan Li/CN=630425041/CN=418024431/CN=531504508/CN=3105862966
type      : RFC compliant proxy
strength  : 2048 bits
path      : ../../228b52d2a8af50f71f43285d8cf0f420b0b16582
timeleft  : 156:28:21
belforte@vocms0121/transfers> 
```
One thing which I can do is to make sure that the delegation result is logged, changing this
https://github.com/dmwm/CRABServer/blob/67c45b2bfcf650e1e2f4f086fa88a9f23e20d3e9/scripts/task_process/transfers.py#L555
to `logging.info`

**Comment by belforte** [comment]
But at this point I got convinced that it is a problem in FTS.
