### ISSUE TITLE
when executing ScriptExe the script stdout is printed twice

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5934]
From a recent job:
```
==== ScriptEXE Execution started at Wed Aug  7 06:36:57 2019 ====
2019-08-07 06:37:06,920:INFO:Scram:Creating a subprocess to run the PSet setup.
2019-08-07 06:37:06,921:INFO:Scram:Also recording SCRAM command-line related output.
2019-08-07 06:37:06,949:INFO:Scram:    Invoking command: /srv/myscript.sh 1 
2019-08-07 11:37:51,159:INFO:Scram:Subprocess stdout was:
Here there are all the input arguments
1
================= PSet.py file ==================
import FWCore.ParameterSet.Config as cms

many lines follow... until

2019-08-07 11:37:51,189:INFO:Scram:Subprocess stderr was:
None
Job exit code: 0
==== CMSSW Stack Execution FINISHED at Wed Aug  7 11:37:51 2019 ====
======== CMSSW OUTPUT STARTING ========
NOTICE: lines longer than 3000 characters will be truncated
WARNING: CMSSW output more then 4000 lines; truncating to first 1000 and last 3000
Use 'crab getlog' to retrieve full output of this job from storage.
=======================================
== CMSSW: Here there are all the input arguments
== CMSSW: 1
== CMSSW: ================= PSet.py file ==================
== CMSSW: import FWCore.ParameterSet.Config as cms
```

This also makes job stdout grow unbounded, since the command stdout which is now logged by Scram () is not trimmed to max 4k lines, differently from stdout piped to file and reported later.

Something went wrong with the adaptation to new Scram() in https://github.com/dmwm/CRABServer/issues/5846

**Comment by belforte** [comment]
THis is at the root of the problem that @mmascher found two weeks ago, see #5925 
which was addressed in https://github.com/dmwm/CRABServer/pull/5930/files

See some debugging information here about this new task (which was not using Heppy) but shows identical behavior. 
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5115/1/2/1/1/2/3/1/1/1/1/3.html

ScriptExe was  killed (by a SIGTERM, likely issued by the site due to using too much
memory) :
```
/srv/myscript.sh: line 14:   214 Killed                  cmsRun -j FrameworkJobReport.xml -p PSet.py
```
and that triggered the whole mess.

It not that HEPPY or some other script changed. But things changed so that full scriptExe stdout is
printed in job stdout, which was not meant to be:
https://github.com/dmwm/CRABServer/blob/c33576ee261a32fd0c076cb95f2db50c48a50aaf/scripts/CMSRunAnalysis.py#L677-L678
Besides the stdout is read in memory by the new Scram() method so that wrapper can later put in a file (instead of piping it like done before)
https://github.com/dmwm/CRABServer/blob/c33576ee261a32fd0c076cb95f2db50c48a50aaf/scripts/CMSRunAnalysis.py#L684-L685
I do not think that the stdout is so large to make the job run out of memory (even it is several MB's) but somehow things do not work properly when there is an exception or the scriptExe is killed, the full stdout ends in the exit code via the new `scram.diagnostic()` method 
https://github.com/dmwm/CRABServer/blob/c33576ee261a32fd0c076cb95f2db50c48a50aaf/scripts/CMSRunAnalysis.py#L679-L683
https://github.com/dmwm/WMCore/blob/73a923990cabfba6d2ba88dc0aecbc98a7a425d8/src/python/WMCore/WMRuntime/Tools/Scram.py#L369

**Comment by belforte** [comment]
So while the patch in https://github.com/dmwm/CRABServer/pull/5930/files should work and be useful if it ever happen that error message goes out of bond again, we clearly want to solve this at the root by doing at least 2 things
   1. avoid duplicate stdout (I still do not understand how this happened)
   1. avoid dumping stdout+stderr in the exception message (this is quite clear, I think)

**Comment by belforte** [comment]
The duplicated output is most likely due to this:
https://github.com/dmwm/CRABServer/blob/c33576ee261a32fd0c076cb95f2db50c48a50aaf/scripts/CMSRunAnalysis.py#L935-L941
which was there since ever, but I am not sure it is needed with new `scram()`

**Comment by belforte** [comment]
plan, with ref, to 1. and 2. above https://github.com/dmwm/CRABServer/issues/5934#issuecomment-520062303 

- [ ]  do not ad stdout to logger and review calls to logging in the code
- [ ] do not insert `scram.diagnostic()` output in the exceptoin, but use it to fill the `cmsRun-stdout.log` file in place of `scram.stdout()`.

**Comment by belforte** [comment]
I ended up in reverting code put in for #5925 and doing the work in here besides a few minor additions to printout.
I tested this running job wrapper interacrively as per
https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#Better_way_with_preparelocal
and forcing scriptExe failure via kill, also tested with output longer then line limits.
More testing with actual jobs is still useful.

**Comment by belforte** [comment]
this is now installed in preprod

**Comment by belforte** [comment]
here's relevant part of job stdout with a scriptExe which fails (hardcoded non zero exti code):
```

===================
==== Sandbox preparation STARTING at Wed Aug 14 19:56:21 2019 ====
Sandbox sandbox.tar.gz already exists, skipping

==== Sandbox preparation FINISHED at Wed Aug 14 19:56:21 2019 ====
==== WMCore filesystem preparation STARTING at Wed Aug 14 19:56:21 2019 ====
==== WMCore filesystem preparation FINISHED at Wed Aug 14 19:56:21 2019 ====
Dashboard startup parameters: {'MonitorID': '190814_195016:belforte_crab_20190814_215009', 'MonitorJobID': '1_https://glidein.cern.ch/1/190814:195016:belforte:crab:20190814:215009_0', 'WNHostName': 'b7w06n0198.cern.ch', 'ExeStart': 'cmsRun'}
==== CMSSW Stack Execution STARTING at Wed Aug 14 19:56:21 2019 ====
==== SCRAM Obj CREATED at Wed Aug 14 19:56:21 2019 ====

==== ScriptEXE Execution started at Wed Aug 14 19:56:27 2019 ====
Executing python /srv/TweakPSet.py --location=/srv --inputFile='job_input_file_list_1.txt' --runAndLumis='job_lumis_1.json' --firstEvent=None --lastEvent=None --firstLumi=None --firstRun=None --seeding=AutomaticSeeding --lheInputFiles=False --oneEventMode=0 --eventsPerLumi=None --maxRuntime=-60
Exdcuting user script: /srv/myscript.sh 1 
WARNING: Unable to parse WMCore's jobReport.json; FJR will not be useful.
 Traceback (most recent call last):
  File "CMSRunAnalysis.py", line 381, in handleException
    report = json.load(open("jobReport.json"))
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python/2.7.13-fmblme/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python/2.7.13-fmblme/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python/2.7.13-fmblme/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/python/2.7.13-fmblme/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

ERROR: Exceptional exit at Wed Aug 14 19:58:18 2019 (10040): Error executing scriptExe.
	See stdout log
== Execution site for failed job from site-local-config.xml: T2_CH_CERN
Dashboard end parameters: {'NCores': 1, 'JobExitCode': 10040, 'MonitorJobID': '1_https://glidein.cern.ch/1/190814:195016:belforte:crab:20190814:215009_0', 'MonitorID': '190814_195016:belforte_crab_20190814_215009'}
Not sending data to popularity service because no input sources found.
Dashboard popularity report: {'Basename': '', 'inputFiles': '', 'BasenameParent': '', 'inputBlocks': '/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#3517e1b6-76e3-11e7-a0c8-02163e00d7b3', 'parentFiles': ''}
==== CMSSW Stack Execution FAILED at Wed Aug 14 19:58:19 2019 ====
======== CMSSW OUTPUT STARTING ========
NOTICE: lines longer than 3000 characters will be truncated
== CMSSW:
== CMSSW:         Scram Command Diagnostic:
== CMSSW:         Command : scramv1
== CMSSW:         Architecture: slc6_amd64_gcc700
== CMSSW:         Executed: /srv/myscript.sh 1
== CMSSW:         Exit Status: 5
== CMSSW:         Stdout: ================= SB CMSRUN starting ====================
== CMSSW: 14-Aug-2019 19:56:39 UTC  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root
== CMSSW: 14-Aug-2019 19:56:47 UTC  Successfully opened file root://eoscms.cern.ch//eos/cms/store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root
== CMSSW: Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 14-Aug-2019 19:56:58.328 UTC
== CMSSW: Begin processing the 101st record. Run 1, Event 101, LumiSection 1 on stream 0 at 14-Aug-2019 19:57:09.921 UTC
== CMSSW: Begin processing the 201st record. Run 1, Event 201, LumiSection 1 on stream 0 at 14-Aug-2019 19:57:22.035 UTC
== CMSSW: Begin processing the 301st record. Run 1, Event 575701, LumiSection 1920 on stream 0 at 14-Aug-2019 19:57:29.823 UTC
== CMSSW: Begin processing the 401st record. Run 1, Event 575801, LumiSection 1920 on stream 0 at 14-Aug-2019 19:57:46.884 UTC
== CMSSW: Begin processing the 501st record. Run 1, Event 575901, LumiSection 1920 on stream 0 at 14-Aug-2019 19:57:55.251 UTC
== CMSSW: 14-Aug-2019 19:58:13 UTC  Closed file root://eoscms.cern.ch//eos/cms/store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root
== CMSSW:
== CMSSW: =============================================
== CMSSW:
== CMSSW: MessageLogger Summary
== CMSSW:
== CMSSW:  type     category        sev    module        subroutine        count    total
== CMSSW:  ---- -------------------- -- ---------------- ----------------  -----    -----
== CMSSW:     1 fileAction           -s file_close                             1        1
== CMSSW:     2 fileAction           -s file_open                              2        2
== CMSSW:
== CMSSW:  type    category    Examples: run/evt        run/evt          run/evt
== CMSSW:  ---- -------------------- ---------------- ---------------- ----------------
== CMSSW:     1 fileAction           PostGlobalEndRun
== CMSSW:     2 fileAction           pre-events       pre-events
== CMSSW:
== CMSSW: Severity    # Occurrences   Total Occurrences
== CMSSW: --------    -------------   -----------------
== CMSSW: System                  3                   3
== CMSSW:
== CMSSW: dropped waiting message count 0
== CMSSW: TimeReport> Time report complete in 104.285 seconds
== CMSSW:  Time Summary:
== CMSSW:  - Min event:   0.0210772
== CMSSW:  - Max event:   9.76941
== CMSSW:  - Avg event:   0.120626
== CMSSW:  - Total loop:  77.2943
== CMSSW:  - Total init:  24.4403
== CMSSW:  - Total job:   104.285
== CMSSW:  - EventSetup Lock:   0
== CMSSW:  - EventSetup Get:   0
== CMSSW:  Event Throughput: 7.76253 ev/s
== CMSSW:  CPU Summary:
== CMSSW:  - Total loop:  66.5578
== CMSSW:  - Total init:  9.65229
== CMSSW:  - Total extra: 0
== CMSSW:  - Total job:   78.3862
== CMSSW:  Processing Summary:
== CMSSW:  - Number of Events:  600
== CMSSW:  - Number of Global Begin Lumi Calls:  2
== CMSSW:  - Number of Global Begin Run Calls: 1
== CMSSW:
== CMSSW: ================= SB CMSRUN finished ====================
== CMSSW: ================= CRAB_Retry value is 0 =============================
== CMSSW: ++ ExeExit=0
== CMSSW: ++ '[' 0 == 0 ']'
== CMSSW: ++ ExeExit=80000
== CMSSW: ++ set +x
== CMSSW: ================= SB CMSRUN exit code was: 80000 =====
== CMSSW:
== CMSSW:         Stderr: None
======== CMSSW OUTPUT FINSHING ========
+ jobrc=56
+ set +x
== The job had an exit code of 56 
======== CMSRunAnalysis.py FINISHING at Wed Aug 14 19:58:19 GMT 2019 ========

real	1m58.808s
user	1m17.097s
sys	0m6.185s
CMSRunAnalysis.sh complete at Wed Aug 14 19:58:19 GMT 2019 with (short) exit status 56
======== CMSRunAnalsysis.sh at Wed Aug 14 19:58:19 GMT 2019 FINISHING ========
======== python2.6 bootstrap for stageout at Wed Aug 14 19:58:19 GMT 2019 STARTING ========
+ '[' -f /cvmfs/cms.cern.ch/cmsset_default.sh ']'
+ set +x
+ '[' -e /cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.6/etc/profile.d/init.sh ']'
+ set +x
+ command -v python2.7
+ rc=0
+ set +x
Found python2.7 at:
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.6/bin/python2.7
======== python2.7 bootstrap for stageout at Wed Aug 14 19:58:19 GMT 2019 FINISHING ========
======== Stageout at Wed Aug 14 19:58:19 GMT 2019 STARTING ========
====== Wed Aug 14 19:58:19 2019: cmscp.py STARTING.
The user has not specified to transfer the log files. No log files stageout (nor log files metadata upload) will be performed.
Stageout policy: local, remote
====== Wed Aug 14 19:58:19 2019: Starting job report validation.
ERROR: Invalid job report: missing 'steps'.
WARNING: Unable to retrieve payload exit code ('jobExitCode') from job report.
Currently this exit code is not used for anything, so this error can be ignored.
Retrieved job wrapper exit code ('exitCode') = 10040 from job report.
====== Wed Aug 14 19:58:19 2019: Finished job report validation (status 80000).
Setting stageout wrapper exit info to {'exit_acronym': 'FAILED', 'exit_code': 80000, 'exit_msg': "CmsCpFailure\ncmscp error message follows.\nERROR: Invalid job report: missing 'steps'."}.
====== Wed Aug 14 19:58:19 2019: Starting to check if user output files exist.
Output file kk.root exists.
====== Wed Aug 14 19:58:19 2019: Finished to check if user output files exist (status 0).
Will use gfal2 commands for direct stageout.
Job wrapper did not finish successfully (exit code 10040). Setting that same exit code for the stageout wrapper.
Stageout wrapper finished with exit code 10040. Will report failure to Dashboard.
Dashboard stageout failure parameters: {'MonitorID': '190814_195016:belforte_crab_20190814_215009', 'MonitorJobID': '1_https://glidein.cern.ch/1/190814:195016:belforte:crab:20190814:215009_0', 'JobExitCode': 10040}
====== Wed Aug 14 19:58:20 2019: cmscp.py FINISHING (status 10040).
======== Stageout at Wed Aug 14 19:58:20 GMT 2019 FINISHING (short status 56) ========
======== gWMS-CMSRunAnalysis.sh FINISHING at Wed Aug 14 19:58:20 GMT 2019 on b7w06n0198.cern.ch with (short) status 56 ========
Local time: Wed Aug 14 19:58:20 UTC 2019
Short exit status: 56
======== Figuring out long exit code of the job for condor_chirp ========
==== Long exit code of the job is 10040 ====
======== Finished condor_chirp -ing the exit code of the job. Exit code of condor_chirp: 0 ========
Job Running time in seconds:  120
```

**Comment by belforte** [comment]
and this is for same job after forcing scriptExe exit code to 0 instead
```

==== Sandbox preparation STARTING at Wed Aug 14 20:10:36 2019 ====
Sandbox sandbox.tar.gz already exists, skipping

==== Sandbox preparation FINISHED at Wed Aug 14 20:10:36 2019 ====
==== WMCore filesystem preparation STARTING at Wed Aug 14 20:10:36 2019 ====
==== WMCore filesystem preparation FINISHED at Wed Aug 14 20:10:36 2019 ====
Dashboard startup parameters: {'MonitorID': '190814_200740:belforte_crab_20190814_220735', 'MonitorJobID': '1_https://glidein.cern.ch/1/190814:200740:belforte:crab:20190814:220735_0', 'WNHostName': 'cmsgli-7998581-0-cmswn2414.fnal.gov', 'ExeStart': 'cmsRun'}
==== CMSSW Stack Execution STARTING at Wed Aug 14 20:10:37 2019 ====
==== SCRAM Obj CREATED at Wed Aug 14 20:10:37 2019 ====

==== ScriptEXE Execution started at Wed Aug 14 20:10:45 2019 ====
Executing python /srv/TweakPSet.py --location=/srv --inputFile='job_input_file_list_1.txt' --runAndLumis='job_lumis_1.json' --firstEvent=None --lastEvent=None --firstLumi=None --firstRun=None --seeding=AutomaticSeeding --lheInputFiles=False --oneEventMode=0 --eventsPerLumi=None --maxRuntime=-60
Exdcuting user script: /srv/myscript.sh 1 
==== ScriptEXE Execution completed at Wed Aug 14 20:13:09 2019 ====
Job exit code: 0
==== CMSSW Stack Execution FINISHED at Wed Aug 14 20:13:09 2019 ====
======== CMSSW OUTPUT STARTING ========
NOTICE: lines longer than 3000 characters will be truncated
== CMSSW: ================= SB CMSRUN starting ====================
== CMSSW: 14-Aug-2019 20:11:01 UTC  Initiating request to open file root://cmsxrootd-site.fnal.gov//store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root
== CMSSW: [2019-08-14 20:11:04.441162 +0000][Warning][XRootDTransport   ] [131.225.205.119:32208 #0.0] Logged in, accepting empty login response.
== CMSSW: %MSG-w XrdAdaptor:  file_open 14-Aug-2019 20:11:04 UTC pre-events
== CMSSW: Data is served from fnal.gov instead of original site T1_US_FNAL
== CMSSW: %MSG
== CMSSW: 14-Aug-2019 20:11:10 UTC  Successfully opened file root://cmsxrootd-site.fnal.gov//store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root
== CMSSW: [2019-08-14 20:11:26.204994 +0000][Warning][XRootDTransport   ] [131.225.206.137:33305 #0.0] Logged in, accepting empty login response.
== CMSSW: Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 14-Aug-2019 20:11:26.834 UTC
== CMSSW: Begin processing the 101st record. Run 1, Event 101, LumiSection 1 on stream 0 at 14-Aug-2019 20:11:40.701 UTC
== CMSSW: Begin processing the 201st record. Run 1, Event 201, LumiSection 1 on stream 0 at 14-Aug-2019 20:11:56.166 UTC
== CMSSW: Begin processing the 301st record. Run 1, Event 575701, LumiSection 1920 on stream 0 at 14-Aug-2019 20:12:04.683 UTC
== CMSSW: Begin processing the 401st record. Run 1, Event 575801, LumiSection 1920 on stream 0 at 14-Aug-2019 20:12:27.907 UTC
== CMSSW: Begin processing the 501st record. Run 1, Event 575901, LumiSection 1920 on stream 0 at 14-Aug-2019 20:12:37.408 UTC
== CMSSW: 14-Aug-2019 20:12:58 UTC  Closed file root://cmsxrootd-site.fnal.gov//store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root
== CMSSW:
== CMSSW: =============================================
== CMSSW:
== CMSSW: MessageLogger Summary
== CMSSW:
== CMSSW:  type     category        sev    module        subroutine        count    total
== CMSSW:  ---- -------------------- -- ---------------- ----------------  -----    -----
== CMSSW:     1 XrdAdaptor           -w file_open                              1        1
== CMSSW:     2 fileAction           -s file_close                             1        1
== CMSSW:     3 fileAction           -s file_open                              2        2
== CMSSW:
== CMSSW:  type    category    Examples: run/evt        run/evt          run/evt
== CMSSW:  ---- -------------------- ---------------- ---------------- ----------------
== CMSSW:     1 XrdAdaptor           pre-events
== CMSSW:     2 fileAction           PostGlobalEndRun
== CMSSW:     3 fileAction           pre-events       pre-events
== CMSSW:
== CMSSW: Severity    # Occurrences   Total Occurrences
== CMSSW: --------    -------------   -----------------
== CMSSW: Warning                 1                   1
== CMSSW: System                  3                   3
== CMSSW:
== CMSSW: dropped waiting message count 0
== CMSSW: TimeReport> Time report complete in 135.417 seconds
== CMSSW:  Time Summary:
== CMSSW:  - Min event:   0.0285392
== CMSSW:  - Max event:   12.3996
== CMSSW:  - Avg event:   0.150501
== CMSSW:  - Total loop:  96.0551
== CMSSW:  - Total init:  32.5206
== CMSSW:  - Total job:   135.417
== CMSSW:  - EventSetup Lock:   0
== CMSSW:  - EventSetup Get:   0
== CMSSW:  Event Throughput: 6.24641 ev/s
== CMSSW:  CPU Summary:
== CMSSW:  - Total loop:  90.0284
== CMSSW:  - Total init:  16.985
== CMSSW:  - Total extra: 0
== CMSSW:  - Total job:   111.621
== CMSSW:  Processing Summary:
== CMSSW:  - Number of Events:  600
== CMSSW:  - Number of Global Begin Lumi Calls:  2
== CMSSW:  - Number of Global Begin Run Calls: 1
== CMSSW:
== CMSSW: ================= SB CMSRUN finished ====================
== CMSSW: ================= CRAB_Retry value is 0 =============================
== CMSSW: ++ ExeExit=0
== CMSSW: ++ '[' 0 == 0 ']'
== CMSSW: ++ ExeExit=00000
== CMSSW: ++ set +x
== CMSSW: ================= SB CMSRUN exit code was: 00000 =====
======== CMSSW OUTPUT FINSHING ========
==== Report file creation STARTING at Wed Aug 14 20:13:09 2019 ====
==== Checksum computation STARTING at Wed Aug 14 20:13:09 2019 ====
==== Checksum FINISHED at Wed Aug 14 20:13:10 2019 ====
== FileName: kk.root  -  FileAdler32: 6ba0d1d8  - FileSize: 77.032 MBytes
== Adding PSet Hash for filename: kk.root
==== PSet Hash computation STARTING at Wed Aug 14 20:13:10 2019 ====
==== PSet Hash computation FINISHED at Wed Aug 14 20:13:34 2019 ====
== edmProvDump pset hash bb695911428445ed11a1006c9940df69
== Execution site from site-local-config.xml: T1_US_FNAL_Disk
Dashboard end parameters: {'MonitorID': '190814_200740:belforte_crab_20190814_220735', 'CRABUserReadMB': 125.50865999999999, 'MonitorJobID': '1_https://glidein.cern.ch/1/190814:200740:belforte:crab:20190814:220735_0', 'CrabCpuPercentage': 0.8268222222222222, 'CRABUserWriteMB': 77.0321, 'CrabUserCpuTime': 111.621, 'NEventsProcessed': 600, 'ExeTime': 135, 'JobExitCode': 0, 'CRABUserPeakRss': 972.867, 'NCores': 1, 'ExeExitCode': 0}
Dashboard popularity report: {'Basename': '/store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000', 'inputFiles': '/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root::1::EDM::Local::1', 'BasenameParent': '', 'inputBlocks': '/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#3517e1b6-76e3-11e7-a0c8-02163e00d7b3', 'parentFiles': ''}
==== Report file creation FINISHED at Wed Aug 14 20:13:35 2019 ====
==== CMSRunAnalysis.py FINISHED at Wed Aug 14 20:13:35 2019 ====
Local time : Wed Aug 14 20:13:35 2019
+ jobrc=0
+ set +x
== The job had an exit code of 0 
======== CMSRunAnalysis.py FINISHING at Wed Aug 14 20:13:35 GMT 2019 ========

real	3m1.797s
user	1m53.559s
sys	0m22.512s
CMSRunAnalysis.sh complete at Wed Aug 14 20:13:35 GMT 2019 with (short) exit status 0
======== CMSRunAnalsysis.sh at Wed Aug 14 20:13:35 GMT 2019 FINISHING ========
```

**Comment by belforte** [comment]
will now test with some normal jobs.
