### ISSUE TITLE
Import of Utils.Throttled fails

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5962]
with ref. to
https://github.com/dmwm/CRABServer/pull/5880
this import
https://github.com/dmwm/CRABServer/blob/65b4d80150caf13018e4c09aa21f819ef93a78a0/src/python/CRABInterface/HTCondorDataWorkflow.py#L23
makes CRABSERVER Rest fail at the very start with this traceback
```
[19/Oct/2019:05:22:08]  ERROR: terminating due to error, error trace follows
[19/Oct/2019:05:22:08]  ERROR:   Traceback (most recent call last):
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Main.py", line 418, in start_daemon
[19/Oct/2019:05:22:08]  ERROR:       self.run()
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Main.py", line 475, in run
[19/Oct/2019:05:22:08]  ERROR:       self.install_application()
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Main.py", line 268, in install_application
[19/Oct/2019:05:22:08]  ERROR:       obj = getattr(module, class_name)(self, view, path)
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/CRABInterface/RESTBaseAPI.py", line 56, in __init__
[19/Oct/2019:05:22:08]  ERROR:       self._add( {'workflow': RESTUserWorkflow(app, self, config, mount, extconfig),
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/CRABInterface/RESTUserWorkflow.py", line 36, in __init__
[19/Oct/2019:05:22:08]  ERROR:       self.userworkflowmgr = DataUserWorkflow()
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/CRABInterface/DataUserWorkflow.py", line 15, in __init__
[19/Oct/2019:05:22:08]  ERROR:       mod = __import__('CRABInterface.%s' % self.workflowManager, fromlist=self.workflowManager)
[19/Oct/2019:05:22:08]  ERROR:     File "/data/srv/HG1911a-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1911.rc1-comp/lib/python2.7/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 23, in <module>
[19/Oct/2019:05:22:08]  ERROR:       from Utils.Throttled import global_user_throttle
[19/Oct/2019:05:22:08]  ERROR:   ImportError: No module named Throttled
```
While if I setup the env. via the crabservber init.sh (even replaying the crabserver startup script) and the open python the import works.
I will need help from experts in WMCore REST.

Until then, I will comment out the call to the throttling code.

**Comment by amaltaro** [comment]
@belforte Stefano, can you please try to import something - in this same module - from the Utils package?
Some time ago I also faced weird import issues that I could not reproduced. I managed to fix that by importing absolute_imports
```
from __future__ import absolute_import
```
it might solve your case too.

**Comment by belforte** [comment]
magic @amaltaro . It worked.
Of course this does not clearly explains why it works from python prompt, but...
I am now wondering if there could be a clash with other Utils subdirectories elsewhere in PYTHONPATH, like we have
```
from CRABInterface.Utils import blah...
```
