### ISSUE TITLE
remove dependency on deprecated htcondor.read_event

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5972]
see #5939 #5708 #5942
need to switch
https://github.com/dmwm/CRABServer/blob/b8d3430438f6c2fcf1a9908d545ec9864fb8fb77/src/python/CRABInterface/HTCondorDataWorkflow.py#L967
to use new `htcondor.JobEventLog` as was done in
https://github.com/dmwm/CRABServer/blob/master/scripts/task_process/cache_status_jel.py

- [ ] after this is in production we can finally remove 
readEvents = getattr(htcondor, 'readEvents', htcondor.read_events)

**Comment by belforte** [comment]
this call in
 https://github.com/dmwm/CRABServer/blob/b8d3430438f6c2fcf1a9908d545ec9864fb8fb77/src/python/CRABInterface/HTCondorDataWorkflow.py#L967
is part of the ``status` API which I believe is not used any more since we switched to using the cache file.

I will begin by commenting this API out in preprod server.

**Comment by belforte** [comment]
the crabserver UI now fails to show tabs other then tw detail
https://cmsweb-test.cern.ch/crabserver/ui/task/191105_133557%3Alecriste_crab_AutomaticSplitt_data_preprod_transfersFalse_clientTest_serverTest_highP/dbver/preprod
crabserver logs has [1]
maybe the API which I deleted is used in the UI ?
[1]
```
[05/Nov/2019:21:50:54]  SERVER DATABASE ERROR 500/403 Execution error __builtins__.TypeError 12fce18d9b7d4fc4a302196ca4d0ad45 [instance: preprod] (status() got an unexpected keyword argument 'verbose'); last statement: None; binds: None, None; offset: None
[05/Nov/2019:21:50:54]    Traceback (most recent call last):
[05/Nov/2019:21:50:54]      File "/data/srv/HG1911c-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1912.rc1/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1769, in dbapi_wrapper
[05/Nov/2019:21:50:54]        return handler(*xargs, **xkwargs)
[05/Nov/2019:21:50:54]      File "/data/srv/HG1911c-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1912.rc1/lib/python2.7/site-packages/CRABInterface/RESTUserWorkflow.py", line 683, in get
[05/Nov/2019:21:50:54]        result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)
[05/Nov/2019:21:50:54]      File "/data/srv/HG1911c-comp4/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.1912.rc1/lib/python2.7/site-packages/CRABInterface/DataUserWorkflow.py", line 173, in status
[05/Nov/2019:21:50:54]        return self.workflow.status(workflow, userdn, userproxy, verbose=verbose)
[05/Nov/2019:21:50:54]    TypeError: status() got an unexpected keyword argument 'verbose'
[05/Nov/2019:21:50:54] crabserver-f548dcb86-ksdhp 137.138.33.200 "GET /crabserver/preprod/workflow?workflow=191105_133557:lecriste_crab_AutomaticSplitt_data_preprod_transfersFalse_clientTest_serverTest_highP HTTP/1.1" 500 Internal Server Error [data: 1911 in 746 out 183092 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "https://cmsweb-test.cern.ch/crabserver/ui/task/191105_133557%3Alecriste_crab_AutomaticSplitt_data_preprod_transfersFalse_clientTest_serverTest_highP/dbver/preprod" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" ]

```

**Comment by belforte** [comment]
indeed, see https://github.com/dmwm/CRABServer/issues/5690

**Comment by belforte** [comment]
I will look into adding back the status API but only keeping the things which fill the table for the UI. The list of jobs will not be among those if it requires parsing  the job_log.
THe best solution still looks to me what indicated in https://github.com/dmwm/CRABServer/issues/5690#issuecomment-395398495
but I am not sure that it is worth the effort.

**Comment by belforte** [comment]
after close investigation looks like the code which parse the job event log, is only used if the flag `verbose` is set to 1, while the UI calls this with `verbose=0`
So I will look into removing modes other than that.
