### ISSUE TITLE
avoid multiple submissions of same task

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6145]
see https://cms-logbook.cern.ch/elog/GlideInWMS/7441

with reference to this code
https://github.com/dmwm/CRABServer/blob/3dad9ce74fb4caf81e8a3ced8ba861a7a3460d82/src/python/TaskWorker/Actions/DagmanSubmitter.py#L514-L520
and taking note of the comment
https://github.com/dmwm/CRABServer/blob/3dad9ce74fb4caf81e8a3ced8ba861a7a3460d82/src/python/TaskWorker/Actions/DagmanSubmitter.py#L532
we should try to make the submission atomic using transactions
https://htcondor.readthedocs.io/en/latest/apis/python-bindings/tutorials/Submitting-and-Managing-Jobs.html

**Comment by belforte** [comment]
naive attempt at replacing:
```
         condorIdDict['ClusterId'] = schedd.submit(dagAd, 1, True, resultAds) 
         schedd.spool(resultAds) 
```
with:
```
         with schedd.transaction as txn:
             condorIdDict['ClusterId'] = schedd.submit(dagAd, 1, True, resultAds) 
             schedd.spool(resultAds) 
```
did not work. The spool command fails with this in SchedLog on schedd
```python
09/01/20 11:36:36 (pid:315785) condor_read(): timeout reading 21 bytes from <188.185.66.166:44531>.
09/01/20 11:36:36 (pid:315785) IO: Failed to read packet header
09/01/20 11:36:36 (pid:3157920) Scheduler::spoolJobFilesWorkerThread(void *arg, Stream* s) NAP TIME
```
where 188.185.66.166 is the IP of my test machine
`166.66.185.188.in-addr.arpa domain name pointer stefanovm.cern.ch.`
but the transaction is completed and `DagmanSubmitter` will think job has been submitted
```
Condor cluster ID just submitted is: 8411983
```
even if there's no sign of such job in the schedd.

**Comment by belforte** [comment]
I stand corrected, the code exited the inner authentication block and printed the cluster ID, but an exception was thrown as
`Failed to abort transaction.`

```
Failed to submit task to: crab3-5@vocms059.cern.ch . Task: 200901_093442:belforte_crab_20200901_113432;
'Failure when submitting task to scheduler. Error reason: 'Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> Failed to abort transaction. <traceback object at 0x7f5016a21950> 
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/DagmanSubmitter.py", line 518, in submitDirect
    condorIdDict = {}
''
Traceback (most recent call last):
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/DagmanSubmitter.py", line 273, in execute
    execInt = self.executeInternal(info, dashboardParams, inputFiles, **kwargs)
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/DagmanSubmitter.py", line 436, in executeInternal
    self.clusterId = self.submitDirect(schedd, 'dag_bootstrap_startup.sh', arg, info)
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/DagmanSubmitter.py", line 547, in submitDirect
    if results.outputMessage != "OK":
TaskWorkerException: Failure when submitting task to scheduler. Error reason: 'Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> Failed to abort transaction. <traceback object at 0x7f5016a21950> 
  File "/data/user/CRABServer/src/python/TaskWorker/Actions/DagmanSubmitter.py", line 518, in submitDirect
    condorIdDict = {}
'

```

**Comment by mmascher** [comment]
Not sure if it was a copy/paste typo, but here you are missing a set of parenthesis:

```with schedd.transaction as txn:```

should be

```with schedd.transaction() as txn:```

**Comment by belforte** [comment]
sorry, it was a typo in the git comment, code has the proper syntax.

**Comment by belforte** [comment]
After having spent a couple days on this, I could not find a way to make transactions work for our use case.
Maybe that stuff is simply too new. From the documentation and examples they appear mostly
a way to submit without having to turn a JDL file into classAd and to submit many jobs witth same clusterId.
But there is no description of how to spool files to the remove schedd, there is not spool=True/Flalse argument to check, and the resultAds returned by the call to `queue` does not have the `clusterId` so it fails when I pass it as argument to `spool()`

**Comment by belforte** [comment]
So, let's try to document the problem first.
Let's pick the first schedd in CRAB's list : vocms0106
and look for duplicates. Our DAGAMANs run as local jobs in scheduler universe, but also subdags for autoamtic splitting do, the way to tell is that the main dag submitted by CRAB has the classAd `TaskType=ROOT` while the subdags for the automatic splitting have `TaskType=PROCESSING` or `TaskType=TAIL`

So here I search for troubles:
```
belforte@vocms0106/~> condor_q -con 'jobuniverse==7&&jobstatus==2&&TaskType=="ROOT"' -af crab_workflow |sort | uniq -c|sort -n|tail
      1 200902_173435:sciaba_crab_HC-95-T2_TR_METU-92661-20200902192102
      1 200902_174016:sciaba_crab_HC-95-T2_BR_SPRACE-92661-20200902192102
      1 200902_180129:sciaba_crab_HC-95-T2_US_MIT-92661-20200902192102
      1 200902_184947:jreicher_crab_TrigEff2017v0p1_SingleMuon2017C
      1 200902_185301:jreicher_crab_TrigEff2017v0p1_dyjetstollM50_2017
      1 200902_191637:sciaba_crab_HC-96-T2_UK_SGrid_Bristol-92666-20200902211106
      1 200902_192525:sciaba_crab_HC-96-T3_UK_London_RHUL-92666-20200902211106
      1 200902_193114:sciaba_crab_HC-96-T2_UK_SGrid_RALPP-92666-20200902211106
      1 200902_204930:kawong_crab_production_0902_MadGraphChargedResonance_WGToLNu_M3500_width5_v2_2016
      3 200902_110317:slehti_crab_ChargedHiggs_HplusTB_HplusToTauNu_M_250
belforte@vocms0106/~>
```
let's look at the last one, which has 3 dag_bootstraps running
```
belforte@vocms0106/~> condor_q -con 'jobuniverse==7&&crab_reqname=="200902_110317:slehti_crab_ChargedHiggs_HplusTB_HplusToTauNu_M_250"'


-- Schedd: crab3@vocms0106.cern.ch : <188.184.80.88:4080?... @ 09/02/20 23:23:16
 ID          OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
46105059.0   cms287          9/2  13:04   0+10:17:39 R  10   0.1 dag_bootstrap_startup.sh RunJobs.dag
46105224.0   cms287          9/2  13:05   0+10:17:39 R  10   0.1 dag_bootstrap_startup.sh RunJobs.dag
46105491.0   cms287          9/2  13:06   0+10:16:48 R  10   0.1 dag_bootstrap_startup.sh RunJobs.dag

Total for query: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
Total for all users: 17754 jobs; 5308 completed, 1877 removed, 8136 idle, 2433 running, 0 held, 0 suspended
belforte@vocms0106/~>
```
All submitted one minute after the other, pretty odd but also pretty telling of "fail-retry" !

Now look at at SchedLog
```
belforte@vocms0106/~> grep 46105059 /var/log/condor/SchedLog.20200902T181414
Iwd = "/etc/condor/condor_local/spool/5059/0/cluster46105059.proc0.subproc0"
GlobalJobId = "crab3@vocms0106.cern.ch#46105059.0#1599044647"
ClusterId = 46105059
09/02/20 13:05:37 (pid:3593109) Job 46105059.0 released from hold: Data files spooled
09/02/20 13:05:37 (pid:3593109) Starting add_shadow_birthdate(46105059.0)
belforte@vocms0106/~> grep 46105224 /var/log/condor/SchedLog.20200902T181414
Iwd = "/etc/condor/condor_local/spool/5224/0/cluster46105224.proc0.subproc0"
GlobalJobId = "crab3@vocms0106.cern.ch#46105224.0#1599044701"
ClusterId = 46105224
09/02/20 13:05:37 (pid:3593109) Job 46105224.0 released from hold: Data files spooled
09/02/20 13:05:37 (pid:3593109) Starting add_shadow_birthdate(46105224.0)
belforte@vocms0106/~> grep 46105491 /var/log/condor/SchedLog.20200902T181414
Iwd = "/etc/condor/condor_local/spool/5491/0/cluster46105491.proc0.subproc0"
GlobalJobId = "crab3@vocms0106.cern.ch#46105491.0#1599044784"
ClusterId = 46105491
09/02/20 13:06:28 (pid:3593109) Job 46105491.0 released from hold: Data files spooled
09/02/20 13:06:28 (pid:3593109) Starting add_shadow_birthdate(46105491.0)
belforte@vocms0106/~> 
```
all good, let's remember that when doing remote submission to the schedd the CRAB TaskWorker does
https://github.com/dmwm/CRABServer/blob/3dad9ce74fb4caf81e8a3ced8ba861a7a3460d82/src/python/TaskWorker/Actions/DagmanSubmitter.py#L517-L518
so the `submit` makes the schedd generate a clusterId and place the jobs in hold, after the spool the hold is released. And there they are, running since 10h.

Why did CRAB TaskWorker submit the same thing 3 times ?
Look at log on that side
```
belforte@crab-prod-tw01/logs> grep 46105059 twlog.txt
2020-09-02 13:04:30,853:DEBUG:DagmanSubmitter,534:Condor cluster ID just submitted is: 46105059
'Failure when submitting task to scheduler. Error reason: 'Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> DCSchedd::spoolJobFiles:7002:File transfer failed for target job 46105059.0: TOOL at 137.138.53.39 failed to send file(s) to <188.184.80.88:4080> <traceback object at 0x7fbe5ac21bd8> 
TaskWorkerException: Failure when submitting task to scheduler. Error reason: 'Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> DCSchedd::spoolJobFiles:7002:File transfer failed for target job 46105059.0: TOOL at 137.138.53.39 failed to send file(s) to <188.184.80.88:4080> <traceback object at 0x7fbe5ac21bd8> 
belforte@crab-prod-tw01/logs> 

belforte@crab-prod-tw01/logs> grep 46105224 twlog.txt
2020-09-02 13:05:24,174:DEBUG:DagmanSubmitter,534:Condor cluster ID just submitted is: 46105224
'Failure when submitting task to scheduler. Error reason: 'Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> DCSchedd::spoolJobFiles:7002:File transfer failed for target job 46105224.0: TOOL at 137.138.53.39 failed to send file(s) to <188.184.80.88:4080> <traceback object at 0x7fbe56e18d40> 
TaskWorkerException: Failure when submitting task to scheduler. Error reason: 'Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> DCSchedd::spoolJobFiles:7002:File transfer failed for target job 46105224.0: TOOL at 137.138.53.39 failed to send file(s) to <188.184.80.88:4080> <traceback object at 0x7fbe56e18d40> 
belforte@crab-prod-tw01/logs> 

belforte@crab-prod-tw01/logs> grep 46105491 twlog.txt
2020-09-02 13:06:27,459:DEBUG:DagmanSubmitter,534:Condor cluster ID just submitted is: 46105491
2020-09-02 13:06:27,462:DEBUG:DagmanSubmitter,445:Pushing information centrally {'status': 'SUBMITTED', 'clusterid': 46105491, 'subresource': 'success', 'workflow': u'200902_110317:slehti_crab_ChargedHiggs_HplusTB_HplusToTauNu_M_250'}
Last successful submission: ClusterId 46105491 submitted to schedd crab3@vocms0106.cern.ch
belforte@crab-prod-tw01/logs> 
```

very clear, and very bad. For two times crab got a `DCSchedd::spoolJobFiles:7002:File transfer failed` and rightfully tried again, until all was good.

But if File transfer failed, why did schedd release the hold ? And if files were not transferred, why did the job start to run ?

I can only conlude that there is some bug in HTCondor so that the `schedd.spool()` works, but an error is reported.

Ah... condor versions:

the submitter (TaskWorker) uses condor python bindings from 8.8.3, the schedds runs 8.8.8


```

**Comment by belforte** [comment]
For the record, here's a mail I just sent to condor developers
```
Subject: Re: Next meeting between the HTCondor Developers and CMS, today July 15th 2020
Date: Thu, 3 Sep 2020 00:21:47 +0200
From: Stefano Belforte <stefano.belforte@cern.ch>
To: Jaime Frey <jfrey@cs.wisc.edu>, Saqib Haleem <saqib.haleem@ncp.edu.pk>
CC: stefano.belforte@cern.ch, Antonio Perez-Calero Yzquierdo <aperez@pic.es>,.... ,many others

Dear Jaime, other HTCondor developers and experts.
I am afraid that I need to hijack this mailing list again to report
what looks like an HTCondor bug.

Short description: we have found cases of duplicated CRAB submissions,
and have tracked it to the python binding used to submit reporting error
(so CRAB retries) but the jobs was nevertheless submitted.

I have put a full example in https://github.com/dmwm/CRABServer/issues/6145#issuecomment-686046818
please have a look and let me know if there's more info that you'd like to have.
In that I looked in one specific CRAB schedd (we run 15), but the issue is
widespread.

Some preliminary notes were posted to elog
https://cms-logbook.cern.ch/elog/GlideInWMS/7440
https://cms-logbook.cern.ch/elog/GlideInWMS/7441
https://cms-logbook.cern.ch/elog/GlideInWMS/7442

While we have no proof, I suspect that this is something that did not
happen "before" or we could have spotted it accidentally already while looking
for jobs matching to crab task name which is a rather common operation.
Indeed also this time it was spotted accidentally.

I know that you can say: hey CRAB, since schedd.submit(O) returned a clusterId,
before you submit again, can't you do send a condor_rm to be on the safe side ?
And I can only say, yes, we should.. but it was Brian's code ... I am damn scared
to touch it, and jokes aside... why can't you report the correct thing to begin with ?
And by the way, how can I be sure that the remove worked, if I can't trust what
the binding reports ?
But jolkes aside, I am not here to kick blame around, so, YES,
while you investigate from your point of view, I am looking into adding
that condor_rm anyhow.

Additional note: Marco Mascheroni kindly helped me to investigate this and
suggested that maybe we could use condor transaction to make the submit+spoool
some sort of atomic operation. I looked at existing documentation and tried
to pursue this (highly unconvenient because I need to create an htcondor.submit()
object from a classAd obejct dealing with quote/unquote/longs and..) anyhow I made
that part work but could not find a way to spool the files, nor find an example of
how to do, the Ads object returned by schedd.queue() does not have the clusterId
and is reject by schedd.spool(), and anyhow schedd.queue() does not have a flag
to activate spool like condor_submit -spool or schedd.submit(), or at least I
did not find it. So after a couple days of trying I gave up on that. BUT.. if that
was simply be being thick, and there is a way to use transactions here, and it will
help, I will *VERY* much appreciate an example !!!

Thanks so much for your help !

Stefano
```

**Comment by belforte** [comment]
Now I will look into explicitely removing the clusterId returned by `schedd.submit`, if any, before trying again.

**Comment by belforte** [comment]
should it ever be useful, the modified `DagmanSubmitter` where I reformatted the `dagAd` as an `htcondor.submit` object in order to use `schedd.queue()` is in my branch
https://github.com/belforte/CRABServer/tree/useTransactions-fix6145
a permalink is:
https://github.com/belforte/CRABServer/blob/738e77c3608bb41a4c11bd30b56c68cebf185357/src/python/TaskWorker/Actions/DagmanSubmitter.py#L492-L564

**NOTE** that is only a preliminary hack to make it possible to use transaction and see if submission works, it could not work as is. More modifications would be needed

**Comment by belforte** [comment]
the commit above has been tested on my VM in case both of timeout (nothing at all returned by condor) or of a messages other thab 'OK' returned by the subprocess. All possibly submitted jobs (dagman_bootstratp, task_process, grid jobs if dagmab was quick enough) are removed.
