### ISSUE TITLE
enable USE_NEW_PUBLISHER flag

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6177]
see https://github.com/dmwm/CRABServer/issues/6139#issuecomment-682420363
- [x] when a task will start on a schedd where that file exist, DAG bootstrap script will create a local file in the spool directory 'USE_NEW_PUBLISHER' marking that task. The PostJob, task_process, task_trasnfer etc., will check for this file to take appropriate decisions
 - [x] modify PostJob so that if `USE_NEW_PUBLIS` is present it sets `asoworker = "schedd"` (or whatever name we like better) in all output file metadata records, including those that require no transfers (now the field is not set for those). Therefore tasks marked for `USE_NEW_PUBLISHER` will never have `asoworker=NULL` in Oracle
- [x] modify relevant scripts in `crabserver/scripts/task_process` so that when transfer is done via FTS or Rucio, for tasks which `USE_NEW_PUBLISHER`, they do not overwrite asoworker field with 'asoless'
- [x] allow to switch on new publisher via a classAd with `config.Debug.extraJDL = ['+CRAB_USE_NEW_PUBLISHER=True']`

**Comment by belforte** [comment]
the schedd configuration flag is the file `/etc/use_new_publisher`

**Comment by belforte** [comment]
Damn... `asoworker` is also used to tell FTS from Rucio
https://github.com/dmwm/CRABServer/blob/43f6377447922d46353072e86d960e3c78967a17/src/python/TransferInterface/RegisterFiles.py#L246-L257
https://github.com/dmwm/CRABServer/blob/43f6377447922d46353072e86d960e3c78967a17/src/python/TransferInterface/__init__.py#L44-L53

@dciangot what do we do ?

**Comment by belforte** [comment]
idea... turn Rucio testers into new publisher tester as well:

```python
if asoworker == 'rucio' or asoworker == 'schedd':
    use_new_publisher = True
```
btw IIUC (and maybe I don't... @dciangot help me)  once this is set to 'rucio' the old publisher will skip them anyhow.

**Comment by belforte** [comment]
assuming the above is correct, I go ahead with code changes as planned in initial comment

**Comment by belforte** [comment]
I think that initial implementation will simply skip file transferred with Rucio, since that is actually a change in Publisher to have more than one string in the configuration.

**Comment by belforte** [comment]
initial attempt to do this in my branch https://github.com/belforte/CRABServer/tree/allow-USE_NEW_PUBLISHER-fix6177
to be tested

**Comment by belforte** [comment]
I tried to set `aso_worker` to `schedd` when first inserting a record in filetransferdb
https://github.com/dmwm/CRABServer/blob/43f6377447922d46353072e86d960e3c78967a17/src/python/TaskWorker/Actions/PostJob.py#L820
But REST rejects it with
```
[25/Sep/2020:23:48:11]  SERVER REST ERROR WMCore.REST.Error.InvalidParameter 3c2ebb67b3cbc4ec920194125c9844f0 (Invalid input parameter)
[25/Sep/2020:23:48:11]    Traceback (most recent call last):
[25/Sep/2020:23:48:11]      File "/data/srv/HG2005d-comp3/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.2005.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 723, in default
[25/Sep/2020:23:48:11]        return self._call(RESTArgs(list(args), kwargs))
[25/Sep/2020:23:48:11]      File "/data/srv/HG2005d-comp3/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.2005.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 801, in _call
[25/Sep/2020:23:48:11]        validate_no_more_input(param)
[25/Sep/2020:23:48:11]      File "/data/srv/HG2005d-comp3/sw.belforte/slc7_amd64_gcc630/cms/crabserver/3.3.2005.rc1-comp/lib/python2.7/site-packages/WMCore/REST/Validation.py", line 272, in validate_no_more_input
[25/Sep/2020:23:48:11]        raise InvalidParameter("Excess keyword arguments, not validated kwargs='%s'" % param.kwargs)
[25/Sep/2020:23:48:11]    InvalidParameter: InvalidParameter 3c2ebb67b3cbc4ec920194125c9844f0 [HTTP 400, APP 302, MSG 'Invalid input parameter', INFO "Excess keyword arguments, not validated kwargs='{'aso_worker': u'schedd'}'", ERR None]
```

**Comment by belforte** [comment]
OK. correct param name to use in REST is `asoworker`, not `aso_worker`
https://github.com/dmwm/CRABServer/blob/43f6377447922d46353072e86d960e3c78967a17/src/python/CRABInterface/RESTFileUserTransfers.py#L52

**Comment by belforte** [comment]
now PJ runs. But asoworker is not set in filetransferdb....

**Comment by belforte** [comment]
All good. Data is published.
