### ISSUE TITLE
when lfn2pfn via Rucio fails, log what was being done

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6238]
currently get things like [1]  . Both in crab status and in tw log. But should write explicitely
that lfn2pfn failed ands report for which site and lfn.

[1]
```
belforte@lxplus750/algomez> crab status -d crab_ST_tW_antitop_nanoAODPostProcessor_2017_v03p20/
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/algomez/crab_ST_tW_antitop_nanoAODPostProcessor_2017_v03p20
Task name:			201105_161453:algomez_crab_ST_tW_antitop_nanoAODPostProcessor_2017_v03p20
Grid scheduler - Task Worker:	N/A yet - crab-prod-tw01
Status on the CRAB server:	SUBMITFAILED
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/201105_161453%3Aalgomez_crab_ST_tW_antitop_nanoAODPostProcessor_2017_v03p20
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=algomez&var-task=201105_161453%3Aalgomez_crab_ST_tW_antitop_nanoAODPostProcessor_2017_v03p20&from=1604589293000&to=now
In case of issues with the dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
Failure message from server:	Problem handling 201105_161453:algomez_crab_ST_tW_antitop_nanoAODPostProcessor_2017_v03p20 because of An unknown exception occurred.
				Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97')) failure, traceback follows
				Traceback (most recent call last):
				  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
				    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
				  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/TaskWorker/Actions/StageoutCheck.py", line 128, in execute
				    pfn = self.getPFN(self.task['tm_output_lfn'], filename, self.task['tm_asyncdest'])
				  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/TaskWorker/Actions/StageoutCheck.py", line 54, in getPFN
				    pfnDict = rucioClient.getPFN(sitename, lfn)
				  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/WMCore/Services/Rucio/Rucio.py", line 286, in getPFN
				    didDict = self.cli.lfns2pfns(site, dids, scheme=protocol)
				  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/external/py2-rucio-clients/1.23.6/lib/python2.7/site-packages/rucio/client/rseclient.py", line 325, in lfns2pfns
				    raise exc_cls(exc_msg)
				RucioException: An unknown exception occurred.
				Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
				
```

**Comment by belforte** [comment]
from Eric Vaandering
```
 believe this is because writing is disabled on T3_CH_PSI. We can enable it. 

In theory, CRAB should use the correct operation when making these queries:

>>> client.lfns2pfns("T3_CH_PSI", ["cms:/store/afile"], operation='read')
{u'cms:/store/afile': u'srm://t3se01.psi.ch:8443/srm/managerv2?SFN=/pnfs/psi.ch/cms/trivcat/store/afile'}
>>> client.lfns2pfns("T3_CH_PSI", ["cms:/store/afile"], operation='write')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/current/lib/python2.7/site-packages/rucio/client/rseclient.py", line 324, in lfns2pfns
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
```
further input from Eric
```
 Can you do write and fall back to read?
```

That is all fine, and doable, but will require changes in `WMCore/Services/Rucio`
https://github.com/dmwm/WMCore/blob/51e3e2f6975b92abbbd9bf7291cf7e8d8eabd2e3/src/python/WMCore/Services/Rucio/Rucio.py#L285

So can't do with just a TW fix. Will take a bit of time and I better create an ad hoc issue

**Comment by belforte** [comment]
see also #6243
