### ISSUE TITLE
latest TW fails to discover datasets in phys03

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6239]
with v3.201104 tasks fail during data discovery with:
```
Error reason: listFileBlockLocation() got an unexpected keyword argument 'dbsOnly'
```
at line
https://github.com/dmwm/CRABServer/blob/926716992bdf777805e128a6a088585d937c8867/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L275

full log snippet:
```
2020-11-05 17:23:28,524:INFO:DBSDataDiscovery:Data discovery with DBS
2020-11-05 17:23:28,524:INFO:DBSDataDiscovery:will connect to DBS at URL: https://cmsweb-k8s-prod.cern.ch/dbs/prod/phys03/DBSReader
2020-11-05 17:23:28,711:DEBUG:DBSDataDiscovery:Data discovery through <WMCore.Services.DBS.DBS3Reader.DBS3Reader object at 0x7f16b5b66f10> for 201105_162316:cprieels_crab_DMscalar_Dilepton_top_tWChan_Mchi1_Mphi250_RunIISummer16_MINIAOD_PrivateFullProd_Sep2020_v2
2020-11-05 17:23:28,809:INFO:DBSDataDiscovery:Will not use Rucio for this dataset
2020-11-05 17:23:28,809:INFO:DBSDataDiscovery:No locations found with Rucio for /CRAB_PrivateMC/cprieels-DMscalar_Dilepton_top_tWChan_Mchi1_Mphi250_RunIISummer16_AODSIM_PrivateFullProd_Sep2020-f7b11725a86c799f51ca60747917325e/USER
2020-11-05 17:23:28,809:INFO:DBSDataDiscovery:USEDR dataset. Looking up data locations using origin site in DBS
2020-11-05 17:23:28,810:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 168, in execute
    result = self.executeInternal(*args, **kwargs)
  File "/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/cms/crabtaskworker/v3.201105/lib/python2.7/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 280, in executeInternal
    " and contact the experts if the error persists.\nError reason: %s" % str(ex)
TaskWorkerException: The CRAB3 server backend could not get the location of the files from rucio nor from dbs.
This is could be a temporary rucio/dbs glitch, please try to submit a new task (resubmit will not work) and contact the experts if the error persists.
Error reason: listFileBlockLocation() got an unexpected keyword argument 'dbsOnly'

2020-11-05 17:23:28,964:INFO:Worker:Uploading failure message to the REST:

```

I suspect that `dbsOnly` arg was removed in new DBS3Reader, but my testing was using older WMCore

this is connected to #6217

**Comment by belforte** [comment]
closed via #6241
