### ISSUE TITLE
WMArchiveUploader service crash while loading empty json file

### ISSUE THREAD

**Issue by sharmaprajesh** [dmwm/CRABServer#6240]
we have WMArchiveUploader service in all CRAB schedds which is  based on python script[1] and upload JSON docs ( task info) to the CMSWEB[2]. 

We observed that it crashed while having empty JSON file in upload directory[3], with error message in log file[4].

[1]
https://gitlab.cern.ch/CMSSI/SubmissionInfrastructureScripts/-/blob/master/WMArchiveUploader.py
path within VM: /data/srv/SubmissionInfrastructureScripts/WMArchiveUploader.py
[2]
https://cmsweb.cern.ch:8443/wmarchive/data/
[3]
JSON doc path in VM: /data/srv/WMArchiveWD/new

[4]
log file path: /data/srv/WMArchiveWD/wmarchiveprocess.log
Error Message:

2020-10-31 10:05:21,911:ERROR:WMArchiveUploader,106:Unhandled exception. Exiting.                                                                                                       
Traceback (most recent call last):                                                                                                                                                      
  File "/data/srv/SubmissionInfrastructureScripts//WMArchiveUploader.py", line 103, in start                                                                                            
	self.run()                                                                                                                                                                          
  File "/data/srv/SubmissionInfrastructureScripts//WMArchiveUploader.py", line 249, in run                                                                                              
	tmpdoc = json.load(fd)                                                                                                                                                              
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load                                                                                                                       
	**kw)                                                                                                                                                                               
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads                                                                                                                      
	return _default_decoder.decode(s)                                                                                                                                                     File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode                                                                                                                      
	obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                   
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode                                                                                                                  
	raise ValueError("No JSON object could be decoded")                                                                                                                                 
ValueError: No JSON object could be decoded

**Comment by belforte** [comment]
looks like some try/except is needed around
https://github.com/dmwm/CRABServer/blob/ef2b9e5f50326d330064433a4ee2c40d6c46f194/src/python/WMArchiveUploader.py#L254-L264

probably good to review a bit and check if there's any other place where things may easily fail and
make sure that bad files are skipped, network errors are retried etc.


@sharmaprajesh now that we moved this script source code into CRABServer's GIT repository, it is likely a good idea to put it in the schedd machines in a place different from SubmissionInfrastructureScripts , can you take care ?
