### ISSUE TITLE
odd error in stageoutcheck

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6243]
Need to find out what this is and make sure a better message is printed.
it is from this task
https://cmsweb.cern.ch/crabserver/ui/task/201106_055051%3Asoohwan_crab_Run2_HIMinBias2_L1_327237_skim
where stageout site is  T2_CH_CERNBOX

I am not surprised that it does not work in Rucio world... but clearly we need a better message

```
2020-11-06 06:51:08,271:ERROR:Handler:Problem handling 201106_055051:soohwan_crab_Run2_HIMinBias2_L1_327237_skim because of coercing to Unicode: need string or buffer, bool found failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.201026/slc7_amd64_gcc630/cms/crabtaskworker/v3.201026/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/v3.201026/slc7_amd64_gcc630/cms/crabtaskworker/v3.201026/lib/python2.7/site-packages/TaskWorker/Actions/StageoutCheck.py", line 98, in execute
    cpCmd += append + os.path.abspath(filename) + " " + pfn
TypeError: coercing to Unicode: need string or buffer, bool found

```

**Comment by belforte** [comment]
as expected CERNBOX is missing in the Rucio compliations of TFC's
and new crab client prints the correct message:
```
belforte@lxplus750/TC3> crab-dev checkwrite --site T2_CH_CERNBOX
Will check write permission in the default location /store/user/<username>
Validating LFN /store/user/belforte...
LFN /store/user/belforte is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/belforte on site T2_CH_CERNBOX
PFN lookup failed
  Stdout:
    Failed to resolve LNF to PFN via Rucio. Error is:
     RSE does not exist.
    Details: RSE 'T2_CH_CERNBOX' cannot be found in vo 'def'
    
belforte@lxplus750/TC3> 
```

**Comment by belforte** [comment]
I was totally wrong here. That error comes from earlier non-Rucio enabled version of TW v3.201026
I have no idea why it failed, maybe something went wrong in PhEDEx or CMSWEB. Anyhow since that code is gone in new version, no point in looking.
Still is true that T2_CH_CERNBOX is missing in Rucio atm. But that gives a clean and clear exception.
