### ISSUE TITLE
Cant run CRAB with private secondary dataset since Rucio migration

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6267]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5856/1/1/1.html
i.e.
```
Dear experts,

I'm trying to run a CRAB job whose primary and secondary datasets inputs are user-published datasets (i.e. outputs of previous CRAB jobs with config.Data.publication = True) and since the Rucio migration, I have not been able to get this to work even though I specify config.Data.inputDBS = 'phys03'. The input datasets are the ff:

PRIMARYDATASET = '/DoubleEG/mandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97/USER'

SECONDARYDATASET = '/DoubleEG/mandrews-Run2017B_17Nov2017-v1_AOD_slim-ext_v2-3bfee02a0afb4bfd03fd5261a90623cd/USER'

both of which are stored on on T3_US_FNALLPC as can be verified in DAS [1,2]. When I submit the job, I get status SUBMITFAILED with the following error:

Failure message from server: No locations found with Rucio for secondaryDataset.

The full task URL can be found in [3]. Notably, before the Rucio migration, I had no problem running on the exact same datasets, but since the Rucio migration, this no longer seems to be the case. Perhaps the inputDBS is not being set correctly for the secondaryDataset under Rucio? The issue does not seem to be FNALLPC-specific: trying the user-published datasets stored on another site (T3_US_CMU) gives the same error. I have tried the suggestion from a previous post (whitelist+ignoreLocality)[4] but this doesn't help either.

Thanks, Michael

[1] https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=site+dataset%3D%2FDoubleEG%2Fmandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97%2FUSER

[2] https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=site+dataset%3D%2FDoubleEG%2Fmandrews-Run2017B_17Nov2017-v1_AOD_slim-ext_v2-3bfee02a0afb4bfd03fd5261a90623cd%2FUSER

[3] https://cmsweb.cern.ch/crabserver/ui/task/201116_160136:mandrews_crab_data2017-Run2017B_TESTv4-copypick

[4] https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5855/1/1/1/1.html 
```

**Comment by belforte** [comment]
@michael.andrews@cern.ch can you send me the CRAB config file so I can reproduce it ? I think I know what it is but it is easier with an example. Unfortuantly the config. is not availble via the HELP URL since submission failed.

**Comment by mbandrews** [comment]
@belforte attached is a sample crab cfg illustrating the issue.
[crabConfig_copypick_TEST.py.zip](https://github.com/dmwm/CRABServer/files/5583528/crabConfig_copypick_TEST.py.zip)

**Comment by belforte** [comment]
expanded config for my convenience, shortened and adapted to my setup

```python
import os
from CRABClient.UserUtilities import config
config = config()

DATASET = '/DoubleEG/mandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97/USER'
SECONDARYDATASET = '/DoubleEG/mandrews-Run2017B_17Nov2017-v1_AOD_slim-ext_v2-3bfee02a0afb4bfd03fd5261a90623cd/USER'

config.General.transferOutputs = True
config.General.transferLogs = False

config.JobType.pluginName = 'Analysis'
config.JobType.psetName = 'demoanalyzer.py'

config.Data.splitting = 'LumiBased'
config.Data.unitsPerJob = 50

config.Data.inputDataset = DATASET
config.Data.secondaryInputDataset = SECONDARYDATASET
config.Data.inputDBS = 'phys03'

config.Data.publication = False

config.Site.storageSite = 'T2_CH_CERN'
```

**Comment by belforte** [comment]
can of course reproduce during standalone DBSDataDiscovery test
```
python src/python/TaskWorker/Actions/DBSDataDiscovery.py prod/phys03 /DoubleEG/mandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97/USER  /DoubleEG/mandrews-Run2017B_17Nov2017-v1_AOD_slim-ext_v2-3bfee02a0afb4bfd03fd5261a90623cd/USER
```
which returns
```
INFO:-1:Data discovery with DBS
INFO:-1:will connect to DBS at URL: https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader/
DEBUG:-1:Data discovery through <WMCore.Services.DBS.DBS3Reader.DBS3Reader object at 0x7f1e6a5a0ed0> for pippo1
INFO:-1:Will not use Rucio for this dataset
INFO:-1:No locations found with Rucio for /DoubleEG/mandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97/USER
INFO:-1:USEDR dataset. Looking up data locations using origin site in DBS
INFO:-1:Trying data location of secondary blocks with Rucio
WARNING:-1:Rucio lookup failed with. 'DBSDataDiscovery' object has no attribute 'rucioClient'
Traceback (most recent call last):
  File "src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 429, in <module>
    'tm_dbs_url': DBSUrl}, tempDir='')
  File "src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 168, in execute
    result = self.executeInternal(*args, **kwargs)
  File "src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 308, in executeInternal
    raise TaskWorkerException(msg)
TaskWorker.WorkerExceptions.TaskWorkerException: No locations found with Rucio for secondaryDataset.
belforte@stefanovm/CRABServer> 

```

**Comment by belforte** [comment]
I will do a quick fix now, but it will be better to refactor DBSDataDiscovery so that:
   1. do not duplicate code but use a function to create blockLocationsMap for both primary and secondary
   1. make it very clear when to use Rucio and when DBS, current code assumed that if dataset in in phys03 it is not in Rucio, but those could be production datasets migrated from global, better to rely on `USER` tier or actually both

**Note that current implementation (and documentation) requires that primary and secondary datasets are in same DBS instance** https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile

**Comment by belforte** [comment]
tested on stefanovm with the datasets in the user config. and with datasets in global:
```
belforte@stefanovm/CRABServer> python src/python/TaskWorker/Actions/DBSDataDiscovery.py prod/phys03 /DoubleEG/mandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97/USER  /DoubleEG/mandrews-Run2017B_17Nov2017-v1_AOD_slim-ext_v2-3bfee02a0afb4bfd03fd5261a90623cd/USER
/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/external/py2-cryptography/2.4.2-comp3/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
INFO:-1:Data discovery with DBS
INFO:-1:will connect to DBS at URL: https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader/
DEBUG:-1:Data discovery through <WMCore.Services.DBS.DBS3Reader.DBS3Reader object at 0x7f5daf63eed0> for pippo1
INFO:-1:Will not use Rucio for this dataset
INFO:-1:No locations found with Rucio for /DoubleEG/mandrews-Run2017B_Era2017_23Feb2020_MINIAOD-skimv1-84d4062339350c0b82cf1392552beb97/USER
INFO:-1:USER dataset. Looking up data locations using origin site in DBS
INFO:-1:Secondary dataset is USER. Looking up data locations using origin site in DBS
INFO:-1:Beginning to match files from secondary dataset
INFO:-1:Done matching files from secondary dataset
DEBUG:-1: Formatting data discovery output 
DEBUG:-1:Tot events found: 544407
DEBUG:-1:Tot lumis found: 24149
DEBUG:-1:Duplicate lumis found: 0
DEBUG:-1:Tot files found: 31
DEBUG:-1:Starting to create compact lumilists for input dataset
DEBUG:-1:Finished to create compact lumilists for input dataset
DEBUG:-1:Got 31 files
belforte@stefanovm/CRABServer> 
```

and

```
belforte@stefanovm/CRABServer> python src/python/TaskWorker/Actions/DBSDataDiscovery.py prod/global /DoubleMuon/Run2018B-02Apr2020-v1/NANOAOD /DoubleMuon/Run2018B-17Sep2018-v1/MINIAOD 2>&1|grep -v urllib3
/data/srv/TaskManager/v3.201105/slc7_amd64_gcc630/external/py2-cryptography/2.4.2-comp3/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
INFO:-1:Data discovery with DBS
INFO:-1:will connect to DBS at URL: https://cmsweb.cern.ch/dbs/prod/global/DBSReader/
DEBUG:-1:Data discovery through <WMCore.Services.DBS.DBS3Reader.DBS3Reader object at 0x7f31ab259ed0> for pippo1
INFO:-1:Initializing Rucio client
DEBUG:rucio.client.baseclient:No VO passed. Trying to get it from environment variable RUCIO_VO.
DEBUG:rucio.client.baseclient:No VO found. Trying to get it from the config file.
DEBUG:rucio.client.baseclient:No VO found. Using default VO.
DEBUG:rucio.client.baseclient:got token from file
DEBUG:dogpile.lock:NeedRegenerationException
DEBUG:dogpile.lock:no value, waiting for create lock
DEBUG:dogpile.lock:value creation lock <dogpile.cache.region._LockWrapper object at 0x7f31a79d3f50> acquired
DEBUG:dogpile.lock:Calling creation function for not-yet-present value
DEBUG:dogpile.lock:Released creation lock
INFO:-1:Looking up data location with Rucio in cms scope.
INFO:-1:Trying data location of secondary dataset blocks with Rucio
INFO:-1:Beginning to match files from secondary dataset
INFO:-1:Done matching files from secondary dataset
DEBUG:-1: Formatting data discovery output 
DEBUG:-1:Tot events found: 35057758
DEBUG:-1:Tot lumis found: 29913
DEBUG:-1:Duplicate lumis found: 0
DEBUG:-1:Tot files found: 24
DEBUG:-1:Starting to create compact lumilists for input dataset
DEBUG:-1:Finished to create compact lumilists for input dataset
DEBUG:-1:Got 24 files
belforte@stefanovm/CRABServer> 

```

**Comment by mbandrews** [comment]
Many thanks, @belforte. When do fixes like these typically get propagated to production?

**Comment by belforte** [comment]
@mbandrews since this is reasonably safe, urgent, and we have nothing else to push in production right now, we can do it quickly. I have installed in preprod, please give it a try via adding in your crab configuration
```
config.General.instance = 'preprod'
```
Note that FNAL is still blacklisted due to Rucio configuration issues, you'll have to add also:
```
config.Data.ignoreLocality = True
config.Site.whitelist = ['T2_US_*']
```
and let us know.

**Comment by mbandrews** [comment]
Thanks a lot for the fix, I no longer get the SUBMITFAILED error. However, I'm still having trouble accessing files stored on T3_US_CMU although this is due to a separate issue (https://ggus.eu/index.php?mode=ticket_info&ticket_id=148987).

**Comment by belforte** [comment]
thanks for confirming that it works. We'll move it to production next week.
That GGUS is a different thing, it may be worth to explain more clearly in there which troubles you exactly have.

**Comment by mbandrews** [comment]
Good to know. Yes, we have an ongoing email thread but then this issue came up and had to be addressed first. Appreciate all the help, @belforte
