### ISSUE TITLE
TaskPublish fails with TypeError:list indices must be integers, not unicode

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABServer#6294]
2020/12/14 Publisher failed for following task:

```CalledProcessError: Command 'python /data/srv/TaskManager/v3.201125/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/lib/python2.7/site-packages/Publisher/TaskPublish.pyc  --configFile=/data/srv/Publisher/PublisherConfig.py --taskname=201214_160611:slaurila_crab_TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8-v1' returned non-zero exit status 1```

with below error:

```
[crab3@crab-prod-tw02 Publisher]$ cat nohup.out
Traceback (most recent call last):
  File "/build/cmsbld/jenkins/workspace/CRABServer_BuildOnRelease/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/CRABServer-v3.201125/build/lib/Publisher/TaskPublish.py", line 948, in <module>
    main()
  File "/build/cmsbld/jenkins/workspace/CRABServer_BuildOnRelease/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/CRABServer-v3.201125/build/lib/Publisher/TaskPublish.py", line 944, in main
    result = publishInDBS3(config, taskname, verbose)
  File "/build/cmsbld/jenkins/workspace/CRABServer_BuildOnRelease/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/CRABServer-v3.201125/build/lib/Publisher/TaskPublish.py", line 788, in publishInDBS3
    published = [x for x in published[dataset] if x not in failed[dataset]]
TypeError: list indices must be integers, not unicode
```

**Comment by belforte** [comment]
corresponding lines in logs/log.txt.2020-12-14 

```
2020-12-14 21:01:59,861:ERROR:PublisherMaster,554:Exception when calling TaskPublish!
Command 'python /data/srv/TaskManager/v3.201125/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/lib/python2.7/site-packages/Publisher/TaskPublish.pyc  --configFile=/data/srv/Publisher/PublisherConfig.py --taskname=201214_160611:slaurila_crab_TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8-v1' returned non-zero exit status 1
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.201125/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/lib/python2.7/site-packages/Publisher/PublisherMaster.py", line 527, in startSlave
    stdout = subprocess.check_output(cmd, shell=True)
  File "/data/srv/TaskManager/v3.201125/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'python /data/srv/TaskManager/v3.201125/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/lib/python2.7/site-packages/Publisher/TaskPublish.pyc  --configFile=/data/srv/Publisher/PublisherConfig.py --taskname=201214_160611:slaurila_crab_TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8-v1' returned non-zero exit status 1

```

**Comment by belforte** [comment]
rerunning the script shows no errors:
```
[crab3@crab-prod-tw02 ste]$ python /data/srv/TaskManager/v3.201125/slc7_amd64_gcc630/cms/crabtaskworker/v3.201125/lib/python2.7/site-packages/Publisher/TaskPublish.pyc  --configFile=/data/srv/Publisher/PublisherConfig.py --taskname=201214_160611:slaurila_crab_TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8-v1
Completed with result in /data/srv/Publisher/logs/tasks/slaurila/201214_160611:slaurila_crab_TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8-v1-19.json
[crab3@crab-prod-tw02 ste]$ 

```

**Comment by belforte** [comment]
script log at time of the error is OK. simply stopped waiting for block migrations and other calls later went all OK so there is nothing to publish now
```
2020-12-14 20:57:27,021:INFO: Migration id 2980373 succeeded.
2020-12-14 20:57:27,042:INFO: Migration id 2980374 succeeded.
2020-12-14 20:57:27,060:INFO: Migration id 2980375 succeeded.
2020-12-14 20:57:27,078:INFO: Migration id 2980376 failed (retry 0), but should be retried.
2020-12-14 20:57:27,097:INFO: Migration id 2980377 succeeded.
2020-12-14 20:57:27,121:INFO: Migration id 2980378 succeeded.
2020-12-14 20:57:27,121:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 20:57:57,205:INFO: Migration id 2980376 failed (retry 0), but should be retried.
2020-12-14 20:57:57,470:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 20:58:27,558:INFO: Migration id 2980376 failed (retry 1), but should be retried.
2020-12-14 20:58:27,558:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 20:58:57,627:INFO: Migration id 2980376 failed (retry 1), but should be retried.
2020-12-14 20:58:57,807:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 20:59:27,908:INFO: Migration id 2980376 failed (retry 1), but should be retried.
2020-12-14 20:59:27,912:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 20:59:57,976:INFO: Migration id 2980376 failed (retry 1), but should be retried.
2020-12-14 20:59:58,004:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 21:00:28,094:INFO: Migration id 2980376 failed (retry 2), but should be retried.
2020-12-14 21:00:28,122:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 21:00:58,211:INFO: Migration id 2980376 failed (retry 2), but should be retried.
2020-12-14 21:00:59,061:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 21:01:29,122:INFO: Migration id 2980376 failed (retry 2), but should be retried.
2020-12-14 21:01:29,432:INFO: 1 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-14 21:01:59,506:INFO: Migration id 2980376 failed (retry 2), but should be retried.
2020-12-14 21:01:59,838:INFO: Migration of /TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM is taking too long - will delay the publication.
2020-12-14 21:01:59,838:INFO: Migration of /TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/MINIAODSIM is taking too long. Not publishing any files.
2020-12-14 21:26:51,769:INFO: Start new iteration. Get files to publish
2020-12-14 21:26:51,775:INFO: Will connect to CRAB service: other
2020-12-14 21:26:51,775:INFO: Will use restHost and dbInstance from config file
2020-12-14 21:26:51,775:INFO: Will connect to CRAB Data Base via URL: https://cmsweb-k8s-prod.cern.ch//crabserver/prod

```

**Comment by belforte** [comment]
indeed the error was a couple lines before the script terminated, at line 788 here

https://github.com/dmwm/CRABServer/blob/9f26e3a5249398bcc593e5ee2a569921fd55db6b/src/python/Publisher/TaskPublish.py#L782-L790

**Comment by belforte** [comment]
ok to keep at low priority.

**Comment by belforte** [comment]
keeps happening, so far in these tasks
```
[crab3@crab-prod-tw02 logs]$ grep -A1   "ERROR:PublisherMaster,554:Exception when calling " log.*|grep taskname|cut -d= -f3|cut -d \' -f1|sort|uniq
201117_100715:anstahll_crab_AODSkim_HIMinimumBias3_HIRun2018_04Apr2019_DiMuMassMin2_20201117
201123_202415:lata_crab_v2_p11_NMSSM_XToYHTo2b2g_MX-300_TuneCP5_13TeV-madgraph-pythia8_00
201126_152649:oiorio_crab_TprimeBToTZM-600Width-10pLHTuneCUETP8M113TeV-madgraph-pythia8
201126_152727:oiorio_crab_TprimeBToTZM-600Width-30pLHTuneCUETP8M113TeV-madgraph-pythia8
201214_160611:slaurila_crab_TT_Mtt-700to1000_TuneCP5_13TeV-powheg-pythia8-v1
201218_082539:mseidel_crab_DYJetsToMuMu_M-50_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos
201218_091932:mseidel_crab_runMassWeights_ZJToTauTau_APVpreVFP
201218_095412:mseidel_crab_runMassWeights_WminusJToTauNu_APVpreVFP
201218_095531:mseidel_crab_runMassWeights_WplusJToTauNu
201218_144616:mseidel_crab_runMassWeights_WplusJToMuNu_batch0
201221_071152:mseidel_crab_runMassWeights_WplusJToMuNu_batch1
[crab3@crab-prod-tw02 logs]$ 

```

**Comment by belforte** [comment]
OTOH, I do not see failed publication yet e.g. for the next to last above:
```
belforte@lxplus718/pub> crab status -d crab_runMassWeights_WplusJToMuNu_batch0
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/pub/crab_runMassWeights_WplusJToMuNu_batch0
Task name:			201218_144616:mseidel_crab_runMassWeights_WplusJToMuNu_batch0
Grid scheduler - Task Worker:	crab3@vocms0120.cern.ch - crab-prod-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb-k8s-prod.cern.ch/crabserver/ui/task/201218_144616%3Amseidel_crab_runMassWeights_WplusJToMuNu_batch0
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=mseidel&var-task=201218_144616%3Amseidel_crab_runMassWeights_WplusJToMuNu_batch0&from=1608299177000&to=now
In case of issues with the dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
Status on the scheduler:	SUBMITTED

Jobs status:                    failed       		  1.0% (  69/6944)
				finished     		 54.8% (3805/6944)
				idle         		 14.0% ( 969/6944)
				running      		  5.4% ( 377/6944)
				toRetry      		 24.2% (1678/6944)
				transferring 		  0.1% (  10/6944)
				unsubmitted  		  0.5% (  36/6944)

Publication status of 1 dataset(s):	acquired     		  0.3% (  22/6944)
(from CRAB internal bookkeeping in transferdb)
					done         		 54.5% (3782/6944)
					new          		  0.0% (   3/6944)
					unsubmitted  		 45.2% (3137/6944)


```

**Comment by belforte** [comment]
whatever it was, it does not appear to be happening now.
Let's close. Many things changed in Publisher.
