### ISSUE TITLE
Publication count does not match number of completed jobs

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6308]
in this example 79 jobs completed OK, but only 72+2 = 74 have been marked for publication
what happened to the other 5 ?

```
belforte@lxplus718/jihun> crab status -d crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5/
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/jihun/crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5
Task name:			201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5
Grid scheduler - Task Worker:	crab3@vocms0107.cern.ch - crab-prod-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb-k8s-prod.cern.ch/crabserver/ui/task/201216_085133%3Ajihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=jihunk&var-task=201216_085133%3Ajihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5&from=1608105093000&to=now
In case of issues with the dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
Warning:			The following sites from the user site whitelist are blacklisted by the CRAB server: [u'T3_US_UCR', u'T2_AT_Vienna', u'T3_FR_IPNL', u'T3_CN_PKU', u'T3_RU_FIAN', u'T3_TW_NTU_HEP', u'T2_FR_IPHC', u'T3_US_UMiss', u'T3_US_NotreDame', u'T2_RU_SINP', u'T2_IT_Rome', u'T3_US_SDSC', u'T3_IN_PUHEP', u'T3_US_OSG', u'T2_GR_Ioannina', u'T3_US_MIT', u'T2_CH_CERN_HLT', u'T3_US_FNALLPC', u'T3_US_Kansas', u'T3_US_Princeton_ICSE', u'T3_US_NERSC', u'T3_GR_IASA', u'T3_US_PSC', u'T3_US_Rutgers', u'T3_IT_MIB', u'T2_RU_ITEP', u'T3_US_JHU', u'T3_BY_NCPHEP', u'T3_US_TACC', u'T3_KR_UOS', u'T3_CH_PSI', u'T3_IN_TIFRCloud']. Since the CRAB server blacklist has precedence, these sites are not considered in the user whitelist.
Status on the scheduler:	FAILED

Jobs status:                    failed       		 56.1% (101/180)
				finished     		 43.9% ( 79/180)

Publication status of 1 dataset(s):	done         		 40.0% ( 72/180)
(from CRAB internal bookkeeping in transferdb)
					new          		  1.1% (  2/180)
					unsubmitted  		 58.9% (106/180)

Output dataset:			/TTbarTypeIHeavyN-Mu_4L_LO_MN60/jihunk-DRPremix_step1__CMSSW_10_2_5-96e2d90999375d8c542ea905b43803e1/USER
Output dataset DAS URL:		https://cmsweb.cern.ch/das/request?input=%2FTTbarTypeIHeavyN-Mu_4L_LO_MN60%2Fjihunk-DRPremix_step1__CMSSW_10_2_5-96e2d90999375d8c542ea905b43803e1%2FUSER&instance=prod%2Fphys03


```

**Comment by belforte** [comment]
the output dataset contains 72 files from this task dated 201216_085133 (in agreement with count from transfersdb) with names like:
```
/store/user/jihunk/TTbarTypeIHeavyN-Mu_4L_LO_MN60/DRPremix_step1__CMSSW_10_2_5/201216_085133/0000/DRPremix_step1_1.root
```

and 110 files from another task dated 201217_113326
with names like
```
/store/user/jihunk/TTbarTypeIHeavyN-Mu_4L_LO_MN60/DRPremix_step1__CMSSW_10_2_5/201217_113326/0000/DRPremix_step1_15.root
```

the files from this task reach up to ID 89 with these holes:
```
belforte@lxplus774/jihun> for i in `seq 89`; do grep -q 085133/0000/DRPremix_step1_$i.root das||echo $i; done
4
15
22
24
27
29
37
42
44
47
50
53
65
82
83
84
86
belforte@lxplus774/jihun> 
```

**Comment by belforte** [comment]
looking at crab status --long , jobid 4,15,44,53 failed with `Postprocessing failed`
jobid 22,24,27,37,50,65,84 failed with exit code 8028.
jobid 90 succeeded.
No jobs with id>90 succeeded.
There of the files not present in output dataset those from successful jobs are: 29, 42, 47, 82, 83, 86, 90

**Comment by belforte** [comment]
FILEMETADATADB for this task contains 78 files:
https://cmsweb.cern.ch/crabserver/prod/filemetadata?taskname=201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5&filetype=EDM

FILETRANSFERSDB from
https://cmsweb.cern.ch/crabserver/prod/fileusertransfers?username=jihunk&taskname=201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5&subresource=getPublicationStatus

has 180 entries (one per job, as it should), I pasted the document into a file with headers
```
{"desc": {"columns": ["tm_id", "tm_jobid", "tm_publication_state", "tm_start_time", "tm_last_update"]}, "result": [
```

so  I find the 2 jobs with PublicationStatus = 0 = NEW:
```
belforte@lxplus774/jihun> cat pub|grep ' 0,'
,["9842467be7f41e3588cfe3f0f52277a51cfb477bb27395c1982dab4b", "82", 0, 1608210046, 1608296541]
,["235b6490dbbc27b254763bffcf28aaaac773d0710876005060da4b12", "42", 0, 1608142234, 1608229586]
belforte@lxplus774/jihun> 

```
I needl to find out why the have not been acquired by Publisher. 5 (
The other problem are the other 5 successful jobs: `29, 47, 83, 86, 90` which have publication status 5 (NOT_REQUIRED) like the logs and in general all files when injected in Transfersdb before ASO is activated.
```
belforte@lxplus774/jihun> cat pub|grep '"29"'
,["798b38dd91b20c76b111ab8c7ce47bc9d5aec84f3449e43a54944d1c", "29", 5, 1608548565, 1608635066]
,["8c3fe7d3d256d584193bb5f69966aac2f385df108c55a88c04524b66", "29", 5, 1608548565, 1608635066]
belforte@lxplus774/jihun> cat pub|grep '"47"'
,["11eb0972fcd8ea6691f8758da493e1d347cee6d065ac32d4f6127d84", "47", 5, 1608518358, 1608605091]
,["61f5d8f0a76540130b8ae086bca023246fbebf5f99f44a9b09a51bd5", "47", 5, 1608518358, 1608605091]
belforte@lxplus774/jihun> cat pub|grep '"83"'
,["eafb70370f50b8e0ac7c12c41c461507d70df5b54026a12c146f7f3a", "83", 5, 1608426248, 1608512754]
,["829e34e891459e957e67096812ed7ff9a2b8c8ed7e05e604f81a6e10", "83", 5, 1608426248, 1608512754]
belforte@lxplus774/jihun> cat pub|grep '"86"'
,["4744f430f4aa1212a2e9daccbf098e4072ca31b45df911987a884674", "86", 5, 1608427531, 1608514043]
,["e112094546bbfcf30f22f1c4d0a4f7cbd493cee22857129c5fabda62", "86", 5, 1608427531, 1608514043]
belforte@lxplus774/jihun> cat pub|grep '"90"'
,["2d1f1c961274828a0a5b2ab0661615485af48d0df9e0a456a45933e5", "90", 5, 1608547470, 1608634083]
,["2d06703255a0c8255772f10ff7bc5228bf4afae0625cf561c0dbcfcd", "90", 5, 1608547470, 1608634083]
belforte@lxplus774/jihun> 
```
One thing at a time:
- [ ] 1. why two files are stuck in NEW
- [ ] 2. why 5 successful jobs did not have the publication flag set

**Comment by belforte** [comment]
1. jobs 42 and 82 have transfer status KILLED.  No successful transfer, no publication, this easy. Problem is that they should have marked as failed !

Job 42 was run 3 times, from PostJob logs:
42.0 : transfer failed with globus error
42.1 : transfer timed out and was killed
42.2 : failed in execution with 8028
So CRAB gave up retrying. 
But the record for jobId 42 in status cache https://cmsweb.cern.ch/scheddmon/0107/cms1620/201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5/status_cache
is
```
'42': {'Retries': 1, 'WallDurations': [8.0, 204.34909391403198, 5266.0, 9.0, 232.72743606567383, 4429.0], 'StartTimes': [1608109045.0, 1608136208.0], 'SubmitTimes': [1608108926.0, 1608136016.0], 'JobIds': ['61903376.0', '61924859.0'], 'EndTimes': [1608114311.0, 1608140637.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'finished', 'ResidentSetSize': [2956732, 3161824], 'TotalUserCpuTimeHistory': [8535, 6305], 'SiteHistory': ['Unknown', 'T2_CH_CERN', 'T2_CH_CERN', 'Unknown', 'T2_UK_London_IC', 'T2_UK_London_IC'], 'TotalSysCpuTimeHistory': [195, 294]},
```
Looking in task SPOOL_DIR so far I found one odd thing at the end of cache_status.log https://cmsweb.cern.ch/scheddmon/0107/cms1620/201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5/SPOOL_DIR/task_process/cache_status.log
but with no time stamps.

```
ERROR:root:error during status_cache handling
Traceback (most recent call last):
  File "task_process/cache_status.py", line 283, in storeNodesInfoInFile
    jobLogCheckpoint = int(nodesStorage.readline())
ValueError: invalid literal for int() with base 10: 'jel-1608721436.pkl\n'
ERROR:root:error during main loop
Traceback (most recent call last):
  File "task_process/cache_status.py", line 359, in main
    storeNodesInfoInFile()
  File "task_process/cache_status.py", line 298, in storeNodesInfoInFile
    jobsLog.seek(jobLogCheckpoint)
UnboundLocalError: local variable 'jobLogCheckpoint' referenced before assignment
DEBUG:root:cache_status.py exiting

```
the task wrapper job terminated normally at
```
005 (61903017.000.000) 2020-12-23 12:08:57 Job terminated.
```
and in any case `status_cache.txt` has been written to until that time
```
belforte@vocms0107/SPOOL_DIR> ls -l task_process/status_cache.txt 
-rw-r--r-- 1 cms1620 zh 459443 Dec 23 12:03 task_process/status_cache.txt
belforte@vocms0107/SPOOL_DIR> 
```
so there is no obvious reason for status_cache.txt not to be correct.

**Comment by belforte** [comment]
The problem is the DAGMAN status tracking, in the `node_state` file jobId 42 is marked as a successful node:
```[
  Type = "NodeStatus";
  Node = "Job42";
  NodeStatus = 5; /* "STATUS_DONE" */
  StatusDetails = "";
  RetryCount = 1;
  JobProcsQueued = 0;
  JobProcsHeld = 0;
]
```

From the DAGMAN log file ` RunJobs.dag.nodes.log`
```
belforte@vocms0107/SPOOL_DIR> grep -B2 Job42 RunJobs.dag.nodes.log 
...
000 (61903376.000.000) 2020-12-16 09:55:26 Job submitted from host: <137.138.62.16:4080?addrs=137.138.62.16-4080&alias=vocms0107.cern.ch&noUDP&sock=schedd_1595_9da5>
    DAG Node: Job42
--
016 (61903376.000.000) 2020-12-16 17:25:52 POST Script terminated.
	(1) Normal termination (return value 1)
    DAG Node: Job42
--
...
000 (61924859.000.000) 2020-12-16 17:26:56 Job submitted from host: <137.138.62.16:4080?addrs=137.138.62.16-4080&alias=vocms0107.cern.ch&noUDP&sock=schedd_1595_9da5>
    DAG Node: Job42
--
016 (61924859.000.000) 2020-12-16 19:14:10 POST Script terminated.
	(1) Normal termination (return value 0)
    DAG Node: Job42
belforte@vocms0107/SPOOL_DIR> 

```
so DAGMAN thought that POSTJob for second retry was successful.

**Comment by belforte** [comment]
Problem sort of solved...
Look at these links:
```
elforte@vocms0107/201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5> ls -l  postjob.42.*
lrwxrwxrwx 1 cms1620 zh 95 Dec 16 09:54 postjob.42.0.txt -> /data/srv/glidecondor/condor_local/spool/3013/0/cluster61903013.proc0.subproc0/postjob.42.0.txt
lrwxrwxrwx 1 cms1620 zh 95 Dec 16 17:11 postjob.42.1.txt -> /data/srv/glidecondor/condor_local/spool/2990/0/cluster61902990.proc0.subproc0/postjob.42.1.txt
lrwxrwxrwx 1 cms1620 zh 95 Dec 16 17:32 postjob.42.2.txt -> /data/srv/glidecondor/condor_local/spool/3013/0/cluster61903013.proc0.subproc0/postjob.42.2.txt
belforte@vocms0107/201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5> ls -l status_cache 
lrwxrwxrwx 1 cms1620 zh 108 Dec 16 09:54 status_cache -> /data/srv/glidecondor/condor_local/spool/2982/0/cluster61902982.proc0.subproc0/task_process/status_cache.txt
belforte@vocms0107/201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5> ls -l SPOOL_DIR
lrwxrwxrwx 1 cms1620 zh 78 Dec 16 09:54 SPOOL_DIR -> /data/srv/glidecondor/condor_local/spool/2982/0/cluster61902982.proc0.subproc0/
belforte@vocms0107/201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5> 


```

there are 3 clusterID for the same task !

more clearly:
```
belforte@vocms0107/~> condor_q -con 'jobuniverse==7&&crab_reqname=="201216_085133:jihunk_crab_TTbarTypeIHeavyN-Mu_4L_LO_MN60__DRPremix_step1__CMSSW_10_2_5"'


-- Schedd: crab3@vocms0107.cern.ch : <137.138.62.16:4080?... @ 12/23/20 18:57:32
 ID          OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
61902982.0   cms1620        12/16 09:52   4+11:07:41 H  10   0.1 dag_bootstrap_startup.sh RunJobs.dag
61902990.0   cms1620        12/16 09:53   5+20:40:11 H  10   0.1 dag_bootstrap_startup.sh RunJobs.dag
61903013.0   cms1620        12/16 09:54   5+18:58:45 H  10   0.1 dag_bootstrap_startup.sh RunJobs.dag

Total for query: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
Total for all users: 10857 jobs; 389 completed, 5901 removed, 4019 idle, 548 running, 0 held, 0 suspended

belforte@vocms0107/~> 

```
the same DAGMAN was submitted 3 times on the same schedd.... no suprise that things got VERY confused.

**Comment by belforte** [comment]
in the end this was simply another manifestation of
https://github.com/dmwm/CRABServer/issues/6151
