### ISSUE TITLE
crab kill fails on tasks in TAPERECALL

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6342]
TW tries to kill task on schedd as well, but of course fails (clusterid is None)
so the task ends in KILLFAILED instead of KILLED e.g.
https://cmsweb.cern.ch/crabserver/ui/task/210114_220110%3Albenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1

Here's TW log from that example:

```
2021-01-15 01:00:20,767:DEBUG:Worker:Process-1: Starting <function handleKill at 0x7fe3ec6137d0> on 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1
2021-01-15 01:00:20,937:DEBUG:Handler:Starting <TaskWorker.Actions.MyProxyLogon.MyProxyLogon object at 0x7fe3e8f16c50> on 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1
2021-01-15 01:00:20,938:INFO:MyProxyLogon:try first to retrieve credential with login name lbenato_CRAB
2021-01-15 01:00:22,133:DEBUG:MyProxyLogon:Valid proxy for /C=DE/O=GermanGrid/OU=uni-hamburg/CN=Lisa Benato now in /data/certs/creds/8abc834faaea5f63392d34f62ae4934b150957a7
2021-01-15 01:00:22,329:INFO:Handler:Finished <TaskWorker.Actions.MyProxyLogon.MyProxyLogon object at 0x7fe3e8f16c50> on 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1 in 1 seconds
2021-01-15 01:00:22,329:DEBUG:Handler:Starting <TaskWorker.Actions.DagmanKiller.DagmanKiller object at 0x7fe3ea60bc50> on 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1
2021-01-15 01:00:22,330:INFO:DagmanKiller:About to kill workflow: 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1.
2021-01-15 01:00:22,333:ERROR:DagmanKiller:210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1: The CRAB server backend was not able to contact the Grid scheduler. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. Message from the scheduler: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.210112/slc7_amd64_gcc630/cms/crabtaskworker/v3.210112/lib/python2.7/site-packages/TaskWorker/Actions/DagmanKiller.py", line 60, in executeInternal
    self.schedd, address = loc.getScheddObjNew(self.task['tm_schedd'])
  File "/data/srv/TaskManager/v3.210112/slc7_amd64_gcc630/cms/crabtaskworker/v3.210112/lib/python2.7/site-packages/HTCondorLocator.py", line 186, in getScheddObjNew
    schedds = coll.query(htcondor.AdTypes.Schedd, 'Name=?=%s' % HTCondorUtils.quote(schedd.encode('ascii', 'ignore')),
AttributeError: 'NoneType' object has no attribute 'encode'
2021-01-15 01:00:22,334:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.210112/slc7_amd64_gcc630/cms/crabtaskworker/v3.210112/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 78, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/v3.210112/slc7_amd64_gcc630/cms/crabtaskworker/v3.210112/lib/python2.7/site-packages/TaskWorker/Actions/DagmanKiller.py", line 136, in execute
    self.executeInternal(apmon, *args, **kwargs)
  File "/data/srv/TaskManager/v3.210112/slc7_amd64_gcc630/cms/crabtaskworker/v3.210112/lib/python2.7/site-packages/TaskWorker/Actions/DagmanKiller.py", line 67, in executeInternal
    raise TaskWorkerException(msg)
TaskWorkerException: The CRAB server backend was not able to contact the Grid scheduler. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. Message from the scheduler: 'NoneType' object has no attribute 'encode'

2021-01-15 01:00:22,540:INFO:Worker:Uploading failure message to the REST:
The CRAB server backend was not able to contact the Grid scheduler. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. Message from the scheduler: 'NoneType' object has no attribute 'encode'
2021-01-15 01:00:22,679:INFO:Worker:Failure message successfully uploaded to the REST
2021-01-15 01:00:22,680:DEBUG:Worker:Process-1: KILL work on 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1 completed in 1 seconds: Status: ERROR
Error = The CRAB server backend was not able to contact the Grid scheduler. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. Message from the scheduler: 'NoneType' object has no attribute 'encode'

2021-01-15 01:00:22,721:DEBUG:Worker:RSS after finishing 210114_220110:lbenato_crab_XXTo4J_M100_CTau50000mm_TuneCP2_13TeV_pythia8-v1: 297.293 MB

```

**Comment by belforte** [comment]
should be enough to check current status here before calling execute Internal
and if it was in TAPERECALL move to KILLED and do not call the Dagman stuff
https://github.com/dmwm/CRABServer/blob/bccc877434a8c55b844b837601dfd4bea9b49f27/src/python/TaskWorker/Actions/DagmanKiller.py#L130-L136

**Comment by mapellidario** [comment]
I just noticed this happening again with a few tasks, for example `221105_132921:schenara_crab_TTToSemi_hdamDown`

**Comment by belforte** [comment]
error is very clear
```
2022-11-05 14:44:24,377:DEBUG:Worker:Process-2: KILL work on 221105_132921:schenara_crab_TTToSemi_hdamDown completed in 3 seconds: Status: ERROR
Error = The CRAB server backend was not able to contact the Grid scheduler. Please try again later. If the error persists send an e-mail to cmstalk+computing-tools@dovecotmta.cern.ch. Message from the scheduler: 'NoneType' object has no attribute 'encode'
```
tasks in tape recall are never sent to schedd, so it is obvious that htcondor gives error.
I.e. the same thing indicated at the top.

There's nothing more to be understood IMHO, beside the code flow and where's the best place to put the check etc. etc.

**Comment by belforte** [comment]
this was fixed. Now it works
