### ISSUE TITLE
Improve DebugFailedBlockPublication.py

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6384]
- [ ] should allow to be run from crab3 account outside the container, similarly to
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABStandardCorrectiveActions

- [ ] should ask operatore before trying to insert the block again and/or support a --dry mode

- [ ]  should handle better the case where the file(s) in the failing block are not in DBS:
```
[crab3@crab-prod-tw02 Utils]$ ./DebugFailedBlockPublication.py --file failed-block-at-1612437406.62.txt
Block is meant to be added to dataset
/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6/USER
Block contains 1 files
file /store/user/dseith/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/YEAR2016ERA0_STRECOSKIM_04February2021/210204_045100/0000/tree_13.root found in DBS
Traceback (most recent call last):
  File "./DebugFailedBlockPublication.py", line 109, in <module>
    main()
  File "./DebugFailedBlockPublication.py", line 74, in main
    lfnDSet = apiP3.listDatasets(logical_file_name=lfn)[0]['dataset']
IndexError: list index out of range
[crab3@crab-prod-tw02 Utils]$ 

```

**Comment by belforte** [comment]
at the moment there is no publication error other then the well known "file already present in DBS"
(cfr. #6307  and https://github.com/dmwm/CRABClient/issues/4980 )
so there is no urgent need for more functionalities and 
https://github.com/dmwm/CRABServer/blob/master/scripts/Utils/DebugFailedBlockPublication.py
is fine as it is now.
