### ISSUE TITLE
debug failed publication

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6385]
```
2021-02-04 12:16:46,580:INFO: About to insert dataset: {'dataset': u'/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6/USER', 'physics_group_name': 'CRAB3', 'dataset_access_type': 'VALID', 'last_modification_date': 1612437406, 'processed_ds_name': u'dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6', 'data_tier_name': u'USER'}
2021-02-04 12:16:46,580:INFO: Found 1 files not already present in DBS which will be published.
2021-02-04 12:16:46,613:ERROR: Error for files: [u'/store/user/dseith/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/YEAR2016ERA0_STRECOSKIM_04February2021/210204_045100/0000/tree_13.root']
2021-02-04 12:16:46,614:ERROR: Error when publishing (/store/temp/user/dseith.9e16a68098fe02e3e1f401ca24ec881d2de0cea4/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/YEAR2016ERA0_STRECOSKIM_04February2021/210204_045100/0000/tree_13.root) HTTP Error 400: Duplicated lfn name when inserting                    files. Traceback (most recent call last):
  File "/build/cmsbld/jenkins/workspace/CRABServer_BuildOnRelease/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/v3.210122/CRABServer-v3.210122/build/lib/Publisher/TaskPublish.py", line 835, in publishInDBS3
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 346, in insertBulkBlock
    result =  self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 203, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 230, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 400: Duplicated lfn name when inserting                    files. 

2021-02-04 12:16:46,617:ERROR: FAILING BLOCK DUE TO HTTP Error 400: Duplicated lfn name when inserting                    fi
```

from this block
```
[crab3@crab-prod-tw02 Utils]$ cat /data/container/Publisher_schedd/PublisherFiles/FailedBlocks/failed-block-at-1612432051.48.txt
{'acquisition_era': {'acquisition_era_name': 'CRAB', 'start_date': 0},
 'block': {'block_name': u'/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6/USER#ce645ce9-3227-467c-9d53-3070bf8e3a06',
           'block_size': 18638536,
           'file_count': 1,
           'open_for_writing': 0,
           'origin_site_name': u'T1_DE_KIT_Disk'},
 'dataset': {'data_tier_name': u'USER',
             'dataset': u'/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6/USER',
             'dataset_access_type': 'VALID',
             'last_modification_date': 1612432048,
             'physics_group_name': 'CRAB3',
             'processed_ds_name': u'dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6'},
 'dataset_conf_list': [{'app_name': 'cmsRun',
                        'global_tag': 'crab3_tag',
                        'output_module_label': 'o',
                        'pset_hash': u'8ecc050433dbcfb7ea89627141b876b6',
                        'release_version': u'CMSSW_11_2_1'}],
 'file_conf_list': [{'app_name': 'cmsRun',
                     'global_tag': 'crab3_tag',
                     'lfn': u'/store/user/dseith/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/YEAR2016ERA0_STRECOSKIM_04February2021/210204_045100/0000/tree_21.root',
                     'output_module_label': 'o',
                     'pset_hash': u'8ecc050433dbcfb7ea89627141b876b6',
                     'release_version': u'CMSSW_11_2_1'}],
 'file_parent_list': [],
 'files': [{'adler32': u'dbe34ee9',
            'check_sum': u'1531524101',
            'event_count': 1,
            'file_lumi_list': [{'lumi_section_num': 1, 'run_num': 1}],
            'file_size': 18638536,
            'file_type': 'EDM',
            'logical_file_name': u'/store/user/dseith/TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/YEAR2016ERA0_STRECOSKIM_04February2021/210204_045100/0000/tree_21.root'}],
 'primds': {'primary_ds_name': u'TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8',
            'primary_ds_type': 'mc'},
 'processing_era': {'description': 'CRAB3_processing_era',
                    'processing_version': 1}}[crab3@crab-prod-tw02 Utils]$ 

```

**Comment by belforte** [comment]
error comes from this task
```
210204_045100:dseith_crab_TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia820160
```

**Comment by belforte** [comment]
So the problem is that the file is already present in DBS, but it has been invalidated.
DBS forbids to inser same LFN twice.
Hence the error.
Problem is in here
https://github.com/dmwm/CRABServer/blob/35d6d99973607a4a12730a00db92f0f84aeb6355/src/python/Publisher/TaskPublish.py#L638-L662
in particular at line 660
https://github.com/dmwm/CRABServer/blob/35d6d99973607a4a12730a00db92f0f84aeb6355/src/python/Publisher/TaskPublish.py#L660

Before I change the code, I will check history to see if there was some reason for this, at first sight it looks a plain misunderstanding of how DBS work by the person who wrote the code (me ???)

**Comment by belforte** [comment]
indeed TaskPublish.py log has this line:
```
2021-02-05 14:18:26,855:INFO: Dataset /TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8/dseith-YEAR2016ERA0_STRECOSKIM_04February2021-8ecc050433dbcfb7ea89627141b876b6/USER already contains 84 files (0 valid, 84 invalid).
```
but it is hard to notice. 
Now that there is one log for each task, no need to repeat the (horribly long) dataset in many lines:
- [ ] TaskPublish.py should print dataset name(s) only once and print taskname once at beginning

**Comment by belforte** [comment]
Had to go way back in history (thanks GH !) But my old  code was not caring for file validity:
https://github.com/dmwm/CRAB2/blob/5eaa74806fa53ec4f25f04776b5e0e1a46d29c16/python/crab_dbs3publish.py#L289-L293

Something happened when Andres imported it into ASO PublishWorker 6 years ago in this commit
https://github.com/dmwm/AsyncStageout/commit/13aa980f8646e12ed98f06e2445eed630d9a67c0
as usual, nobody makes so much harm as those who try to do good. A pity that such a good guy
as Andres did not check with me or Yuyi before this change. But surely there was no good reason for
having introduced the check.
Then Diego just reused code in standalone publisher and here we are.

Oh well...
On with the fix.

Straight into : this is the first time that someone checks publish errors before users complain !!
Well.. given how little people cared in the past, it is pretty reassuring that we have so few troubles.

**Comment by belforte** [comment]
I noticed a different problem, some DBS server error which is not properly handled.
Example
```
2021-02-02 09:27:58,926:ERROR: Error when publishing (/store/temp/user/mmoser.dd03bd70eccad040b0b0467ab98da4657b2881bb/tZq_ll_4f_13TeV-amcatnlo-pythia8/crab_RunIISummer16MiniAODv3-PU
Moriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands/210201_143517/0000/nanoAOD_11.root, /store/temp/user/mmoser.dd03bd70eccad040b0b0467ab98da4657b2881bb/tZq_ll_4f_13TeV-amcatnlo-py
thia8/crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands/210201_143517/0000/nanoAOD_22.root, /store/temp/user/mmoser.dd03bd70eccad040b0b0467ab98da465
7b2881bb/tZq_ll_4f_13TeV-amcatnlo-pythia8/crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands/210201_143517/0000/nanoAOD_1.root) (52, 'Empty reply fro
m server')Traceback (most recent call last):
  File "/build/cmsbld/jenkins/workspace/CRABServer_BuildOnRelease/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/v3.210122/CRABServer-v3.210122/build/lib/Publisher/TaskPublish.py", lin
e 835, in publishInDBS3
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 346, in insertBulkBlock
    result =  self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 201, in __callServer
    self.http_response = method_func(self.url, method, params, data, request_headers)
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.16.0-comp/lib/python2.7/site-packages/RestClient/RestApi.py", line 40, in post
    return http_request(self._curl)
  File "/data/srv/TaskManager/v3.210122/slc7_amd64_gcc630/cms/dbs3-pycurl-client/3.16.0-comp/lib/python2.7/site-packages/RestClient/RequestHandling/HTTPRequest.py", line 57, in __cal
l__
    curl_object.perform()
error: (52, 'Empty reply from server')

```
from
```
/data/srv/Publisher/logs/tasks/mmoser/210201_143517:mmoser_crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands.log
```
which resulted in
```
/data/srv/Publisher_files/FailedBlocks/failed-block-at-1612254478.93.txt
```
in this case current `DebugFailedBlockPublication` works and  indicates again attempt to publish files already present in DBS
```
[crab3@crab-prod-tw02 FailedBlocks]$ /data/hostdisk/repos/CRABServer/scripts/Utils/DebugFailedBlockPublication.py --file failed-block-at-1612254478.93.txt
Block is meant to be added to dataset
/tZq_ll_4f_13TeV-amcatnlo-pythia8/mmoser-crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands-91e8898dad3723f03bca2e9d2835912d/USER
Block contains 3 files
file /store/user/mmoser/tZq_ll_4f_13TeV-amcatnlo-pythia8/crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands/210201_143517/0000/nanoAOD_11.root found in DBS
this lfn is already in target dataset
file /store/user/mmoser/tZq_ll_4f_13TeV-amcatnlo-pythia8/crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands/210201_143517/0000/nanoAOD_22.root found in DBS
this lfn is already in target dataset
file /store/user/mmoser/tZq_ll_4f_13TeV-amcatnlo-pythia8/crab_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1_v6_PFCands/210201_143517/0000/nanoAOD_1.root found in DBS
this lfn is already in target dataset
3/3 file(s) from input blocks are already in DBS/phys03. Publication will fail
files already present in target dataset: 3
files present in DBS in another dataset: 0
[crab3@crab-prod-tw02 FailedBlocks]$ 

```

**Comment by belforte** [comment]
In conclusion I have one simple bug to fix: https://github.com/dmwm/CRABServer/issues/6387
and a couple improvements for easier operations/debugging: #6384 #6386

**Comment by belforte** [comment]
but fix pushed to production, will work on improvements.
