### ISSUE TITLE
make sure there's no unicode in Oracle DB

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6471]
latest version of CRABServer REST with py3 compat. changes inserts some unicode strings in the DB.
E.g. in TASK table fields `tm_edm_outfiles` and `tm_extrajdl`

https://cmsweb.cern.ch/crabserver/ui/task/210317_133006%3Aalgomez_crab_QCDPt170to300TuneCP513TeVpythia8RunIIFall17MiniAODv2-PU201712Apr201894Xmc2017
or
https://cmsweb.cern.ch/crabserver/ui/task/210317_150947%3Abelforte_crab_20210317_160942/dbver/preprod

where e.g.
```
tm_extrajdl = [u'+CRAB_USE_NEW_PUBLISHER=True']

```

These creates problems.
In particular the extraJdl is send to HTCondor as a classAd and unicode in there breaks condor submission https://cms-logbook.cern.ch/elog/Analysis+Operations/3435

**Comment by belforte** [comment]
So far I have no indication of unicode in FILEMETADATA or FILETRANSFERSDB table. 
But I have only sampled some FILETRANSFERSDB records in my tasks while looking for aso/publication issues and not looked at FILEMETADATA yet.

**Comment by belforte** [comment]
This points to some problem in https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py which is what handles the crab submit.
And where I modified the initial arg. validation forcing things to `ustr`
OTOH, why this does not happen to other lists like `tm_site_whitelist` ? see
https://cmsweb.cern.ch/crabserver/ui/task/210317_164207%3Abelforte_crab_20210317_174202/dbver/preprod

Also all such lists  when passed to the `WMCore/Server` API in
https://github.com/dmwm/CRABServer/blob/2a5bcee6bcc5d7b0157dc59decb8549b88d22fcd/src/python/CRABInterface/DataWorkflow.py#L106
are cast into `str` via the call to `dbserializer` i.e.
https://github.com/dmwm/CRABServer/blob/2a5bcee6bcc5d7b0157dc59decb8549b88d22fcd/src/python/CRABInterface/DataWorkflow.py#L173
and
https://github.com/dmwm/CRABServer/blob/2a5bcee6bcc5d7b0157dc59decb8549b88d22fcd/src/python/CRABInterface/DataWorkflow.py#L205-L209
https://github.com/dmwm/CRABServer/blob/2a5bcee6bcc5d7b0157dc59decb8549b88d22fcd/src/python/CRABInterface/DataWorkflow.py#L239

**Comment by belforte** [comment]
actually `sitewhitelist` is already a list of strings before
https://github.com/dmwm/CRABServer/blob/2a5bcee6bcc5d7b0157dc59decb8549b88d22fcd/src/python/CRABInterface/DataWorkflow.py#L189
i.e.
```
(Pdb) sitewhitelist
['T2_IT_Legnaro', 'T2_FR_GRIF_LLR', 'T2_ES_CIEMAT', 'T2_FR_IPHC', 'T2_FR_CCIN2P3', 'T2_IT_Rome', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_FR_GRIF_IRFU', 'T2_IT_Bari', 'T2_IT_Pisa', 'T2_ES_IFCA']
```
I gues that it was the result of site expansion in 
https://github.com/dmwm/CRABServer/blob/2a5bcee6bcc5d7b0157dc59decb8549b88d22fcd/src/python/CRABInterface/RESTUserWorkflow.py#L43

**Comment by belforte** [comment]
Sticking with the example of putting this in crabConfig
```
config.Data.userInputFiles = ['a','b','c']
```
which results in `userfiles=[u'a', u'c', u'b']`  if I use `validate_strlist` instead -f `validate_ustrlst` I get the list elements expressed as strings of new bytes : `[b'a', b'c', b'b']`
Now.. `b'xyz'` is a proper python2 string (e.g. https://www.linuxjournal.com/content/bytes-characters-and-python-2 ). 
I'll give this a try.

**Comment by belforte** [comment]
this is working. But now I have to think that I should change all the `validate_ustr*` which I put one month ago into `validate_str` other than thhe cases where unicode is really needed (so fare we know of site white/block list). And then run extensive validation of all possible crab submission use cases and crab commands which sends var/lists to the rest (starting with resubmit etc. etc.).

sounds a very big project

**Comment by belforte** [comment]
testing the "almost full revert" of "use validate_ustr everywhere" in https://github.com/dmwm/CRABServer/commit/ac481a58ae853da0a583d5bcbca7377bd1ef70f9
in my branch https://github.com/belforte/CRABServer/tree/limit-use-of-validate-ustr-in-REST-fix-6471

**Comment by belforte** [comment]
indeed, moving from validate_str to validate_ustr everywhere now mostly a way to work around a shortcoming of WMCore/REST/Validation 1.4.6.pre2 which then was discussed with Dario and fixed in https://github.com/dmwm/WMCore/commit/d6b9591d0325b523bb63e5b693aa8aab75234e2d#diff-4777b993af8a3d85e3b3ae9c0a1581455964bdadbaaff4aa17b0cc216211e410
Now that we use final production tag of 1.4.6 that is not needed anymore. And I could even look into changing 
https://github.com/dmwm/CRABServer/blob/4afcb0070d3cf359d78ac94f1cae121d532ca021/src/python/CRABInterface/RESTUserWorkflow.py#L43
to cast expanded site list into strings and get crabserver sort of "back where it was"

**Comment by belforte** [comment]
long story short, I reverted almost all `validate_ustr` to `validatae_str` and then had to discover and fight one at a time places where the code was casting strings into strings again, most likely totally useless in the original version, unelss old validate_str was not working.
IN current situation `str(b'astring') would result in `"b'astring'"` and break a lo of things.

Code is no cleaner since the multiple cast have been removed, and in latest version
in https://github.com/belforte/CRABServer/tree/limit-use-of-validate-ustr-in-REST-fix-6471
is actually working including publication.

I wander if taking the last step of using `validate_str` instead of `validate_ustr` also for site lists (the only place where it is used now) and rather convert from unicode to string the lists read from CRIC to avoid errors like
`b'T2_CH_CERN' is not among known sites`

**Comment by belforte** [comment]
remaining `validate_ustr` are:
```
LapSB:CRABInterface$ grep validate_ustr *
grep: Pages: Is a directory
RESTUserWorkflow.py:from WMCore.REST.Validation import validate_str, validate_strlist, validate_ustr, validate_ustrlist,\
RESTUserWorkflow.py:            validate_ustrlist("siteblacklist", param, safe, RX_CMSSITE)
RESTUserWorkflow.py:            validate_ustrlist("sitewhitelist", param, safe, RX_CMSSITE)
RESTUserWorkflow.py:            ## Calling validate_ustr with a fake regexp to move the param to the
RESTUserWorkflow.py:            validate_ustr("asyncdest", param, safe, RX_CMSSITE, optional=False)
RESTUserWorkflow.py:            ## validate_ustrlist as it would fail.
RESTUserWorkflow.py:                validate_ustrlist("siteblacklist", param, safe, RX_CMSSITE)
RESTUserWorkflow.py:                validate_ustrlist("sitewhitelist", param, safe, RX_CMSSITE)
LapSB:CRABInterface$ 

```

**Comment by belforte** [comment]
should remove banneedDestinationa. Was a bad idea to bigin with and wsa never used.

**Comment by belforte** [comment]
latest submission have what looks like 14 jobs stuck in publication aquired. Investigating

**Comment by belforte** [comment]
Publisher slaves report this w/o details:
```
2021-03-21 22:33:17,366:WARNING:slave:Error retrieving status from /crabserver/preprod/workflow for 210321_161439:belforte_crab_20210321_171432.

```

**Comment by belforte** [comment]
which matches this server side:
```
[21/Mar/2021:23:01:17]  SERVER DATABASE ERROR 500/403 Execution error cherrypy._cperror.HTTPError f9a9cd876bee8d
619734cc32493cf876 [instance: preprod] (('429 Too Many Requests', 'The current number of active operations for t
his resource exceeds the limit of 3 for user service@crab-preprod-tw01.cern.ch')); last statement: None; binds: None, None; offset: None
[21/Mar/2021:23:01:17]    Traceback (most recent call last):
[21/Mar/2021:23:01:17]      File "/data/repos/WMCore/src/python/WMCore/REST/Server.py", line 1773, in dbapi_wrapper
[21/Mar/2021:23:01:17]        return handler(*xargs, **xkwargs)
[21/Mar/2021:23:01:17]      File "/data/repos/CRABServer/src/python/CRABInterface/RESTUserWorkflow.py", line 691, in get
[21/Mar/2021:23:01:17]        result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)
[21/Mar/2021:23:01:17]      File "/data/repos/CRABServer/src/python/CRABInterface/DataUserWorkflow.py", line 173, in status
[21/Mar/2021:23:01:17]        return self.workflow.status(workflow, userdn, userproxy)
[21/Mar/2021:23:01:17]      File "/data/repos/WMCore/src/python/Utils/Throttled.py", line 203, in throttled_wrapped_function
[21/Mar/2021:23:01:17]        with self.throttleContext(username, debug):
[21/Mar/2021:23:01:17]      File "/data/repos/WMCore/src/python/Utils/Throttled.py", line 68, in __enter__
[21/Mar/2021:23:01:17]        raise cherrypy.HTTPError("429 Too Many Requests", msg)
[21/Mar/2021:23:01:17]    HTTPError: ('429 Too Many Requests', 'The current number of active operations for this resource exceeds the limit of 3 for user service@crab-preprod-tw01.cern.ch')
[21/Mar/2021:23:01:17] crabserver-d95dcfb87-bfb57 188.184.89.161 "GET /crabserver/preprod/workflow?workflow=210318_212229%3Abelforte_crab_20210318_222223 HTTP/1.1" 500 Internal Server Error [data: 4232 in 745 out 15906 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=tw/crab-preprod-tw01.cern.ch" "" ] [ref: "" "CRABPublisher/v3.210312" ]

```

**Comment by belforte** [comment]
restarted crabserver with throttle limit increased from 3 to 10
https://github.com/dmwm/CRABServer/blob/411c8128603bb378e25e600d2f33c481d8a79ce9/src/python/CRABInterface/HTCondorDataWorkflow.py#L25

**Comment by belforte** [comment]
that did it. But somehow this throttling is not working as one would expect.
with this in crabserver/config.py
```
srv.thread_pool = 25
```
it makes no sense that the throttling limit was hit. Maybe it means max of 3 per users summed over all threads, but then it is too strict.

For sure need to report is better client side.
