### ISSUE TITLE
in v3.210422 AutomaticSplitting fails on preprod

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6561]
task: https://cmsweb-testbed.cern.ch/crabserver/ui/task/210423_101344%3Abelforte_crab_20210423_121339
PreDag log:
```
Fri, 23 Apr 2021 12:29:58 CEST(+0000):INFO:PreDAG Pre-DAG started with output redirected to /data/srv/glidecondor/condor_local/spool/638/0/cluster8610638.proc0.subproc0/prejob_logs/predag.0.txt
Fri, 23 Apr 2021 12:29:58 CEST(+0000):INFO:PreDAG found 5 completed jobs
Fri, 23 Apr 2021 12:29:58 CEST(+0000):INFO:PreDAG jobs remaining to process: 0-1, 0-2, 0-3, 0-4, 0-5
Fri, 23 Apr 2021 12:29:58 CEST(+0000):INFO:PreDAG jobs remaining to process: 0-1, 0-2, 0-3, 0-4, 0-5
Got a fatal exception: __init__() takes at most 3 arguments (5 given)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/srv/glidecondor/condor_local/spool/638/0/cluster8610638.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 85, in <module>
    retval = bootstrap()
  File "/data/srv/glidecondor/condor_local/spool/638/0/cluster8610638.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 28, in bootstrap
    return PreDAG.PreDAG().execute(*sys.argv[2:])
  File "TaskWorker/Actions/PreDAG.py", line 114, in execute
    retval = self.executeInternal(*args)
  File "TaskWorker/Actions/PreDAG.py", line 189, in executeInternal
    banSites = CRAB3BanDestinationSites(config, 'dummy', 'dummy', self.logger)
TypeError: __init__() takes at most 3 arguments (5 given)

```

**Comment by belforte** [comment]
sorry @ddaina we'll need a new tag

**Comment by belforte** [comment]
but submission using splitting other than automaticSplitting are working well.
