### ISSUE TITLE
Improve chek on user-provided LFN

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6629]
in spite of #6590 and #6601 we still have cases where users manage to ask CRAB to build LFN's which are too long to fit in the DataBase (there is a 500 char maximum for LFN in DBS).
@ddaina just spotted this case
```
[04/Jun/2021:10:55:00]  SERVER REST ERROR WMCore.REST.Error.InvalidParameter fcc58e26cefd4b7e80729c14a1c30fab (Invalid input parameter)
[04/Jun/2021:10:55:00]    Traceback (most recent call last):
[04/Jun/2021:10:55:00]      File "/data/srv/HG2106c-comp/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.210521/lib/python2.7/site-packages/WMCore/REST/Server.py", line 727, in default
[04/Jun/2021:10:55:00]        return self._call(RESTArgs(list(args), kwargs))
[04/Jun/2021:10:55:00]      File "/data/srv/HG2106c-comp/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.210521/lib/python2.7/site-packages/WMCore/REST/Server.py", line 804, in _call
[04/Jun/2021:10:55:00]        v(apiobj, request.method, api, param, safe)
[04/Jun/2021:10:55:00]      File "/data/srv/HG2106c-comp/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.210521/lib/python2.7/site-packages/CRABInterface/RESTFileMetadata.py", line 50, in validate
[04/Jun/2021:10:55:00]        validate_str("outtmplfn", param, safe, RX_LFN, optional=True)
[04/Jun/2021:10:55:00]      File "/data/srv/HG2106c-comp/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.210521/lib/python2.7/site-packages/WMCore/REST/Validation.py", line 124, in validate_str
[04/Jun/2021:10:55:00]        _validate_one(argname, param, safe, _check_str, optional, rx, custom_err)
[04/Jun/2021:10:55:00]      File "/data/srv/HG2106c-comp/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.210521/lib/python2.7/site-packages/WMCore/REST/Validation.py", line 88, in _validate_one
[04/Jun/2021:10:55:00]        safe.kwargs[argname] = checker(argname, val, *args)
[04/Jun/2021:10:55:00]      File "/data/srv/HG2106c-comp/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.210521/lib/python2.7/site-packages/WMCore/REST/Validation.py", line 42, in _check_str
[04/Jun/2021:10:55:00]        raise InvalidParameter(return_message("Incorrect '%s' parameter" % argname, custom_err))
[04/Jun/2021:10:55:00]    InvalidParameter: InvalidParameter fcc58e26cefd4b7e80729c14a1c30fab [HTTP 400, APP 302, MSG 'Invalid input parameter', INFO "Incorrect 'outtmplfn' parameter", ERR None]
[04/Jun/2021:10:55:00] crabserver-84c67ddb7c-xhxnk 188.185.120.166 "PUT /crabserver/prod/filemetadata HTTP/1.1" 400 Bad Request [data: 2648 in 733 out 3630 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=lportale/CN=820031/CN=Louis Portales" "" ] [ref: "" "CRABSchedd/v3.210526p1" ]
``` 
which shows up as a lot of HTPP errors (code 400) in our monitoring
![Screenshot from 2021-06-04 11-32-00](https://user-images.githubusercontent.com/1837785/120780518-807d6f80-c528-11eb-9bb3-05127c053ead.png)
all those error come from PostJobs for a single user  (well.. only PostJob writed to filemetadata)
![Screenshot from 2021-06-04 11-33-09](https://user-images.githubusercontent.com/1837785/120780715-a99e0000-c528-11eb-8f0e-0edaf22e9f2a.png)

looking at recent tasks from that person, I find e.g.
https://cmsweb.cern.ch:8443/scheddmon/0194/cms589/210603_135909:lportale_crab_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_5/
where in submission config:
```
config.Data.outLFNDirBase = '/store/user/lportale/HHNtuples_res/RadionToHHTo2b2tau_narrow_METtriggers_2018/MC_rad18_METtrigger_fixed_03Jun2021/5_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8__RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1'
```
is already 252 chars long.

Then PostJob fails with e.g. this from https://cmsweb.cern.ch:8443/scheddmon/0194/cms589/210603_135909:lportale_crab_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_5/postjob.0-2.0.txt
```
Thu, 03 Jun 2021 16:22:40 CEST(+0000):INFO:PostJob ====== Starting upload of input files metadata.
Thu, 03 Jun 2021 16:22:40 CEST(+0000):DEBUG:PostJob Uploading input metadata for /store/mc/RunIIAutumn18MiniAOD/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/250000/9C6BEDB7-7D77-DC42-87B9-9ADE92D49CE5.root_0-2 to https://cmsweb.cern.ch:8443/crabserver/prod/filemetadata: [('outlfn', u'/store/mc/RunIIAutumn18MiniAOD/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/250000/9C6BEDB7-7D77-DC42-87B9-9ADE92D49CE5.root_0-2'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('outsize', '0'), ('checksumcksum', '0'), ('checksumadler32', '0'), ('jobid', '0-2'), ('outtmplfn', '/store/temp/user/lportale.5793009c9df5edf840f56ab414eea9e8453526c2/HHNtuples_res/RadionToHHTo2b2tau_narrow_METtriggers_2018/MC_rad18_METtrigger_fixed_03Jun2021/5_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8__RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_5/210603_135909/0000'), ('appver', 'CMSSW_10_2_23'), ('outtype', 'POOLIN'), ('checksummd5', '0'), ('publishdataname', 'GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_5-00000000000000000000000000000000'), ('events', 3000), ('taskname', '210603_135909:lportale_crab_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_5'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Florida'), ('outlocation', 'T2_FR_GRIF_LLR'), ('directstageout', 0), ('outfileruns', '1'), ('outfilelumis', '46,47,48')]
Thu, 03 Jun 2021 16:22:40 CEST(+0000):DEBUG:RESTInteractions Sleeping 25 seconds after HTTP error. Error details:  {'Content-Length': '733', 'X-Error-Http': '400', 'X-Rest-Time': '2088.070 us', 'Server': 'nginx/1.17.10', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=14151 t=1622730160859281', 'X-Rest-Status': '302', 'Date': 'Thu, 03 Jun 2021 14:22:40 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outtmplfn' parameter", 'X-Error-Id': 'dd1bf46bdcac7510e30fa59d2bd767fb'}
Thu, 03 Jun 2021 16:23:05 CEST(+0000):DEBUG:RESTInteractions Sleeping 39 seconds after HTTP error. Error details:  {'Content-Length': '733', 'X-Error-Http': '400', 'X-Rest-Time': '3571.033 us', 'Server': 'nginx/1.17.10', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=19879 t=1622730185912847', 'X-Rest-Status': '302', 'Date': 'Thu, 03 Jun 2021 14:23:05 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outtmplfn' parameter", 'X-Error-Id': '8890534eeb87cec0e90e2df4270e4793'}
Thu, 03 Jun 2021 16:23:45 CEST(+0000):DEBUG:RESTInteractions Sleeping 51 seconds after HTTP error. Error details:  {'Content-Length': '733', 'X-Error-Http': '400', 'X-Rest-Time': '1985.073 us', 'Server': 'nginx/1.17.10', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=14327 t=1622730225066883', 'X-Rest-Status': '302', 'Date': 'Thu, 03 Jun 2021 14:23:45 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outtmplfn' parameter", 'X-Error-Id': '457c20f9070467b7f7b63cd7e76c7648'}
Thu, 03 Jun 2021 16:24:36 CEST(+0000):ERROR:RESTInteractions Fatal error reading data from https://cmsweb.cern.ch:8443/crabserver/prod/filemetadata using outlfn=%2Fstore%2Fmc%2FRunIIAutumn18MiniAOD%2FGluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8%2FMINIAODSIM%2F102X_upgrade2018_realistic_v15-v1%2F250000%2F9C6BEDB7-7D77-DC42-87B9-9ADE92D49CE5.root_0-2&outdatasetname=%2FFakeDataset%2Ffakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9%2FUSER&globalTag=None&outsize=0&checksumcksum=0&checksumadler32=0&jobid=0-2&outtmplfn=%2Fstore%2Ftemp%2Fuser%2Flportale.5793009c9df5edf840f56ab414eea9e8453526c2%2FHHNtuples_res%2FRadionToHHTo2b2tau_narrow_METtriggers_2018%2FMC_rad18_METtrigger_fixed_03Jun2021%2F5_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8__RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1%2FGluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8%2FGluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_5%2F210603_135909%2F0000&appver=CMSSW_10_2_23&outtype=POOLIN&checksummd5=0&publishdataname=GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_5-00000000000000000000000000000000&events=3000&taskname=210603_135909%3Alportale_crab_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_5&acquisitionera=null&outtmplocation=T2_US_Florida&outlocation=T2_FR_GRIF_LLR&directstageout=0&outfileruns=1&outfilelumis=46%2C47%2C48
Thu, 03 Jun 2021 16:24:36 CEST(+0000):ERROR:PostJob Fatal error uploading input files metadata: local variable 'datares' referenced before assignment
Traceback (most recent call last):
  File "TaskWorker/Actions/PostJob.py", line 2153, in execute_internal
    self.upload_input_files_metadata()
  File "TaskWorker/Actions/PostJob.py", line 2445, in upload_input_files_metadata
    self.crabserver.put(api=rest_api, data=encodeRequest(configreq))
  File "RESTInteractions.py", line 229, in put
    return self.server.put(uri, data)
  File "RESTInteractions.py", line 116, in put
    return self.makeRequest(uri=uri, data=data, verb='PUT')
  File "RESTInteractions.py", line 176, in makeRequest
    result = JSONRequests(idict={"pycurl" : True}).decode(datares)
UnboundLocalError: local variable 'datares' referenced before assignment
```
where indeed `outtmplfn` variable is 517 char long
('outtmplfn', '/store/temp/user/lportale.5793009c9df5edf840f56ab414eea9e8453526c2/HHNtuples_res/RadionToHHTo2b2tau_narrow_METtriggers_2018/MC_rad18_METtrigger_fixed_03Jun2021/5_GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8__RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_5/210603_135909/0000')

 I am puzzled that this happens in spite of a reasonalble
 [('outlfn', u'/store/mc/RunIIAutumn18MiniAOD/GluGluToRadionToHHTo2B2Tau_M-700_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/250000/9C6BEDB7-7D77-DC42-87B9-9ADE92D49CE5.root_0-2')
 
But clearly the check I have put in DagmanCreator needs to be improved.

The fact that after the 3rd attempt a bogus ` local variable 'datares' referenced before assignment` is raised comes from https://github.com/dmwm/CRABServer/issues/6609#issuecomment-852012386 . The fix for that is not deployed in production yet.

**Comment by belforte** [comment]
still in same PJ  I noticed these two classAds:
                     **CRAB_OutLFNDir**    /store/user/lportale/HHNtuples_res/RadionToHHTo2b2tau_narrow_METtriggers_2018/MC_rad18_METtrigger_fixed_03Jun2021/7_GluGluToRadionToHHTo2B2Tau_M-900_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8__RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/GluGluToRadionToHHTo2B2Tau_M-900_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/GluGluToRadionToHHTo2B2Tau_M-900_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_7/210604_084154
                 **CRAB_OutTempLFNDir**    /store/temp/user/lportale.5793009c9df5edf840f56ab414eea9e8453526c2/HHNtuples_res/RadionToHHTo2b2tau_narrow_METtriggers_2018/MC_rad18_METtrigger_fixed_03Jun2021/7_GluGluToRadionToHHTo2B2Tau_M-900_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8__RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1/GluGluToRadionToHHTo2B2Tau_M-900_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/GluGluToRadionToHHTo2B2Tau_M-900_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8_MC_rad18_METtrigger_fixed_03Jun2021_7/210604_084154
the former is 467 char, the latter 513.

I wander if the problem is this line
https://github.com/dmwm/CRABServer/blob/56feb9f8b6e8e6d6bec0d28b9c71a08fa414e386/src/python/TaskWorker/Actions/DagmanCreator.py#L248-L249
where I left 5 space (5 char) for `/temp` but not for the proxy FQAN hash `lportale.5793009c9df5edf840f56ab414eea9e8453526c2` which is 40-char long !

**Comment by belforte** [comment]
also, that check is only enabled in case of Publication
https://github.com/dmwm/CRABServer/blob/56feb9f8b6e8e6d6bec0d28b9c71a08fa414e386/src/python/TaskWorker/Actions/DagmanCreator.py#L570-L572
but `outtmplfn` is uploaded in any case since PostJob always uploads the metadata

https://github.com/dmwm/CRABServer/blob/56feb9f8b6e8e6d6bec0d28b9c71a08fa414e386/src/python/TaskWorker/Actions/PostJob.py#L2150-L2171

**Comment by belforte** [comment]
yes, the problem was this:
https://github.com/dmwm/CRABServer/blob/56feb9f8b6e8e6d6bec0d28b9c71a08fa414e386/src/python/TaskWorker/Actions/DagmanCreator.py#L569-L572
simply we need to make that check all of the times and use the longest directory name i.e. `temp_dest`
