### ISSUE TITLE
TapeRecallStatus recurring action fails with UnboundLocalError

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6693]
from e.g.
`/data/srv/TaskManager/logs/tasks/recurring/TapeRecallStatus_210714-0816.log`
the procedure starts working on the list of tasks but in the middle crashes on an error and some tasks are not checked.

```
2021-07-14 08:16:38,312:INFO:TapeRecallStatus:Retrieving TAPERECALL tasks
2021-07-14 08:16:55,253:INFO:TapeRecallStatus:Retrieved a total of 12 TAPERECALL tasks
2021-07-14 08:16:55,256:INFO:TapeRecallStatus:Working on task 210708_115750:atulupov_crab_Bfinder_2017_PsiKS_C
2021-07-14 08:16:55,259:INFO:TapeRecallStatus:Task points to Rucio RuleId:  a87fd986a7634d13adcbe38acf13e490 
2021-07-14 08:16:55,263:INFO:RucioUtils:Initializing native Rucio client
2021-07-14 08:16:55,283:INFO:RucioUtils:Rucio server v.1.25.7 contacted
2021-07-14 08:16:55,307:INFO:RucioUtils:Rucio client initialized for crab_tape_recall in status ACTIVE
2021-07-14 08:16:55,323:INFO:TapeRecallStatus:Working on task 210710_142146:rosingh_crab_PbPbppRereco2015_cumulants_2sub_b6_v10
2021-07-14 08:16:55,327:INFO:TapeRecallStatus:Task points to Rucio RuleId:  55019d59d949407e985521d340ab158a 
2021-07-14 08:16:55,347:INFO:TapeRecallStatus:Working on task 210710_142253:rosingh_crab_PbPbppRereco2015_TrkOnly_cumulants_2sub_b6_v10
2021-07-14 08:16:55,349:INFO:TapeRecallStatus:Task points to Rucio RuleId:  125f042ca02d4883a4e34944eeae3671 
2021-07-14 08:16:55,367:INFO:TapeRecallStatus:Working on task 210711_004713:gkaratha_crab_GluGluH250_Phi30_ctau50_pu140
2021-07-14 08:16:55,369:INFO:TapeRecallStatus:Task points to Rucio RuleId:  ae11b355f31f42e5b153331f77e176df 
2021-07-14 08:16:55,384:INFO:TapeRecallStatus:Request ae11b355f31f42e5b153331f77e176df is completed, setting status of task 210711_004713:gkaratha_crab_GluGluH250_Phi30_ctau50_pu140 to NEW
2021-07-14 08:16:55,471:ERROR:BaseRecurringAction:Error while runnig recurring action.
2021-07-14 08:16:55,473:ERROR:BaseRecurringAction:local variable 'user_proxy' referenced before assignment
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.210701/slc7_amd64_gcc630/cms/crabtaskworker/v3.210701/lib/python2.7/site-packages/TaskWorker/Actions/Recurring/BaseRecurringAction.py", line 35, in execute
    self._execute(config, task)
  File "/data/srv/TaskManager/v3.210701/slc7_amd64_gcc630/cms/crabtaskworker/v3.210701/lib/python2.7/site-packages/TaskWorker/Actions/Recurring/TapeRecallStatus.py", line 132, in _execute
    if user_proxy: mpl.deleteWarnings(recallingTask['user_proxy'], taskName)
UnboundLocalError: local variable 'user_proxy' referenced before assignment
```

**Comment by belforte** [comment]
example task "letft unchecked" likely because of this:
https://cmsweb.cern.ch/crabserver/ui/task/210711_084818%3Adwalter_crab_TnPPairTrees_UL_2017C_V13

Rucio has staged out all files since July 11, but task is still in TAPERECALL and this task name does not appear in taperecall logs.

**Comment by belforte** [comment]
problem happens in
https://github.com/dmwm/CRABServer/blob/109b0f98aa41acbce128c53561cea53685da2e85/src/python/TaskWorker/Actions/Recurring/TapeRecallStatus.py#L128-L132
and is due to the fact that when crabCache is S3, the call to myproxy to grab the user credential is not done
https://github.com/dmwm/CRABServer/blob/109b0f98aa41acbce128c53561cea53685da2e85/src/python/TaskWorker/Actions/Recurring/TapeRecallStatus.py#L104-L107
so the `user_proxy` variable stays un-initialized.

**Comment by belforte** [comment]
hacked a fix in production, should be unstuck now:
```
Wed, 14 Jul 2021 12:25:54 CEST(+0000):INFO:TapeRecallStatus Request 0319e1e7e7ce4ac68d828dc952eac00d is completed, setting status of task 210711_084818:dwalter_crab_TnPPairTrees_UL_2017C_V13 to NEW
Wed, 14 Jul 2021 12:25:55 CEST(+0000):INFO:TapeRecallStatus Request 379d04d7951947c9ab334112abc79d38 is completed, setting status of task 210711_084944:dwalter_crab_TnPPairTrees_UL_2017H_V13 to NEW
```
