### ISSUE TITLE
make code for sched py3compatible

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6813]
I am not sure it is worth to move "code for scheds" independently from other code, since it carries with it also a large part of TW. Have started to talk to @mapellidario about doing basic things in a unified way.
Anyhow there also things which required more ad hoc code changes and in any case I need a place where to track my todo list in order to use python3 in sched.

**Comment by belforte** [comment]
I resubmitted my test and got same error as Jenkins. At least there's consistency !
OTOH 
1. the local DagmanCreator.py in the spool dire of the tasks which fails/succed are identical as far as hashlib calls
2. the task which succeedes still had
```
Fri, 29 Oct 2021 16:48:09 CEST(+0000):ERROR:BanDestinationSites Got exception in retrieving usable sites list from https://cmssst.web.cern.ch/cmssst/analysis/usableSites.json. Exception: Traceback (most recent call last):
  File "TaskWorker/Actions/Recurring/BanDestinationSites.py", line 50, in execute
    usableSites = urllib2.urlopen(self.config.Sites.DashboardURL).read()
NameError: global name 'urllib2' is not defined
```
3. the tasks which fail now have
```
Fri, 29 Oct 2021 18:33:29 CEST(+0200):ERROR:BanDestinationSites Got exception in retrieving usable sites list from https://cmssst.web.cern.ch/cmssst/analysis/usableSites.json. Exception: Traceback (most recent call last):
  File "/data/srv/glidecondor/condor_local/spool/6408/0/cluster8956408.proc0.subproc0/TaskWorker/Actions/Recurring/BanDestinationSites.py", line 49, in execute
    usableSites = urllib3.urlopen(self.config.Sites.DashboardURL).read()
AttributeError: module 'urllib3' has no attribute 'urlopen'
```

so at the very least I was wrong in https://github.com/dmwm/CRABServer/pull/6841 and since there's no arguing with compilers I need to fix the hashlib call as already stated https://github.com/dmwm/CRABServer/issues/6813#issuecomment-950385629

**Comment by belforte** [comment]
things are hopefully fixed in https://github.com/dmwm/CRABServer/pull/6843

**Comment by belforte** [comment]
I tagged a new version https://github.com/dmwm/CRABServer/releases/tag/py3.211029pre4 with that last change and deployed it on crab-dev-tw01
Automatic splitting now works w/o any error in `predag.0.txt` log
For final confirmation I am re-running Jenkins as well

**Comment by belforte** [comment]
jenkins test was good this time
https://cmsweb-test2.cern.ch/crabserver/ui/task/211029_214226%3Acmsbot_crab_20211029_234224

back to waiting for

I.e. sched-specific code is OK for python3 now. Other than
- [ ] RUCIO_Transfers.py and its dependencies (to do) (should better be done at same time as, or after, Diego  revise the code)
- [ ] FTS_Transfers.py and its dependencies (waiting for FTS py3 client)

**Comment by belforte** [comment]
Makes no sense to keep this open in Hold waiting for new FTS client. Let's have an ad-hoc issue for that and make stock of "sched code runs with python3 now".
