### ISSUE TITLE
stop using asoConfig in REST Config

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6844]
the external config file
https://gitlab.cern.ch/crab3/CRAB3ServerConfig/blob/master/cmsweb-rest-config.json
still has references like
```
 "asoConfig": [{"couchURL": "https://cmsweb-testbed.cern.ch/couchdb", "couchDBName": "asodb3"}]
```
or
```
 "asoConfig": [{"couchURL": "https://cmsweb-auth.cern.ch/crabserver/prod", "couchDBName": "filetransfers"}]
```
which are not needed, since ASO always talk with `transfersdb` via the same REST Host used for all CRABServer calls.

Need to

- [x] properly cleanup PostJob,py

and then can remove the code which deals with the asoConfig in
- [x] ./python/CRABInterface/Utilities.py
here it is only in comments referring to backed-urls manipulation, to be removed once ASO config. stuff is removed from REST JSON file
- [x] ./python/CRABInterface/RESTUserWorkflow.py
here is used in `_getAsoConfig` see above. We need to make ASO work w/to those config. things first.

**Comment by belforte** [comment]
in doing this I assume that previous PostJob cleanup was done, i.e. it must be applied on the branch where https://github.com/dmwm/CRABServer/pull/6848 was merged

**Comment by belforte** [comment]
cleanup is more extensive than initially thought.
https://github.com/dmwm/CRABServer/blob/cef2ad9982a75f3201f8a75c50c4b47f2d236196/src/python/CRABInterface/RESTUserWorkflow.py#L226
turns the params from REST JSON config `asourl` and `asodb` into DB entries which are refernces in a lot of places
```
LapSB:src$ pyfind asourl|grep py
./python/TaskWorker/Actions/DagmanResubmitter.py
./python/TaskWorker/Actions/DagmanSubmitter.py
./python/TaskWorker/Actions/DagmanCreator.py
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
./python/CRABInterface/DataUserWorkflow.py
./python/CRABInterface/HTCondorDataWorkflow.py
./python/CRABInterface/DataWorkflow.py
./python/CRABInterface/RESTUserWorkflow.py
LapSB:src$ 
```

**Comment by belforte** [comment]
Anyhow this is an old relic to get rid of, but just a few lines here and there and should have no impact on porting code to python3.

**Comment by belforte** [comment]
work in progress in my branch
https://github.com/belforte/CRABServer/tree/remove-asoConfig
will get again to this later next week

**Comment by belforte** [comment]
progress. Now all TW parts are cleaned and worth testing before finalizing cleanup of REST and Database code:
```
LapSB:src$ pyfind asourl|grep py
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
./python/CRABInterface/DataUserWorkflow.py
./python/CRABInterface/HTCondorDataWorkflow.py
./python/CRABInterface/DataWorkflow.py
LapSB:src$ pyfind asodb|grep py
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
./python/CRABInterface/DataUserWorkflow.py
./python/CRABInterface/HTCondorDataWorkflow.py
./python/CRABInterface/DataWorkflow.py
LapSB:src$ 
```
and variables in `asoConfig` dictionary in REST JSON config are only referenced in comments
```
LapSB:src$ pyfind couchURL
        #             u'asoConfig': [{ u'couchURL': '', u'couchDBName': ''}],
        #         u'asoConfig': [{u'couchURL': '', u'couchDBName': ''}],
./python/CRABInterface/Utilities.py
LapSB:src$ pyfind couchDBName
        #             u'asoConfig': [{ u'couchURL': '', u'couchDBName': ''}],
        #         u'asoConfig': [{u'couchURL': '', u'couchDBName': ''}],
./python/CRABInterface/Utilities.py
LapSB:src$ 
```

**Comment by belforte** [comment]
on HOLD. will wait until #6830 is done and REST has a bit of stability.

**Comment by belforte** [comment]
time to complete this. As soon as I get test instance back for testing. @mapellidario do you need it ?

**Comment by belforte** [comment]
I tested removing asoConfig from JSON config on gitlab (just for cmsweb-test1) [1]
switchin cmsweb-test1 mode in `data/srv/current/config/crabserver/config.py` last line:
```
[_crabserver@crabserver-68649b7ff5-dhf7d data]$ tail -1 /data/srv/current/config/crabserver/config.py
data.mode = "cmsweb-test1"
[_crabserver@crabserver-68649b7ff5-dhf7d data]$ 
```
and crabserver still starts. I will now try to remove the code which is supposed to read it as well.

[1]
https://gitlab.cern.ch/crab3/CRAB3ServerConfig/-/commit/d2b0c727a8a1e8daea99c15e423b597444938608

**Comment by belforte** [comment]
now need to look at https://github.com/dmwm/CRABServer/blob/cef2ad9982a75f3201f8a75c50c4b47f2d236196/src/python/CRABInterface/RESTUserWorkflow.py#L226

**Comment by belforte** [comment]
after removing the call to getAsoConfig, PostJob fails with
Mon, 20 Dec 2021 15:43:41 CET(+0100):ERROR:PostJob Could not determine the following required attributes from the job ad: ['CRAB_ASOURL']
cleaning of PJ was not good enough.

**Comment by belforte** [comment]
**RESET**
I have been doing too many things and lost track.
I has started this cleanup already in three branches by now, but never made PR's not created related issues.
https://github.com/belforte/CRABServer/tree/removeAsoUrlAsoConfig
https://github.com/belforte/CRABServer/tree/cleanupRESTJson
https://github.com/belforte/CRABServer/tree/stop-using-asoCongig-fix-6844

I need to consolidate all this work in a single branch on top of current python3.

**Comment by belforte** [comment]
OK. have a new branch where I merged the 3 above
https://github.com/belforte/CRABServer/tree/stop-using-AsoUrlAsoConfig
and am back to situation of https://github.com/dmwm/CRABServer/issues/6844#issuecomment-960559841
with no reference to `asoConfig` but also this `ASOURL` and `ASODB`  to care of (were not "found" previousy)
```
LapSB:src$ pyfind ASODB
RX_ASODB = RX_USERNAME
./python/CRABInterface/Regexps.py
LapSB:src$ pyfind ASOURL
RX_ASOURL = RX_DBSURL
./python/CRABInterface/Regexps.py
        #Always returning ASOURL also, it is required for kill, resubmit
        result['ASOURL'] = row.asourl
./python/CRABInterface/HTCondorDataWorkflow.py
        args = {'ASOURL' : getattr(row, 'asourl', '')}
./python/CRABInterface/DataWorkflow.py
LapSB:src$ 

```

**Comment by belforte** [comment]
status:
```
LapSB:src$ find . -name '*py' -exec grep -qi aso_db {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi aso_url {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi asodb {} \; -print
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
./python/CRABInterface/DataUserWorkflow.py
./python/CRABInterface/HTCondorDataWorkflow.py
./python/CRABInterface/DataWorkflow.py
LapSB:src$ find . -name '*py' -exec grep -qi asourl {} \; -print
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
./python/CRABInterface/DataUserWorkflow.py
./python/CRABInterface/HTCondorDataWorkflow.py
./python/CRABInterface/DataWorkflow.py
LapSB:src$ 

```
let's leave Database i/f cleanup for later. And deal with the 3 `*Data*` in CRABInterface one at a time.
sorted by numer of occurrences of the `asourl/db` strings
- [ ] DataUserWorkflow.py
- [ ] HTCondorDataWorkflow.py
- [ ] DataWorkflow.py

**Comment by belforte** [comment]
Now need to clean the Database access code.
```
LapSB:src$ find . -name '*py' -exec grep -qi asodb {} \; -print
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
LapSB:src$ find . -name '*py' -exec grep -qi asourl {} \; -print
./python/Databases/TaskDB/Oracle/Task/Task.py
./python/Databases/TaskDB/Oracle/Create.py
LapSB:src$ 
```

**Comment by belforte** [comment]
done:
```
LapSB:src$ find . -name '*py' -exec grep -qi aso_conf {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi asoconf {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi asourl {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi asodb {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi aso_url {} \; -print
LapSB:src$ find . -name '*py' -exec grep -qi aso_db {} \; -print
LapSB:src$ 
```

**Comment by belforte** [comment]
maybe I overdid it. Now crab client fails to get status of publication:
```
elforte@lxplus722/TC3> crab status -d crab_20211221_174241/
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20211221_174241
Task name:			211221_164248:belforte_crab_20211221_174241
Grid scheduler - Task Worker:	crab3@vocms0120.cern.ch - crab-dev-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb-test1.cern.ch/crabserver/ui/task/211221_164248%3Abelforte_crab_20211221_174241
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=211221_164248%3Abelforte_crab_20211221_174241&from=1640101368000&to=now
Status on the scheduler:	COMPLETED

Jobs status:                    finished     		100.0% (5/5)
Fatal error trying to connect to https://cmsweb-test1.cern.ch:8443/crabserver/dev/workflow?username=belforte&asodb=asynctransfer&asourl=None&subresource=publicationstatus&workflow=211221_164248%3Abelforte_crab_20211221_174241 using username=belforte&asodb=asynctransfer&asourl=None&subresource=publicationstatus&workflow=211221_164248%3Abelforte_crab_20211221_174241.
The server answered with an error.
Server answered with: Invalid input parameter
Reason is: Excess keyword arguments, not validated kwargs='{'Debug.ASODB': 'asynctransfer', 'Debug.ASOURL': 'None'}'
Error Id: 017daf18f18d6fc42d2846e20b0c66ef
belforte@lxplus722/TC3> 
```
I need to keep supporting old client while cleaning up server.

**Comment by belforte** [comment]
traceback from cliient
```
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 136, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 229, in __call__
    shortResult['numUnpublishable'], asourl, asodb, taskname, user, crabDBInfo)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 1015, in printPublication
    pubStatus = self.publicationStatus(taskname, asourl, asodb, user)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 330, in publicationStatus
    'asourl':asourl, 'asodb':asodb, 'username':user})
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/CrabRestInterface.py", line 255, in get
    return self.server.get(uri, data)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/CrabRestInterface.py", line 122, in get
    return self.makeRequest(uri=uri, data=data, verb='GET')
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/CrabRestInterface.py", line 202, in makeRequest
    raise RESTInterfaceException(stderr)

```

**Comment by belforte** [comment]
indeed this URL works finely
https://cmsweb-test1.cern.ch/crabserver/dev/workflow?username=belforte&subresource=publicationstatus&workflow=211221_164248%3Abelforte_crab_20211221_174241
while client uses
https://cmsweb-test1.cern.ch:8443/crabserver/dev/workflow?username=belforte&asodb=asynctransfer&asourl=None&subresource=publicationstatus&workflow=211221_164248%3Abelforte_crab_20211221_174241

**Comment by belforte** [comment]
more relevant, REST side traceback, which alas does not indicate exactly whith of the CRABInterface methods was being called... pfff
```
[21/Dec/2021:20:15:53]  SERVER REST ERROR WMCore.REST.Error.InvalidParameter 017daf18f18d6fc42d2846e20b0c66ef (Invalid input parameter)
[21/Dec/2021:20:15:53]    Traceback (most recent call last):
[21/Dec/2021:20:15:53]      File "/data/repos/WMCore/src/python/WMCore/REST/Server.py", line 726, in default
[21/Dec/2021:20:15:53]        return self._call(RESTArgs(list(args), kwargs))
[21/Dec/2021:20:15:53]      File "/data/repos/WMCore/src/python/WMCore/REST/Server.py", line 804, in _call
[21/Dec/2021:20:15:53]        validate_no_more_input(param)
[21/Dec/2021:20:15:53]      File "/data/repos/WMCore/src/python/WMCore/REST/Validation.py", line 271, in validate_no_more_input
[21/Dec/2021:20:15:53]        raise InvalidParameter("Excess keyword arguments, not validated kwargs='%s'" % param.kwargs)
[21/Dec/2021:20:15:53]    WMCore.REST.Error.InvalidParameter: InvalidParameter 017daf18f18d6fc42d2846e20b0c66ef [HTTP 400, APP 302, MSG 'Invalid input parameter', INFO "Excess keyword arguments, not validated kwargs='{'asodb': 'asynctransfer', 'asourl': 'None'}'", ERR None]
[21/Dec/2021:20:15:53] crabserver-7f7684f88c-w6mdm 137.138.31.6 "GET /crabserver/dev/workflow?username=belforte&asodb=asynctransfer&asourl=None&subresource=publicationstatus&workflow=211221_164248%3Abelforte_crab_20211221_174241 HTTP/1.1" 400 Bad Request [data: 8076 in 733 out 3409 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "" "CRABClient/v3.211130" ]
```

**Comment by belforte** [comment]
compatibility with current client is restored by this commit: https://github.com/belforte/CRABServer/commit/2023f895896c1c88ec2f3462ad2d007f969f649c

**Comment by belforte** [comment]
[ - ] need to check compatibility of changes in PostJob and REST.
Have to make sure that we can have new rest wotk with old PJs, or viceversa.

**Comment by belforte** [comment]
I am afrai that I need to break this into two PR's.
One for TW. Than one for REST once all old jobs are drained from the system.
At that point we can possibly have updated client as well and skip the need of https://github.com/belforte/CRABServer/commit/2023f895896c1c88ec2f3462ad2d007f969f649c

**Comment by belforte** [comment]
starting from the branch which I have been testing in cmsweb-test1 and crab-dev-tw01
https://github.com/belforte/CRABServer/tree/stop-using-AsoUrlAsoConfig
I created two branches for the two PR's:
https://github.com/belforte/CRABServer/tree/clean-asourlasodb-from-TW
https://github.com/belforte/CRABServer/tree/clean-asourlasodb-from-REST
and verified that merging both on top of `python3` branch reproduces the former one.
Here I go with PR's

**Comment by belforte** [comment]
for TW: https://github.com/dmwm/CRABServer/pull/6929

**Comment by belforte** [comment]
Can close afternew  CRAB REST is in production and RESTCOnfig.json is cleaned

**Comment by belforte** [comment]
last step done as per https://cms-logbook.cern.ch/elog/Analysis+Operations/3718
https://gitlab.cern.ch/crab3/CRAB3ServerConfig/-/blob/master/cmsweb-rest-config.json is now free of asoconfig
