### ISSUE TITLE
CRABServer fails when reading config from gitlab

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#6897]
### desired behaviour

CRAB Server should work even if gitlab.cern.ch is down for a few hours.

### description of the problem

Submission worked intermittently for about 1h this morning with errors like [1]. Moreover, opening the website https://cmsweb-testbed.cern.ch:8443/crabserver/preprod/info?subresource=delegatedn from a web browser returned HTTP error 500.

Digging into the logs, Stefano found

```plaintext
[02/Dec/2021:11:55:15]  Reading http://gitlab.cern.ch/crab3/CRAB3ServerConfig/raw/master/cmsweb-rest-config.json returned 503.
```

We usually cache that data in memory, but this morning we restared the pods while gitlab was down.

[1]

```plaintext
> crab submit crabConfig_Data_analysis.py 
Will use CRAB configuration file crabConfig_Data_analysis.py
Fatal error trying to connect to https://cmsweb-testbed.cern.ch:8443/crabserver/preprod/info?subresource=delegatedn using subresource=delegatedn.
The server answered with an error.
Server answered with: Execution error
Error Id: 49d588d0b4323e251143fefb551ee3ee
Log file is /afs/cern.ch/user/d/dmapelli/crab/submit/analysis-data/crab_projects/crab_20211202_120939/crab.log
```

**Comment by belforte** [comment]
pointer to the gitlab -is-down incident
https://cern.service-now.com/service-portal?id=outage&n=OTG0067864
they say downtime started at 11:30 and was fixed at 12:30
we see first error in e.g. this log: crabserver-20211202-crabserver-55cc7d9cc7-24wj6.log
at
```
[02/Dec/2021:11:55:15]  Reading http://gitlab.cern.ch/crab3/CRAB3ServerConfig/raw/master/cmsweb-rest-config.json returned 503.
```
with this traceback
```
[02/Dec/2021:11:55:15]  Reading http://gitlab.cern.ch/crab3/CRAB3ServerConfig/raw/master/cmsweb-rest-config.json returned 503.
Using cached values for external configuration.
[02/Dec/2021:11:55:15]  SERVER DATABASE ERROR 500/403 Execution error __builtins__.TypeError 8c2f0046cc14086a5b5853ffff0f63d3 [instance: prod] (expected string or buffer); last statement: None; binds: None, None; offset: None
[02/Dec/2021:11:55:15]    Traceback (most recent call last):
[02/Dec/2021:11:55:15]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1773, in dbapi_wrapper
[02/Dec/2021:11:55:15]        return handler(*xargs, **xkwargs)
[02/Dec/2021:11:55:15]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/CRABInterface/RESTServerInfo.py", line 39, in get
[02/Dec/2021:11:55:15]        return getattr(RESTServerInfo, subresource)(self, **kwargs)
[02/Dec/2021:11:55:15]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/CRABInterface/Utilities.py", line 177, in wrapped_func
[02/Dec/2021:11:55:15]        args[0].centralcfg = ConfigCache(centralconfig=getCentralConfig(extconfigurl=args[0].config.extconfigurl, mode=args[0].config.mode), cachetime=mktime(gmtime()))
[02/Dec/2021:11:55:15]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/cms/crabserver/v3.210701/lib/python2.7/site-packages/CRABInterface/Utilities.py", line 124, in getCentralConfig
[02/Dec/2021:11:55:15]        extConfCommon = json.loads(retrieveConfig(extconfigurl))
[02/Dec/2021:11:55:15]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/external/python/2.7.13-comp2/lib/python2.7/json/__init__.py", line 339, in loads
[02/Dec/2021:11:55:15]        return _default_decoder.decode(s)
[02/Dec/2021:11:55:15]      File "/data/srv/HG2108h/sw/slc7_amd64_gcc630/external/python/2.7.13-comp2/lib/python2.7/json/decoder.py", line 364, in decode
[02/Dec/2021:11:55:15]        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[02/Dec/2021:11:55:15]    TypeError: expected string or buffer
[02/Dec/2021:11:55:15] crabserver-55cc7d9cc7-24wj6 188.184.97.219 "GET /crabserver/prod/info?subresource=version HTTP/1.1" 500 Internal Server Error [data: 922 in 745 out 84729 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba" "" ] [ref: "" "CRABClient/v3.210610" ]

```

what puzzles me is that looking at the source code listed in there it looks like this error can only happen if `centralCfgFallback` was filled with an invalid value in a previously successful call to gitlab
https://github.com/dmwm/CRABServer/blob/87ada3b82688376fb2c8c90156689a7e05fd2638/src/python/CRABInterface/Utilities.py#L111-L124
Note that code did not go through Line 119, so `centralCfgFallback` is not empty, i.e. this is not the first call after an application restart.
Also the log has no sign of recent restarts.

Simply it was likley time to refresh cache as required every 30min by
https://github.com/dmwm/CRABServer/blob/87ada3b82688376fb2c8c90156689a7e05fd2638/src/python/CRABInterface/Utilities.py#L176-L177

Maybe gitlab returned a corrupted file (with http code 200!!) before going down ?

I can only think of adding an exception handling for the case when
https://github.com/dmwm/CRABServer/blob/87ada3b82688376fb2c8c90156689a7e05fd2638/src/python/CRABInterface/Utilities.py#L124
fails and print out diagnostic info.

But AFAIK once there is cached value in memory it is used "forever" if gitlab is down.

@mapellidario @ddaina I find that I get lost easily in this code, I will be thankful if one of you have the strengths to go through it and confirm (or invalidate) my understanding.

Daina, you may remember having worked on this as one of your first python tasks in CRAB, maybe you remember enough to answer an unrelated question about
https://github.com/dmwm/CRABServer/blob/87ada3b82688376fb2c8c90156689a7e05fd2638/src/python/CRABInterface/Utilities.py#L126
surely the transition period ended and it is time to cleanup. I would think that we should keep the code after that line (well.. remove the commented out lines) and drop
https://github.com/dmwm/CRABServer/blob/87ada3b82688376fb2c8c90156689a7e05fd2638/src/python/CRABInterface/Utilities.py#L157
do you agree ?

**Comment by belforte** [comment]
side note, only when we call info with a subresource fied the external config is needed and the above description holds, for the simple info which just returns the version number, things are different and REST returns immediately[1], which explains why liveness/readyness probes did not fail and the comment from Imran this morning "I checked inside crabserver pods, and livenessprobe is working", see https://mattermost.web.cern.ch/cms-o-and-c/pl/bsd1o8zwj7goiqijakuzp13yuc

[1] see code in: https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTServerInfo.py

**Comment by ddaina** [comment]
@belforte you are right about code clean up - we can delete if/else block and leave only 
https://github.com/dmwm/CRABServer/blob/87ada3b82688376fb2c8c90156689a7e05fd2638/src/python/CRABInterface/Utilities.py#L128-L155

*I would suggest to keep comment about json structure for the documentation purpose (if I understood correctly, you are proposing to remove it)

**Comment by belforte** [comment]
thanks @ddaina I admint that I did not read carefully the comment, it looked like old code but you are of course correct.

**Comment by belforte** [comment]
side note, only when we call info with a subresource fied the external config is needed and the above description holds, for the simple info which just returns the version number, things are different and REST returns immediately[1], which explains why liveness/readyness probes did not fail and the comment from Imran this morning "I checked inside crabserver pods, and livenessprobe is working", see https://mattermost.web.cern.ch/cms-o-and-c/pl/bsd1o8zwj7goiqijakuzp13yuc

[1] see code in: https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTServerInfo.py

**Comment by belforte** [comment]
solved via https://github.com/dmwm/CRABServer/pull/6910
