### ISSUE TITLE
TW's dryrunUploader fails in py3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6920]
here for the record.
As agreed with @mapellidario in https://github.com/dmwm/CRABServer/issues/6918#issuecomment-994154447  let's wait for a full review of py3 comaptibility of the code base
before addressing issues "as they come". This may well be gone after that review.

```
2021-12-16 12:56:50,283:INFO:Handler:Finished <TaskWorker.Actions.DagmanCreator.DagmanCreator object at 0x7fb29ab056d0> on 211216_115636:belforte_crab_20211216_125624 in 1 seconds
2021-12-16 12:56:50,283:DEBUG:Handler:Starting <TaskWorker.Actions.DryRunUploader.DryRunUploader object at 0x7fb29ab05160> on 211216_115636:belforte_crab_20211216_125624
2021-12-16 12:56:50,284:DEBUG:Handler:Traceback (most recent call last):
  File "/data/srv/TaskManager/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/slc7_amd64_gcc630/cms/crabtaskworker/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/lib/python3.8/site-packages/TaskWorker/Actions/DryRunUploader.py", line 87, in execute
    return self.executeInternal(*args, **kw)
  File "/data/srv/TaskManager/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/slc7_amd64_gcc630/cms/crabtaskworker/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/lib/python3.8/site-packages/TaskWorker/Actions/DryRunUploader.py", line 46, in executeInternal
    splittingSummary.dump('splitting-summary.json')
  File "/data/srv/TaskManager/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/slc7_amd64_gcc630/cms/crabtaskworker/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/lib/python3.8/site-packages/TaskWorker/Actions/DryRunUploader.py", line 140, in dump
    json.dump(summary, f)
  File "/data/srv/TaskManager/py3.211215-478c8f9ffd5f0a6ab9e470e1a80fff5e/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'

```

at first sight I guess that json file should not be open in binary more
https://github.com/dmwm/CRABServer/blob/e74b065b57906ddbe53f399097ff59a6e8b245e5/src/python/TaskWorker/Actions/DryRunUploader.py#L139-L140

**Comment by mapellidario** [comment]
This was addressed in #6921. I tested it in preprod by running `crab submit --dryrun` and it seems to work [1]. I think we can close this issue, do you agree @belforte ?

[1]:

```plaintext
2022-01-07 10:14:10,899:DEBUG:Handler,111:Starting <TaskWorker.Actions.DryRunUploader.DryRunUploader object at 0x7f8ec5a205b0> on 220107_091311:dmapelli_crab_20220107_101307
2022-01-07 10:14:10,904:DEBUG:DryRunUploader,30:Adding InputFiles.tar.gz to dry run tarball
2022-01-07 10:14:10,980:DEBUG:DryRunUploader,30:Adding splitting-summary.json to dry run tarball
2022-01-07 10:14:10,982:INFO:DryRunUploader,51:Uploading dry run tarball to the user file cache
2022-01-07 10:14:11,056:DEBUG:ServerUtilities,825:Will execute:
curl -f -v -X POST  -H "User-Agent: CRAB" -F "key=dmapelli/220107_091311:dmapelli_crab_20220107_101307/runtimefiles" -F "AWSAccessKeyId=[...]" -F "policy=[...]" -F "signature=[...]" -F "file=@dry-run-sandbox.tar.gz" "https://s3.cern.ch/crabcache_preprod"
2022-01-07 10:14:12,185:DEBUG:ServerUtilities,829:exitcode: 0
stdout: b''
2022-01-07 10:14:12,186:DEBUG:ServerUtilities,731:runtimefiles dry-run-sandbox.tar.gz successully uploaded to S3
2022-01-07 10:14:12,187:INFO:DryRunUploader,56:Uploaded dry run tarball to the user file cache
2022-01-07 10:14:12,188:DEBUG:DryRunUploader,61:runtimefiles upload took 1.2055230140686035 secs and completed at 10:14:12
2022-01-07 10:14:12,188:DEBUG:DryRunUploader,62:check if tarball is available
2022-01-07 10:14:12,188:DEBUG:DryRunUploader,66:download tarball to /dev/null
2022-01-07 10:14:12,231:DEBUG:ServerUtilities,760:PreSignedUrl to download runtimefiles received OK
2022-01-07 10:14:12,236:DEBUG:ServerUtilities,868:Will execute:
wget -Sq -O /dev/null  "https://s3.cern.ch/crabcache_preprod/dmapelli/220107_091311%3Admapelli_crab_20220107_101307/runtimefiles?AWSAccessKeyId=[...]&Signature=[...]&Expires=1641550452"
2022-01-07 10:14:12,333:DEBUG:ServerUtilities,871:exitcode: 0
stdout: b''
2022-01-07 10:14:12,334:DEBUG:DryRunUploader,69:OK, it worked
2022-01-07 10:14:12,334:DEBUG:DryRunUploader,77:Updating task status: {'workflow': '220107_091311:dmapelli_crab_20220107_101307', 'subresource': 'state', 'status': 'UPLOADED'}
2022-01-07 10:14:12,415:DEBUG:ServerUtilities,825:Will execute:
curl -f -v -X POST  -H "User-Agent: CRAB" -F "key=dmapelli/220107_091311:dmapelli_crab_20220107_101307/twlog" -F "AWSAccessKeyId=[...]" -F "policy=[...]=" -F "signature=[...]" -F "file=@./logs/tasks/dmapelli/220107_091311:dmapelli_crab_20220107_101307.log" "https://s3.cern.ch/crabcache_preprod"
2022-01-07 10:14:13,479:DEBUG:ServerUtilities,829:exitcode: 0
stdout: b''
2022-01-07 10:14:13,480:DEBUG:ServerUtilities,731:twlog ./logs/tasks/dmapelli/220107_091311:dmapelli_crab_20220107_101307.log successully uploaded to S3
2022-01-07 10:14:13,480:INFO:Handler,128:Finished <TaskWorker.Actions.DryRunUploader.DryRunUploader object at 0x7f8ec5a205b0> on 220107_091311:dmapelli_crab_20220107_101307 in 2 seconds
```

**Comment by belforte** [comment]
thanks Dario. I agree. Closing

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6921  (only fixed in python3 branch)
