### ISSUE TITLE
fix erros in TaskPublish

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6940]
looking at logs I see some apparantley not fully fatal but surely bad errors
- [x] reference to undefined variable
```
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/crabtaskworker/v3.211111/lib/python2.7/site-packages/Publisher/TaskPublish.py", line 284, in requestBlockMigration
    msg = "Result of migration request: %s" % str(result)
UnboundLocalError: local variable 'result' referenced before assignment
```

- [x] not-handled exception form DBS
```
Exception: Failed to execute command: python /data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/crabtaskworker/v3.211111/lib/python2.7/site-packages/Publisher/TaskPublish.pyc  --configFile=/data/srv/Publisher/PublisherConfig.py --taskname=211229_141843:nshadski_crab__QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_0.
 StdErr: Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/crabtaskworker/v3.211111/lib/python2.7/site-packages/Publisher/TaskPublish.py", line 1001, in <module>
    main()
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/crabtaskworker/v3.211111/lib/python2.7/site-packages/Publisher/TaskPublish.py", line 997, in main
    result = publishInDBS3(config, taskname, verbose)
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/crabtaskworker/v3.211111/lib/python2.7/site-packages/Publisher/TaskPublish.py", line 633, in publishInDBS3
    destApi.insertPrimaryDataset(primds_config)
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 442, in insertPrimaryDataset
    return self.__callServer("primarydatasets", data=primaryDSObj, callmethod='POST' )
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 203, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 227, in __parseForException
    raise http_error
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 500: Internal Server Error

```
- [x] misreported, was not wrong DBS URL
```
2021-12-30 00:37:31,896:INFO: DBS Source API URL: https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader
2021-12-30 00:37:31,897:INFO: DBS Global API URL: https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader
2021-12-30 00:37:31,897:INFO: DBS Destination API URL: https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSWriter
2021-12-30 00:37:31,897:INFO: DBS Destination read API URL: https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSReader
2021-12-30 00:37:31,897:INFO: DBS Migration API URL: https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSMigrate
2021-12-30 00:37:31,897:INFO: inputDataset: /SingleMuon/Run2016H-UL2016_MiniAODv2-v2/MINIAOD
2021-12-30 00:37:31,930:ERROR: Wrong DBS URL https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSWriter
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/crabtaskworker/v3.211111/lib/python2.7/site-packages/Publisher/TaskPublish.py", line 585, in publishInDBS3
    existing_datasets = sourceApi.listDatasets(dataset=inputDataset, detail=True, dataset_access_type='*')
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 798, in listDatasets
    return self.__callServer("datasets", params=kwargs)
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 203, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/TaskManager/v3.211111/slc7_amd64_gcc630/cms/dbs3-client/3.16.0-comp/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 227, in __parseForException
    raise http_error
HTTPError: HTTP Error 500: Internal Server Error
[crab3@crab-prod-tw01 Publisher]$ 
```

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6942
