### ISSUE TITLE
task_proc_wrapper should not mix py2 and py3 envs

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6948]
we currently need to use python2 for running FTS_transfers.py but python3 for the status_cache and RUCIO_transfers.
So need a separate pythonpath !
I have no idea why things are working as they are now, always adding Rucio client python3 version to the env.
I can not reliably reproduce the problem, at times current setup works, at times I get a more proper complain from FTS3 python2 being mixed with Rucio python3 libs:
```

Traceback (most recent call last):
  File "task_process/FTS_Transfers.py", line 18, in <module>
    import fts3.rest.client.easy as fts3
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/__init__.py", line 19, in <module>
    from context import Context
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/context.py", line 36, in <module>
    from request import Request
  File "/usr/lib/python2.7/site-packages/fts3/rest/client/request.py", line 20, in <module>
    import requests
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/cryptography/x509/base.py", line 23, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/cryptography/x509/extensions.py", line 22, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 22, in <module>
    from cryptography.hazmat.primitives.serialization.ssh import (
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 27, in <module>
    from bcrypt import kdf as _bcrypt_kdf
  File "/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py3/current/lib/python3.6/site-packages/bcrypt/__init__.py", line 57
    def gensalt(rounds: int = 12, prefix: bytes = b"2b") -> bytes:
                      ^
SyntaxError: invalid syntax
```
current script has
https://github.com/dmwm/CRABServer/blob/c3437ab5a2fd9075899bf1432e9463032e232c13/scripts/task_process/task_proc_wrapper.sh#L21
which conflicts with the global setup
https://github.com/dmwm/CRABServer/blob/c3437ab5a2fd9075899bf1432e9463032e232c13/scripts/task_process/task_proc_wrapper.sh#L98-L104

**Comment by belforte** [comment]
ran on task with this on crab-dev-tw01, looks good. Ready for more tests.

**Comment by belforte** [comment]
I suspect the non-reproducible error was due to things like "it depends on what was in system memory".... sort of typical of non-properly initialized environments. Can't find any rational for previous code to work !

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6949
(merged in python3 branch only)
