### ISSUE TITLE
[py3] Sometimes automatic crabserver restart fails

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#6951]
I noticed that sometimes the crabserver (py3 version) fails to be restarted. I had a quick look at the most recent event in preprod, from this morning.

Events:

1. `[05/Jan/2022:09:00:02]  INFO: exiting server from termination signal 2 - Podname=crabserver-dcd56f4b-jlq46`: This is the root cause of the restart. It is not clear to me why the crabserver failed here, this will be investigated at a later time (if ever).
2. `[05/Jan/2022:09:00:03]  WATCHDOG: starting server daemon (pid 450185) - Podname=crabserver-dcd56f4b-jlq46`: fails, because of openssl version
3. `[05/Jan/2022:09:03:37]  WATCHDOG: starting server daemon (pid 77) - Podname=crabserver-dcd56f4b-jlq46`: succeeds, because we are hiding the openssl version problem under the carpet with https://github.com/dmwm/CMSKubernetes/blob/master/docker/crabserver/start.sh#L42

Why did the restart at `9:00:03` not use the version of `start.sh` that sets the env variable that allows us to use an older version of openssl? Is it there another restart procedure that I am not aware of?

Full log

```
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ ENTER cmsweb_analysis_preprod@int2r CRABInterface.RESTBaseAPI.RESTBaseAPI (GET preprod info) inuse=0 idle=1 - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ (previously OrJCYKjFBXDH) connected, client: 19.11.0.0.0, server: 19.13.0.0.0, stmtcache: 50 - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ ping - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ check [select sysdate from dual] - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ connection established - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ prepare [select NULL from DUAL] - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ execute: () {} - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59] crabserver-dcd56f4b-jlq46 127.0.0.1 "GET /crabserver/preprod/info HTTP/1.1" 200 OK [data: 302 in 105 out 3391 us ] [auth: OK "" "" ] [ref: "" "Go-http-client/1.1" ] - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ release with rollback - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:08:59:59]  RESTSQL:kDAxJNtawbsZ RELEASED cmsweb_analysis_preprod@int2r timeout=300 inuse=0 idle=1 - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02]  INFO: exiting server from termination signal 2 - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus STOPPING - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8270)) shut down - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus STOPPED - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus EXITING - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus EXITED - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Waiting for child threads to terminate... - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Waiting for thread DBConnectionPool. - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Waiting for thread DBConnectionPool. - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Waiting for thread DBConnectionPool. - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Waiting for thread DBConnectionPool. - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02]  WATCHDOG: server exited with exit code 0 - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:03]  WATCHDOG: starting server daemon (pid 450185) - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:03]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
'request.methods_with_bodies': ('POST', 'PUT', 'DELETE'), - Podname=crabserver-dcd56f4b-jlq46
'request.show_tracebacks': False, - Podname=crabserver-dcd56f4b-jlq46
'server.environment': 'production', - Podname=crabserver-dcd56f4b-jlq46
'server.max_request_body_size': 0, - Podname=crabserver-dcd56f4b-jlq46
'server.socket_host': '0.0.0.0', - Podname=crabserver-dcd56f4b-jlq46
'server.socket_port': 8270, - Podname=crabserver-dcd56f4b-jlq46
'server.socket_queue_size': 100, - Podname=crabserver-dcd56f4b-jlq46
'server.thread_pool': 25, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.group': None, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.key_file': '/data/srv/current/auth/wmcore-auth/header-auth-key', - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.role': None, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.site': None, - Podname=crabserver-dcd56f4b-jlq46
'tools.encode.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.log_headers.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.log_tracebacks.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.proxy.base': 'crabserver-dcd56f4b-jlq46:8270', - Podname=crabserver-dcd56f4b-jlq46
'tools.proxy.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.time.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.trailing_slash.on': True} - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:03]  INFO: loading data into /crabserver - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:03]  ERROR: terminating due to error: Traceback (most recent call last): - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/cms/crabserver/py3.211222patch1/lib/python3.8/site-packages/WMCore/REST/Main.py", line 435, in start_daemon - Podname=crabserver-dcd56f4b-jlq46
self.run() - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/cms/crabserver/py3.211222patch1/lib/python3.8/site-packages/WMCore/REST/Main.py", line 496, in run - Podname=crabserver-dcd56f4b-jlq46
self.install_application() - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/cms/crabserver/py3.211222patch1/lib/python3.8/site-packages/WMCore/REST/Main.py", line 275, in install_application - Podname=crabserver-dcd56f4b-jlq46
module = __import__(module_name, globals(), locals(), [class_name]) - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/cms/crabserver/py3.211222patch1/lib/python3.8/site-packages/CRABInterface/RESTBaseAPI.py", line 13, in <module> - Podname=crabserver-dcd56f4b-jlq46
from CRABInterface.Utilities import ConfigCache, globalinit, getCentralConfig - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/cms/crabserver/py3.211222patch1/lib/python3.8/site-packages/CRABInterface/Utilities.py", line 17, in <module> - Podname=crabserver-dcd56f4b-jlq46
from WMCore.Credential.SimpleMyProxy import SimpleMyProxy, MyProxyException - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/cms/crabserver/py3.211222patch1/lib/python3.8/site-packages/WMCore/Credential/SimpleMyProxy.py", line 20, in <module> - Podname=crabserver-dcd56f4b-jlq46
from OpenSSL import SSL, crypto - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/external/py3-pyOpenSSL/18.0.0-comp/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module> - Podname=crabserver-dcd56f4b-jlq46
from OpenSSL import crypto, SSL - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/external/py3-pyOpenSSL/18.0.0-comp/lib/python3.8/site-packages/OpenSSL/crypto.py", line 16, in <module> - Podname=crabserver-dcd56f4b-jlq46
from OpenSSL._util import ( - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/external/py3-pyOpenSSL/18.0.0-comp/lib/python3.8/site-packages/OpenSSL/_util.py", line 6, in <module> - Podname=crabserver-dcd56f4b-jlq46
from cryptography.hazmat.bindings.openssl.binding import Binding - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/external/py3-cryptography/3.2.1-comp/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 222, in <module> - Podname=crabserver-dcd56f4b-jlq46
_verify_openssl_version(Binding.lib) - Podname=crabserver-dcd56f4b-jlq46
File "/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/external/py3-cryptography/3.2.1-comp/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 182, in _verify_openssl_version - Podname=crabserver-dcd56f4b-jlq46
raise RuntimeError( - Podname=crabserver-dcd56f4b-jlq46
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2. - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:03]  WATCHDOG: server exited with exit code 1 - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:03:37]  WATCHDOG: starting server daemon (pid 77) - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:03:37]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
'request.methods_with_bodies': ('POST', 'PUT', 'DELETE'), - Podname=crabserver-dcd56f4b-jlq46
'request.show_tracebacks': False, - Podname=crabserver-dcd56f4b-jlq46
'server.environment': 'production', - Podname=crabserver-dcd56f4b-jlq46
'server.max_request_body_size': 0, - Podname=crabserver-dcd56f4b-jlq46
'server.socket_host': '0.0.0.0', - Podname=crabserver-dcd56f4b-jlq46
'server.socket_port': 8270, - Podname=crabserver-dcd56f4b-jlq46
'server.socket_queue_size': 100, - Podname=crabserver-dcd56f4b-jlq46
'server.thread_pool': 25, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.group': None, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.key_file': '/data/srv/current/auth/wmcore-auth/header-auth-key', - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.role': None, - Podname=crabserver-dcd56f4b-jlq46
'tools.cms_auth.site': None, - Podname=crabserver-dcd56f4b-jlq46
'tools.encode.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.log_headers.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.log_tracebacks.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.proxy.base': 'crabserver-dcd56f4b-jlq46:8270', - Podname=crabserver-dcd56f4b-jlq46
'tools.proxy.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.time.on': True, - Podname=crabserver-dcd56f4b-jlq46
'tools.trailing_slash.on': True} - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:03:37]  INFO: loading ui into /crabserver/ui - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:03:37]  INFO: loading data into /crabserver - Podname=crabserver-dcd56f4b-jlq46
/data/srv/HG2201b-comp7/sw.dmapelli/slc7_amd64_gcc630/external/py3-cryptography/3.2.1-comp/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py:175: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will completely remove support for it. - Podname=crabserver-dcd56f4b-jlq46
warnings.warn( - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:03:38]  INFO: starting server in /data/srv/state/crabserver - Podname=crabserver-dcd56f4b-jlq46

```

**Comment by belforte** [comment]
hmm.. interesting.
At the very least we need a new label, since this is not a python3 problem.
I guess the first thing is to find out what thing exactly writes messages as `WATCHDOG` in order to find out how it restarts the server. Maybe..
https://github.com/dmwm/WMCore/blob/001cc51651052405a7ecd811cde91da611b1dc57/src/python/WMCore/REST/Main.py#L462
I have the feeling that liveness probe e.g. restarts things properly. But am not sure what restarts the pods vs. what restarts the application only. 

I am quite puzzled by these messages in the log
```
[05/Jan/2022:09:00:02] ENGINE Bus STOPPING - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8270)) shut down - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus STOPPED - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus EXITING - Podname=crabserver-dcd56f4b-jlq46
[05/Jan/2022:09:00:02] ENGINE Bus EXITED - Podname=crabserver-dcd56f4b-jlq46
```
since I can't find the `STOPPING` string nor the `Bus` string in CRABServer+WMCore source code ! Something inside cherrypy ?

**Comment by belforte** [comment]
@mapellidario do I understand correcty that both restarts, the failed one at 9:00:03 and the working one at 9:03:37 (3 minutes later) were done automatically ?

If the server was down for only a few minutes, chances are that this has been happening "since ever in K8s" and we never noticed

**Comment by mapellidario** [comment]
Yes, both restarts were done automatically

**Comment by mapellidario** [comment]
This is the list of the last automatic restarts of the crabserver in preprod, using `registry.cern.ch/cmsweb/crabserver:py3.211222patch1.nodbs`:

```
> grep -r "INFO: final CherryPy configuration:" /data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/2*
[...]
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/25/cmsweb-testbed-logs-m6ccq-startAt=09:00_0.txt:[25/Dec/2021:09:03:37]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/27/cmsweb-testbed-logs-m6ccq-startAt=22:00_0.txt:[27/Dec/2021:22:08:45]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/29/cmsweb-testbed-logs-m6ccq-startAt=09:00_0.txt:[29/Dec/2021:09:00:04]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/29/cmsweb-testbed-logs-m6ccq-startAt=09:00_0.txt:[29/Dec/2021:09:03:37]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
> vocms0750 ~
> grep -r "INFO: final CherryPy configuration:" /data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/3*
> vocms0750 ~
> grep -r "INFO: final CherryPy configuration:" /data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2022     
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2022/01/01/cmsweb-testbed-logs-m6ccq-startAt=09:00_0.txt:[01/Jan/2022:09:03:37]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2022/01/05/cmsweb-testbed-logs-m6ccq-startAt=09:00_0.txt:[05/Jan/2022:09:00:03]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
/data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2022/01/05/cmsweb-testbed-logs-m6ccq-startAt=09:00_0.txt:[05/Jan/2022:09:03:37]  INFO: final CherryPy configuration: {'engine.autoreload.on': False, - Podname=crabserver-dcd56f4b-jlq46
```

The timings look suspicious...

**Comment by belforte** [comment]
suspicion confirmed
```
[_crabserver@crabserver-599d989549-bz5ft data]$ crontab -l
0 9 1-31/4 * * /data/srv/current/config/crabserver/manage start 'I did read documentation' &> /dev/null
[_crabserver@crabserver-599d989549-bz5ft data]$ 
```
so it is restarted every 4 days... a relic of memory leak fears in VM times, but does not explain why it is started with wrong env. first and correct one 3 minutes later.

**Comment by belforte** [comment]
sorry, it does explain !
the above command does not use `/data/run.sh` nor `/data/start.sh` and thus does not setup the openssl version. I suspect that server starts, fails, and then liveness probe restarts the pods which at this point calls `/data/run.sh`
I had noticed that crontab already and made a mental note to remove it, but never put in the list as it looked reasonably harmless (a restart every 4 days...).
Indeed in K8s there is no need for it, if there's a memory leak the pod is killed and restarted byt K8s.

**Comment by belforte** [comment]
I think main reason why i did not pursue cleanup of this is that I do not know how exactly that crontab gets configured, since it is not in the K8s yaml nor could I find it in Docker creation scripts. We may have to ask Imran.

**Comment by belforte** [comment]
well., the crontab is already in the docker image, it is not K8s doing
```
belforte@cmsdocker01/~> docker run -ti cmssw/crabserver:py3.220105  /bin/bash
[_crabserver@8c798c7558ff data]$ crontab -l
0 9 1-31/4 * * /data/srv/current/config/crabserver/manage start 'I did read documentation' &> /dev/null
[_crabserver@8c798c7558ff data]$ 
```

**Comment by mapellidario** [comment]
can it be this?

https://github.com/dmwm/deployment/blob/6770cbacac00212c977cea504ad789127ea50fbe/crabserver/deploy#L47

**Comment by belforte** [comment]
there since 6 years ago.... I hope server is not "significantly leaking" anymore. In case we should investigate
https://github.com/dmwm/deployment/commit/af6e9a8442b08bab457b67fdb7e9238cc43920a6

**Comment by belforte** [comment]
since everytthing appears understood, I propose to close and open one in deployement repo about removing the crontab

**Comment by belforte** [comment]
opened https://github.com/dmwm/CRABServer/issues/6958 to track the needed action.
