### ISSUE TITLE
error in exception handling (due to py3 code ?)

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6995]
something is wrong in exception handling code, I suspect that this was introduced with changes to python3.
We already saw this, I do nto remember if now it is another instance or we never properly kept track for fixing.

from TaskWorker log

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 80, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/TaskWorker/Actions/DagmanCreator.py", line 1193, in execute
    info, params, inputFiles, splitterResult = self.executeInternal(*args, **kw)
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/TaskWorker/Actions/DagmanCreator.py", line 1182, in executeInternal
    info, splitterResult, subdags, dagSpecs = self.createSubdag(*args, **kw)
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/TaskWorker/Actions/DagmanCreator.py", line 785, in createSubdag
    self.uploadWarning(msg, kwargs['task']['user_proxy'], kwargs['task']['tm_taskname'])
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/TaskWorker/Actions/TaskAction.py", line 62, in uploadWarning
    self.crabserver.post(api='/task', data=urlencode(configreq))
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/RESTInteractions.py", line 230, in post
    return self.server.post(uri, data)
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/RESTInteractions.py", line 113, in post
    return self.makeRequest(uri=uri, data=data, verb='POST')
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/RESTInteractions.py", line 162, in makeRequest
    if (i < 2) or (retriableError(ex) and (i < self['retry'])):
  File "/data/srv/TaskManager/py3.220121-447edae2d598ed751062bbfbe1727f79/slc7_amd64_gcc630/cms/crabtaskworker/py3.220121-447edae2d598ed751062bbfbe1727f79/lib/python3.8/site-packages/RESTInteractions.py", line 47, in retriableError
    return ex[0] in [28, 35]
TypeError: 'error' object is not subscriptable

```

**Comment by belforte** [comment]
closed in python3 branch via https://github.com/dmwm/CRABServer/pull/6996
