### ISSUE TITLE
odd  TW error from cmsbot submission

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7038]
by chance I found that one Jenkins job submissions failed with this odd message,
I am suprised that ` TaskWorker.WorkerExceptions.NoAvailableSite` may have disappeared and mostly that such a common error is only surfaced in this task.
Should be investigated. Is this something wrong in new TW ?

```
Problem handling 220201_225602:cmsbot_crab_whitelist because of module 'TaskWorker.WorkerExceptions' has no attribute 'NoAvailableSite' failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/slc7_amd64_gcc630/cms/crabtaskworker/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 80, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/slc7_amd64_gcc630/cms/crabtaskworker/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/lib/python3.8/site-packages/TaskWorker/Actions/DagmanCreator.py", line 1193, in execute
    info, params, inputFiles, splitterResult = self.executeInternal(*args, **kw)
  File "/data/srv/TaskManager/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/slc7_amd64_gcc630/cms/crabtaskworker/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/lib/python3.8/site-packages/TaskWorker/Actions/DagmanCreator.py", line 1182, in executeInternal
    info, splitterResult, subdags, dagSpecs = self.createSubdag(*args, **kw)
  File "/data/srv/TaskManager/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/slc7_amd64_gcc630/cms/crabtaskworker/py3.220124-5fbdb6c50f5c40d6793d876abd53b5fb/lib/python3.8/site-packages/TaskWorker/Actions/DagmanCreator.py", line 918, in createSubdag
    raise TaskWorker.WorkerExceptions.NoAvailableSite(msg)
AttributeError: module 'TaskWorker.WorkerExceptions' has no attribute 'NoAvailableSite'
```

**Comment by belforte** [comment]
hmm... indeed master branch had
https://github.com/dmwm/CRABServer/blob/d2d1a15bb79ee26a1488ffdceb0becd866e1a4bd/src/python/TaskWorker/WorkerExceptions.py#L35-L38
but this was remove in python3 branch during clenup of Panda code: https://github.com/dmwm/CRABServer/commit/4a970c6a6e697de18c7b7f2a591015765be1274e#diff-8cb5b0b7e40fa1d38b4190cba3df260bd86e2c76146d15091bc1a7ae42c8188b

should instead have simply make inherit from `TaskWorkerException`

**Comment by belforte** [comment]
solved in python3 branch via https://github.com/dmwm/CRABServer/pull/7039
