### ISSUE TITLE
PreDag still crash when all probe fails

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7065]
as reported by @tvami in https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/6306.html
when all probe jobs fail eventsThr and eventsSize are used w/o being initialized
```
Wed, 09 Feb 2022 21:45:26 CET(+0100):INFO:PreDAG Pre-DAG started with output redirected to /data/srv/glidecondor/condor_local/spool/7219/0/cluster35747219.proc0.subproc0/prejob_logs/predag.0.txt
Wed, 09 Feb 2022 21:45:26 CET(+0100):INFO:PreDAG found 5 completed jobs
Wed, 09 Feb 2022 21:45:26 CET(+0100):INFO:PreDAG jobs remaining to process: 0-1, 0-2, 0-3, 0-4, 0-5
Wed, 09 Feb 2022 21:45:26 CET(+0100):INFO:PreDAG jobs remaining to process: 0-1, 0-2, 0-3, 0-4, 0-5
Got a fatal exception: local variable 'eventsThr' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/srv/glidecondor/condor_local/spool/7219/0/cluster35747219.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 85, in <module>
    retval = bootstrap()
  File "/data/srv/glidecondor/condor_local/spool/7219/0/cluster35747219.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 28, in bootstrap
    return PreDAG.PreDAG().execute(*sys.argv[2:])
  File "/data/srv/glidecondor/condor_local/spool/7219/0/cluster35747219.proc0.subproc0/TaskWorker/Actions/PreDAG.py", line 116, in execute
    retval = self.executeInternal(*args)
  File "/data/srv/glidecondor/condor_local/spool/7219/0/cluster35747219.proc0.subproc0/TaskWorker/Actions/PreDAG.py", line 215, in executeInternal
    self.logger.info("average throughput for %s jobs: %s evt/s", count, eventsThr)
UnboundLocalError: local variable 'eventsThr' referenced before assignment

```

**Comment by belforte** [comment]
solved  in python3 branch via https://github.com/dmwm/CRABServer/pull/7066
