### ISSUE TITLE
New DBS has different interface to retrieve its own details

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7092]
The `serviceinfo`API of the new DBS is different from the old one we relied on, [see comment from Valentin](https://cms-talk.web.cern.ch/t/crab-submit-failed-due-to-typeerror-list-indices-must-be-integers-or-slices-not-str/7235/2).

This caused new submissions to fail [1]

We pathced the TW in prod with [2], but there must be a better way.

PS: see [this](https://its.cern.ch/jira/browse/CMSKUBERNETES-114?focusedCommentId=4205577&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4205577) comment from Valentin as a starting point for gathering more info about the DBS APIs available.

[1]:

```plaintext
> crab status -d crab_projects/crab_20220223_155218 
CRAB project directory:         /afs/cern.ch/user/d/dmapelli/crab/submit/analysis-data/crab_projects/crab_20220223_155218
Task name:                      220223_145223:dmapelli_crab_20220223_155218
Grid scheduler - Task Worker:   N/A yet - crab-preprod-tw01
Status on the CRAB server:      SUBMITFAILED
Task URL to use for HELP:       https://cmsweb-testbed.cern.ch/crabserver/ui/task/220223_145223%3Admapelli_crab_20220223_155218
Dashboard monitoring URL:       https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=dmapelli&var-task=220223_145223%3Admapelli_crab_20220223_155218&from=1645624343000&to=now
Failure message from server:    Problem handling 220223_145223:dmapelli_crab_20220223_155218 because of list indices must be integers or slices, not str failure, traceback follows
                                Traceback (most recent call last):
                                  File "/data/srv/TaskManager/py3.220215-7d8cb5b163ca673fc220f63c003120a5/slc7_amd64_gcc630/cms/crabtaskworker/py3.220215-7d8cb5b163ca673fc220f63c003120a5/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 80, in executeAction
                                    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
                                  File "/data/srv/TaskManager/py3.220215-7d8cb5b163ca673fc220f63c003120a5/slc7_amd64_gcc630/cms/crabtaskworker/py3.220215-7d8cb5b163ca673fc220f63c003120a5/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 243, in execute
                                    result = self.executeInternal(*args, **kwargs)
                                  File "/data/srv/TaskManager/py3.220215-7d8cb5b163ca673fc220f63c003120a5/slc7_amd64_gcc630/cms/crabtaskworker/py3.220215-7d8cb5b163ca673fc220f63c003120a5/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 262, in executeInternal
                                    self.dbsInstance = self.dbs.dbs.serverinfo()["dbs_instance"]
                                TypeError: list indices must be integers or slices, not str
```

[2]

```diff
[crab3@crab-prod-tw01 TaskManager]$ diff -u /data/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py py3.220203-fb21e34d414e2cf55ccf861e305e8c2c/slc7_amd64_gcc630/cms/crabtaskworker/py3.220203-fb21e34d414e2cf55ccf861e305e8c2c/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py 
--- /data/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py    2022-02-22 18:52:35.252138197 +0100
+++ py3.220203-fb21e34d414e2cf55ccf861e305e8c2c/slc7_amd64_gcc630/cms/crabtaskworker/py3.220203-fb21e34d414e2cf55ccf861e305e8c2c/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py        2022-02-23 17:08:41.843449833 +0100
@@ -259,7 +259,11 @@
             dbsurl = dbsurl.replace(hostname, self.config.Services.DBSHostName)
         self.logger.info("will connect to DBS at URL: %s", dbsurl)
         self.dbs = DBSReader(dbsurl)
-        self.dbsInstance = self.dbs.dbs.serverinfo()["dbs_instance"]
+        # self.dbsInstance = self.dbs.dbs.serverinfo()["dbs_instance"]
+        # TODO FIXME PRODUCTION HOTFIX FOR DBS MIGRATION
+        # self.dbsInstance = "prod/global"  # THIS WAS A MISTAKE, DARIO'S FAULT
+        dbsinstance = dbsurl.split("//")[1].split("/")[3]
+        self.dbsInstance = "prod/{}".format(dbsinstance)
 
         self.taskName = kwargs['task']['tm_taskname']           # pylint: disable=W0201
         self.username = kwargs['task']['tm_username']           # pylint: disable=W0201
```

**Comment by mapellidario** [comment]
@belforte do you think we can close this or would you like a different solution from the one provided in #7093 ?
