### ISSUE TITLE
'didDict' referenced before assignment in TW stageout check

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7107]
serendiptious finding in tw log
```
2022-03-04 05:41:48,470:INFO:StageoutCheck:Will check stageout at T2_CH_CERNBOX
2022-03-04 05:41:48,470:WARNING:RucioUtils:Try Rucio lfn2pn with operation third_party_copy
2022-03-04 05:41:48,498:WARNING:RucioUtils:Rucio lfn2pfn resolution for third_party_copy failed with:
RSE does not exist.
Details: RSE 'T2_CH_CERNBOX' cannot be found in vo 'def'
Try next one.
2022-03-04 05:41:48,498:WARNING:RucioUtils:Try Rucio lfn2pn with operation write
2022-03-04 05:41:48,508:WARNING:RucioUtils:Rucio lfn2pfn resolution for write failed with:
RSE does not exist.
Details: RSE 'T2_CH_CERNBOX' cannot be found in vo 'def'
Try next one.
2022-03-04 05:41:48,508:WARNING:RucioUtils:Try Rucio lfn2pn with operation read
2022-03-04 05:41:48,528:WARNING:RucioUtils:Rucio lfn2pfn resolution for read failed with:
RSE does not exist.
Details: RSE 'T2_CH_CERNBOX' cannot be found in vo 'def'
Try next one.
2022-03-04 05:41:48,529:INFO:ServerUtilities:Warning: Failed to delete file 220304044113hwencrabskim6900to4muxining_crab3check.tmp
2022-03-04 05:41:48,532:ERROR:Handler:Problem handling 220304_044113:hwen_crab_skim_X6900to4mu_xining because of local variable 'didDict' referenced before assignment failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/py3.220225-c05c3bac4cb7fda7b0c4ade9224b6414/slc7_amd64_gcc630/cms/crabtaskworker/py3.220225-c05c3bac4cb7fda7b0c4ade9224b6414/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 80, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/py3.220225-c05c3bac4cb7fda7b0c4ade9224b6414/slc7_amd64_gcc630/cms/crabtaskworker/py3.220225-c05c3bac4cb7fda7b0c4ade9224b6414/lib/python3.8/site-packages/TaskWorker/Actions/StageoutCheck.py", line 96, in execute
    pfn = getWritePFN(self.rucioClient, siteName=self.task['tm_asyncdest'], lfn=lfn, logger=self.logger)
  File "/data/srv/TaskManager/py3.220225-c05c3bac4cb7fda7b0c4ade9224b6414/slc7_amd64_gcc630/cms/crabtaskworker/py3.220225-c05c3bac4cb7fda7b0c4ade9224b6414/lib/python3.8/site-packages/RucioUtils.py", line 56, in getWritePFN
    if not didDict:
UnboundLocalError: local variable 'didDict' referenced before assignment

```

**Comment by belforte** [comment]
main problem is that the message uploaded to user is only the obscure

2022-03-04 05:41:48,532:ERROR:Handler:Problem handling 220304_044113:hwen_crab_skim_X6900to4mu_xining because of local variable 'didDict' referenced before assignment failure, traceback follows

instead of the much more clear
Details: RSE 'T2_CH_CERNBOX' cannot be found in vo 'def'

**Comment by belforte** [comment]
moreover task gets stuck in QUEUED status, same as https://github.com/dmwm/CRABServer/issues/8230
