### ISSUE TITLE
latest PostJob fails when transferLogs=True

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7136]
fix for  #7088 in https://github.com/dmwm/CRABServer/pull/7116 does not work when transferLogs=True and fails with
```
Wed, 16 Mar 2022 18:25:59 CET(+0100):ERROR:PostJob Stageout failure: local variable 'outputdataset' referenced before assignment
Traceback (most recent call last):
  File "/data/srv/glidecondor/condor_local/spool/1710/0/cluster77841710.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 2056, in execute_internal
    ret_code = self.perform_transfers()
  File "/data/srv/glidecondor/condor_local/spool/1710/0/cluster77841710.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 2203, in perform_transfers
    aso_job_retval = ASO_JOB.run()
  File "/data/srv/glidecondor/condor_local/spool/1710/0/cluster77841710.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 506, in run
    self.docs_in_transfer = self.inject_to_aso()
  File "/data/srv/glidecondor/condor_local/spool/1710/0/cluster77841710.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 667, in inject_to_aso
    'outputdataset': outputdataset,
UnboundLocalError: local variable 'outputdataset' referenced before assignment
```
see https://cms-talk.web.cern.ch/t/local-variable-outputdataset-referenced-before-assignment/8267/1

**Comment by belforte** [comment]
alas this was visible in Jenkins[1], but since often jobs there fails for random (grid) reasons[2], I did not pay needed attention
[1] https://github.com/dmwm/CRABServer/issues/7129
[2] https://github.com/dmwm/CRABServer/issues/7130 https://github.com/dmwm/CRABServer/issues/7124
