### ISSUE TITLE
improve ClientValidation Jenkins test 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7176]
I noticed "by chance" that `crab report` is currently  broken due to a change in `dasgoclient` [1]
And am surprised that no user noticed/reported. But mostly that I have been running Jenkins ClientValidation (CV) a lot lately and it always say success.
I think this is because CV runs too early, when jobs are still in transferring and so exit immediately w/o doing anything.
There may be other places where the current strategy "test is OK if crab command completes with exit code 0" may be inadequate. 
Time for a critical review

[1] see https://github.com/dmwm/CRABServer/issues/7162#issuecomment-1075477608

**Comment by belforte** [comment]
Indeed currently `crab report` fails in dasgoclient but still exits with status 0 and still prints some info. I guess it is debatable what to do :-(
```
belforte@lxplus793/bot> crab-prod report
Running crab status first to fetch necessary information.
Failed running command dasgoclient --query 'run,lumi dataset=/GenericTTbar/cmsbot-CRAB3_analysis-2203-94ba0e06145abd65ccb1d21786dc7e1d/USER instance=prod/phys03' --json. Exitcode is 2
  Stderr:
    panic: interface conversion: interface {} is json.Number, not []interface {}
    
    goroutine 1 [running]:
    github.com/dmwm/das2go/services.OrderByRunLumis({0xc000101000, 0x78, 0x7c5b3f})
    	/home/runner/go/pkg/mod/github.com/dmwm/das2go@v0.0.0-20220310203810-12589cef23f2/services/helpers.go:316 +0x8ea
    github.com/dmwm/das2go/services.fileRunLumi({{0xc0003c4100, 0x7a}, {0x7ffda1d86c68, 0x74}, {0xc00039a3e0, 0x20}, 0xc0003bcf90, {0xc0001abdc0, 0x2, 0x2}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/dmwm/das2go@v0.0.0-20220310203810-12589cef23f2/services/helpers.go:303 +0x349
    github.com/dmwm/das2go/services.LocalAPIs.RunLumi4Dataset(...)
    	/home/runner/go/pkg/mod/github.com/dmwm/das2go@v0.0.0-20220310203810-12589cef23f2/services/dbs.go:167
    reflect.Value.call({0x7c0140, 0xac37e8, 0xa93d40}, {0x7c59d7, 0x4}, {0xc000225108, 0x1, 0x40c34b})
    	/opt/hostedtoolcache/go/1.17.7/x64/src/reflect/value.go:556 +0x845
    reflect.Value.Call({0x7c0140, 0xac37e8, 0xc0001af878}, {0xc000225108, 0x1, 0x1})
    	/opt/hostedtoolcache/go/1.17.7/x64/src/reflect/value.go:339 +0xc5
    main.processLocalApis({{0xc0003c4100, 0x7a}, {0x7ffda1d86c68, 0x74}, {0xc00039a3e0, 0x20}, 0xc0003bcf90, {0xc0001abdc0, 0x2, 0x2}, ...}, ...)
    	/home/runner/work/dasgoclient/dasgoclient/main.go:1001 +0x505
    main.process({0x7ffda1d86c68, 0x74}, 0x1, {0x842680, 0x1}, 0x0, {0x0, 0x0}, {0x7cd077, 0x16}, ...)
    	/home/runner/work/dasgoclient/dasgoclient/main.go:509 +0x130f
    main.main()
    	/home/runner/work/dasgoclient/dasgoclient/main.go:155 +0x120d
    
Will save lumi files into output directory /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20220323_113544/results
Summary from jobs in status 'finished':
  Number of files processed: 1
  Number of events read: 6000
  Number of events written in EDM files: 6000
  Number of events written in TFileService files: 0
  Number of events written in other type of files: 0
  Processed lumis written to processedLumis.json
Summary from output datasets in DBS:
  Number of events:
    /GenericTTbar/cmsbot-CRAB3_analysis-2203-94ba0e06145abd65ccb1d21786dc7e1d/USER: 36000
Additional report lumi files:
  Input dataset lumis (from DBS, at task submission time) written to inputDatasetLumis.json
  Lumis to process written to lumisToProcess.json
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20220323_113544/crab.log
belforte@lxplus793/bot> echo $?
0
belforte@lxplus793/bot> 
```
I am quite surprised that files with lumi lists are created after dasgoclient failed
```
/results@lxplus793/bot> ls -l /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20220323_113544 
total 6
-rw-r--r--. 1 belforte zh 301 Mar 23 12:17 inputDatasetLumis.json
-rw-r--r--. 1 belforte zh   2 Mar 23 12:17 input_dataset_duplicate_lumis.json
-rw-r--r--. 1 belforte zh 300 Mar 23 12:17 input_dataset_lumis.json
-rw-r--r--. 1 belforte zh 272 Mar 23 12:17 lumisToProcess.json
-rw-r--r--. 1 belforte zh 272 Mar 23 12:17 processedLumis.json
-rw-r--r--. 1 belforte zh 589 Mar 23 12:17 run_and_lumis.tar.gz
belforte@lxplus793/bot> 
```

maybe we need to review what `crab report` does ?
