### ISSUE TITLE
Data Type error in PostJob 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7262]
an effect or py3 migration ? Or has it been there since ever and nobody noticed ? Or simply a missing protection against an undefined variable ( `NoneType` ) in rare situations ?
from
https://cmsweb.cern.ch:8443/scheddmon/0137/mteroerd/220509_113910:mteroerd_crab_PMSSM_set_2_prompt_1_Fall17/postjob.107.0.txt
```

======== Starting execution again after deferral
Mon, 23 May 2022 00:23:15 CEST(+0200):DEBUG:PostJob (Parsed job ad.)
Mon, 23 May 2022 00:23:15 CEST(+0200):ERROR:PostJob Stageout failure: '>' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
  File "/data/srv/glidecondor/condor_local/spool/1052/0/cluster78051052.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 2060, in execute_internal
    ret_code = self.perform_transfers()
  File "/data/srv/glidecondor/condor_local/spool/1052/0/cluster78051052.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 2209, in perform_transfers
    aso_job_retval = ASO_JOB.check_transfers()
  File "/data/srv/glidecondor/condor_local/spool/1052/0/cluster78051052.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 405, in check_transfers
    transfers_statuses = self.get_transfers_statuses()
  File "/data/srv/glidecondor/condor_local/spool/1052/0/cluster78051052.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 1055, in get_transfers_statuses
    if (time.time() - last_query < 900) and (last_query > self.aso_start_timestamp):
TypeError: '>' not supported between instances of 'float' and 'NoneType'
Mon, 23 May 2022 00:23:15 CEST(+0200):INFO:PostJob ====== Finished to check for ASO transfers.
```
the list which raises is
https://github.com/dmwm/CRABServer/blob/76c59fa891c041cc21948a6f60c4b2869ed8fb93/src/python/TaskWorker/Actions/PostJob.py#L1055

**Comment by belforte** [comment]
tracking `aso_start_timestamp` in PostJob.py is a nightmare
