### ISSUE TITLE
Delete workflow fails with error 500

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7291]
#### description

After deploying to production the changes from v3.220529, I noticed a group of error 500 [0]. Having a look at the logs [1] it seems that we need to fix our code. 

[0] [grafana](https://monit-grafana.cern.ch/d/VML5DJEnk/crab-crabserver-timber?orgId=11&from=1655201247779&to=1655201569703&var-method=All&var-api=All&var-code=500&var-metadataType=All&var-cluster=All&var-env=All&var-dnFilter=.*&var-Bin=10s&var-crabserverpod=All)

[1]

```plaintext
[14/Jun/2022:12:10:33]  RESTSQL:qtJAUIgQmapZ prepare [SELECT tm_taskname, tm_task_status, tm_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_algo, tm_split_args, tm_save_logs, tm_username,
         tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir,              tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time, tw_name
    FROM tasks WHERE tm_taskname=:taskname]
[14/Jun/2022:12:10:33]  RESTSQL:qtJAUIgQmapZ execute: () {'taskname': '220614_095223:mmarz_crab_NMSSM_14_6_22_Signal_nanoaodv9_UL_MH600_MhS60_hSToBB_hToTauTau_0'}
[14/Jun/2022:12:10:33]  RESTSQL:qtJAUIgQmapZ disconnecting
[14/Jun/2022:12:10:33]  SERVER DATABASE ERROR 500/403 Execution error __builtins__.NameError e1e0c70a2e12fb614361946dc11bf494 [instance: prod] (name 'args' is not defined); last statement: SELECT tm_taskname, tm_task_status, tm
_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_algo, tm_split_args, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir,              tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time, tw_name              FROM tasks WHERE tm_taskname=:taskname; binds: (), {'taskname': '220614_095223:mmarz_cra
b_NMSSM_14_6_22_Signal_nanoaodv9_UL_MH600_MhS60_hSToBB_hToTauTau_0'}; offset: None
[14/Jun/2022:12:10:33]    Traceback (most recent call last):
[14/Jun/2022:12:10:33]      File "/data/srv/HG2206e-f41669621c2496ca6d1d47917af53d9d/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220529-98c8762ce16fb2a56a9a86f8cc282e59/lib/python3.8/site-packages/WMCore/REST/Server.py", line 1777, in dbapi_wrapper
[14/Jun/2022:12:10:33]        return handler(*xargs, **xkwargs)
[14/Jun/2022:12:10:33]      File "/data/srv/HG2206e-f41669621c2496ca6d1d47917af53d9d/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220529-98c8762ce16fb2a56a9a86f8cc282e59/lib/python3.8/site-packages/CRABInterface/RESTUserWorkflow.py", line 654, in delete
[14/Jun/2022:12:10:33]        return self.userworkflowmgr.kill(workflow, killwarning)
[14/Jun/2022:12:10:33]      File "/data/srv/HG2206e-f41669621c2496ca6d1d47917af53d9d/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220529-98c8762ce16fb2a56a9a86f8cc282e59/lib/python3.8/site-packages/CRABInterface/DataUserWorkflow.py", line 174, in kill
[14/Jun/2022:12:10:33]        return self.workflow.kill(workflow, killwarning)
[14/Jun/2022:12:10:33]      File "/data/srv/HG2206e-f41669621c2496ca6d1d47917af53d9d/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220529-98c8762ce16fb2a56a9a86f8cc282e59/lib/python3.8/site-packages/CRABInterface/Utilities.py", line 173, in wrapped_func
[14/Jun/2022:12:10:33]        return func(*args, **kwargs)
[14/Jun/2022:12:10:33]      File "/data/srv/HG2206e-f41669621c2496ca6d1d47917af53d9d/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220529-98c8762ce16fb2a56a9a86f8cc282e59/lib/python3.8/site-packages/CRABInterface/DataWorkflow.py", line 394, in kill
[14/Jun/2022:12:10:33]        self.api.modify(self.Task.SetArgumentsTask_sql, taskname = [workflow], arguments = [str(args)])
[14/Jun/2022:12:10:33]    NameError: name 'args' is not defined
[14/Jun/2022:12:10:33] crabserver-74c6d9bc55-skfrh 188.184.75.82 "DELETE /crabserver/prod/workflow HTTP/1.1" 500 Internal Server Error [data: 971 in 745 out 12909 us ] [auth: OK "/C=DE/O=GermanGrid/OU=KIT/CN=Martin Marz" "" ] [ref: "" "CRABClient/v3.220323" ]
[14/Jun/2022:12:10:33]  RESTSQL:qtJAUIgQmapZ DISCONNECTED cms_analysis_reqmgr_w@cmsr timeout=300 inuse=0 idle=2 queue=0
[14/Jun/2022:12:10:33]  DB CONNECTION RAND WAIT TIME: timeout=18
```

**Comment by mapellidario** [comment]
This has been likely caused by this change:

https://github.com/dmwm/CRABServer/commit/b0dd6f2e7f60b1eb9a256dd1f817ebee839e877b#diff-11f8bcf03707a89a3f921d112abfed4fa78920ef1691d99f0316c58c758b74b6L400

**Comment by belforte** [comment]
changed priority because I realized that this is not a bug in production version, simply delays an upgrade. No need to be "critical".
