### ISSUE TITLE
Jobs are reported as failed despite multiple successfull attempts

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7292]
#### description

As reported by a user in [1], despite a job had multiple successful attempts, it is still reported as failed by `crab status`. 

I am not sure if this a crab client or server problem, so I am opening the issue here.

For the time being, I will just add some conflicting information:

- crab staus: reporting job ids77, 81, 95 as failed [2]
- [grafana task monitoring](https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=lian&var-task=220607_083353:lian_crab_NtupleULV13METm_qcdht0200_20161&from=1654587233000&to=now&var-site=All&var-schedd=0121&var-cmsUserId=&var-current_url=https:%2F%2Fmonit-grafana.cern.ch%2Fd%2FcmsTMDetail%2Fcms_task_monitoring&var-task_str=lian_crab_NtupleULV13METm_qcdht0200_20161&var-status=All&var-crabid=77&var-crabid=81&var-crabid=95&var-rest_host=https:%2F%2Fcmsweb.cern.ch:8443), reporting multiple successful attempts for these jobs.

I do not think it is a problem of the REST api, around the time that the first successful jobs started and finished, I see only http requests with exit 200 [3]. 

I am very confused

#### more info

[1] https://cms-talk.web.cern.ch/t/inconsistent-crab-job-status/11706/3
[2]

```plaintext
> crab status --sort=exitcode --long --jobids=1,95,81,77 crab_NtupleULV13METm_qcdht0200_20161
CRAB project directory:         /afs/cern.ch/user/d/dmapelli/crab/submit/others/crab_NtupleULV13METm_qcdht0200_20161
Task name:                      220607_083353:lian_crab_NtupleULV13METm_qcdht0200_20161
Grid scheduler - Task Worker:   crab3@vocms0121.cern.ch - crab-prod-tw01
Status on the CRAB server:      SUBMITTED
Task URL to use for HELP:       https://cmsweb.cern.ch/crabserver/ui/task/220607_083353%3Alian_crab_NtupleULV13METm_qcdht0200_20161
Dashboard monitoring URL:       https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=lian&var-task=220607_083353%3Alian_crab_NtupleULV13METm_qcdht0200_20161&from=1654587233000&to=now
Status on the scheduler:        FAILED

Jobs status:                    failed                    5.0% (  8/161)
                                finished                 95.0% (153/161)

Publication status of 1 dataset(s):     done                    100.0% (161/161)
(from CRAB internal bookkeeping in transferdb)

Output dataset:                 /QCD_HT200to300_TuneCP5_PSWeights_13TeV-madgraphMLM-pythia8/lpclonglived-NtupleULV13METm_20161-dc29a38563233ab6e48015fc1bbb0892/USER
Output dataset DAS URL:         https://cmsweb.cern.ch/das/request?input=%2FQCD_HT200to300_TuneCP5_PSWeights_13TeV-madgraphMLM-pythia8%2Flpclonglived-NtupleULV13METm_20161-dc29a38563233ab6e48015fc1bbb0892%2FUSER&instance=prod%2Fphys03

Error Summary: (use crab status --verboseErrors for details about the errors)

  1 jobs failed with exit code 60307

  7 jobs failed in postprocessing step

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.

Extended Job Status Table:

 Job State        Most Recent Site        Runtime   Mem (MB)      CPU %    Retries   Restarts      Waste       Exit Code
   1 finished     T3_UK_London_QMUL       0:04:43         64         10          0          0    0:07:55               0
  77 failed       T2_BR_SPRACE            0:06:46         51         29          8          0    1:08:51  Postprocessing failed
  81 failed       T2_US_Nebraska          0:10:18        792         74          9          1    3:02:18  Postprocessing failed
  95 failed       T2_BR_SPRACE            0:15:14       1062         38          8          0    1:49:42  Postprocessing failed

Warning: the max jobs runtime is less than 30% of the task requested value (1250 min), please consider to request a lower value for failed jobs (allowed through crab resubmit) and/or improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task.

Warning: the average jobs CPU efficiency is less than 50%, please consider to improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task

Summary of run jobs:
 * Memory: 64MB min, 1062MB max, 493MB ave
 * Runtime: 0:04:43 min, 0:15:14 max, 0:09:15 ave
 * CPU eff: 10% min, 74% max, 43% ave
 * Waste: 6:08:47 (91% of total)


Jobs sorted by exit code:

Exit Code            Job Id(s)

0                    1
90000                77, 81, 95

Log file is /afs/cern.ch/user/d/dmapelli/crab/submit/others/crab_NtupleULV13METm_qcdht0200_20161/crab.log
```

[3] [crab FE timber](https://monit-grafana.cern.ch/d/qUVV6S0Gk/crab-timber-pods?orgId=11&from=1655144978916&to=1655161258505&var-system=crabserver&var-method=All&var-api=All&var-code=All&var-metadataType=All&var-Filters=data.code%7C%3E%7C1&var-Filters=data.api%7C!%3D%7Cinfo&var-copy_of_system=All&var-cluster=cmsweb&var-env=k8s-prod&var-client=All&var-bin=100s&var-dnFilter=.*Ang%20Li.*)

**Comment by belforte** [comment]
odd that also the number of retries is different in crab status and grafana.
I have given a first look at SPOOL_DIR and looks an error in parsing condor logs :-(

**Comment by belforte** [comment]
from some time on, `task_process/cache_status.log`  file is full ths errors (sadly, no timestamps)
```
DEBUG:root:cache file found, opening
DEBUG:root:reading cache file
ERROR:root:error during main loop
Traceback (most recent call last):
  File "task_process/cache_status.py", line 538, in main
    cacheDoc = storeNodesInfoInFile()
  File "task_process/cache_status.py", line 330, in storeNodesInfoInFile
    jel = pickle.load(f)
EOFError: Ran out of input
DEBUG:root:cache_status_jel.py exiting
```
looking in the "readable" version `status_cache.txt` I see what looks like truncated output.

INdeed `status_cache.txt` and `status_cache.pkl` have not been updated since June 8, while DAG ketp running until June 14
```
belforte@vocms0121/SPOOL_DIR> ls -ltr task_process/
total 1660
-rw-r--r-- 1 crabtw zh  19132 Jun  7 10:34 CMSRucio.py
-rwxrwxrwx 1 crabtw zh   8045 Jun  7 10:34 task_proc_wrapper.sh*
-rw-r--r-- 1 crabtw zh  24196 Jun  7 10:34 cache_status.py
-rw-r--r-- 1 crabtw zh  30941 Jun  7 10:34 RUCIO_Transfers.py
-rw-r--r-- 1 crabtw zh  27026 Jun  7 10:34 FTS_Transfers.py
-rw-r--r-- 1 crabtw zh      0 Jun  7 10:35 daemon.err.79515774.0
-rw-r--r-- 1 crabtw zh    110 Jun  7 10:37 RestInfoForFileTransfers.json
-rw-r--r-- 1 crabtw zh      0 Jun  7 10:40 fjr_parse_results.txt.lock
-rw-r--r-- 1 crabtw zh  60819 Jun  7 15:04 transfers_direct.txt
drwxr-xr-x 2 crabtw zh  20480 Jun  8 19:02 jel_pickles/
-rw-r--r-- 1 crabtw zh 100299 Jun  8 19:02 status_cache.txt
-rw-r--r-- 1 crabtw zh 118462 Jun  8 19:02 status_cache.pkl
-rw-r--r-- 1 crabtw zh  36209 Jun  9 19:54 daemon.out.79515774.0
-rw-r--r-- 1 crabtw zh    521 Jun 13 21:27 daemon.jdl
-rw-r--r-- 1 crabtw zh      0 Jun 13 21:27 daemon.err.79892151.0
-rw-r--r-- 1 crabtw zh 532225 Jun 14 21:58 transfers.txt
-rw-r--r-- 1 crabtw zh 123978 Jun 14 22:28 fjr_parse_results.txt
drwxr-xr-x 2 crabtw zh  12288 Jun 15 22:28 transfers/
-rw-r--r-- 1 crabtw zh  73295 Jun 15 22:33 daemon.out.79892151.0
-rw-r--r-- 1 crabtw zh 457017 Jun 15 22:33 cache_status.log
-rw-r--r-- 1 crabtw zh   5928 Jun 15 22:33 daemon.PC.log
belforte@vocms0121/SPOOL_DIR> ls -l job_log 
-rw-r--r-- 1 crabtw zh 2386763 Jun 14 21:58 job_log
belforte@vocms0121/SPOOL_DIR> 

```
for what concerns the saved JEL files which contain the current pointer to last read record in job_log:
```
belforte@vocms0121/SPOOL_DIR> ls -ltr task_process/jel_pickles/|tail
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:15 jel-1654704917.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:20 jel-1654705219.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:25 jel-1654705520.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:30 jel-1654705821.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:35 jel-1654706122.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:40 jel-1654706424.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:45 jel-1654706725.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:51 jel-1654707074.pkl
-rw-r--r-- 1 crabtw zh 73 Jun  8 18:56 jel-1654707391.pkl
-rw-r--r-- 1 crabtw zh  0 Jun  8 19:02 jel-1654707749.pkl
belforte@vocms0121/SPOOL_DIR> 

```

So the initial diagnosis is that something went wron on Jun  8 19:02 , the JEL file was written with no content, and things could not recover. So crab status output is "frozen as of June 8th".

I have not found (yet) any "event" around 7pm on June 8 which could explain the incident.

odd...

**Comment by belforte** [comment]
condor_schedd daemon was restarted on June 8th, the report does not way when it stopped working
```
belforte@vocms0121/SPOOL_DIR> cat /var/log/condor/ScheddRestartReport
The schedd crab3@vocms0121.cern.ch restarted at 06/08/22 19:49:54.
It attempted to reconnect to machines where its jobs may still be running.
All reconnect attempts have finished.
Here is a summary of the reconnect attempts:

3670 total jobs where reconnecting is possible
0 reconnects are still being attempted
3670 reconnects weren't attempted because the lease expired before the schedd restarted
```
but looking in schedd log for June 8
```
06/08/22 19:02:49 (pid:2027917) Negotiating for owner: highprio.cmsdataops@cms
06/08/22 19:02:49 (pid:2027917) Negotiating owner=highprio.cmsdataops@cms jobprio restricted, min=600000 max=600000
06/08/22 19:02:49 (pid:2027917) Negotiation ended - 0 jobs matched
06/08/22 19:02:49 (pid:2027917) Finished negotiating for analysis.hindrich in local pool: 0 matched, 7 rejected
06/08/22 19:43:30 (pid:8154) Setting maximum file descriptors to 46080.
06/08/22 19:43:30 (pid:8154) ******************************************************
06/08/22 19:43:30 (pid:8154) ** condor_schedd (CONDOR_SCHEDD) STARTING UP
```

i.e. the schedd stopped working at 19:02, just when the 0-size JEL file was written.

looking at system
```
belforte@vocms0121/SPOOL_DIR> uptime
 00:59:50 up 13 days,  5:16,  1 user,  load average: 2.57, 2.52, 2.50
```
suggests that host was rebooted at that time, I see what looks like a boot log file with that date
```
-rw-r--r--  1 root   root         40288 Jun  8 19:43 dmesg
```

So my current hypothesis is that machine was rebooted while the JEL file was being written, leading to a corrupted file with 0 size. A very rare occurrence !!!

I am not sure that it is worth to modifty `cache_status.py` to make it robust against such event. In case it would be better to cover more than 0 size and the action would probably be to re-read log from start (to be tested).
Current code writes the JEL pickle file before it updates the cache status file with the name of the JEL file, so somehow the two operations were both in progress when system was rebooted, one file was properly closed, the other was not.

**Comment by belforte** [comment]
I would say that problem is understood as "corrupted JEL file" and this issue can be closed.
I am not sure if it is worth to add a protection, but should not be too difficult.
I'd rather open a new issue to track that.

**Comment by belforte** [comment]
indeed looking the previous zipped message file, things stopped at 19:02 and system was rebooted at 19:42:59

```
Jun  8 19:02:53 vocms0121.cern.ch systemd: Starting Send request to specified server, indicating server is alive and well...
Jun  8 19:02:53 vocms0121.cern.ch systemd: Started Send request to specified server, indicating server is alive and well.
Jun  8 19:42:59 vocms0121.cern.ch kernel: Initializing cgroup subsys cpuset
Jun  8 19:42:59 vocms0121.cern.ch kernel: Initializing cgroup subsys cpu
Jun  8 19:42:59 vocms0121.cern.ch kernel: Initializing cgroup subsys cpuacct
Jun  8 19:42:59 vocms0121.cern.ch kernel: Linux version 3.10.0-1160.66.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed May 18 16:02:34 UTC 2022

```

**Comment by belforte** [comment]
should have looked at our log earlier, would have saved some head scratching and lot of time. Oh well.. thanks for confirming.
