### ISSUE TITLE
REST - fix remove unused argument in DataWorkflow.py

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7321]
#### description

I tested https://github.com/dmwm/CRABServer/pull/7297 in preprod and got the error that we feared could have hit us [1] [2].

following instructions from cx_Oracle docs [3], I would suggest changing 

https://github.com/dmwm/CRABServer/blob/2b7f3a2487a9051cc600d5ca025d8b364553bac5/src/python/CRABInterface/DataWorkflow.py#L394

to 

```python
self.api.modify(self.Task.SetArgumentsTask_sql, taskname = [workflow], arguments = None)
```

Or, maybe, we can even drop this query altogether.

#### more info

[1] https://github.com/dmwm/CRABServer/pull/7297#issuecomment-1158646125

[3] https://cx-oracle.readthedocs.io/en/latest/user_guide/bind.html?highlight=bind#binding-null-values

<details><summary>[2] crabserver rest traceback</summary>

[2]

```plaintext
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp ENTER cmsweb_analysis_preprod@int2r CRABInterface.RESTBaseAPI.RESTBaseAPI (DELETE preprod workflow) inuse=0 idle=0 - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp instantiating a new connection - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp connected, client: 19.11.0.0.0, server: 19.13.0.0.0, stmtcache: 50 - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp ping - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp check [select sysdate from dual] - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp connection established - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  DEBUG: authz operator {'dn': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=dmapelli/CN=817881/CN=Dario Mapelli', 'method': 'X509Proxy', 'login': 'dmapelli', 'name': 'Dario Mapelli', 'roles': {'admin': {'site': set(), 'group': {'reqmgr'}}, 'data-manager': {'site': set(), 'group': {'reqmgr'}}, 'operator': {'site': set(), 'group': {'crab3'}}, 'user': {'site': set(), 'group': {'users'}}}} to access resources ['220628_145148:dmapelli_crab_20220628_165145'] - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp prepare [SELECT tm_taskname, tm_task_status, tm_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_algo, tm_split_args, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir,              tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time, tw_name              FROM tasks WHERE tm_taskname=:taskname] - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp execute: () {'taskname': '220628_145148:dmapelli_crab_20220628_165145'} - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp prepare [UPDATE tasks SET tm_arguments = :arguments WHERE tm_taskname = :taskname] - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp executemany: ([{'taskname': '220628_145148:dmapelli_crab_20220628_165145'}],) {} - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  RESTSQL:UCkwoDKNAuWp disconnecting - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]  SERVER DATABASE ERROR 500/403 Execution error cx_Oracle.DatabaseError fcc44c9985e74ea54971de39603cdf0c [instance: preprod] (ORA-01008: not all variables bound); last statement: <**>UPDATE tasks SET tm_arguments = :arguments WHERE tm_taskname = :taskname; binds: ([{'taskname': '220628_145148:dmapelli_crab_20220628_165145'}],), {}; offset: 0 - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]    Traceback (most recent call last): - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/WMCore/REST/Server.py", line 1774, in dbapi_wrapper - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        return handler(*xargs, **xkwargs) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/CRABInterface/RESTUserWorkflow.py", line 654, in delete - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        return self.userworkflowmgr.kill(workflow, killwarning) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/CRABInterface/DataUserWorkflow.py", line 174, in kill - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        return self.workflow.kill(workflow, killwarning) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/CRABInterface/Utilities.py", line 173, in wrapped_func - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        return func(*args, **kwargs) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/CRABInterface/DataWorkflow.py", line 394, in kill - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        self.api.modify(self.Task.SetArgumentsTask_sql, taskname = [workflow]) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/WMCore/REST/Server.py", line 2209, in modify - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        c, _ = self.executemany(sql, kwbinds, *binds) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]      File "/data/srv/HG2207d-faca2ba0a9ac0a4e438be62a3e0643e3/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220628-5f40f928177b17b8979e887bdbff5180/lib/python3.8/site-packages/WMCore/REST/Server.py", line 2118, in executemany - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]        return c, c.executemany(None, *binds, **kwbinds) - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51]    cx_Oracle.DatabaseError: ORA-01008: not all variables bound - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
[28/Jun/2022:17:21:51] crabserver-7545b9b448-rncz6 188.185.14.61 "DELETE /crabserver/preprod/workflow HTTP/1.1" 500 Internal Server Error [data: 6491 in 745 out 440761 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=dmapelli/CN=817881/CN=Dario Mapelli" "" ] [ref: "" "CRABClient/v3.220323" ] - Podname=crabserver-7545b9b448-rncz6 Type=cherrypylog
```
</details>

**Comment by belforte** [comment]
sigh

**Comment by belforte** [comment]
OK @mapellidario seems like you understand this code better than me. I am a bit lot atm but would like to understans before I give an opinion on which way to go. I think we need the `modify` API, so am not sure what you mena by "drop this query".

**Comment by mapellidario** [comment]
I had a look at the code, trying to understand why we call `.modify(self.Task.SetArgumentsTask_sql ..` [0] when killing a task.
This may be super obvious, but can point us to the correct approach for addressing this issue.

- the `tm_arguments` column in TaskDB is used for uploading the resubmission parameters. [1]
- when we kill a task, we used (abused?) this column to store the aso URL and the list of jobs to kill. [2]

Since now we do not use the list of jobs to kill nor the aso url, I think we can simply remove the line [0] (which is what i meant with "dropping this query". ok, that was a bad wording, i meant "do not call the SetArgumentsTask query when killing a task").

[0] https://github.com/dmwm/CRABServer/blob/2b7f3a2487a9051cc600d5ca025d8b364553bac5/src/python/CRABInterface/DataWorkflow.py#L394

#### more info

[1] The `tm_arguments` columns is set by the query `SetArgumentsTask_sql` https://github.com/dmwm/CRABServer/blob/2b7f3a2487a9051cc600d5ca025d8b364553bac5/src/python/Databases/TaskDB/Oracle/Task/Task.py#L102-L103 

We use this query twice. Once when we resubmit a task, here https://github.com/dmwm/CRABServer/blob/2b7f3a2487a9051cc600d5ca025d8b364553bac5/src/python/CRABInterface/DataWorkflow.py#L353

and once when we kill a task (which is what we are trying to fix at the moment) https://github.com/dmwm/CRABServer/blob/2b7f3a2487a9051cc600d5ca025d8b364553bac5/src/python/CRABInterface/DataWorkflow.py#L394

If a task was not resubmitted, this is "empty" (the column is a CLOB, so this is actually `{}`). However, if a task is resubmitted, this column looks something like: (link to [crabserverui](https://cmsweb.cern.ch/crabserver/ui/task/220620_090606%3Admapelli_crab_20220620_110604) )

```plaintext
tm_arguments | {'resubmit_jobids':  ['4', '29'], 'site_blacklist': ['T2_ES_IFCA'], 'site_whitelist':  ['T2_UK_London_Brunel', 'T1_IT_CNAF', 'T2_IT_Rome', 'T2_US_Wisconsin',  'T2_IT_Legnaro', 'T2_UK_SGrid_Bristol', 'T2_IT_Bari', 'T2_ES_CIEMAT',  'T2_IT_Pisa', 'T2_US_Florida', 'T1_RU_JINR', 'T1_US_FNAL',  'T2_US_Caltech', 'T2_DE_RWTH', 'T2_UK_SGrid_RALPP', 'T2_FR_GRIF_IRFU',  'T2_FR_IPHC', 'T2_ES_IFCA', 'T2_US_MIT', 'T1_ES_PIC', 'T2_US_Nebraska',  'T1_UK_RAL', 'T1_FR_CCIN2P3', 'T2_US_Purdue', 'T2_UK_London_IC',  'T2_DE_DESY', 'T1_DE_KIT', 'T2_FR_GRIF_LLR', 'T2_US_UCSD',  'T2_US_Vanderbilt'], 'maxjobruntime': 1250, 'maxmemory': 100,  'numcores': 1, 'priority': 10}
```

[2] This is what the code looked like when we were actually using this column when killing a task. https://github.com/dmwm/CRABServer/blob/b6337d0c83b7a975b0d9d0a9f75c0f1bcf65947e/src/python/CRABInterface/DataWorkflow.py#L402-L405 

there have been two changes since then:

- remove the list of jobs to kill: https://github.com/dmwm/CRABServer/commit/ba81c0b3792925491e1050eb1e73cd6c5f4c432d
- remove asorul: https://github.com/dmwm/CRABServer/commit/b0dd6f2e7f60b1eb9a256dd1f817ebee839e877b

But `self.api.modify(self.Task.SetArgumentsTask_sql, taskname = [workflow], arguments = [str(args)])` was left intact, despite it does not seem to be really useful.

**Comment by belforte** [comment]
I see now !! Thanks.
Dropping that line appears the most logic option. Since we would call it w/o any argument.
Yet I was not sure of the reason why the line is there in the first place, so was trying to be conservative. Give a bit to check.

**Comment by belforte** [comment]
OK. CHecked. I agree with dropping that line
https://github.com/dmwm/CRABServer/blob/2b7f3a2487a9051cc600d5ca025d8b364553bac5/src/python/CRABInterface/DataWorkflow.py#L394

can you pls take care ?

**Comment by mapellidario** [comment]
Yes, i will do. thanks Stefano for having a look!
