### ISSUE TITLE
fail publication when parent dataset is not allowed for migration 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7446]
ref https://github.com/dmwm/CRABServer/issues/7334#issuecomment-1294175234

from Publisher slave process log:
```
2022-10-27 23:49:20,411:INFO:slave:TaskPublishScript done : b"DBS Server error: [{'error': {'reason': 'dataset /BsToDsPi_DsToPhiPi_PhiToKK_MuFilter_TuneCP5_13TeV_pythia8-evtgen/RunIIAutumn18MiniAOD-PUPoissonAve20_BParking_102X_upgrade2018_realistic_v15-v1/MINIAODSIM has status PRODUCTION'
```
In this case current code simply exits leaving the files in ACQUIRED status. Should change to FAILED instead.

**Comment by belforte** [comment]
how to reproduce:
```bash
# log into Publsher, then:

source env.sh
python3 /data/repos/CRABServer/src/python/Publisher/TaskPublish.py --taskname=221027_085653:ktaeun_crab_BsToPiDs
```

**Comment by belforte** [comment]
Some facts:

- this is hard to do cleanly because TaskPublish.py was crafted around the statement from DBS developers of the time that "Migrations will always eventually succeed".
- This is not true anymore, there is no way to make dbs2go migrate a dataset from one DBS instance to another if status is 'PRODUCTION'.
- Datasets in PRODUCTION status should eventually complete and be set to VALID, but it may take months.
- This is only a transient need until #7334 is resolved

Conclusion:
an ugly patch even to be used by running by hand the patched version like this will do
```bash
python3 /data/repos/CRABServer/src/python/Publisher/TaskPublish_InvalidateNotAllowed.py --taskname=...
```
maybe even a simpler and more direct script where we directly set to FAILED the publication flag for all files in a task !
```bash
python3 /data/repos/CRABServer/src/python/Publisher/TaskPublishFail.py --taskname=...
```
of course with some instructions in the twiki on how to detect the situation and find the proper task names

I will see which one is easier to code

**Comment by belforte** [comment]
hmm.. my code in https://github.com/belforte/CRABServer/blob/fail-publication-if-cant-migrate-fix-7446/src/python/Publisher/TaskPublish-FailNotAllowed.py appears to work, and I was testing it on task stuck acquired like
`ktaeun/221027_092707:ktaeun_crab_B0ToKD`

 but for some reasons fails to update file publication status with a very odd error from REST `Required object is missing'`:
```
[28/Oct/2022:17:24:13]  RESTSQL:eNhSRgoIbkLV executemany: ([{'last_update': 1666970653, 'asoworker': 'schedd', 'publication_state': 2, 'id': 'd43372d2f88c877cde961ed80ee8dad2562bcd485372cd6b639aba60', 'fail_reason': 'Cannot migrate. Input dataset has status PRODUCTION', 'retry_value': 1, 'publish': -1}],) {}
[28/Oct/2022:17:24:13]  RESTSQL:eNhSRgoIbkLV disconnecting
[28/Oct/2022:17:24:13]  SERVER REST ERROR WMCore.REST.Error.MissingObject b27b89ac4e755b1207708b808859ad73 (Required object is missing)
[28/Oct/2022:17:24:13]    Traceback (most recent call last):
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/WMCore/REST/Server.py", line 728, in default
[28/Oct/2022:17:24:13]        return self._call(RESTArgs(list(args), kwargs))
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/WMCore/REST/Server.py", line 809, in _call
[28/Oct/2022:17:24:13]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/WMCore/REST/Server.py", line 1776, in dbapi_wrapper
[28/Oct/2022:17:24:13]        self._dberror(e, format_exc(), False)
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/WMCore/REST/Server.py", line 1774, in dbapi_wrapper
[28/Oct/2022:17:24:13]        return handler(*xargs, **xkwargs)
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/CRABInterface/RESTFileTransfers.py", line 216, in post
[28/Oct/2022:17:24:13]        self.api.modify(self.transferDB.UpdatePublication_sql, **binds)
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/WMCore/REST/Server.py", line 2211, in modify
[28/Oct/2022:17:24:13]        result = self.rowstatus(c, expected)
[28/Oct/2022:17:24:13]      File "/data/srv/HG2210a-86be8f564b0dad2c35b82e476c08caf8/sw.crab_master/slc7_amd64_gcc630/cms/crabserver/v3.220912-4d65b11ea8119698119e8c7fcc94e6ac/lib/python3.8/site-packages/WMCore/REST/Server.py", line 2260, in rowstatus
[28/Oct/2022:17:24:13]        raise MissingObject(info="%d vs. %d expected" % (c.rowcount, expected))
[28/Oct/2022:17:24:13]    WMCore.REST.Error.MissingObject: MissingObject b27b89ac4e755b1207708b808859ad73 [HTTP 400, APP 303, MSG 'Required object is missing', INFO '0 vs. 1 expected', ERR None]

```

**Comment by belforte** [comment]
In the end change was simpler than I feared, even if I failed big time in first version and wasted time in chasing non-existing problems before I figured out how exactly fileId hash needs to be constructed. So I used the first method to code/test on a couple tasks then pointed /data/repos/CRABServer to the code in the PR and ran TaskPublish.py from there on the other tasks.
