### ISSUE TITLE
list index out of range calling Rucio inside tape_recall

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7452]
see
https://cms-talk.web.cern.ch/t/crab-submitfailed-due-to-dbs-errors/17277/1
TW log for that task https://cmsweb.cern.ch/crabserver/ui/task/221108_171646%3Asobhatta_crab_QCD_Pt_800to1000
has
```
2022-11-08 18:17:04,348:INFO:RucioUtils:Rucio client initialized for crab_tape_recall in status ACTIVE
2022-11-08 18:17:04,348:INFO:DBSDataDiscovery:Create RUcio container /TapeRecall/221108_171646.sobhatta_crab_QCD_Pt_800to1000/USER
2022-11-08 18:17:04,533:INFO:DBSDataDiscovery:Rucio container user.crab_tape_recall:/TapeRecall/221108_171646.sobhatta_crab_QCD_Pt_800to1000/USER created with 77 blocks
2022-11-08 18:17:06,991:INFO:DBSDataDiscovery:Total size of data to recall : 2 TBytes
2022-11-08 18:17:08,197:ERROR:Handler:Problem handling 221108_171646:sobhatta_crab_QCD_Pt_800to1000 because of list index out of range failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.221027-097f67f5afa852c3b3b6aa98d525214d/slc7_amd64_gcc630/cms/crabtaskworker/v3.221027-097f67f5afa852c3b3b6aa98d525214d/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 80, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/v3.221027-097f67f5afa852c3b3b6aa98d525214d/slc7_amd64_gcc630/cms/crabtaskworker/v3.221027-097f67f5afa852c3b3b6aa98d525214d/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 265, in execute
    result = self.executeInternal(*args, **kwargs)
  File "/data/srv/TaskManager/v3.221027-097f67f5afa852c3b3b6aa98d525214d/slc7_amd64_gcc630/cms/crabtaskworker/v3.221027-097f67f5afa852c3b3b6aa98d525214d/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 459, in executeInternal
    self.requestTapeRecall(blockList=blocksWithLocation, system='Rucio', msgHead=msg)
  File "/data/srv/TaskManager/v3.221027-097f67f5afa852c3b3b6aa98d525214d/slc7_amd64_gcc630/cms/crabtaskworker/v3.221027-097f67f5afa852c3b3b6aa98d525214d/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 161, in requestTapeRecall
    size = list(rucioClient.get_rse_usage(rse, filters={'source': 'static'}))[0]['used']  # bytes
IndexError: list index out of range

```
Maybe it was a transient error from Rucio, but code should cope with that, or return a sensible message like "can't talk to RUcio, try again". Not leave the user with gibberish.

**Comment by belforte** [comment]
guilty code is:
https://github.com/dmwm/CRABServer/blob/42d5a7b8a7e1848f0789861111f3d01d22590981/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L153-L161
the `list index out of range` exception is raised in Line 161 (last one)
log does not say which was the RSE when the call failed.

**Comment by belforte** [comment]
I can reproduce the error "by hand" the problem is T2_FR_GRIF which returns an empty list
```
In [15]: rse                                                                                                        
Out[15]: 'T2_FR_GRIF'

In [16]: list(rucioClient.get_rse_usage(rse, filters={'source': 'static'}))                                         
Out[16]: []
```
the two GRIF subsites (IRFU and LLR) are OK, but the "simpre" GRIF is somehow a new entry with no config:
```
In [21]: list(rucioClient.get_rse_usage('T2_FR_GRIF_IRFU', filters={'source': 'static'}))                           
Out[21]: 
[{'rse_id': '2e90d1bdc8144b149673759472738a75',
  'source': 'static',
  'used': 1300000000000000,
  'free': None,
  'total': 1300000000000000,
  'files': None,
  'updated_at': datetime.datetime(2021, 5, 31, 11, 38, 33),
  'rse': 'T2_FR_GRIF_IRFU'}]

In [22]: list(rucioClient.get_rse_usage('T2_FR_GRIF_LLR', filters={'source': 'static'}))                            
Out[22]: 
[{'rse_id': 'eceb9c426cc7403c911a8e48522711bd',
  'source': 'static',
  'used': 1532000000000000,
  'free': None,
  'total': 1532000000000000,
  'files': None,
  'updated_at': datetime.datetime(2022, 5, 30, 12, 21),
  'rse': 'T2_FR_GRIF_LLR'}]

In [23]: list(rucioClient.get_rse_usage('T2_FR_GRIF', filters={'source': 'static'}))                                
Out[23]: []
```
Odd that it could have been selected via `ddm_quota>0`

**Comment by belforte** [comment]
I suspect that `T2_FR_GRIF` was introduced very recently for some possibly good reason, but they broke the "RSE" definition in Rucio, somehow, I can undersand that rse_usage is empty, but then why does it have a ddm_quota ? Anyhow let's skip it immediately and ask DM folks to clarify later. I will patch production TW and create new tag

**Comment by belforte** [comment]
the commit above is a quick patch to avoid breaking all tape recalls. But for long term we need to make sure that code is robust against possible Rucio transient errors.

**Comment by belforte** [comment]
I can't test on original use case since that dataset is on disk now.

**Comment by belforte** [comment]
here's a dataset on tape from a different user task `/DYtoMuMu_M-10to30_pPb-EmbEPOS_8p16_PowhegNoEW/pPb816Summer16DR-pPbEmb_80X_mcRun2_pA_v4-v1/AODSIM`

**Comment by belforte** [comment]
OK. Patch validated
```
belforte@lxplus8s12/TC3> crab status
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20221109_155722
Task name:			221109_145726:belforte_crab_20221109_155722
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-prod-tw01
Status on the CRAB server:	TAPERECALL
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/221109_145726%3Abelforte_crab_20221109_155722
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=221109_145726%3Abelforte_crab_20221109_155722&from=1668002246000&to=now
Warning:			Task could not be submitted because there is no DISK replica for dataset /DYtoMuMu_M-10to30_pPb-EmbEPOS_8p16_PowhegNoEW/pPb816Summer16DR-pPbEmb_80X_mcRun2_pA_v4-v1/AODSIM
				N.B.: the input dataset is stored at T1_FR_CCIN2P3_Tape, but those are TAPE locations.
				Will try to request a disk copy for you. See: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#crab_submit_fails_with_Task_coul
				A disk replica has been requested to Rucio (rule ID: 14914b9305b141c8a7324e5e2af876b6 )
				you can check progress via either of the following two commands:
				 rucio rule-info 14914b9305b141c8a7324e5e2af876b6
				 rucio list-rules user.crab_tape_recall:/TapeRecall/221109_145726.belforte_crab_20221109_155722/USER
				or simply check 'state' line in this page: https://cms-rucio-webui.cern.ch/rule?rule_id=14914b9305b141c8a7324e5e2af876b6
				This task will be automatically submitted as soon as the stage-out is completed.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20221109_155722/crab.log
belforte@lxplus8s12/TC3> 

```
