### ISSUE TITLE
input data locking fails in preprod v3.230803

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7799]
```
2023-08-06 23:17:29,714:ERROR:DBSDataDiscovery:Fatal exception in lockData:
name 'config' is not defined
Traceback (most recent call last):
  File "/data/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 430, in executeInternal
    locker = RucioAction(config=config, crabserver=self.crabserver,
NameError: name 'config' is not defined
2023-08-06 23:17:29,715:INFO:DBSDataDiscovery:Locking of input data failed. Details in TaskWorker log. Submit anyhow
```

**Comment by belforte** [comment]
same bug affects tape recall. I do not know why I did not see this when testing :-(

**Comment by belforte** [comment]
test:
- [ ] input dataset lock
- [ ] tape recall

**Comment by belforte** [comment]
hmmm.. another bug
```
  File "/data/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 338, in executeInternal
    self.requestTapeRecall(dataToRecall=dataToRecall, sizeToRecall=totalSizeBytes,
  File "/data/repos/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py", line 467, in requestTapeRecall
    recaller.recallData(dataToRecall=dataToRecall, sizeToRecall=sizeToRecall,
  File "/data/repos/CRABServer/src/python/TaskWorker/Actions/RucioActions.py", line 229, in recallData
    self.setTaskToTapeRecall(ruleId=ruleId, msg=msg)
  File "/data/repos/CRABServer/src/python/TaskWorker/Actions/RucioActions.py", line 165, in setTaskToTapeRecall
    self.uploadWarning(msg, self.userproxy, self.taskName)
AttributeError: 'RucioAction' object has no attribute 'uploadWarning'
```

**Comment by belforte** [comment]
tape recall and input lock now works in preprod using https://github.com/belforte/CRABServer/tree/fix-7799

**Comment by novicecpp** [comment]
I am a bit surprise that `NameError` exception is not catch by `pylint`. For `uploadWarning`, it is understandable because it hidden in `self` which `pylint` does not design to detect that.

I think static type checker tools like `mypy/pyright/pyre` can detect this kind of bug but it is yet-another-3rdparty-software we need to maintain. (I use [pyright](https://github.com/microsoft/pyright) in my editor and it work quite well when I develop Rucio ASO, especially methods and variables hidden in `self` in [ASO/Rucio/Transfer.py](https://github.com/dmwm/CRABServer/blob/8ff0d6f15fb1f15a6996149c6b181d379ce2c191/src/python/ASO/Rucio/Transfer.py)).
