### ISSUE TITLE
All tasks with a user dataset as an input dataset fail to submit in latest prod (v3.231214)

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#8100]
Example task: https://cmsweb.cern.ch/crabserver/ui/task/231214_220917%3Abcho_crab_step2_GEMTnP_TTbar
Error logs (from `/data/container/TaskWorker/logs/tasks/bcho/231214_220917:bcho_crab_step2_GEMTnP_TTbar.log` in `crab-prod-tw01`):
```
2023-12-14 23:10:07,177:ERROR:Handler:Problem handling 231214_220917:bcho_crab_step2_GEMTnP_TTbar because of local variable 'partialLocationsMap' referenced before assignment failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/v3.231214-cb7a07945859cb5ccc4af98a0484c1d8/slc7_amd64_gcc630/cms/crabtaskworker/v3.231214-cb7a07945859cb5ccc4af98a0484c1d8/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 86, in executeAction
    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/v3.231214-cb7a07945859cb5ccc4af98a0484c1d8/slc7_amd64_gcc630/cms/crabtaskworker/v3.231214-cb7a07945859cb5ccc4af98a0484c1d8/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 110, in execute
    result = self.executeInternal(*args, **kwargs)
  File "/data/srv/TaskManager/v3.231214-cb7a07945859cb5ccc4af98a0484c1d8/slc7_amd64_gcc630/cms/crabtaskworker/v3.231214-cb7a07945859cb5ccc4af98a0484c1d8/lib/python3.8/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 312, in executeInternal
    self.keepOnlyDiskRSEs(partialLocationsMap)
UnboundLocalError: local variable 'partialLocationsMap' referenced before assignment
```

This bug was introduced in PR [#8001](https://github.com/dmwm/CRABServer/pull/8001).

**Comment by novicecpp** [comment]
I think put `partialLocationsMap = {}` before [line 192](https://github.com/belforte/CRABServer/blob/94a11eb7bf795a1f344efb64fe0cea7c960386ff/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L192) should fix. I need to test and reread the code to confirm there will be no side effect.

**Comment by novicecpp** [comment]
All `possibly unbound ` reported from [pyright](https://github.com/microsoft/pyright):
```
[thanayut@localhost Actions]$ pyright DBSDataDiscovery.py | grep --color 'possibly unbound'
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:267:81 - error: "secondaryBlocks" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:278:43 - error: "secondaryBlocks" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:280:81 - error: "scope" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:300:30 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:302:43 - error: "secondaryLocationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:306:33 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:311:31 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:312:31 - error: "partialLocationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:314:28 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:324:33 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:325:33 - error: "partialLocationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:326:25 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:326:47 - error: "partialLocationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:347:38 - error: "secondaryBlocksWithLocation" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:386:62 - error: "locations" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:386:72 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
  /home/thanayut/myhome/coding/cern/fork/CRABServer/src/python/TaskWorker/Actions/DBSDataDiscovery.py:408:39 - error: "locationsMap" is possibly unbound (reportUnboundVariable)
```

For `locationsMap` and `partialLocationsMap`, I have checked with the code using it and pretty sure it ok to fix by define default value before line 192. For other value I blindly do the same and will test it with testsuite later.

**Comment by belforte** [comment]
We need to understand why this test did not catch the problem
https://github.com/dmwm/CRABServer/blob/eafa9ddbf0f068b5e0056b3068a9f42939012ed9/test/makeTests.py#L305-L317

**Comment by belforte** [comment]
OK. CCV fails to submit because we deprecated `sendPythonFolder`. Why was this not noticed ?

**Comment by belforte** [comment]
hmm... CCV was not run since October :-(
![image](https://github.com/dmwm/CRABServer/assets/1837785/243bc876-84fd-43e7-902b-c0b2d9cbea9a)

**Comment by novicecpp** [comment]
My bad. I did not know I should run CCV too. **"Client"** in *"**Client**_Configuration_Validation"* threw me off, thought it wasn't related to the Server code."
