### ISSUE TITLE
ZeroDivisionError from TapeRecallManager.py

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#8626]
I found it while scrolling at TW logs: 
```
2024-08-16 10:42:17,752:INFO:TapeRecallManager,119:Rule 6b6464d4a4e44cee98738bca29b68a37 is INJECT
2024-08-16 10:42:17,752:ERROR:BaseRecurringAction,38:Error while runnig recurring action.
2024-08-16 10:42:17,753:ERROR:BaseRecurringAction,39:integer division or modulo by zero
Traceback (most recent call last):
  File "/data/srv/current/lib/python/site-packages/TaskWorker/Actions/Recurring/BaseRecurringAction.py", line 35, in execute
    self._execute(config, task)
  File "/data/srv/current/lib/python/site-packages/TaskWorker/Actions/Recurring/TapeRecallManager.py", line 46, in _execute
    self.handleRecall()
  File "/data/srv/current/lib/python/site-packages/TaskWorker/Actions/Recurring/TapeRecallManager.py", line 137, in handleRecall
    okFraction = ok * 100 // total
ZeroDivisionError: integer division or modulo by zero
```

**Comment by belforte** [comment]
thanks

**Comment by belforte** [comment]
to have total=0 it must be a rule with no locks (no ok, no rep, no stuck). interesting
